Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.LayoutBuilderEngine=function(a){this._selectedTable=null;
this._selectedCell=null;
this._selectedRow=null;
this._selectedRowCells=[];
this._selectedRowIndex=null;
this._tableState=[];
this._tableStateRowsCount=0;
this._tableStateColsCount=0;
this._tableStateId="LayoutBuilder_tableState_dump";
this._tableStateTableStyle="radtblder_stateMatrixTable";
this._tableStateCellStyle="radtblder_stateMatrixCell";
this._selectedCellClassName="";
this._states=[];
this._currentStateIndex=-1;
this.set_selectedTable(a);
if(this._selectedTable){this.set_selectedCell();
}if(!a){a=document.createElement("table");
}Telerik.Web.UI.LayoutBuilderEngine.initializeBase(this,[a]);
};
Telerik.Web.UI.LayoutBuilderEngine.prototype={get_selectedTable:function(){return this._selectedTable;
},set_selectedTable:function(a){this._selectedTable=null;
if(a&&a.tagName=="TABLE"){this._selectedTable=a;
this._setTableState();
}},get_selectedCell:function(){return this._selectedCell;
},set_selectedCell:function(b,a){if(!this._selectedTable||this._selectedTable.tagName!="TABLE"){return;
}if(!b){b=this._selectedTable.rows[0].cells[0];
}if(b.tagName=="TD"||b.tagName=="TH"){if(this._selectedCell!=b){this._selectedCellClassName=b.className;
}this._selectedCell=b;
}else{this._selectedCell=null;
}if(this._selectedCell){this.set_selectedRow();
}if(this._selectedCell&&(false!=a)&&this._currentStateIndex==-1){if(this._states.length==1&&this._states[0]["commandName"]=="selection"){this._states=[];
}var c={commandName:"selection",selectedColIndex:this._selectedCell.cellIndex,selectedRowIndex:this._selectedRowIndex,nextSelectedColIndex:this._selectedCell.cellIndex,nextSelectedRowIndex:this._selectedRowIndex};
this._storeState(c);
}},set_selectedRow:function(){if(this._selectedCell){this._selectedRow=this._selectedCell.parentNode;
if(this._selectedRow){this._selectedRowCells=this._selectedRow.cells;
this._selectedRowIndex=this._selectedRow.rowIndex;
}else{this._selectedRowCells=null;
this._selectedRowIndex=null;
}}},_raiseException:function(a){},_initializesTableStateCounts:function(){var h=this._selectedTable.rows;
var e=h.length;
var d=0;
for(var b=0;
b<e;
b++){var f=0;
var g=h[b].cells;
var a=g.length;
for(var c=0;
c<a;
c++){f+=this._getColSpan(g[c]);
}if(d<f){d=f;
}}this._tableStateRowsCount=e;
this._tableStateColsCount=d;
},dumpState:function(){var c=document.createElement("Table");
var e=$get(this._tableStateId);
if(e){e.parentNode.removeChild(e);
}c.id=this._tableStateId;
c.className=this._tableStateTableStyle;
var f=this._tableState.length;
for(i=0;
i<f;
i++){var d=this._tableState[i].length;
var a=c.insertRow(i);
for(j=0;
j<d;
j++){var b=a.insertCell(j);
b.className=this._tableStateCellStyle;
b.innerHTML=this._tableState[i][j];
}}this._selectedTable.parentNode.appendChild(c);
},_initializesTableState:function(d,c){for(var a=0;
a<d;
a++){this._tableState[a]=[];
for(var b=0;
b<c;
b++){this._tableState[a][b]="";
}}},_processTD:function(b,g,h){var f=this._getRowSpan(b);
var e=this._getColSpan(b);
for(var a=0;
a<f;
a++){for(var c=0;
c<e;
c++){var d=g+a;
if(this._tableState[d]==undefined){this._tableState[d]=[];
}this._tableState[d][h+c]=b.parentNode.rowIndex+","+b.cellIndex;
}}},_setTableState:function(){this._tableState=[];
this._initializesTableStateCounts();
this._initializesTableState(this._tableStateRowsCount,this._tableStateColsCount);
var g=this._selectedTable.rows;
var b=g.length;
for(var f=0;
f<b;
f++){var a=0;
var e=g[f].cells;
var c=e.length;
for(var d=0;
d<c;
d++){while(this._tableState[f][a]){a++;
}this._processTD(e[d],f,a);
}}},_getStateValueIndexes:function(c,a){var f={};
var d=this._tableState.length-1;
if(c>d){c=d;
}var b=this._tableState[c][a];
if(b){var e=b.split(",");
if(e.length==2){f.rowIndex=parseInt(e[0]);
f.colIndex=parseInt(e[1]);
}}return f;
},_getSelectedTableCellByStateIndexes:function(a,d){var c=this._getStateValueIndexes(a,d);
var b=c.rowIndex;
var a=this._selectedTable.rows[b];
return(a!=undefined)?a.cells[c.colIndex]:null;
},_getLeftTopStateIndexes:function(f,g){var e={};
var d=f+","+g;
for(var b=0;
b<this._tableStateRowsCount;
b++){var c=false;
for(var a=0;
a<this._tableStateColsCount;
a++){if(this._tableState[b][a]==d){e.rowIndex=b;
e.colIndex=a;
c=true;
break;
}}if(c){break;
}}return e;
},_getRightTopStateIndexes:function(f,g){var e={};
var d=f+","+g;
for(var b=0;
b<this._tableStateRowsCount;
b++){var c=false;
for(var a=this._tableStateColsCount-1;
a>-1;
a--){if(this._tableState[b][a]==d){e.rowIndex=b;
e.colIndex=a;
c=true;
break;
}}if(c){break;
}}return e;
},_getLeftBottomStateIndexes:function(f,g){var e={};
var d=f+","+g;
for(var b=(this._tableStateRowsCount-1);
b>-1;
b--){var c=false;
for(var a=0;
a<this._tableStateColsCount;
a++){if(this._tableState[b][a]==d){e.rowIndex=b;
e.colIndex=a;
c=true;
break;
}}if(c){break;
}}return e;
},_insertRow:function(a){var b=null;
if(this._selectedCell.tagName=="TH"){if(this._selectedRow){b=this._selectedRow.parentNode.insertRow(a);
}}else{b=this._selectedTable.insertRow(a);
}return b;
},_insertCell:function(c,g,b,d){if(!g){g=0;
}var f=null;
if(c&&c.tagName=="TR"){var e=c.parentNode;
if(e.tagName=="THEAD"){var h=c.document?c.document:c.ownerDocument;
f=h.createElement("th");
if(b){f.innerHTML=b;
}if(c.cells.length==g){c.appendChild(f);
}else{var a=c.cells[g];
if(a){c.insertBefore(f,a);
}}}else{f=c.insertCell(g);
if(b){f.innerHTML=b;
}}$telerik.mergeElementAttributes(d,f);
this._cleanNewCellAttributes(f);
}return f;
},_cleanNewCellAttributes:function(a){if(!a){return;
}a.removeAttribute("rowSpan");
a.removeAttribute("colSpan");
a.removeAttribute("name");
a.removeAttribute("ID");
},_getRowSpan:function(a){if(a){var b=parseInt(a.getAttribute("rowSpan"));
if(isNaN(b)){b=1;
}return b;
}return 0;
},_getColSpan:function(a){if(a){var b=parseInt(a.getAttribute("colSpan"));
if(isNaN(b)){b=1;
}return b;
}return 0;
},_setRowSpan:function(a,b){if(!a){return;
}b=parseInt(b);
if(isNaN(b)||b<2){a.removeAttribute("rowSpan");
}else{a.setAttribute("rowSpan",b);
}},_setColSpan:function(a,b){if(!a){return;
}b=parseInt(b);
if(isNaN(b)||b<2){a.removeAttribute("colSpan");
}else{a.setAttribute("colSpan",b);
}},_alterRowSpan:function(c,d){var b=this._getRowSpan(c)+d;
var a=true;
if(b>0){this._setRowSpan(c,b);
}else{a=false;
}return a;
},canUndo:function(){return(0<this._currentStateIndex);
},canRedo:function(){return(this._currentStateIndex<this._states.length-1);
},undo:function(){var d=this._currentStateIndex-1;
var c=this._states[this._currentStateIndex];
if(d<this._states.length){var b=this._states[d];
if(b){this._replaceSelectedTable(b);
this._currentStateIndex--;
var a={commandName:"undo "+c.commandName,selectedColIndex:c.selectedColIndex,selectedRowIndex:c.selectedRowIndex};
this._raiseEvent("onCommand",a);
}}},redo:function(){var d=this._currentStateIndex+1;
var c=this._states[this._currentStateIndex];
if(d<this._states.length){var b=this._states[d];
if(b){this._replaceSelectedTable(b);
this._currentStateIndex++;
var a={commandName:"redo "+c.commandName,selectedColIndex:c.selectedColIndex,selectedRowIndex:c.selectedRowIndex};
this._raiseEvent("onCommand",a);
}}},_replaceSelectedTable:function(d){var b=this._selectedTable.parentNode;
var a=d.table.cloneNode(true);
b.insertBefore(a,this._selectedTable);
b.removeChild(this._selectedTable);
this.set_selectedTable(a);
var c=a.rows[d.nextSelectedRowIndex].cells[d.nextSelectedColIndex];
this._selectedCellClassName=d.selectedCellClassName;
this.set_selectedCell(c,false);
},_storeState:function(b){if(!this._selectedTable){return false;
}this._currentStateIndex++;
if(this._states.length!=0){this._states=this._states.slice(0,this._currentStateIndex);
}var a={table:this._selectedTable.cloneNode(true),selectedRowIndex:b.selectedRowIndex,selectedColIndex:b.selectedColIndex,nextSelectedRowIndex:b.nextSelectedRowIndex,nextSelectedColIndex:b.nextSelectedColIndex,selectedCellClassName:this._selectedCellClassName,commandName:b.commandName};
this._states.push(a);
},_removeEptyTrElements:function(){if(!this._selectedTable){return false;
}var e=this._selectedTable.rows;
var m=e.length;
var d=[];
var a=0;
for(var k=0;
k<m;
k++){var c=e[k];
var f=c.cells.length;
if(f==0){d[a++]=c;
if(k!=0){var n=e[k-1];
var g=n.cells;
var b=g.length;
for(var l=0;
l<b;
l++){var o=g[l];
var h=this._getRowSpan(o);
if(h>1){this._setRowSpan(o,h-1);
}}}}}for(var k=0;
k<a;
k++){var c=d[0];
c.parentNode.removeChild(c);
}},executeCommand:function(d,b){if(!this._selectedTable||!this._selectedCell||!d){return false;
}var a=true;
var c={commandName:d,selectedColIndex:this._selectedCell.cellIndex,selectedRowIndex:this._selectedRowIndex,nextSelectedColIndex:this._selectedCell.cellIndex,nextSelectedRowIndex:this._selectedRowIndex};
switch(d){case"deleteColumn":case"deleteRow":case"deleteCell":case"insertRowAbove":case"insertRowBelow":case"insertColumnToTheLeft":case"insertColumnToTheRight":case"mergeLeft":case"mergeTop":case"mergeRight":case"mergeDown":case"setAsContentCell":case"splitCellHorizontally":case"splitCellVertically":a=this[d](b);
break;
default:this._raiseException(d+" is not implemented!");
return false;
break;
}if(a){this._setTableState();
this._raiseEvent("onCommand",c);
this.set_selectedRow();
if(d!="deleteColumn"&&d!="deleteRow"&&d!="deleteCell"){c.nextSelectedColIndex=this._selectedCell.cellIndex;
c.nextSelectedColIndex=this._selectedRowIndex;
}this._storeState(c);
this._removeEptyTrElements();
}return a;
},_alterNonCurrentRowCellsRowspan:function(f,a){var b=";";
var h="";
for(var e=0;
e<this._tableStateColsCount;
e++){var c=this._getStateValueIndexes(f,e);
var g=c.rowIndex;
var d=c.colIndex;
if(c.rowIndex!=f){var h=g+","+d+";";
if(b.indexOf(";"+h)==-1){b+=h;
this._alterRowSpan(this._selectedTable.rows[g].cells[d],a);
}}}},_getNewCellIndex:function(l,m,b){var c=l+1;
var k=l+","+m;
var f=(b)?b:0;
for(var h=0;
h<this._tableStateColsCount;
h++){if(this._tableState[c][h]==k){if(h!=0){var g=h-1;
for(var a=g;
a>0;
a--){var e=this._getStateValueIndexes(c,g);
var d=e.rowIndex;
if(d==c){var h=e.colIndex;
f=parseInt(h);
break;
}}}break;
}}return f;
},deleteRow:function(q){if(!this._selectedTable){return false;
}var b=this._getLeftTopStateIndexes(this._selectedRowIndex,this._selectedCell.cellIndex);
var c=b.rowIndex;
var d=c-1;
var r=this._selectedRowIndex+1;
var a=this._selectedTable.rows[r];
if(typeof(c)!="undefined"&&typeof(b.colIndex)!="undefined"){var l=";";
var g=0;
for(var n=0;
n<this._tableStateColsCount;
n++){var e=this._tableState[c][n]+";";
if(l.indexOf(";"+e)==-1){l+=e;
var s=this._getSelectedTableCellByStateIndexes(c,n);
var f=this._getRowSpan(s);
if(f==1){}else{if(d>=0&&this._tableState[c][n]==this._tableState[d][n]){var m=this._getSelectedTableCellByStateIndexes(d,n);
this._alterRowSpan(m,-1);
}else{for(var h=n;
h>-1;
h--){var k=this._getStateValueIndexes(r,h);
if(r==k.rowIndex){g=parseInt(k.colIndex)+1;
break;
}}var p=this._insertCell(a,g,s.innerHTML,s);
this._setColSpan(p,this._getColSpan(s));
this._setRowSpan(p,f-1);
g++;
}}}}var o=this._selectedRow.parentNode;
if(o){o.removeChild(this._selectedRow);
}return true;
}},insertRowBelow:function(f){if(!this._selectedTable){return false;
}var l=this._getLeftBottomStateIndexes(this._selectedRowIndex,this._selectedCell.cellIndex);
if(typeof(l.rowIndex)!="undefined"&&typeof(l.colIndex)!="undefined"){var d=l.rowIndex;
var k=d+1;
var e=this._insertRow(k);
$telerik.mergeElementAttributes(this._selectedRow,e);
var g=";";
for(var a=0;
a<this._tableStateColsCount;
a++){stateValue=this._tableState[d][a];
if(g.indexOf(";"+stateValue+";")==-1){g+=stateValue+";";
var h=this._getSelectedTableCellByStateIndexes(d,a);
if(this._getRowSpan(h)>1&&k!=this._tableStateRowsCount&&this._tableState[d][a]==this._tableState[k][a]){this._alterRowSpan(h,1);
}else{var c=this._insertCell(e,e.cells.length,"&nbsp;",h);
var b=this._getColSpan(h);
if(b>1){this._setColSpan(c,b);
}}}}}return true;
},insertRowAbove:function(h){if(!this._selectedTable){return false;
}var d=this._insertRow(this._selectedRowIndex);
$telerik.mergeElementAttributes(this._selectedRow,d);
var b=0;
var f=this._selectedRowCells.length;
this._alterNonCurrentRowCellsRowspan(this._selectedRowIndex,1);
for(var a=0;
a<f;
a++){var g=this._selectedRowCells[a];
var e=this._getColSpan(this._selectedRowCells[a]);
var c=this._insertCell(d,b++,"&nbsp;",g);
if(e>1){this._setColSpan(c,e);
}}return true;
},insertColumnToTheLeft:function(e){if(!this._selectedTable){return false;
}var b=this._getLeftTopStateIndexes(this._selectedRowIndex,this._selectedCell.cellIndex);
if(typeof(b.colIndex)!="undefined"){var m=parseInt(b.colIndex);
if(isNaN(m)){m=0;
}for(var g=0;
g<this._tableStateRowsCount;
g++){var f=this._selectedTable.rows[g];
var n=this._getStateValueIndexes(g,m);
var l=n.rowIndex;
var a=n.colIndex;
if(l==g){var d=false;
if(m==0){d=true;
}else{var q=this._selectedTable.rows[l].cells[a];
var h=this._getColSpan(q);
if(this._tableState[g][m]==this._tableState[g][m-1]&&h>1&&g!=this._selectedRowIndex){q.setAttribute("colSpan",h+1);
var c=this._getRowSpan(q);
if(c>1){for(var k=1;
k<c;
k++){g++;
}}}else{d=true;
}}if(d){var o=this._insertCell(f,a,"&nbsp;",f.cells[a]);
}}else{var p=0;
for(var k=m-1;
k>-1;
k--){var n=this._getStateValueIndexes(g,k);
if(n.rowIndex==g){p=n.colIndex+1;
break;
}}var q=this._getSelectedTableCellByStateIndexes(g,m);
var o=this._insertCell(f,p,"&nbsp;",q);
}}}return true;
},insertColumnToTheRight:function(e){if(!this._selectedTable){return false;
}var b=this._getRightTopStateIndexes(this._selectedRowIndex,this._selectedCell.cellIndex);
if(typeof(b.colIndex)!="undefined"){var m=parseInt(b.colIndex);
if(isNaN(m)){m=0;
}for(var g=0;
g<this._tableStateRowsCount;
g++){var f=this._selectedTable.rows[g];
var n=this._getStateValueIndexes(g,m);
var l=n.rowIndex;
var a=parseInt(n.colIndex);
if(isNaN(a)){a=0;
}if(l==g){var d=false;
if(m==this._tableStateColsCount-1){d=true;
}else{var q=this._selectedTable.rows[l].cells[a];
var h=this._getColSpan(q);
if(this._tableState[g][m]==this._tableState[g][m+1]&&h>1&&g!=this._selectedRowIndex){q.setAttribute("colSpan",h+1);
var c=this._getRowSpan(q);
if(c>1){for(var k=1;
k<c;
k++){g++;
}}}else{d=true;
}}if(d){var o=this._insertCell(f,a+1,"&nbsp;",f.cells[a]);
}}else{var p=this._selectedTable.rows[g].cells.length;
for(var k=m+1;
k<this._tableStateColsCount;
k++){var n=this._getStateValueIndexes(g,k);
if(n.rowIndex==g){p=parseInt(n.colIndex);
if(isNaN(p)){p=0;
}break;
}}var q=this._getSelectedTableCellByStateIndexes(g,m);
var o=this._insertCell(f,p,"&nbsp;",q);
}}}return true;
},deleteColumn:function(e){if(!this._selectedTable){return false;
}var m=this._getLeftTopStateIndexes(this._selectedRowIndex,this._selectedCell.cellIndex);
var f=m.colIndex;
if(typeof(f)!="undefined"){for(var c=0;
c<this._tableStateRowsCount;
c++){var g=this._selectedTable.rows[c];
var k=this._getStateValueIndexes(c,f);
var a=parseInt(k.colIndex);
var h=g.cells[a];
var d=this._getRowSpan(h);
var l=this._getColSpan(h);
if(l>1){this._setColSpan(h,l-1);
}else{g.removeChild(h);
}if(d>1){for(var b=1;
b<d;
b++){c++;
}}}return true;
}return false;
},canMergeLeft:function(g){if(!g){g=this._selectedCell;
}if(!g||!g.parentNode){return false;
}var c=true;
var e=g.cellIndex;
var h=g.parentNode;
var f=h.rowIndex;
if(e==0||e==-1){c=false;
}else{var k=this._getLeftTopStateIndexes(f,e);
if(typeof(k.rowIndex)=="undefined"||typeof(k.colIndex)=="undefined"){return false;
}var a=this._getSelectedTableCellByStateIndexes(k.rowIndex,k.colIndex-1);
if(a){var b=a.parentNode.rowIndex;
var d=this._getRowSpan(a);
if(b!=f||this._getRowSpan(g)!=this._getRowSpan(a)){c=false;
}}}return c;
},mergeLeft:function(c){var d=(c&&c.cell)?c.cell:this._selectedCell;
if(!d||!d.parentNode){return false;
}var b=true;
var e=d.parentNode;
if(this.canMergeLeft(d)){var f=e.cells[d.cellIndex-1];
this._setColSpan(d,this._getColSpan(d)+this._getColSpan(f));
var a=f.innerHTML;
if(a!=" "&&a!="&nbsp;"){d.innerHTML=a+"<br />"+d.innerHTML;
}e.removeChild(f);
}else{this._raiseException("The cell can not be merged left!");
b=false;
}return b;
},canMergeTop:function(e){if(!e){e=this._selectedCell;
}if(!e||!e.parentNode){return false;
}var a=true;
var b=e.parentNode.rowIndex;
if(b==0){a=false;
}else{var c=this._getLeftTopStateIndexes(b,e.cellIndex);
if(typeof(c.rowIndex)=="undefined"||typeof(c.colIndex)=="undefined"){return false;
}var d=this._getSelectedTableCellByStateIndexes(c.rowIndex-1,c.colIndex);
a=this.canMergeDown(d);
}return a;
},mergeTop:function(c){var d=(c&&c.cell)?c.cell:this._selectedCell;
if(!d||!d.parentNode){return false;
}var a=true;
if(this.canMergeTop(d)){var f=d.parentNode;
var g=this._getLeftTopStateIndexes(f.rowIndex,d.cellIndex);
var e=this._getSelectedTableCellByStateIndexes(g.rowIndex-1,g.colIndex);
var b=d.innerHTML;
if(b!=" "&&b!="&nbsp;"){e.innerHTML+="<br />"+b;
}this.set_selectedCell(e,false);
this._alterRowSpan(e,this._getRowSpan(d));
f.removeChild(d);
}else{this._raiseException("The cell cannot be merged top!");
a=false;
}return a;
},canMergeRight:function(e){if(!e){e=this._selectedCell;
}if(!e||!e.parentNode){return false;
}var a=true;
var d=e.cellIndex;
var b=e.parentNode;
var f=b.rowIndex;
if(typeof(f)=="undefined"){return false;
}var g=b.cells.length;
if(d==g-1){a=false;
}else{var h=this._getRightTopStateIndexes(f,d);
if(typeof(h.rowIndex)=="undefined"||typeof(h.colIndex)=="undefined"){return false;
}var c=this._getSelectedTableCellByStateIndexes(h.rowIndex,h.colIndex+1);
if(c&&(c.parentNode.rowIndex!=f||this._getRowSpan(e)!=this._getRowSpan(c))){a=false;
}}return a;
},mergeRight:function(f){var d=(f&&f.cell)?f.cell:this._selectedCell;
if(!d||!d.parentNode){return false;
}var a=true;
if(this.canMergeRight(d)){var c=d.parentNode;
var b=c.cells[d.cellIndex+1];
var e=b.innerHTML;
if(e!=" "&&e!="&nbsp;"){d.innerHTML+="<br />"+e;
}this._setColSpan(d,this._getColSpan(d)+this._getColSpan(b));
c.removeChild(b);
}else{this._raiseException("The cell can not be merged right!");
a=false;
}return a;
},canMergeDown:function(o){if(!o){o=this._selectedCell;
}if(!o||!o.parentNode){return false;
}var e=true;
var n=this._getRowSpan(o);
var d=this._getColSpan(o);
var g=o.parentNode.rowIndex;
var c=g+n;
if(c==this._tableStateRowsCount){e=false;
}else{var b=this._getLeftTopStateIndexes(g,o.cellIndex);
if(typeof(b.colIndex)!="undefined"){var l=b.colIndex;
var m=this._getStateValueIndexes(c,l);
var f=m.rowIndex;
var a=parseInt(m.colIndex);
if(this._selectedTable.rows[f]==undefined){return false;
}var h=this._selectedTable.rows[f].cells[a];
if(h.parentNode.parentNode.tagName!=o.parentNode.parentNode.tagName){return false;
}var k=this._getColSpan(h);
if(d!=k){e=false;
}else{if(l!=0){if(this._tableState[c]==undefined||this._tableState[c][l-1]==this._tableState[c][l]){e=false;
}}}}}return e;
},mergeDown:function(f){var d=(f&&f.cell)?f.cell:this._selectedCell;
if(!d||!d.parentNode){return false;
}var b=true;
if(this.canMergeDown(d)){var a=this._getLeftBottomStateIndexes(d.parentNode.rowIndex,d.cellIndex);
var e=this._getSelectedTableCellByStateIndexes(a.rowIndex+1,a.colIndex);
var c=e.innerHTML;
if(c!=" "&&c!="&nbsp;"){d.innerHTML+="<br />"+c;
}this._alterRowSpan(d,this._getRowSpan(e));
e.parentNode.removeChild(e);
}else{this._raiseException("The cell can not be merged down!");
b=false;
}return b;
},canDeleteCell:function(g){if(!g){g=this._selectedCell;
}if(!g||!g.parentNode){return false;
}var h=0;
var a=this._getRowSpan(g);
var b=this._getColSpan(g);
var e=g.parentNode.rowIndex;
var d=g.cellIndex;
var f=this._getLeftTopStateIndexes(e,d);
var c=this._getLeftBottomStateIndexes(e,d);
if(a==this._tableStateRowsCount){h=1;
}else{if(b==this._tableStateColsCount){h=2;
}else{if(this.canMergeLeft(g)){h=3;
}else{if(this.canMergeRight(g)){h=4;
}else{if(this.canMergeDown(g)){h=5;
}else{if(this.canMergeTop(g)){h=6;
}}}}}}return h;
},deleteCell:function(f){var g=(f&&f.cell)?f.cell:this._selectedCell;
if(!g||!g.parentNode){return false;
}var a=true;
var c=g.parentNode;
var l=this.canDeleteCell(g);
switch(l){case 1:c.removeChild(g);
break;
case 2:c.parentNode.removeChild(c);
break;
case 3:var d=c.cells[g.cellIndex-1];
this.set_selectedCell(d,false);
a=this.mergeRight();
break;
case 4:var e=c.cells[g.cellIndex+1];
this.set_selectedCell(e,false);
a=this.mergeLeft();
break;
case 5:var b=this._getLeftBottomStateIndexes(c.rowIndex,g.cellIndex);
var k=this._getSelectedTableCellByStateIndexes(b.rowIndex+1,b.colIndex);
this.set_selectedCell(k,false);
a=this.mergeTop();
break;
case 6:var b=this._getLeftBottomStateIndexes(c.rowIndex,g.cellIndex);
var h=this._getSelectedTableCellByStateIndexes(b.rowIndex-1,b.colIndex);
this.set_selectedCell(h,false);
a=this.mergeDown();
break;
default:this._raiseException("The cell can not be deleted!");
a=false;
break;
}if(a&&c&&c.cells.length==0){c.parentNode.removeChild(c);
}return a;
},splitCellHorizontally:function(g){if(!this._selectedCell){return false;
}var u=this._selectedCell;
var l=true;
var m=this._getColSpan(u);
var e=u.cellIndex;
var h=this._selectedRow;
var c=this._selectedRowIndex;
var f=c+","+e;
var t=this._insertCell(h,e+1,"&nbsp;",u);
this._setRowSpan(t,this._getRowSpan(u));
if(m==1){var s=this._getLeftTopStateIndexes(c,e);
var d=s.colIndex;
var p=";";
for(var o=0;
o<this._tableStateRowsCount;
o++){var a=this._tableState[o][d];
if(o!=c&&a!=f&&p.indexOf(";"+a+";")){p+=a+";";
var n=this._getSelectedTableCellByStateIndexes(o,d);
this._setColSpan(n,this._getColSpan(n)+1);
}}}else{var b=(g)?parseInt(g.rightColSpan):null;
if(!b||isNaN(b)||b>=m){var q=Math.ceil(m/2);
var k,r;
if(m%2==0){k=q;
r=q;
}else{k=q;
r=q-1;
}}else{k=m-b;
r=b;
}this._setColSpan(u,k);
this._setColSpan(t,r);
}return l;
},splitCellVertically:function(e){var s=this._selectedCell;
if(!s){return false;
}if(!s.parentNode){return false;
}var h=true;
var l=this._getRowSpan(s);
var d=s.cellIndex;
var g=this._selectedRow;
var c=this._selectedRowIndex;
var q=this._selectedRowCells;
var n=q.length;
var m=";";
var k=null;
var r=[];
if(l==1){for(var o=0;
o<this._tableStateColsCount;
o++){k=this._getSelectedTableCellByStateIndexes(c,o);
stateValue=this._tableState[c][o];
r=this._getStateValueIndexes(c,o);
if((k.cellIndex!=d||c!=r.rowIndex)&&m.indexOf(";"+stateValue+";")==-1){m+=stateValue+";";
this._alterRowSpan(k,1);
}}newRow=this._insertRow(c+1);
$telerik.mergeElementAttributes(g,newRow);
newCell=this._insertCell(newRow,newRow.cells.length,"&nbsp;",s);
this._setColSpan(newCell,this._getColSpan(s));
}else{var a=Math.ceil(l/2),f,b;
var p=(e)?parseInt(e.downRowSpan):null;
if(!p||isNaN(p)||p>=l){if(l%2==0){f=a;
b=a;
}else{f=a;
b=a-1;
}}else{f=l-p;
b=p;
}this._setRowSpan(s,f);
arStateIndexes=this._getLeftTopStateIndexes(c,d);
alterRowIndex=c+f;
newCellColIndex=0;
for(var o=arStateIndexes.colIndex;
o>-1;
o--){r=this._getStateValueIndexes(alterRowIndex,o);
if(r.rowIndex==alterRowIndex){newCellColIndex=r.colIndex+1;
break;
}}newCell=this._insertCell(this._selectedTable.rows[alterRowIndex],newCellColIndex,"&nbsp;",s);
this._setColSpan(newCell,this._getColSpan(s));
this._setRowSpan(newCell,b);
}return h;
},setAsContentCell:function(b){var a=this._selectedCell;
if(!a){return false;
}if(!a.parentNode){return false;
}a.style.width="100%";
a.style.height="100%";
return true;
},add_onCommand:function(a){this.get_events().addHandler("onCommand",a);
},_raiseEvent:function(b,c){var a=this.get_events().getHandler(b);
if(a){if(!c){c=Sys.EventArgs.Empty;
}a(this,c);
}}};
Telerik.Web.UI.LayoutBuilderEngine.registerClass("Telerik.Web.UI.LayoutBuilderEngine",Telerik.Web.UI.RadWebControl);
