Type.registerNamespace("Telerik.Web.UI");
(function(){var a=Telerik.Web.UI,b=$telerik.$;
a.ResourceStyleMappingCollection=function(){this._array=[];
};
a.ResourceStyleMappingCollection.prototype={add:function(d){var c=this._array.length;
this._array[c]=d;
},getStyleMapping:function(c){return this._array[c];
},getMatchingClasses:function(d){var c=[];
b.each(this._getMatchingStyleMappings(d),function(){var e=this.get_applyCssClass();
if(!e){return;
}c[c.length]=e;
});
return c;
},getMatchingBackColor:function(c){var d="";
b.each(this._getMatchingStyleMappings(c),function(){var e=this.get_backColor();
if(!e){return;
}d=e;
});
return d;
},getMatchingBorderColor:function(c){var d="";
b.each(this._getMatchingStyleMappings(c),function(){var e=this.get_borderColor();
if(!e){return;
}d=e;
});
return d;
},get_count:function(){return this._array.length;
},forEach:function(e){for(var d=0,c=this.get_count();
d<c;
d++){e(this.getStyleMapping(d));
}},_getMatchingStyleMappings:function(c){var d=[];
this.forEach(function(f){var g=f.get_type();
var h=f.get_key();
var e=f.get_text();
if(!g&&!h&&!e){return;
}if(g&&g!=c.get_type()){return;
}if(h&&h!=c.get_key()){return;
}if(e&&e!=c.get_text()){return;
}d[d.length]=f;
});
return d;
}};
a.ResourceStyleMappingCollection.registerClass("Telerik.Web.UI.ResourceStyleMappingCollection");
})();
