Telerik.Web.UI.RadContextMenuEventArgs=function(a){Telerik.Web.UI.RadContextMenuEventArgs.initializeBase(this);
this._domEvent=a||null;
};
Telerik.Web.UI.RadContextMenuEventArgs.prototype={get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.RadContextMenuEventArgs.registerClass("Telerik.Web.UI.RadContextMenuEventArgs",Sys.EventArgs);
Telerik.Web.UI.RadContextMenuShownEventArgs=function(b,a){Telerik.Web.UI.RadContextMenuShownEventArgs.initializeBase(this);
this._targetElement=b;
this._domEvent=a||null;
};
Telerik.Web.UI.RadContextMenuShownEventArgs.prototype={get_targetElement:function(){return this._targetElement;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.RadContextMenuShownEventArgs.registerClass("Telerik.Web.UI.RadContextMenuShownEventArgs",Sys.EventArgs);
Telerik.Web.UI.RadContextMenuCancelEventArgs=function(b,a){Telerik.Web.UI.RadContextMenuCancelEventArgs.initializeBase(this);
this._targetElement=b;
this._domEvent=a;
};
Telerik.Web.UI.RadContextMenuCancelEventArgs.prototype={get_targetElement:function(){return this._targetElement;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.RadContextMenuCancelEventArgs.registerClass("Telerik.Web.UI.RadContextMenuCancelEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.RadContextMenuShowingEventArgs=function(b,a){Telerik.Web.UI.RadContextMenuShowingEventArgs.initializeBase(this,[b,a]);
};
Telerik.Web.UI.RadContextMenuShowingEventArgs.registerClass("Telerik.Web.UI.RadContextMenuShowingEventArgs",Telerik.Web.UI.RadContextMenuCancelEventArgs);
Telerik.Web.UI.RadContextMenuItemEventArgs=function(c,b,a){Telerik.Web.UI.RadContextMenuItemEventArgs.initializeBase(this,[c,a]);
this._targetElement=b;
};
Telerik.Web.UI.RadContextMenuItemEventArgs.prototype={get_targetElement:function(){return this._targetElement;
}};
Telerik.Web.UI.RadContextMenuItemEventArgs.registerClass("Telerik.Web.UI.RadContextMenuItemEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadContextMenuItemCancelEventArgs=function(c,b,a){Telerik.Web.UI.RadContextMenuItemCancelEventArgs.initializeBase(this,[c,a]);
this._targetElement=b;
};
Telerik.Web.UI.RadContextMenuItemCancelEventArgs.prototype={get_targetElement:function(){return this._targetElement;
}};
Telerik.Web.UI.RadContextMenuItemCancelEventArgs.registerClass("Telerik.Web.UI.RadContextMenuItemCancelEventArgs",Telerik.Web.UI.RadMenuItemCancelEventArgs);
(function(){var b=$telerik.$;
var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.ContextMenuTargetType=function(){throw Error.notImplemented();
};
a.ContextMenuTargetType.prototype={Control:0,Element:1,TagName:2,Document:3};
a.ContextMenuTargetType.registerEnum("Telerik.Web.UI.ContextMenuTargetType");
a.RadContextMenu=function(c){a.RadContextMenu.initializeBase(this,[c]);
this._enableSelection=false;
this._targets=[];
this._targetElements=null;
this._shown=false;
this._scrollWrapElement=null;
this._scroller=null;
this._animatedElement=null;
this._slide=null;
this._collapseAnimationEndedDelegate=null;
this._detached=false;
this._currentTarget=null;
this._flow=a.ItemFlow.Vertical;
};
a.RadContextMenu.contextMenus={};
a.RadContextMenu.hideAll=function(){for(var c in a.RadContextMenu.contextMenus){a.RadContextMenu.contextMenus[c].hide();
}};
a.RadContextMenu._getAllHidden=function(){for(var c in a.RadContextMenu.contextMenus){if(a.RadContextMenu.contextMenus[c]._shown){return false;
}}return true;
};
a.RadContextMenu.prototype={initialize:function(){this.get_element().style.display="block";
this.get_element().style.visibility="hidden";
this._getContextMenuElement().style.display="block";
this._getContextMenuElement().style.visibility="hidden";
a.RadContextMenu.callBaseMethod(this,"initialize");
this._getContextMenuElement().style.display="none";
this._getContextMenuElement().style.visibility="visible";
this._getContextMenuElement().id=this.get_id()+"_detached";
this.get_element().style.display="none";
this.get_element().style.visibility="visible";
this._getContextMenuElement().style.zIndex=this._originalZIndex;
if(!this.get_childListElement()){this._createChildListElement();
}this.get_childListElement().style.cssFloat="left";
a.RadContextMenu.contextMenus[this.get_id()]=this;
this._elementContextMenu=Function.createDelegate(this,this._elementContextMenu);
this._attachShowHandlers();
this._documentClickHandler=Function.createDelegate(this,this._documentClickHandler);
$telerik.addHandler(document,"click",this._documentClickHandler);
this._itemClickedHandler=Function.createDelegate(this,this._itemClickedHandler);
this.add_itemClicked(this._itemClickedHandler);
this._initializeAnimation();
this._initializeScroller();
},dispose:function(){if(this._detached){this.attachContextMenu();
}$telerik.removeHandler(document,"click",this._documentClickHandler);
if(Sys&&Sys.WebForms){var c=Sys.WebForms.PageRequestManager.getInstance();
if(c&&c.get_isInAsyncPostBack()){$telerik.disposeElement(this._getContextMenuElement());
}}this._detachShowHandlers();
this._targetElements=null;
this._contextMenuElement=null;
if(this._collapseAnimationEndedDelegate){if(this._slide){this._slide.remove_collapseAnimationEnded(this._collapseAnimationEndedDelegate);
}this._collapseAnimationEndedDelegate=null;
}if(this._slide){this._slide.dispose();
this._slide=null;
}if(this._scroller){this._scroller.dispose();
this._scroller=null;
}delete Telerik.Web.UI.RadContextMenu.contextMenus[this.get_id()];
a.RadContextMenu.callBaseMethod(this,"dispose");
},repaint:function(){a.RadMenu._adjustRootItemWidth(this.get_id(),this.get_childListElement());
},addTargetElement:function(c){if(c){this._addTargetElement(c);
var d=$telerik.isOpera&&!("oncontextmenu" in document.documentElement)?"mousedown":"contextmenu";
$telerik.addHandler(c,d,this._elementContextMenu);
}},removeTargetElement:function(c){if(!c){return;
}var d=$telerik.isOpera&&!("oncontextmenu" in document.documentElement)?"mousedown":"contextmenu";
if(Array.remove(this._targetElements,c)){$telerik.removeHandler(c,d,this._elementContextMenu);
}},_createChildListElement:function(){var e=this._getContextMenuElement();
var c=b("div.rmScrollWrap",e);
if(this._childListElementCssClass==null){if(c.length==1){this._childListElementCssClass="rmActive rmVertical";
}else{this._childListElementCssClass="rmActive rmVertical rmGroup rmLevel1";
}}if(!this._childListElementCssClass){return;
}var d=b("<ul class='"+this._childListElementCssClass+"'></ul>");
if(c.length==1){d.appendTo(c);
}else{d.appendTo(e);
}},_initializeEventMap:function(){this._eventMap.initialize(this,this._getContextMenuElement());
},_childInserted:function(d,e,c){a.RadContextMenu.callBaseMethod(this,"_childInserted",[d,e,c]);
if(c._shown){if(e._getWidth()>0||e.get_isSeparator()){a.RadMenu._adjustChildrenWidth(c);
}}},_attachShowHandlers:function(){var c=$telerik.isOpera&&!("oncontextmenu" in document.documentElement)?"mousedown":"contextmenu";
var d=this._getTargetElements();
for(var e=0;
e<d.length;
e++){$telerik.addHandler(d[e],c,this._elementContextMenu);
}$telerik.addHandler(this._getContextMenuElement(),c,this._elementContextMenu);
},_detachShowHandlers:function(){var c=$telerik.isOpera&&!("oncontextmenu" in document.documentElement)?"mousedown":"contextmenu";
var e=this._getTargetElements();
for(var g=0;
g<e.length;
g++){var d=e[g];
try{$telerik.removeHandler(d,c,this._elementContextMenu);
}catch(f){}}try{$telerik.removeHandler(this._getContextMenuElement(),c,this._elementContextMenu);
}catch(f){}},_documentClickHandler:function(d){var c=this._getContextMenuElement();
if(!$telerik.isDescendant(c,d.target)){this.close();
this._clicked=false;
this._hide(d);
}},_itemClickedHandler:function(c,d){if(!this.get_clickToOpen()){this._hide(d.get_domEvent());
}},_initializeAnimation:function(){var c=this._getAnimatedElement();
if(c){this._slide=new a.jSlide(c,this.get_expandAnimation(),this.get_collapseAnimation(),this.get_enableOverlay());
this._slide.initialize();
this._slide.set_direction(this._getSlideDirection());
this._collapseAnimationEndedDelegate=Function.createDelegate(this,this._onCollapseAnimationEnded);
this._slide.add_collapseAnimationEnded(this._collapseAnimationEndedDelegate);
this._expandAnimationStartedDelegate=Function.createDelegate(this,this._onExpandAnimationStarted);
this._slide.add_expandAnimationStarted(this._expandAnimationStartedDelegate);
this._expandAnimationEndedDelegate=Function.createDelegate(this,this._onExpandAnimationEnded);
this._slide.add_expandAnimationEnded(this._expandAnimationEndedDelegate);
}},_getRtlClassName:function(){var c=a.RadContextMenu.callBaseMethod(this,"_getRtlClassName");
c+=" RadMenu_Context_rtl";
if(this._skin){c+=" RadMenu_"+this._skin+"_Context_rtl";
}return c;
},_getMainElement:function(){return this._getContextMenuElement();
},_getSlideDirection:function(){var c=this.get_defaultGroupSettings().get_expandDirection();
if(c==a.ExpandDirection.Auto){return a.ExpandDirection.Down;
}return c;
},_getScrollWrapElement:function(){var c=this._getContextMenuElement();
if(!this._scrollWrapElement){if(this.get_defaultGroupSettings().get_height()||this.get_defaultGroupSettings().get_width()){this._scrollWrapElement=$telerik.getFirstChildByTagName(c,"div",0);
}}return this._scrollWrapElement;
},_getAnimatedElement:function(){if(!this._animatedElement){this._animatedElement=this._getScrollWrapElement()||this.get_childListElement();
}return this._animatedElement;
},_onExpandAnimationEnded:function(){},_onExpandAnimationStarted:function(){},_onCollapseAnimationEnded:function(){this._restoreZIndex();
},_getTargetElements:function(){if(this._targetElements==null){this._targetElements=[];
for(var c=0;
c<this._targets.length;
c++){this._addTargetElements(this._targets[c]);
}}return this._targetElements;
},_addTargetElements:function(c){switch(c.type){case a.ContextMenuTargetType.Document:this._addTargetElement(document);
break;
case a.ContextMenuTargetType.Control:case a.ContextMenuTargetType.Element:this._addTargetElement($get(c.id));
break;
case a.ContextMenuTargetType.TagName:var e=document.getElementsByTagName(c.tagName);
for(var d=0;
d<e.length;
d++){this._addTargetElement(e[d]);
}break;
}},_addTargetElement:function(c){if(c){this._targetElements[this._targetElements.length]=c;
}},_adjustPositionForScreenBoundaries:function(c,e){var d=a.RadMenu._getViewPortSize();
var f=this._getContextMenuElement();
e=Math.min(e,d.height-f.offsetHeight);
if(this.get_rightToLeft()){c=Math.max(0,c);
}else{c=Math.min(c,d.width-f.offsetWidth);
}if(isNaN(c)){c=0;
}if(isNaN(e)){e=0;
}this._getContextMenuElement().style.left=c+"px";
this._getContextMenuElement().style.top=e+"px";
},_detach:function(){if(!$telerik.isIE||document.readyState=="complete"||document.readyState=="interactive"){var c=false;
if(arguments[0]){var e=$telerik.$(arguments[0].target||arguments[0].srcElement).parents("form");
c=e[e.length-1];
}if(!c){c=document.forms[0];
}this._getContextMenuElement().parentNode.removeChild(this._getContextMenuElement());
var d=c||document.body;
d.insertBefore(this._getContextMenuElement(),d.firstChild);
this._detached=true;
}},_getContextMenuElement:function(){if(!this._contextMenuElement){this._contextMenuElement=$telerik.getFirstChildByTagName(this.get_element(),"div",0);
}return this._contextMenuElement;
},_isMainElementDescendant:function(c){return $telerik.isDescendant(this._getContextMenuElement(),c);
},attachContextMenu:function(){if(!this._detached){return;
}this._getContextMenuElement().parentNode.removeChild(this._getContextMenuElement());
this.get_element().insertBefore(this._getContextMenuElement(),$get(this.get_clientStateFieldID()));
this._detached=false;
},_getExtendedItemClickingEventArgs:function(c){return new a.RadContextMenuItemCancelEventArgs(c.get_item(),this._targetElement,c.get_domEvent());
},_getExtendedItemClickedEventArgs:function(c){return new a.RadContextMenuItemEventArgs(c.get_item(),this._targetElement,c.get_domEvent());
},_updateScrollWrapSize:function(){var c=this._getScrollWrapElement();
var d=this.get_childListElement();
if(!c){return;
}if(!c.style.height){c.style.height=d.offsetHeight+"px";
}c.style.width=d.offsetWidth+"px";
},_getAnimationContainer:function(){return this._getContextMenuElement();
},_initializeScroller:function(){var c=this._getScrollWrapElement();
if(c){if(this._scroller){this._scroller.dispose();
}this._scroller=new a.MenuItemScroller(this.get_childListElement(),a.ItemFlow.Vertical);
this._scroller.initialize();
}},_adjustRootItemsWidthOnShow:function(){var f=this.get_items();
var d=f.get_count();
for(var c=0;
c<d;
c++){var e=f.getItem(c);
if(e._adjustSiblingsWidthOnShow){e._adjustSiblingsWidth();
e._adjustSiblingsWidthOnShow=false;
return;
}}},_onTopArrowMouseDown:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onTopArrowMouseDown",[c]);
return;
}this._onScrollArrowMouseDown(a.ArrowPosition.Top);
},_onTopArrowMouseUp:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onTopArrowMouseDown",[c]);
return;
}this._onScrollArrowMouseUp(a.ArrowPosition.Top);
},_onTopArrowMouseOver:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onTopArrowMouseOver",[c]);
return;
}this._onScrollArrowMouseOver(a.ArrowPosition.Top);
},_onTopArrowMouseOut:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onTopArrowMouseOut",[c]);
return;
}this._onScrollArrowMouseOut(a.ArrowPosition.Top);
},_onBottomArrowMouseDown:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onBottomArrowMouseDown",[c]);
return;
}this._onScrollArrowMouseDown(a.ArrowPosition.Bottom);
},_onBottomArrowMouseUp:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onBottomArrowMouseUp",[c]);
return;
}this._onScrollArrowMouseUp(a.ArrowPosition.Bottom);
},_onBottomArrowMouseOver:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onBottomArrowMouseOver",[c]);
return;
}this._onScrollArrowMouseOver(a.ArrowPosition.Bottom);
},_onBottomArrowMouseOut:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onBottomArrowMouseOut",[c]);
return;
}this._onScrollArrowMouseOut(a.ArrowPosition.Bottom);
},_onLeftArrowMouseDown:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onLeftArrowMouseDown",[c]);
return;
}this._onScrollArrowMouseDown(a.ArrowPosition.Left);
},_onLeftArrowMouseUp:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onLeftArrowMouseUp",[c]);
return;
}this._onScrollArrowMouseUp(a.ArrowPosition.Left);
},_onLeftArrowMouseOver:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onLeftArrowMouseOver",[c]);
return;
}this._onScrollArrowMouseOver(a.ArrowPosition.Left);
},_onLeftArrowMouseOut:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onLeftArrowMouseOut",[c]);
return;
}this._onScrollArrowMouseOut(a.ArrowPosition.Left);
},_onRightArrowMouseDown:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onRightArrowMouseDown",[c]);
return;
}this._onScrollArrowMouseDown(a.ArrowPosition.Right);
},_onRightArrowMouseUp:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onRightArrowMouseUp",[c]);
return;
}this._onScrollArrowMouseUp(a.ArrowPosition.Right);
},_onRightArrowMouseOver:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onRightArrowMouseOver",[c]);
return;
}this._onScrollArrowMouseOver(a.ArrowPosition.Right);
},_onRightArrowMouseOut:function(c){var d=this._extractItemFromDomElement(c.eventMapTarget);
if(d!=null){a.RadContextMenu.callBaseMethod(this,"_onRightArrowMouseOut",[c]);
return;
}this._onScrollArrowMouseOut(a.ArrowPosition.Right);
},_onScrollArrowMouseDown:function(){if(!this._scroller){return;
}this._scroller.changeScrollSpeed(a.ScrollerSpeed.Fast);
},_onScrollArrowMouseUp:function(){if(!this._scroller){return;
}this._scroller.changeScrollSpeed(a.ScrollerSpeed.Slow);
},_onScrollArrowMouseOver:function(c){if(!this._scroller){return;
}var d=1;
if(c==a.ArrowPosition.Top||c==a.ArrowPosition.Left){d=-1;
}this._scroller.startScroll(a.ScrollerSpeed.Slow,d);
},_onScrollArrowMouseOut:function(){if(!this._scroller){return;
}this._scroller.stopScroll();
},_elementContextMenu:function(c){if($telerik.isDescendantOrSelf(this._getContextMenuElement(),c.target)){$telerik.cancelRawEvent(c);
return false;
}if($telerik.isOpera&&!("oncontextmenu" in document.documentElement)){if(c.button!=2){return;
}}this.show(c);
},_showAt:function(c,d,f){a.RadContextMenu.hideAll();
if(!a.RadContextMenu._getAllHidden()){return;
}this._shown=true;
this._ensureRoundedCorners();
this._ensureShadows();
a.RadMenu._ensureCorners(this,this);
if(!this._detached){this._detach(f);
if(this._rightToLeft&&$telerik.isIE6){this._getContextMenuElement().dir="rtl";
}this._getContextMenuElement().style.visibility="hidden";
this._getContextMenuElement().style.display="block";
this.repaint();
}this._slide.show();
this._adjustRootItemsWidthOnShow();
this._updateScrollWrapSize();
this._slide.updateSize();
if(this._rightToLeft){c-=this._getContextMenuElement().offsetWidth;
}this._getContextMenuElement().style.left=c+"px";
this._getContextMenuElement().style.top=d+"px";
if(this.get_enableScreenBoundaryDetection()){this._adjustPositionForScreenBoundaries(c,d);
}if(this._scroller){this._scroller.updateState();
}this._getContextMenuElement().style.visibility="visible";
this._slide.expand();
this.raise_shown(new a.RadContextMenuShownEventArgs(this._targetElement,f||null));
},_hide:function(d){if(!this._shown){return;
}var f=new a.RadContextMenuCancelEventArgs(this._targetElement,d||null);
this.raise_hiding(f);
if(f.get_cancel()){return;
}this._shown=false;
this._slide.collapse();
this.raise_hidden(new a.RadContextMenuEventArgs(d||null));
this._targetElement=null;
this._clicked=false;
if(this._focusedItem){this._focusedItem._doBlur();
}var c=this.get_openedItem();
if(c){c.close();
}},_adjustRootItemWidth:function(){},_ensureRoundedCorners:function(){if(this._roundedCornersRendered){return;
}if(this.get_enableRoundedCorners()){this._roundedCornersRendered=true;
a.RadMenu._renderCornerElements(this);
}},_ensureShadows:function(){if(this._shadowsRendered){return;
}if(this.get_enableShadows()){this._shadowsRendered=true;
a.RadMenu._renderCornerElements(this,"shadow");
}},get_childListElement:function(){if(this._getScrollWrapElement()){this._childListElement=$telerik.getFirstChildByTagName(this._getScrollWrapElement(),"ul",0);
}if(!this._childListElement){this._childListElement=$telerik.getFirstChildByTagName(this._getContextMenuElement(),"ul",0);
}return this._childListElement;
},set_targets:function(c){this._targets=c;
},get_targets:function(){return this._targets;
},get_contextMenuElement:function(){return this._getContextMenuElement();
},show:function(d){if(this._shown){this._hide();
}if(d.target){this._targetElement=d.target;
}else{if(d.srcElement){this._targetElement=d.srcElement;
}}var f=new a.RadContextMenuShowingEventArgs(this._targetElement||null,d||null);
this.raise_showing(f);
if(f.get_cancel()){return;
}var c=$telerik.getDocumentRelativeCursorPosition(d);
this._showAt(c.left,c.top,d);
$telerik.cancelRawEvent(d);
},showAt:function(c,d){var e=new a.RadContextMenuShowingEventArgs();
this.raise_showing(e);
if(e.get_cancel()){return;
}this._showAt(c,d,null);
},hide:function(){this._hide(null);
},add_showing:function(c){this.get_events().addHandler("showing",c);
},remove_showing:function(c){this.get_events().removeHandler("showing",c);
},raise_showing:function(c){if(this._fireEvents){this.raiseEvent("showing",c);
}},raise_hiding:function(c){if(this._fireEvents){this.raiseEvent("hiding",c);
}},add_shown:function(c){this.get_events().addHandler("shown",c);
},remove_shown:function(c){this.get_events().removeHandler("shown",c);
},raise_shown:function(c){if(this._fireEvents){this.raiseEvent("shown",c);
}},add_hiding:function(c){this.get_events().addHandler("hiding",c);
},remove_hiding:function(c){this.get_events().removeHandler("hiding",c);
},add_hidden:function(c){this.get_events().addHandler("hidden",c);
},remove_hidden:function(c){this.get_events().removeHandler("hidden",c);
},raise_hidden:function(c){if(this._fireEvents){this.raiseEvent("hidden",c);
}}};
a.RadContextMenu.registerClass("Telerik.Web.UI.RadContextMenu",a.RadMenu);
})();
