Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.TreeListItemDrag=function(){Telerik.Web.UI.TreeListItemDrag.initializeBase(this);
this._owner=null;
this._draggedItems=[];
this._draggedContainer=null;
this._dropClue=null;
this._originalDragItem=null;
this._isDragging=false;
this._dropTargetDataCache=[];
this._mouseDownDelegate=null;
this._documentMouseMoveDelegate=null;
this._documentMouseUpDelegate=null;
};
Telerik.Web.UI.TreeListItemDrag.prototype={initialize:function(){Telerik.Web.UI.TreeListItemDrag.callBaseMethod(this,"initialize");
if(this._owner){var a=this._owner.get_element();
this._mouseDownDelegate=$telerik.addMobileHandler(this,a,"mousedown",this._mouseDown);
}},dispose:function(){this._cleanUp();
Telerik.Web.UI.TreeListItemDrag.callBaseMethod(this,"dispose");
},_mouseDown:function(a){if(!this._owner._canRaiseItemEvent(a)||a.ctrlKey||a.shiftKey||((a.rawEvent&&a.rawEvent.metaKey))){return;
}var b=this._owner.getTargetItem(a);
if(!b){return;
}this._originalDragItem=b;
if(!this._shouldInitializeDrag(b)){return;
}this._attachDragHandlers();
Telerik.Web.UI.RadTreeList.ClearDocumentEvents();
if(!$telerik.isTouchDevice){return false;
}},_shouldInitializeDrag:function(a){return a.get_selected()||(this._owner._selection&&this._owner._clientSettings._selecting&&!this._owner._clientSettings._selecting._useSelectColumnOnly);
},_createDraggedContainer:function(e){if(!e.length){return;
}this._draggedContainer=document.createElement("div");
var f=e[0].get_element().parentNode.parentNode.getElementsByTagName("colgroup")[0];
var b=f?f.innerHTML:"";
var d=[];
for(var a=0,g=e.length;
a<g;
a++){var c=e[a].get_element();
d[d.length]=String.format("<tr class='{0}'>",c.className)+c.innerHTML+"</tr>";
this._draggedItems[this._draggedItems.length]=e[a];
}this._draggedContainer.innerHTML=String.format("<div style='overflow:hidden;'><table class='{0}'><colgroup>{1}</colgroup><tbody>{2}</tbody></table></div>",e[0].get_element().parentNode.parentNode.className,b,d.join(""));
this._copyAttributes(this._draggedContainer,this._owner.get_element());
this._copyAttributes(this._draggedContainer.getElementsByTagName("table")[0],e[0].get_element().parentNode.parentNode);
this._draggedContainer.id=this._owner.get_clientID()+"_DraggedContainer";
this._draggedContainer.style.position="absolute";
this._draggedContainer.className=String.format("{0} TreeListDraggedRows_{1}",this._owner.get_element().className,this._getSkin());
this._draggedContainer.style.zIndex=99999;
this._draggedContainer.style.display="none";
this._draggedContainer.style.width=this._owner.get_element().offsetWidth-2+"px";
this._originalCursor=document.body.style.cursor;
document.body.style.cursor="default";
document.body.appendChild(this._draggedContainer);
this._removeServiceCells(this._draggedContainer);
this._createDropClue();
},_removeServiceCells:function(n){n.style.marginLeft=-10000+"px";
n.style.display="";
var p=[];
var h=[];
var a=0;
var f=[];
var m=n.getElementsByTagName("colgroup")[0];
if(m){f=m.getElementsByTagName("col");
}var c=n.getElementsByTagName("tr");
for(var k=0;
k<c.length;
k++){var b=c[k];
var q;
var l=false;
var e=0;
for(var g=0;
g<b.cells.length&&!l;
g++){q=b.cells[g];
var d=f[g];
if(q.className.indexOf("rtlL")>-1){p.push(q);
if(d&&d.style.width){e+=parseInt(d.style.width);
}else{e+=q.offsetWidth;
}}if(q.className.indexOf("rtlCF")>-1){h.push(q);
l=true;
}}a=Math.max(a,e);
}n.style.width=n.offsetWidth-a+"px";
while(p.length){var q=p.pop();
q.parentNode.removeChild(q);
}while(h.length){var q=h.pop();
q.removeAttribute("colspan");
}if(m){m.parentNode.removeChild(m);
}var o=$get(this._owner.get_id()+"_rtlData");
if(o){this._draggedContainer.getElementsByTagName("div")[0].scrollLeft=o.scrollLeft;
}n.getElementsByTagName("table")[0].style.tableLayout="auto";
n.style.marginLeft="";
},_copyAttributes:function(b,a){if(b.mergeAttributes){b.mergeAttributes(a);
}else{Telerik.Web.UI.RadTreeList.CopyAttributes(b,a);
}},_destroyDraggedContainer:function(){if(this._draggedContainer){this._destroyDropClue();
document.body.style.cursor=this._originalCursor;
this._originalCursor=null;
this._draggedContainer.parentNode.removeChild(this._draggedContainer);
this._draggedContainer=null;
}},_createDropClue:function(){if(this._draggedContainer){this._dropClue=document.createElement("div");
this._dropClue.id=this._owner.get_clientID()+"_DropClue";
this._dropClue.className="rtlDrag";
this._draggedContainer.appendChild(this._dropClue);
}},_destroyDropClue:function(){if(this._dropClue){this._dropClue.parentNode.removeChild(this._dropClue);
this._dropClue=null;
}},_setDropClueVisibility:function(a){if(!this._dropClue){return;
}if(a){this._dropClue.style.visibility="";
}else{this._dropClue.style.visibility="hidden";
}},_getDropTargetData:function(g){var f;
if($telerik.isTouchDevice){f=$telerik.getTouchTarget(g);
}else{f=g.target||g.srcElement;
}if(!f){return null;
}for(var a=0,c=this._dropTargetDataCache.length;
a<c;
a++){var b=this._dropTargetDataCache[a];
if(b&&b.target===f){return b;
}}var d={};
d.target=f;
d.item=this._owner.getContainerItem(f);
d.isOverHeader=!d.item&&this._isOverHeader(g);
d.canDrop=d.isOverHeader;
if(!d.isOverHeader){if(!d.item||(d.item!==this._originalDragItem&&!this._isDraggedItemOrChild(d.item))){d.canDrop=true;
}else{d.item=null;
d.canDrop=false;
}}this._dropTargetDataCache[this._dropTargetDataCache.length]=d;
return d;
},_isDraggedItemOrChild:function(c){var a=function(e,g){var h=e.get_childItems();
for(var j=0,f=h.length;
j<f;
j++){if(h[j]===g||a(h[j],g)){return true;
}}return false;
};
for(var d=0,b=this._draggedItems.length;
d<b;
d++){if(this._draggedItems[d]===c||a(this._draggedItems[d],c)){return true;
}}return false;
},_positionDragElement:function(a,e){var b=13,c=15;
var g,d;
if($telerik.isTouchDevice){var f=$telerik.getTouchEventLocation(e);
g=f.x;
d=f.y;
}else{g=e.clientX;
d=e.clientY;
}a.style.top=d+document.documentElement.scrollTop+c+document.body.scrollTop+1+"px";
a.style.left=g+document.documentElement.scrollLeft+b+document.body.scrollLeft+1+"px";
if($telerik.isOpera||$telerik.isSafari2){a.style.top=parseInt(a.style.top)-document.body.scrollTop+"px";
}},_getMousePosition:function(d){var b=$telerik.getScrollOffset(document.body,true);
var a=d.clientX;
var c=d.clientY;
a+=b.x;
c+=b.y;
return{x:a,y:c};
},_getSkin:function(){var d=this._owner.get_element().className;
var b=d.split("RadTreeList");
for(var a=0,c=b.length;
a<c;
a++){if(b[a].length>0&&b[a][0]==="_"){return b[a].substr(1);
}}return"";
},_attachDragHandlers:function(){this._documentMouseMoveDelegate=$telerik.addMobileHandler(this,document,"mousemove",this._mouseMove,null,true);
this._documentMouseUpDelegate=$telerik.addMobileHandler(this,document,"mouseup",this._mouseUp,null,true);
},_detachDragHandlers:function(){if(this._documentMouseMoveDelegate){$telerik.removeMobileHandler(document,"mousemove",this._documentMouseMoveDelegate,null,true);
this._documentMouseMoveDelegate=null;
}if(this._documentMouseUpDelegate){$telerik.removeMobileHandler(document,"mouseup",this._documentMouseUpDelegate,null,true);
this._documentMouseUpDelegate=null;
}},_mouseMove:function(d){if(this._isDragging){if(this._draggedContainer){this._draggedContainer.style.position="absolute";
this._draggedContainer.style.display="";
this._positionDragElement(this._draggedContainer,d);
var b=this._getDropTargetData(d);
this._setDropClueVisibility(b.canDrop&&(b.item||b.isOverHeader));
if(this._owner._events&&this._owner._events._list.itemDragging){var a=this._owner._buildEventArgs(new Sys.EventArgs(),{draggedContainer:this._draggedContainer,domEvent:d,canDrop:b.canDrop,targetItem:b.item,isOverHeaderItem:b.isOverHeader});
var c=this;
a.set_canDrop=function(e){a._canDrop=b.canDrop=e;
};
a.set_dropClueVisible=function(e){c._setDropClueVisibility(e);
};
this._owner.raise_itemDragging(a);
}}}else{if(!this._originalDragItem.get_selected()&&this._owner._selection){if(this._owner._clientSettings._selecting._allowToggleSelection){this._originalDragItem.set_selected(true);
}else{this._owner._selection.exclusiveSelectItem(this._originalDragItem);
this._owner.updateClientStateIfModified();
}}this._setupDrag(d);
this._isDragging=true;
}return false;
},_setupDrag:function(f){if(!this._originalDragItem){return;
}var d=this._getDraggedItems();
if(!d.length){d[d.length]=this._originalDragItem;
}this._createDraggedContainer(d);
var b=this._owner._buildEventArgs(new Sys.CancelEventArgs(),{item:this._originalDragItem,draggedItems:d,draggedContainer:this._draggedContainer});
b.set_draggedContainer=function(e){b._draggedContainer=e;
};
this._owner.raise_itemDragStarted(b);
if(b.get_cancel()){this._destroyDraggedContainer();
return;
}else{if(b.get_draggedContainer()!==this._draggedContainer){var a=b.get_draggedContainer();
if(a&&a.tagName){var c=document.createElement("div");
c.id=this._draggedContainer.id;
c.style.position="absolute";
c.style.zIndex=99999;
document.body.appendChild(c);
c.appendChild(a);
this._destroyDraggedContainer();
this._draggedContainer=c;
}}}if(this._draggedContainer&&f){this._positionDragElement(this._draggedContainer,f);
}},_getDraggedItems:function(){var e=[];
var d=this._owner.get_selectedIndexes();
if(d.length>0){if(d.length==1){return this._owner.get_selectedItems();
}else{var a=[];
for(var b=0,c=d.length;
b<c;
b++){a[d[b]]=this._owner.get_dataItems()[d[b]];
}for(var b=0,c=a.length;
b<c;
b++){if(a[b]){e[e.length]=a[b];
}}}}return e;
},_isOverHeader:function(c){var a;
if($telerik.isTouchDevice){a=$telerik.getTouchTarget(c);
}else{a=c.target||c.srcElement;
}var b=this._owner.get_element().getElementsByTagName("thead")[0];
return b&&$telerik.isDescendantOrSelf(b,a);
},_mouseUp:function(d){if(this._draggedContainer){var c=this._getDropTargetData(d);
if(c.canDrop){var b={targetDataItem:c.item,destinationHtmlElement:c.target,draggedItems:this._draggedItems,isOverHeader:c.isOverHeader};
var a=this._owner._buildEventArgs(new Sys.CancelEventArgs(),b);
a.set_destinationHtmlElement=function(e){a._destinationHtmlElement=e;
};
this._owner.raise_itemDropping(a);
if(!a.get_cancel()){this._cleanUp();
this._owner.raise_itemDropped(this._owner._buildEventArgs(new Sys.EventArgs(),b));
this._saveEventData(a);
this._owner.fireCommand("ItemDrop",String.format("{0};{1}",a._targetDataItem?a._targetDataItem.get_displayIndex():c.isOverHeader?-1:"",a._destinationHtmlElement?a._destinationHtmlElement.id:""));
return;
}}}this._cleanUp();
},_saveEventData:function(b){this._owner._draggedIndexes=[];
for(var a=0,c=b._draggedItems.length;
a<c;
a++){Array.add(this._owner._draggedIndexes,b._draggedItems[a].get_displayIndex());
}this._owner.updateClientState();
},_cleanUp:function(){this._isDragging=false;
this._detachDragHandlers();
this._destroyDraggedContainer();
this._originalDragItem=null;
this._draggedItems=[];
this._dropTargetDataCache=[];
Telerik.Web.UI.RadTreeList.RestoreDocumentEvents();
},get_owner:function(){return this._owner;
},set_owner:function(a){this._owner=a;
}};
Telerik.Web.UI.TreeListItemDrag.registerClass("Telerik.Web.UI.TreeListItemDrag",Sys.Component);
