Type.registerNamespace("Telerik.Web");
(function(){$telerik.toRating=function(b){return b;
};
$telerik.findRating=$find;
var a=Telerik.Web.UI;
a.RatingPrecision=function(){};
a.RatingPrecision.prototype={Item:0,Half:1,Exact:2};
a.RatingPrecision.registerEnum("Telerik.Web.UI.RatingPrecision");
a.RatingSelectionMode=function(){};
a.RatingSelectionMode.prototype={Single:0,Continuous:1};
a.RatingSelectionMode.registerEnum("Telerik.Web.UI.RatingSelectionMode");
a.RadRatingRatingEventArgs=function(b){a.RadRatingRatingEventArgs.initializeBase(this);
this._newValue=b;
};
a.RadRatingRatingEventArgs.prototype={get_newValue:function(){return this._newValue;
}};
a.RadRatingRatingEventArgs.registerClass("Telerik.Web.UI.RadRatingRatingEventArgs",Sys.CancelEventArgs);
a.RadRatingRatedEventArgs=function(b){a.RadRatingRatedEventArgs.initializeBase(this);
this._oldValue=b;
};
a.RadRatingRatedEventArgs.prototype={get_oldValue:function(){return this._oldValue;
}};
a.RadRatingRatedEventArgs.registerClass("Telerik.Web.UI.RadRatingRatedEventArgs",Sys.EventArgs);
a.RadRating=function(b){a.RadRating.initializeBase(this,[b]);
this._itemCount=5;
this._value=0;
this._doubleValue="0";
this._selectionMode=a.RatingSelectionMode.Continuous;
this._precision=a.RatingPrecision.Item;
this._orientation=a.Orientation.Horizontal;
this._isDirectionReversed=false;
this._enableToolTips=true;
this._autoPostBack=false;
this._readOnly=false;
this._enabled=true;
this._uniqueID=null;
this._preInitializeComplete=false;
this._ulWrapper=null;
this._items=[];
this._itemData=[];
this._definedItems=false;
this._itemWidth="";
this._itemHeight="";
this._documentMouseMoveDelegate=null;
this._selectedItemCssClass="rrtSelected";
this._hoveredItemCssClass="rrtOver";
this._clearSelectedStateOnHover=false;
};
a.RadRating.prototype={initialize:function(){if(!this._preInitializeComplete){a.RadRating._preInitialize(this.get_id(),this._orientation);
}a.RadRating.callBaseMethod(this,"initialize");
var c=this._ulWrapper=$telerik.getFirstChildByTagName(this.get_element(),"ul",0);
this._decorateListWrapper();
this._createItemData();
if(!this._readOnly&&this._enabled){var b=this._getMainEventHandlers();
$addHandlers(c,b,this);
}$addHandler(c,"click",$telerik.cancelRawEvent);
this._synchronizeUIWithValue(this._value,true);
this.get_element().value=this._doubleValue;
var d=this;
setTimeout(function(){d._requestItemsHoverImages();
},0);
this.raiseEvent("load");
if(!this.canRepaint()){this.add_parentShown(this.get_element());
}},dispose:function(){this._attachDocumentHandlers(false);
this._createPartElements(false);
this._storeStartCoords(false);
this._spanSize=null;
this._hoveredItem=null;
$clearHandlers(this._ulWrapper);
this._ulWrapper=null;
this._items=null;
this._itemData=[];
a.RadRating.callBaseMethod(this,"dispose");
},repaint:function(){a.RadRating._preInitialize(this.get_id(),this._orientation);
var b=this._value;
this._clearSelection(b);
this._synchronizeUIWithValue(b);
},_decorateListWrapper:function(){if($telerik.isMobileSafari){$telerik.$(this._ulWrapper).addClass("_Telerik_MobileSafari");
}},_getMainEventHandlers:function(){return $telerik.isTouchDevice?{mouseup:this._mouseUpTouchDevice}:{mouseover:this._mouseOver,mouseup:this._mouseUp,mouseout:this._mouseOut};
},_createItemData:function(){var k=this._isDirectionReversed;
var c=this._items=$telerik.getChildrenByTagName(this._ulWrapper,"li");
if(k){var e=[];
for(var m=(c.length-1);
m>=0;
m--){e[e.length]=c[m];
}c=this._items=e;
}var f=0;
var o=0;
var j=this._itemData;
var r=this._definedItems=(j&&j.length>0);
for(var m=0,g=c.length;
m<g;
m++){var p;
if(!r){p={value:(m+1)};
}else{p=j[m];
var d={};
var h={};
if(!p.imageUrl){p.imageUrl="";
}else{d.url="url("+p.imageUrl+")";
}if(!p.selectedImageUrl){p.selectedImageUrl=p.imageUrl;
}if(p.selectedImageUrl){h.url="url("+p.selectedImageUrl+")";
}if(p.imageUrl||p.selectedImageUrl){f++;
}var q=p.hoveredImageUrl;
var l=p.hoveredSelectedImageUrl;
if(q||l){p.hoveredImageUrl=q?q:l;
p.hoveredSelectedImageUrl=l?l:q;
o++;
}else{p.hoveredImageUrl=p.selectedImageUrl;
p.hoveredSelectedImageUrl=p.selectedImageUrl;
}if(p.hoveredImageUrl){d.hoveredUrl="url("+p.hoveredImageUrl+")";
}if(p.hoveredSelectedImageUrl){h.hoveredUrl="url("+p.hoveredSelectedImageUrl+")";
}p.item=(k?h:d);
p.itemSpan=(k?d:h);
}p.index=m;
p.itemElement=c[m];
j[m]=p;
}if(r&&o==0&&f>0){this._clearSelectedStateOnHover=true;
}var b=this._itemWidth;
var s=(""!=b);
b=parseInt(b)+"px";
var n=this._itemHeight;
var t=(""!=n);
n=parseInt(n)+"px";
if(a.Orientation.Horizontal==this._orientation){if(s){c.itemSpanWidth=k?b:"0px";
c.itemSpanSelectedWidth=k?"0px":b;
if(t){c.itemPartsStaticSize=n;
}}}else{if(t){c.itemSpanHeight=k?n:"0px";
c.itemSpanSelectedHeight=k?"0px":n;
if(s){c.itemPartsStaticSize=b;
}}}},_requestItemsHoverImages:function(){var d=this._itemData;
for(var c=0,f=d.length;
c<f;
c++){var b=d[c];
var e=b.hoveredImageUrl;
if(e!=b.selectedImageUrl){this._requestImage(e);
var g=b.hoveredSelectedImageUrl;
if(g!=e){this._requestImage(g);
}}}},_requestImage:function(c){var b=document.createElement("img");
b.setAttribute("src",c);
b.setAttribute("alt","");
b.setAttribute("class","rrtHiddenImages");
this.get_element().appendChild(b);
},_getItem:function(b){for(var c=0;
c<3&&b!==this._ulWrapper;
c++,b=b.parentNode){if("li"==b.tagName.toLowerCase()){return b;
}}return null;
},_getItemA:function(c){var b=c.getElementsByTagName("a");
if(b&&b.length>0){return b[0];
}return null;
},_getItemSpan:function(b){var c=b.getElementsByTagName("span");
if(c&&c.length>0){return c[0];
}return null;
},_getItemData:function(e){var b=this._itemData;
for(var f=0,d=b.length;
f<d;
f++){var c=b[f];
if(c.itemElement===e){return c;
}}},_getItemValue:function(c,d){var b=this._getItemData(c).value;
if(a.RatingPrecision.Item!=this._precision){b-=1;
b+=this._getFraction(c,d);
}if(!isNaN(b)){return b;
}return 0;
},_getItemByValue:function(b){b=Math.ceil(b);
var c=this._itemData;
for(var f=0,d=c.length;
f<d;
f++){var e=c[f];
if(e.value===b){return e.itemElement;
}}},_getItemIndexByValue:function(b){b=Math.ceil(b);
var c=this._itemData;
for(var f=0,d=c.length;
f<d;
f++){var e=c[f];
if(e.value===b){return e.index;
}}},_getItemIndex:function(c){var b=this._getItemData(c).index;
if(!isNaN(b)){return b;
}return -1;
},_getFraction:function(j,d){if(!j){return;
}var e=0;
var i=(a.Orientation.Horizontal==this._orientation?"width":"height");
var g=$telerik.getSize(this._getItemA(j))[i];
var c=this._overPartItem;
var b=this._overPartItemComplement;
if(d&&c&&b){var f=$telerik.getSize(c)[i];
var h=$telerik.getSize(b)[i];
e=Math.max(f,h);
if(0==e&&Sys.UI.DomElement.containsCssClass(j,this._hoveredItemCssClass)){return 1;
}}else{e=$telerik.getSize(this._getItemSpan(j))[i];
if(this._isDirectionReversed){e=g-e;
}}return this._calculateFraction(e,g);
},_calculateFraction:function(c,b){return Math.round((c/b)*10)/10;
},_markContinuousHovered:function(f){if(this._selectionMode!=a.RatingSelectionMode.Continuous){return;
}var e=this._items;
for(var b=0,c=e.length;
b<c;
b++){var d=e[b];
if(f===d){break;
}this._markItemHovered(d);
}},_markItemHovered:function(g){Sys.UI.DomElement.addCssClass(g,this._hoveredItemCssClass);
var b=this._getItemData(g);
var d=b.itemSpan;
if(d&&d.hoveredUrl){var e=this._getItemSpan(g);
e.style.backgroundImage=d.hoveredUrl;
}var c=b.item;
if(c&&c.hoveredUrl){var f=this._getItemA(g);
f.style.backgroundImage=c.hoveredUrl;
}},_clearOverState:function(c){var e=(a.RatingSelectionMode.Continuous==this._selectionMode);
var g=this._items;
var d=this._hoveredItemCssClass;
var f=c?this._getItemIndex(c):null;
for(var b=(g.length-1);
b>=0;
b--){var h=g[b];
if(e&&f!=null&&(f>this._getItemIndex(h))){return;
}this._clearItemOverState(h);
}},_clearItemOverState:function(g){Sys.UI.DomElement.removeCssClass(g,this._hoveredItemCssClass);
var b=this._getItemData(g);
var d=b.itemSpan;
if(d&&d.url){var e=this._getItemSpan(g);
e.style.backgroundImage=d.url;
}var c=b.item;
if(c&&c.url){var f=this._getItemA(g);
f.style.backgroundImage=c.url;
}},_markContinuousSelected:function(b){var f=this._items;
var d=f.itemSpanSelectedWidth;
var g=f.itemSpanSelectedHeight;
this._markItemSelected(b,d,g);
if(a.RatingSelectionMode.Continuous!=this._selectionMode){return;
}for(var c=0,e=f.length;
c<e;
c++){var h=f[c];
if(b===h){break;
}this._markItemSelected(h,d,g);
}},_markItemSelected:function(c,b,d){Sys.UI.DomElement.addCssClass(c,this._selectedItemCssClass);
this._setItemSize(c,b,d);
},_clearSelection:function(l){var g=(a.RatingSelectionMode.Continuous==this._selectionMode);
var j=this._items;
var c=j.itemSpanWidth;
var k=j.itemSpanHeight;
var b=this._getItemIndexByValue(l);
var h=this._getItemIndexByValue(this._value);
for(var d=h;
d>=0;
d--){var e=j[d];
if(h==d){this._clearPart(e);
}var f=this._getItemIndex(e);
if(b!=null&&((g&&b>f)||(b==f))){return;
}this._clearItemSelectedState(e,c,k);
}},_clearItemSelectedState:function(c,d,b){Sys.UI.DomElement.removeCssClass(c,this._selectedItemCssClass);
this._setItemSize(c,d,b);
},_setItemSize:function(c,d,b){var e=this._getItemSpan(c);
if(d){e.style.width=d;
}if(b){e.style.height=b;
}},_clearPart:function(d,c){var e=this._getItemSpan(d);
if(!e){return;
}var b=c?(c.toString()+"px"):"";
e.style[a.Orientation.Horizontal==this._orientation?"width":"height"]=b;
},_updateHoveredItem:function(r){this._mouseOut(r,true);
var u=this._hoveredItem;
var g=this._overPartItem;
var p=this._overPartItemComplement;
if(!u||!g||!p){return;
}var n=$telerik.getDocumentRelativeCursorPosition(r)[this._locationProperty];
var t=n-this._ulLocation;
t=Math.min(this._maxMousePosition,Math.max(0,t));
t%=this._itemOuterSize;
t-=this._positionOffset;
this._clearItemOverState(u);
var s=this._getOverPartsSize(t,u);
var k=s.partSize;
var f=s.partComplementSize;
var h=this._sizeProperty;
var b=parseInt(g.style[h]);
if(isNaN(b)||b<1){g.style[h]="1px";
}var c=parseInt(p.style[h]);
if(isNaN(b)||c<1){p.style[h]="1px";
}var m=(a.Orientation.Horizontal==this._orientation);
if(this._isDirectionReversed){var o=this._marginProperty;
var i=this._itemSize;
var l=this._spanSize;
var v=i-k-(m?0:l);
g.style[o]=v.toString()+"px";
var d=i-f-(m?0:(l+v+k));
p.style[o]=d.toString()+"px";
}else{if(!m){g.style.marginTop=(-f).toString()+"px";
}}g.style[h]=k.toString()+"px";
p.style[h]=f.toString()+"px";
this._updateHoveredItemPartsImages(u);
if(this._enableToolTips){var q=this._getItemData(u);
if(!q.tooltip){var j=this._getItemA(u);
j.title=this._getItemValue(u,true);
}}},_updateHoveredItemPartsImages:function(h){var f=this._isDirectionReversed?"right bottom":"left top";
var b=this._getItemData(h);
var e=b.itemSpan;
var c=this._overPartItem.style;
if(e&&e.hoveredUrl){c.backgroundImage=e.hoveredUrl;
c.backgroundPosition=f;
}else{if(c.backgroundPosition){this._clearBackgroundPosition(c);
}}var d=b.item;
var g=this._overPartItemComplement.style;
if(d&&d.hoveredUrl){g.backgroundImage=d.hoveredUrl;
g.backgroundPosition=f;
}else{if(g.backgroundPosition){this._clearBackgroundPosition(g);
}}},_clearBackgroundPosition:function(b){if(b.removeAttribute){b.removeAttribute("backgroundPosition");
}else{b.removeProperty("backgroundPosition");
}},_getOverPartsSize:function(h,d){var k=this._isDirectionReversed;
var j=this._itemSize;
var i=this._itemHalfSize;
var g=this._precision;
var c=(a.RatingPrecision.Half==g);
var b=0;
var e=0;
if(((a.RatingPrecision.Exact==g)&&(h<0||h>=j))||(c&&((!k&&h>i)||(k&&h<=i)))){if((!k&&h>=0)||(k&&h<j)){this._markItemHovered(d);
}}else{var f=this._spanSize;
if(k){if(h>f){e=c?i:(j-h);
if(c&&(f>i)){b=i;
e=(j-f);
}}else{b=c?i:(j-h);
e=j-f;
}}else{if((h>f)||(c&&(f<i))){b=f;
e=c?i:h;
}else{b=c?i:h;
}}}return{partSize:((b<0)?0:b),partComplementSize:((e<0)?0:e)};
},_createPartElements:function(f){var d=this._overPartItem;
var c=this._overPartItemComplement;
if(f){if(!d){d=document.createElement("span");
d.className="rrtPart";
c=document.createElement("span");
c.className="rrtPartComplement";
var b=this._items.itemPartsStaticSize;
if(b){var g=(a.Orientation.Horizontal==this._orientation)?"height":"width";
d.style[g]=b;
c.style[g]=b;
var e="-"+b;
d.style.marginTop=e;
c.style.marginTop=e;
}this._overPartItem=d;
this._overPartItemComplement=c;
}}else{if(d&&c){d.parentNode.removeChild(d);
this._overPartItem=null;
c.parentNode.removeChild(c);
this._overPartItemComplement=null;
}}},_storeStartCoords:function(g){if(g){var c=(a.Orientation.Horizontal==this._orientation);
var h=this._items[0];
var e=this._getItemA(h);
var d=this._ulWrapper;
var b=this._locationProperty=c?"left":"top";
var f=this._sizeProperty=c?"width":"height";
this._marginProperty=c?"marginLeft":"marginTop";
this._ulLocation=$telerik.getLocation(d)[c?"x":"y"]+($telerik.getMarginBox(d)[b]+$telerik.getBorderBox(d)[b]+$telerik.getPaddingBox(d)[b]);
this._itemOuterSize=$telerik.getOuterSize(h)[f];
this._itemSize=$telerik.getSize(e)[f];
this._itemHalfSize=Math.round(this._itemSize/2);
this._positionOffset=$telerik.getMarginBox(e)[b]+$telerik.getBorderBox(e)[b];
this._maxMousePosition=(this._itemOuterSize*this._itemCount)-1;
}else{this._locationProperty=null;
this._sizeProperty=null;
this._marginProperty=null;
this._ulLocation=null;
this._itemOuterSize=null;
this._itemSize=null;
this._itemHalfSize=null;
this._positionOffset=null;
this._maxMousePosition=null;
}},_attachDocumentHandlers:function(b){if(true==b){this._documentMouseMoveDelegate=Function.createDelegate(this,this._updateHoveredItem);
$telerik.addExternalHandler(document,"mousemove",this._documentMouseMoveDelegate);
}else{if(this._documentMouseMoveDelegate){$telerik.removeExternalHandler(document,"mousemove",this._documentMouseMoveDelegate);
this._documentMouseMoveDelegate=null;
}}},_getFractionSize:function(q,i){var p=this._overPartItem;
var n=this._overPartItemComplement;
if(!(p&&n)&&typeof(i)=="undefined"){return 0;
}var h=this._isDirectionReversed;
var k=(a.Orientation.Horizontal==this._orientation);
var e=(k?"width":"height");
var b=this._items;
var g=$telerik.getSize(this._getItemA(q?q:b[0]))[e];
var l=0;
if(p&&n){var o=$telerik.getSize(p)[e];
var d=$telerik.getSize(n)[e];
l=(o>d)?o:d;
if(0==l&&Sys.UI.DomElement.containsCssClass(q,this._hoveredItemCssClass)){l=g;
}if(h){l=g-l;
}}else{if(i!=null){var m=i-Math.floor(i);
if(m>0){if(h){m=1-m;
}l=Math.round(g*m);
}else{l=(-1);
}}}var c=(h&&l==g)||(!h&&l==0);
var f=(h&&l==0)||(!h&&l==g);
var j=k?(""!=this._itemWidth):(""!=this._itemHeight);
if((!j&&f)||c){l=(-1);
if(c){this._clearItemSelectedState(q,b.itemSpanWidth,b.itemSpanHeight);
}}l=(l<0)?"":l.toString()+"px";
return l;
},_mouseOver:function(g){var d=this._getItem(g.target||g.srcElement);
if(!d){this._hoveredItem=null;
return;
}var b=this._hoveredItem;
if(b&&b===d){return;
}this._clearOverState(d);
if(this._clearSelectedStateOnHover){this._clearSelection();
}this._markContinuousHovered(d);
if(a.RatingPrecision.Item!=this._precision){this._mouseOverPrecise(d,g);
}else{this._markItemHovered(d);
}if(this._enableToolTips){var c=this._getItemA(d);
var f=this._getItemData(d).tooltip;
c.title=f?f:this._getItemValue(d);
}},_mouseOverPrecise:function(g,i){this._createPartElements(true);
this._hoveredItem=g;
var c=(a.Orientation.Horizontal==this._orientation);
var b=(c?"width":"height");
var j=this._getItemSpan(g);
if(j){this._spanSize=$telerik.getSize(j)[b];
}var f=this._overPartItem;
var d=this._overPartItemComplement;
var k=this._isDirectionReversed;
f.style[b]="0px";
d.style[b]="0px";
if(!c&&!k){d.style.marginTop=(-this._spanSize).toString()+"px";
}var h=this._getItemA(g);
h.appendChild(k?f:d);
h.appendChild(k?d:f);
if(!this._itemOuterSize){this._storeStartCoords(true);
}if(!this._documentMouseMoveDelegate){this._attachDocumentHandlers(true);
}this._updateHoveredItem(i);
},_mouseUp:function(k){var d=this._getItem(k.target||k.srcElement);
if(!d){return;
}var c=(a.RatingPrecision.Item!=this._precision);
var l=this._overPartItem;
var j=this._overPartItemComplement;
if(c&&(!l||!this._overPartItemComplement)){return;
}var g=this._value;
var n=this._getItemValue(d,true);
var b=new a.RadRatingRatingEventArgs(n);
this.raiseEvent("rating",b);
if(b.get_cancel()){return;
}if(g!=n){this._clearSelection(n);
this._markContinuousSelected(d);
if(c){var h=this._getItemSpan(d);
var f=this._getFractionSize(d,n);
var i=(a.Orientation.Horizontal==this._orientation);
var m=i?"width":"height";
l.style[m]="1px";
j.style[m]="1px";
h.style[m]=f;
this._spanSize=$telerik.getSize(h)[m];
if(!i&&!this._isDirectionReversed){f=(f!="")?("-"+f):"";
j.style.marginTop=f;
}this._updateHoveredItem(k);
}}this._setValue(n);
this.raiseEvent("rated",new a.RadRatingRatedEventArgs(g));
if(this._autoPostBack){this._raiseServerEvent();
}},_mouseUpTouchDevice:function(q){var n=this._getItem(q.target||q.srcElement);
if(!n){return;
}var k=this._getItemA(n);
var m=this._precision!=a.RatingPrecision.Item;
var l={left:q.clientX,top:q.clientY};
var h=$telerik.getLocation(n);
h={left:h.x,top:h.y};
var p=a.Orientation.Horizontal==this._orientation?"left":"top";
var i=a.Orientation.Horizontal==this._orientation?"width":"height";
var j=$telerik.getSize(n)[i]-2*($telerik.getMarginBox(k)[p]+$telerik.getBorderBox(k)[p]);
var g=0,c=0;
if(m){c=l[p]-h[p];
var d=this._isDirectionReversed?j-c:c;
g=this._calculateFraction(d,j);
c=this._calculateFractionSize(j,c);
}var b=this._value;
var o=this._calculateItemValue(n,g);
var r=new a.RadRatingRatingEventArgs(o);
this.raiseEvent("rating",r);
if(r.get_cancel()){return;
}if(b!=o){this._clearSelection(o);
this._markContinuousSelected(n);
if(m){var f=this._getItemSpan(n);
f.style[i]=c+"px";
this._spanSize=c;
}}this._setValue(o);
this.raiseEvent("rated",new a.RadRatingRatedEventArgs(b));
if(this._autoPostBack){this._raiseServerEvent();
}},_calculateItemValue:function(d,c){var e=this._getItemData(d).value;
var b=e-1;
switch(this._precision){case a.RatingPrecision.Item:return e;
case a.RatingPrecision.Half:return c>0.5?e:e-0.5;
case a.RatingPrecision.Exact:return b+c;
default:throw"impossible";
}},_calculateFractionSize:function(c,b){var e=parseInt(c/2);
var d=this._isDirectionReversed?[e,0]:[c,e];
switch(this._precision){case a.RatingPrecision.Item:return 0;
case a.RatingPrecision.Half:return b>e?d[0]:d[1];
case a.RatingPrecision.Exact:return b;
default:throw"impossible";
}},_mouseOut:function(d,b){var c=$telerik.isMouseOverElementEx(this._ulWrapper,d);
if(c){if(!b&&a.RatingPrecision.Item!=this._precision){this._hoveredItem=null;
}return $telerik.cancelRawEvent(d);
}this._attachDocumentHandlers(false);
this._createPartElements(false);
this._storeStartCoords(false);
this._spanSize=null;
this._hoveredItem=null;
this._clearOverState();
if(this._clearSelectedStateOnHover){this._synchronizeUIWithValue(this._value);
}},_raiseServerEvent:function(){setTimeout(Function.createDelegate(this,function(){__doPostBack(this._uniqueID);
}),0);
},add_load:function(b){this.get_events().addHandler("load",b);
},remove_load:function(b){this.get_events().removeHandler("load",b);
},add_rating:function(b){this.get_events().addHandler("rating",b);
},remove_rating:function(b){this.get_events().removeHandler("rating",b);
},add_rated:function(b){this.get_events().addHandler("rated",b);
},remove_rated:function(b){this.get_events().removeHandler("rated",b);
},get_itemCount:function(){return this._itemCount;
},get_value:function(){return this._value;
},set_value:function(b){var c=this._value;
var e=this.get_isInitialized();
if(e){b=this._fixValuePrecision(b);
var d=new a.RadRatingRatingEventArgs(b);
this.raiseEvent("rating",d);
if(d.get_cancel()){return;
}if(b!=c){this._clearSelection(b);
this._synchronizeUIWithValue(b);
}}this._setValue(b);
if(e){this.raiseEvent("rated",new a.RadRatingRatedEventArgs(c));
if(this._autoPostBack){this._raiseServerEvent();
}}},_setValue:function(b){this._value=b;
this._doubleValue=b.toString();
this.get_element().value=this._doubleValue;
this.updateClientState();
},_synchronizeUIWithValue:function(b,e){var f=this._getItemByValue(b);
if(f){if(!e){this._markContinuousSelected(f);
}if(b!=parseInt(b)){var c=this._getItemSpan(f);
var d=this._getFractionSize(f,b);
c.style[a.Orientation.Horizontal==this._orientation?"width":"height"]=d;
}}},_fixValuePrecision:function(b){var d=this._precision;
if(!this._definedItems){var c=this._items;
if(b<0){b=0;
}else{if(b>c.length){b=c.length;
}}}return Math.round(b*10)/10;
},get_selectionMode:function(){return this._selectionMode;
},set_selectionMode:function(b){this._selectionMode=b;
},get_precision:function(){return this._precision;
},set_precision:function(b){this._precision=b;
},get_orientation:function(){return this._orientation;
},set_orientation:function(b){this._orientation=b;
},get_isDirectionReversed:function(){return this._isDirectionReversed;
},set_isDirectionReversed:function(b){this._isDirectionReversed=b;
},get_enableToolTips:function(){return this._enableToolTips;
},set_enableToolTips:function(b){this._enableToolTips=b;
},get_readOnly:function(){return this._readOnly;
},set_readOnly:function(b){if(this.get_isInitialized()&&b!=this._readOnly){this._enableRatingControl(!b);
}this._readOnly=b;
this.updateClientState();
},get_enabled:function(){return this._enabled;
},set_enabled:function(b){if(this.get_isInitialized()&&b!=this._enabled){this._enableRatingControl(b);
}this._enabled=b;
},get_itemData:function(){return this._itemData;
},set_itemData:function(b){this._itemData=b;
},_enableRatingControl:function(g){var d=this._ulWrapper;
$clearHandlers(d);
this._attachDocumentHandlers(false);
if(g){$addHandlers(d,{mouseover:this._mouseOver,mouseup:this._mouseUp,mouseout:this._mouseOut},this);
}else{this._clearOverState();
if(this._enableToolTips){var e=this.get_value();
var f=this._ulWrapper.getElementsByTagName("a");
for(var b=0,c=f.length;
b<c;
b++){f[b].title=e;
}}}$addHandler(d,"click",$telerik.cancelRawEvent);
},saveClientState:function(){var b=["readOnly"];
var f={value:this._doubleValue};
for(var d=0,c=b.length;
d<c;
d++){var e=b[d];
f[e]=this["get_"+e]();
}return Sys.Serialization.JavaScriptSerializer.serialize(f);
}};
a.RadRating._preInitialize=function(i,l){var d=$get(i);
if(!d||($telerik.getInvisibleParent(d)!=null)){return;
}var e=d.getElementsByTagName("li");
if(e&&e.length>0){var m=e[0];
var h=a.RadRating._getElementBox(m);
var c=a.RadRating._getElementBox($telerik.getChildrenByTagName(d,"ul")[0]);
var j=$telerik.getChildrenByTagName(m,"a")[0];
var g=$telerik.getOuterSize(j);
g.width+=h.horizontal;
g.height+=h.vertical;
var k=e.length;
var f=(0==l);
var n=c.horizontal+(f?(k*g.width):g.width);
var b=c.vertical+(f?g.height:(k*g.height));
if(parseInt(d.style.width)!=n||parseInt(d.style.height)!=b){$telerik.setContentSize(d,{width:n,height:b});
}}};
a.RadRating._getElementBox=function(d){var f={horizontal:0,vertical:0};
if(d){var c=$telerik.getBorderBox(d);
var b=$telerik.getPaddingBox(d);
var e=$telerik.getMarginBox(d);
f.horizontal=c.horizontal+b.horizontal+e.horizontal;
f.vertical=c.vertical+b.vertical+e.vertical;
}return f;
};
a.RadRating.registerClass("Telerik.Web.UI.RadRating",a.RadWebControl);
})();
