Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadFilter=function(a){var b=["filterCreating","filterCreated","filterDestroying"];
this._initializeEvents(b);
Telerik.Web.UI.RadFilter.initializeBase(this,[a]);
this._postBackFunction="__doPostBack('{0}','{1}')";
this._uniqueID=null;
this._clientID=null;
this._clickDelegate=null;
this._mouseOverDelegate=null;
this._addExpressionForItemIndex=null;
this._contextMenu=null;
this._onMenuClickingDelegate=null;
this._onMenuHiddenDelegate=null;
this._dataFields=null;
this._expressionItems=null;
this._skin=null;
this._repaintFlag=false;
};
Telerik.Web.UI.RadFilter.HandleFilterOnBlur=function(f,d){d=d||window.event;
var b=false;
if(d.keyCode==13||d.keyCode==20){d.cancelBubble=true;
d.returnValue=false;
if(d.stopPropagation){d.stopPropagation();
d.preventDefault();
}b=true;
}if(b||d.type=="change"){var e=d.srcElement||d.target;
var a=e.value;
var c=$find(e.id.replace(/_text$/,""));
if(c){c.set_value(a);
}setTimeout(function(){$find(f).applyExpressions();
},0);
}};
Telerik.Web.UI.RadFilter.HandleDateInputFilterOnBlur=function(b,c,a){c=c||window.event;
var d=false;
if(c.keyCode==13||c.keyCode==20){c.cancelBubble=true;
c.returnValue=false;
if(c.stopPropagation){c.stopPropagation();
c.preventDefault();
}d=true;
}if(d||c.type=="change"){setTimeout(function(){try{var h=$find(a.id.replace(/_text$/,""));
var i=h.get_textBoxValue();
var f=h.parseDate(i);
h.set_selectedDate(f);
}catch(g){}$find(b).applyExpressions();
},0);
}};
Telerik.Web.UI.RadFilter.prototype={initialize:function(){Telerik.Web.UI.RadFilter.callBaseMethod(this,"initialize");
this._expressionItems=Sys.Serialization.JavaScriptSerializer.deserialize(this._expressionItems);
this._dataFields=Sys.Serialization.JavaScriptSerializer.deserialize(this._dataFields);
this.raise_filterCreating(new Sys.EventArgs());
this._attachEventHandlers();
this.repaint();
if($telerik.getCurrentStyle(this.get_element(),"direction")=="rtl"){this.get_element().className+=String.format(" RadFilterRTL RadFilterRTL_{0}",this._skin);
}this.raise_filterCreated(new Sys.EventArgs());
},_attachEventHandlers:function(){this._clickDelegate=Function.createDelegate(this,this._clickHandler);
$addHandler(this.get_element(),"click",this._clickDelegate);
},_disposeEventHandlers:function(){this._mouseOverDelegate=null;
this._mouseOutDelegate=null;
this._clickDelegate=null;
this._onMenuHiddenDelegate=null;
this._onMenuClickingDelegate=null;
this._contextMenu=null;
},dispose:function(){this.raise_filterDestroying(new Sys.EventArgs());
$clearHandlers(this.get_element());
this._disposeEventHandlers();
Telerik.Web.UI.RadFilter.callBaseMethod(this,"dispose");
},_findFirstParentByTagName:function(a,b){while(a&&a.parentNode){if(a.tagName.toLowerCase()==b.toLowerCase()){return a;
}a=a.parentNode;
}return null;
},_findParentItemIndexForElement:function(b){var c=this._findFirstParentByTagName(b,"li");
if(c.id==""){return;
}var a=c.id.split("__");
return a[a.length-1];
},_clickHandler:function(c){var a=c.target;
if(a.tagName.toUpperCase()=="A"){var b=this.get_contextMenu();
var e="";
if(a.className=="rfOper"){e="ChangeGroupOperator";
}else{if(a.className=="rfExp"){e="ChangeFilterFunction";
}else{if(a.className=="rfField"){e="ChangeExpressionFieldName";
}}}if(e===""){return;
}this._intializeContextMenu(this._findParentItemIndexForElement(a),e);
var d=$telerik.getLocation(a);
b.showAt(d.x,d.y+$telerik.getSize(a).height);
$telerik.cancelRawEvent(c);
}},_intializeContextMenu:function(a,b){this._onMenuClickingDelegate=Function.createDelegate(this,this._menuClickingHandler);
this._contextMenu.add_itemClicking(this._onMenuClickingDelegate);
this._onMenuHiddenDelegate=Function.createDelegate(this,this._menuHiddenHandler);
this._contextMenu.add_hidden(this._onMenuHiddenDelegate);
this._contextMenu.get_attributes().setAttribute("ItemHierarchyIndex",a);
this._contextMenu.get_attributes().setAttribute("CommandName",b);
this._ensureItemVisibility(b,a);
},_itemVisibilityLambdaFactory:function(e,c){var a=this;
var b=function(f,g){return function(h){var i=h.get_attributes().getAttribute(f);
if(i&&typeof(g)=="function"){i=i&&g.call(a,c,h.get_value());
}h.set_visible(!!i);
};
};
if(e=="ChangeGroupOperator"){return b("isGroupItem");
}else{if(e=="ChangeFilterFunction"){var d=function(g,i){var h=this._expressionItems[g];
var f;
Array.forEach(this._dataFields,function(j){if(j.FieldName==h){f=j.DataType;
return;
}});
if(f=="System.Boolean"){if(i=="EqualTo"||i=="NotEqualTo"||i=="IsNull"||i=="NotIsNull"){return true;
}return false;
}else{if(f!="System.String"){if(i=="Contains"||i=="DoesNotContain"||i=="StartsWith"||i=="EndsWith"||i=="IsEmpty"||i=="NotIsEmpty"){return false;
}}}return true;
};
return b("isFunctionItem",d);
}else{if(e=="ChangeExpressionFieldName"){return b("isFieldItem");
}}}return null;
},_ensureItemVisibility:function(c,a){var b=this._itemVisibilityLambdaFactory(c,a);
if(b==null){return;
}this._contextMenu.get_items().forEach(b);
},_menuClickingHandler:function(d,b){var c=d.get_attributes().getAttribute("ItemHierarchyIndex");
var e=d.get_attributes().getAttribute("CommandName");
var a=b.get_item().get_value();
d.hide();
this.fireCommand(e,String.format("{0}||{1}",c,a));
},_menuHiddenHandler:function(a,b){if(this._onMenuClickingDelegate){this._contextMenu.remove_itemClicking(this._onMenuClickingDelegate);
}},_initializeEvents:function(c){if(c){var e=this;
for(var a=0,b=c.length;
a<b;
a++){var d=c[a];
this["add_"+d]=function(f){return function(g){this.get_events().addHandler(f,g);
};
}(d);
this["remove_"+d]=function(f){return function(g){this.get_events().removeHandler(f,g);
};
}(d);
this["raise_"+d]=function(f){return function(g){this.raiseEvent(f,g);
};
}(d);
}}},repaint:function(){if(this._repaintFlag){return;
}if($telerik.isIE6){if(!this.canRepaint()){this.add_parentShown(this.get_element());
return;
}else{this._clearParentShowHandlers();
}var b=this.get_id();
var c=$telerik.$("#"+b+" div.rfDiv");
for(var a=0;
a<c.length;
a++){c[a].style.width="800px";
}window.setTimeout(function(){var f=$telerik.$("#"+b+" div.rfDiv");
for(var e=0;
e<f.length;
e++){var g=f[e].childNodes;
var h=0;
for(var d=0;
d<g.length;
d++){h+=g[d].clientWidth;
}f[e].style.width=h+20+"px";
}},1);
this._repaintFlag=true;
}},get_contextMenu:function(){if(Telerik.Web.UI.RadContextMenu&&!this._contextMenu){this._contextMenu=$find(this._clientID+"_rfContextMenu");
}return this._contextMenu;
},get_clientID:function(){return this._clientID;
},get_uniqueID:function(){return this._uniqueID;
},_constructPostBackData:function(b,a){return String.format("FireCommand:{0}|;{1}|;",b,a);
},fireCommand:function(b,a){this._executePostBackEvent(this._constructPostBackData(b,a));
},_executePostBackEvent:function(a){var b=this._postBackFunction;
b=b.replace("{0}",this.get_uniqueID());
b=b.replace("{1}",a);
eval(b);
},_filterCommandInternal:function(d,c,a){if(d==""||c==null){return;
}if(!this._isValidItemIndex(c)){return;
}var b=a!==""?String.format("{0}||{1}",c,a):c;
this.fireCommand(d,b);
},_isValidItemIndex:function(a){return this._expressionItems[a]!=null;
},addExpression:function(a){this._filterCommandInternal("AddExpression",a);
},addGroup:function(a){this._filterCommandInternal("AddGroup",a);
},changeGroupOperator:function(a,b){this._filterCommandInternal("ChangeGroupOperator",a,b);
},changeFilterFunction:function(a,b){this._filterCommandInternal("ChangeFilterFunction",a,groupOperator);
},changeExpressionFieldName:function(a,b){this._filterCommandInternal("ChangeExpressionFieldName",a,groupOperator);
},applyExpressions:function(){this._filterCommandInternal("ApplyExpressions",0);
}};
Telerik.Web.UI.RadFilter.registerClass("Telerik.Web.UI.RadFilter",Telerik.Web.UI.RadWebControl);
