Type.registerNamespace("Telerik.Web.UI.Scheduler.Views.Month.GroupedByResource");
(function(b){var a=b.Views.Month,c=$telerik.$;
a.GroupedByResource.Model=function(d,e,f){a.GroupedByResource.Model.initializeBase(this,[d]);
this._groupingResource=e;
this._isVertical=f;
this._monthModels=[];
this._resources=null;
};
a.GroupedByResource.Model.prototype={initialize:function(){this._resources=this._owner.get_resources().getResourcesByType(this._groupingResource);
for(var d=0;
d<this._resources.get_count();
d++){this._monthModels[d]=new a.Model(this._owner);
}},addToBlocks:function(d){var e=this._getAppointmentModelIndex(d.appointment);
d.appointment.__modelIndex=e;
this._monthModels[e].addToBlocks(d);
},removeFromBlock:function(d){var e=d.appointment.__modelIndex;
this._monthModels[e].removeFromBlock(d);
},getTimeSlotFromDomElement:function(g){var f=this._getRawIndexFromDomElement(g);
if(!f){return null;
}var e=this._getTimeFromDomElement(g);
var d=this._resources.getResource(f.modelIndex);
return new a.GroupedByResource.TimeSlot(f,e,d,g);
},_getAllDayTimeSlotForAppointmentPart:function(d){return this._getAllDayTimeSlot(d.start,d.modelIndex);
},_getAllDayTimeSlot:function(h,g){var f=this._getTimeSlotIndices(h);
f.modelIndex=g;
var d=this._resources.getResource(g);
var e=this._getTimeSlotDomElement(f);
return new a.GroupedByResource.TimeSlot(f,h,d,e);
},getTimeSlotForAppointment:function(d){var e=this._getAppointmentModelIndex(d);
if(e==-1){return null;
}return this._getAllDayTimeSlot(d.get_start(),e);
},_getAppointmentModelIndex:function(d){var f=-1;
var e=this;
d.get_resources().forEach(function(g){var h=e._resources.getResourceByTypeAndKey(g.get_type(),g.get_key());
if(h){f=Array.indexOf(e._resources._array,h);
}});
return f;
},_getTimeSlotDomElement:function(e){var g=e.modelIndex||0;
var d=this._owner.get_element();
var i=Math.floor(e.dayIndex/this.get_weekLength());
var f=Math.floor(e.dayIndex%this.get_weekLength());
var h=c(".rsTopWrap .rsContentTable",d)[g];
return h.tBodies[0].rows[i].cells[f];
},_getTimeFromDomElement:function(d){return this._monthModels[0]._getTimeFromDomElement(d);
},_getRawIndexFromDomElement:function(f){while(f&&(f.tagName.toUpperCase()!="TD")){f=f.parentNode;
}if(!f){return null;
}var i=f.parentNode;
var h=i.parentNode;
var j=h.parentNode;
var k=this._owner._modelTables;
var g=this._owner._getElementIndex(k,j);
var e=this._monthModels[g];
var d=null;
if(e){d=e._getRawIndexFromDomElement(f);
d.modelIndex=g;
}return d;
},isVisible:function(d){var e=a.GroupedByResource.Model.callBaseMethod(this,"isVisible",[d]);
var f=this._getAppointmentModelIndex(d)!=-1;
return e&&f;
},_getRenderer:function(){if(!this._renderer){this._renderer=new b.Rendering.ResourceGroupedMonthViewRenderer(this);
}return this._renderer;
}};
a.GroupedByResource.Model.registerClass("Telerik.Web.UI.Scheduler.Views.Month.GroupedByResource.Model",a.ModelBase);
a.GroupedByResource.TimeSlot=function(f,e,d,g){this._resource=d;
a.GroupedByResource.TimeSlot.initializeBase(this,[f,e,g]);
};
a.GroupedByResource.TimeSlot.prototype={get_index:function(){var e=this.get_rawIndex();
var d=a.GroupedByResource.TimeSlot.callBaseMethod(this,"get_index");
return String.format("{0}:{1}",e.modelIndex,d);
},get_resource:function(){return this._resource;
}};
a.GroupedByResource.TimeSlot.registerClass("Telerik.Web.UI.Scheduler.Views.Month.GroupedByResource.TimeSlot",a.TimeSlot);
})(Telerik.Web.UI.Scheduler);
