Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadTab=function(){Telerik.Web.UI.RadTab.initializeBase(this);
this._properties=new Telerik.Web.UI.PropertyBag(this);
};
Telerik.Web.UI.RadTab.prototype={_requiresScrolling:function(){return this.get_tabStrip()._tabContainerRequiresScrolling(this);
},_createChildControls:function(){this._children=new Telerik.Web.UI.RadTabCollection(this);
Telerik.Web.UI.RadTabStrip._createChildControls(this,this._children);
},_tabsFromSameLevel:function(){var b=[];
Array.addRange(b,this.get_tabStrip()._children._array);
while(b.length>0){var c=b.length;
if(Array.indexOf(b,this)>-1){return b;
}for(var a=0;
a<c;
a++){var d=b[0];
Array.remove(b,d);
Array.addRange(b,d._children._array);
}}return b;
},_getChildListIndex:function(){if(!this.get_tabData()){return -1;
}var c=this._tabsFromSameLevel();
var b=-1;
for(var a=0;
a<c.length;
a++){var d=c[a];
if(d.get_tabData()){b++;
}if(d==this){break;
}}return b;
},_ensureElements:function(){if(!this.get_childListElement()){this._createChildListElement();
}},_createChildListElement:function(){var b=document.createElement("ul");
b.className="rtsUL";
var a=this._getListItemsForTheCurrentLevel();
if(!a){this.get_parent()._ensureElements();
this.get_tabStrip()._createLevelElement(this.get_level()+2);
a=this._getListItemsForTheCurrentLevel();
}this._requireChildList();
this.get_levelElement().insertBefore(b,a[this._getChildListIndex()]||null);
Array.insert(a,this._getChildListIndex(),b);
return b;
},_shouldInitializeChild:function(a){return true;
},_getListItemsForTheCurrentLevel:function(){return this.get_tabStrip()._getListElementsForLevel(this._getLevelIndex());
},_getChildElements:function(){return $telerik.getChildrenByTagName(this.get_childListElement(),"li");
},_requireChildList:function(){this._itemData=[];
},_doesNotRequireChildList:function(){this._itemData=null;
},_destroyChildListElement:function(){this.get_tabStrip()._destroyChildren(this);
this._doesNotRequireChildList();
},_renderSeparator:function(a){a[a.length]="<li class='rtsLI rtsSeparator'>";
a[a.legnth]=this.get_text();
a[a.length]="</li>";
},_renderTab:function(a){a[a.length]="<li class='rtsLI";
if(this.get_isFirst()){a[a.length]=" rtsFirst";
}if(this.get_isLast()){a[a.length]=" rtsLast";
}a[a.length]="'><a ";
if(this.get_target()){a[a.length]="target='";
a[a.length]=this.get_target();
a[a.length]="' ";
}a[a.length]="href='";
if(this.get_navigateUrl()){a[a.length]=this.get_navigateUrl();
}else{a[a.length]="#";
}a[a.length]="' class='";
a[a.length]=this._determineCssClass(this.get_index());
a[a.length]="'><span class='rtsOut'><span class='rtsIn'>";
var b=this._determineImage();
if(b){a[a.length]="<img alt='' class='rtsImg' src='";
a[a.length]=b;
a[a.length]="' />";
}a[a.length]="<span class='rtsTxt'>";
a[a.length]=this.get_text();
a[a.length]="</span></span></span></a></li>";
},_determineCssClass:function(c){var b=[];
var a=this.get_parent().get_selectedIndex();
var d=this.get_linkElement()?this.get_linkElement().className:"";
b[b.length]="rtsLink";
if(this.get_cssClass()){b[b.length]=this.get_cssClass();
}if(c==a){b[b.length]="rtsSelected";
if(this.get_selectedCssClass()){b[b.length]=this.get_selectedCssClass();
}}if(!this.get_enabled()){b[b.length]="rtsDisabled";
if(this.get_disabledCssClass()){b[b.length]=this.get_disabledCssClass();
}}if(a>-1){if(a-1==c){b[b.length]="rtsBefore";
}if(a+1==c){b[b.length]="rtsAfter";
}}if(d.search("rtsClicked")!=-1){b[b.length]="rtsClicked";
}return b.join(" ");
},_render:function(a){if(this.get_isSeparator()){this._renderSeparator(a);
}else{this._renderTab(a);
}this._updateSiblings();
if(this.get_tabs().get_count()>0){this._renderChildren();
}},_getPreviousVisibileTab:function(){var c=this.get_parent().get_tabs();
for(var a=this.get_index()-1;
a>-1;
a--){var b=c.getTab(a);
if(b.get_visible()){return b;
}}return null;
},_getNextVisibleTab:function(){var d=this.get_parent().get_tabs();
for(var a=this.get_index()+1,c=d.get_count();
a<c;
a++){var b=d.getTab(a);
if(b.get_visible()){return b;
}}return null;
},_updateSiblings:function(c){var b=this._getPreviousVisibileTab();
if(b){b._updateAppearance(c);
}var a=this._getNextVisibleTab();
if(a){a._updateAppearance(c);
}},_renderChildren:function(){var b=this._createChildListElement();
var a=[];
this.get_tabs().forEach(function(c){c._render(a);
});
b.innerHTML=a.join("");
},_cacheDomProperties:function(){this.get_text();
this.get_navigateUrl();
},_cleanElements:function(){this._cacheDomProperties();
this.get_tabs().forEach(function(a){a._cacheDomProperties();
a._cleanElements();
});
this.get_parent().get_childListElement().removeChild(this.get_element());
this._element=null;
if($telerik.getChildrenByTagName(this.get_parent().get_childListElement(),"li")<1){this.get_parent()._destroyChildListElement();
}},_getLevelIndex:function(){if(this.get_tabStrip()._ascendingRendering()){return this.get_level()+1;
}return this.get_tabStrip()._getLevelElements().length-this.get_level()-2;
},_getFirstVisibleIndex:function(){var c=this.get_parent().get_tabs();
for(var b=0,a=c.get_count();
b<a;
b++){if(c.getTab(b).get_visible()){return b;
}}return c.get_count();
},_getLastVisibleIndex:function(){var b=this.get_parent().get_tabs();
for(var a=b.get_count()-1;
a>-1;
a--){if(b.getTab(a).get_visible()){return a;
}}return -1;
},_updateAppearance:function(c){if(!this.get_element()){return;
}var b=this.get_index();
if(this.get_linkElement()){this._setCssClass(this.get_linkElement(),this._determineCssClass(b));
}this._updateImage();
if(c){return;
}var a="rtsLI";
if(b==this._getFirstVisibleIndex()){a+=" rtsFirst";
}if(b==this._getLastVisibleIndex()){a+=" rtsLast";
}if(this.get_outerCssClass()){a+=" "+this.get_outerCssClass();
}this._setCssClass(this.get_element(),a);
},_determineImage:function(){var a=this.get_imageUrl();
if(this.get_selected()&&this.get_selectedImageUrl()){a=this.get_selectedImageUrl();
}if(!this.get_enabled()&&this.get_disabledImageUrl()){a=this.get_disabledImageUrl();
}return a;
},_updateImage:function(){if(!this.get_element()){return;
}var b=this._determineImage();
if(!b){return;
}if(!this.get_imageElement()){var a=document.createElement("img");
a.className="rtsImg";
a.alt="";
this.get_innerWrapElement().insertBefore(a,this.get_textElement());
}if(this.get_imageElement().src!=b){this.get_imageElement().src=b;
}},_setChildListDisplay:function(a){var d=this.get_tabStrip();
var b=this;
while(b){var c=b.get_childListElement();
if(c){c.style.display=a;
if(a!="none"&&d._align==Telerik.Web.UI.TabStripAlign.Justify){Telerik.Web.UI.RadTabStrip._justify(c,d._orientation);
}}b=b.get_selectedTab();
}},_setHighlight:function(e){var a=this.get_previousTab();
var b=this.get_nextTab();
if(a){var c=a.get_linkElement();
if(c){if(e){Sys.UI.DomElement.addCssClass(c,"rtsHoverBefore");
}else{Sys.UI.DomElement.removeCssClass(c,"rtsHoverBefore");
}}}if(b){var d=b.get_linkElement();
if(d){if(e){Sys.UI.DomElement.addCssClass(d,"rtsHoverAfter");
}else{Sys.UI.DomElement.removeCssClass(d,"rtsHoverAfter");
}}}},_highlight:function(){if(this.get_hoveredCssClass()){Sys.UI.DomElement.addCssClass(this.get_linkElement(),this.get_hoveredCssClass());
}this._setHighlight(true);
if(!this.get_enabled()){return;
}if(!this.get_hoveredImageUrl()){return;
}if(!this.get_imageElement()){return;
}if(this.get_imageElement().src!=this.get_hoveredImageUrl()){this.get_imageElement().src=this.get_hoveredImageUrl();
}},_unhighlight:function(){if(this.get_hoveredCssClass()){Sys.UI.DomElement.removeCssClass(this.get_linkElement(),this.get_hoveredCssClass());
}this._setHighlight(false);
this._updateImage();
},_shouldPostBack:function(){var a=this.get_tabStrip();
if(!a){return false;
}return this.get_postBack()&&a._postBackReference!=null;
},_initialize:function(a,b){Telerik.Web.UI.RadTab.callBaseMethod(this,"_initialize",[a,b]);
this._perTabScrolling=this._properties.getValue("perTabScrolling",false);
this._scrollChildren=this._properties.getValue("scrollChildren",false);
this._scrollButtonsPosition=this._properties.getValue("scrollButtonsPosition",Telerik.Web.UI.TabStripScrollButtonsPosition.Right);
this._ensureChildControls();
},_dispose:function(){Telerik.Web.UI.RadTab.callBaseMethod(this,"_dispose");
if(this._scroller){this._scroller.dispose();
}},_initScrolling:function(){if(this.get_selected()&&this._requiresScrolling()){this.get_tabStrip()._initScrollingForTabContainer(this);
}},_selectPageView:function(b){var a=this.get_pageView();
if(a){a._select(b);
}if(this.get_selectedIndex()>-1){this.get_selectedTab()._selectPageView(b);
}},_getGlobalIndex:function(){return Array.indexOf(this.get_tabStrip().get_allTabs(),this);
},scrollIntoView:function(){var b=this.get_parent();
if(!b){return;
}var a=b._scroller;
if(!a){return;
}var e=this.get_tabStrip();
if(!e){return;
}a._scrollTo(a._minPosition);
var d=e._isVertical?"offsetTop":"offsetLeft";
var c=this.get_element()[d];
c=Math.min(c,a._maxPosition);
c=Math.max(c,a._minPosition);
a.set_currentPosition(c);
a._currentTabIndex=this.get_index();
e._updateScrollState(b,b._scroller._currentPosition);
},scrollIntoViewWhenNeeded:function(){var j=this.get_parent();
if(!j){return;
}var k=j.get_levelElement();
if(!k){return;
}var c=j._scroller;
if(!c){return;
}var p=this.get_tabStrip();
if(!p){return;
}if(!$telerik.isIE6&&!$telerik.isIE7&&!$telerik.quirksMode){k[p._isVertical?"scrollTop":"scrollLeft"]=0;
}var h=j.get_childListElement();
var d=p._isVertical?"offsetTop":"offsetLeft";
var i=p._isVertical?"offsetHeight":"offsetWidth";
var a=c._getMinScrollImageSize();
var n=c._getMaxScrollImageSize();
var e=-h[d];
var b=e+k[i];
var f=b-e;
var o=Math.abs(this.get_element()[d]);
var l=this.get_element()[i];
var m=o+l;
if(o<e+a||m>b-n){var g=0;
if(($telerik.isIE6||$telerik.isIE7||$telerik.quirksMode)&&p._rightToLeft){if(e-o<m-b){g=m+a-c._tabsWidth;
}else{g=o-a+f-c._tabsWidth;
}}else{if(e-o>m-b){g=o-a;
}else{g=m-f+n;
}}c.set_currentPosition(g);
if(p._perTabScrolling){c._currentTabIndex=this.get_index();
}p._updateScrollState(j,j._scroller._currentPosition);
}},get_nextTab:function(){return this.get_nextSibling();
},get_previousTab:function(){return this.get_previousSibling();
},click:function(b){if(!this.get_isEnabled()){if(b.preventDefault){b.preventDefault();
}return false;
}var a=this.get_tabStrip();
if(!a){return false;
}if(a.get_causesValidation()){if(typeof(Page_ClientValidate)!=="undefined"&&!Page_ClientValidate(a.get_validationGroup())){return false;
}}if(!this.select(b)){return false;
}if(this._shouldNavigate()){return true;
}if(this._shouldPostBack()){a._postback(this);
}return false;
},get_pageView:function(){var b=this.get_tabStrip().get_multiPage();
if(!b){return null;
}if(this.get_pageViewID()){return b.findPageViewByID(this.get_pageViewID());
}var a=this._properties.getValue("_implPageViewID","");
if(a){return b.findPageViewByID(a);
}return b.get_pageViews().getPageView(this._getGlobalIndex());
},get_pageViewID:function(){return this._properties.getValue("pageViewID",null);
},set_pageViewID:function(a){this._properties.setValue("pageViewID",a);
},get_target:function(){if(this.get_linkElement()){return this._properties.getValue("target",this.get_linkElement().target);
}return this._properties.getValue("target",null);
},set_target:function(a){this._properties.setValue("target",a,true);
if(this.get_linkElement()){this.get_linkElement().target=a;
}},get_navigateUrl:function(){return this._getNavigateUrl();
},set_navigateUrl:function(a){this._properties.setValue("navigateUrl",a,true);
if(this.get_linkElement()){this.get_linkElement().href=a;
}},get_postBack:function(){return this._properties.getValue("postback",true);
},set_postBack:function(a){this._properties.setValue("postback",a,true);
},get_selected:function(){if(!this.get_parent()){return false;
}return this.get_index()==this.get_parent().get_selectedIndex();
},set_selected:function(a){if(a){this.select();
}else{this.unselect();
}},selectParents:function(){var b=[];
var c=this;
while(c!=this.get_tabStrip()){b[b.length]=c;
c=c.get_parent();
}var a=b.length;
while(a--){b[a].select();
}},select:function(f){var d=this.get_parent();
if(!d){this._cachedSelected=true;
return true;
}var a=this._shouldNavigate();
var g=d.get_selectedTab();
var b=this.get_tabStrip();
if(!a&&g==this&&!b.get_clickSelectedTab()){return false;
}if(b._raiseCancelEvent("tabSelecting",this,f)){return false;
}var c=this._shouldPostBack()||(a&&(!this.get_target()||this.get_target()=="_self"));
if(!f){c=false;
}if(g&&g!=this){g.unselect(c,f);
}d._setSelectedIndex(this.get_index());
b._registerSelectedTab(this);
if(!c){this._updateAppearance(true);
this._updateSiblings(true);
this._setChildListDisplay("");
if(this._scroller){this._scroller._showArrows();
}else{b._scrollInitInProgress=true;
this._initScrolling();
b._scrollInitInProgress=false;
}if(b._reorderTabsOnSelect){Telerik.Web.UI.RadTabStrip._reorderTabs(d.get_childListElement(),this.get_element());
}}if(b.get_multiPage()){this._selectPageView(c);
}b._raiseEvent("tabSelected",this,f);
return true;
},unselect:function(d,f){var a=this.get_parent();
if(!a){return;
}if(!this.get_selected()){return;
}a._setSelectedIndex(-1);
var c=this.get_tabStrip();
c._unregisterSelectedTab(this);
if(!d){this._setChildListDisplay("none");
if(this._scroller){this._scroller._hideArrows();
}this._updateAppearance(true);
this._updateSiblings(true);
}var b=this.get_selectedTab();
if(c.get_unselectChildren()&&b){b.unselect(d);
}c._raiseEvent("tabUnSelected",this,f);
},get_selectedIndex:function(){return this._properties.getValue("selectedIndex",-1);
},_setSelectedIndex:function(a){this._properties.setValue("selectedIndex",a);
},set_selectedIndex:function(a){if(a>-1){var b=this.get_tabs().getTab(a);
if(b){b.select();
}}else{var c=this.get_selectedTab();
if(c){c.unselect();
}}},get_selectedTab:function(){return this.get_tabs().getTab(this.get_selectedIndex())||null;
},get_tabStrip:function(){return this._getControl();
},get_isSeparator:function(){return this._properties.getValue("isSeparator",false);
},set_isSeparator:function(a){this._properties.setValue("isSeparator",a);
},get_tabData:function(){return this.get_itemData();
},get_levelElement:function(){if(!this._levelElement){this._levelElement=this._getControl()._getLevelElements()[this._getLevelIndex()]||null;
}return this._levelElement;
},get_textElement:function(){if(this.get_isSeparator()){return this.get_element();
}if(!this.get_innerWrapElement()){return null;
}if(!this._textElement){this._textElement=$telerik.getChildByClassName(this.get_innerWrapElement(),"rtsTxt");
}return this._textElement;
},get_linkElement:function(){if(!this.get_element()){return null;
}if(!this._linkElement){this._linkElement=$telerik.getChildByClassName(this.get_element(),"rtsLink");
}return this._linkElement;
},get_imageElement:function(){if(!this.get_innerWrapElement()){return null;
}if(!this._imageElement){this._imageElement=$telerik.getChildByClassName(this.get_innerWrapElement(),"rtsImg");
}return this._imageElement;
},get_outerWrapElement:function(){if(!this.get_linkElement()){return null;
}if(!this._outerWrapElement){this._outerWrapElement=$telerik.getChildByClassName(this.get_linkElement(),"rtsOut");
}return this._outerWrapElement;
},get_innerWrapElement:function(){if(!this.get_outerWrapElement()){return null;
}if(!this._innerWrapElement){this._innerWrapElement=$telerik.getChildByClassName(this.get_outerWrapElement(),"rtsIn");
}return this._innerWrapElement;
},get_childListElement:function(){if(!this._childListElement){var a=this._getListItemsForTheCurrentLevel();
if(!a){return null;
}this._childListElement=a[this._getChildListIndex()]||null;
}return this._childListElement;
},get_tabs:function(){return this._getChildren();
},enable:function(){this.set_enabled(true);
},disable:function(){this.set_enabled(false);
},set_visible:function(a){Telerik.Web.UI.RadTab.callBaseMethod(this,"set_visible",[a]);
if(a){this.show();
}else{this.hide();
}},show:function(){this.get_element().style.display="";
this._updateSiblings();
},hide:function(){this.get_element().style.display="none";
this._updateSiblings();
this.unselect();
},set_enabled:function(a){Telerik.Web.UI.RadTab.callBaseMethod(this,"set_enabled",[a]);
this._updateAppearance();
},get_disabledCssClass:function(){return this._properties.getValue("disabledCssClass",null);
},set_disabledCssClass:function(a){this._properties.setValue("disabledCssClass",a,true);
this._updateAppearance();
},get_selectedCssClass:function(){return this._properties.getValue("selectedCssClass",null);
},set_selectedCssClass:function(a){this._properties.setValue("selectedCssClass",a,true);
this._updateAppearance();
},get_hoveredCssClass:function(){return this._properties.getValue("hoveredCssClass",null);
},set_hoveredCssClass:function(a){this._properties.setValue("hoveredCssClass",a,true);
},get_cssClass:function(){return this._properties.getValue("cssClass",null);
},set_cssClass:function(a){this._properties.setValue("cssClass",a,true);
this._updateAppearance();
},get_outerCssClass:function(){return this._properties.getValue("outerCssClass",null);
},set_outerCssClass:function(a){this._properties.setValue("outerCssClass",a,true);
this._updateAppearance();
},get_imageUrl:function(){return this._properties.getValue("imageUrl",null);
},set_imageUrl:function(a){this._properties.setValue("imageUrl",a,true);
this._updateImage();
},get_selectedImageUrl:function(){return this._properties.getValue("selectedImageUrl",null);
},set_selectedImageUrl:function(a){this._properties.setValue("selectedImageUrl",a,true);
this._updateImage();
},get_disabledImageUrl:function(){return this._properties.getValue("disabledImageUrl",null);
},set_disabledImageUrl:function(a){this._properties.setValue("disabledImageUrl",a,true);
this._updateImage();
},get_hoveredImageUrl:function(){return this._properties.getValue("hoveredImageUrl",null);
},set_hoveredImageUrl:function(a){this._properties.setValue("hoveredImageUrl",a,true);
},get_isBreak:function(){return this._properties.getValue("isBreak",false);
},set_isBreak:function(a){this._properties.setValue("isBreak",a,true);
}};
Telerik.Web.UI.RadTab.registerClass("Telerik.Web.UI.RadTab",Telerik.Web.UI.ControlItem);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadTabCollection=function(a){Telerik.Web.UI.RadTabCollection.initializeBase(this,[a]);
this._tabStrip=a.get_tabStrip?a.get_tabStrip():a;
};
Telerik.Web.UI.RadTabCollection.prototype={getTab:function(a){return this.getItem(a);
},add:function(b){Telerik.Web.UI.RadTabCollection.callBaseMethod(this,"add",[b]);
if(this._parent){if(this._parent._scroller){this._parent._scroller.repaint();
}else{var a=this._parent;
var c=this._tabStrip;
setTimeout(function(){if(a._scrollChildren&&!a._scroller){if(c._tabContainerRequiresScrolling(a)){a._initScrolling();
}}},0);
}}}};
Telerik.Web.UI.RadTabCollection.registerClass("Telerik.Web.UI.RadTabCollection",Telerik.Web.UI.ControlItemCollection);
Type.registerNamespace("Telerik.Web.UI");
$telerik.findTabStrip=$find;
$telerik.toTabStrip=function(a){return a;
};
Telerik.Web.UI.TabStripOrientation=function(){};
Telerik.Web.UI.TabStripOrientation.prototype={HorizontalTop:0,HorizontalBottom:1,VerticalRight:2,VerticalLeft:3};
Telerik.Web.UI.TabStripOrientation.isHorizontal=function(a){return a==Telerik.Web.UI.TabStripOrientation.HorizontalTop||a==Telerik.Web.UI.TabStripOrientation.HorizontalBottom;
};
Telerik.Web.UI.TabStripOrientation.isVertical=function(a){return !Telerik.Web.UI.TabStripOrientation.isHorizontal(a);
};
Telerik.Web.UI.TabStripOrientation.registerEnum("Telerik.Web.UI.TabStripOrientation");
Telerik.Web.UI.TabStripAlign=function(){};
Telerik.Web.UI.TabStripAlign.prototype={Left:0,Center:1,Right:2,Justify:3};
Telerik.Web.UI.TabStripAlign.registerEnum("Telerik.Web.UI.TabStripAlign");
Telerik.Web.UI.TabStripScrollButtonsPosition=function(){};
Telerik.Web.UI.TabStripScrollButtonsPosition.prototype={Left:0,Middle:1,Right:2};
Telerik.Web.UI.TabStripScrollButtonsPosition.registerEnum("Telerik.Web.UI.TabStripScrollButtonsPosition");
Telerik.Web.UI.RadTabStripCancelEventArgs=function(a,b){Telerik.Web.UI.RadTabStripCancelEventArgs.initializeBase(this);
this._tab=a;
this._domEvent=b;
};
Telerik.Web.UI.RadTabStripCancelEventArgs.prototype={get_tab:function(){return this._tab;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.RadTabStripCancelEventArgs.registerClass("Telerik.Web.UI.RadTabStripCancelEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.RadTabStripEventArgs=function(a,b){Telerik.Web.UI.RadTabStripEventArgs.initializeBase(this);
this._tab=a;
this._domEvent=b;
};
Telerik.Web.UI.RadTabStripEventArgs.prototype={get_tab:function(){return this._tab;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.RadTabStripEventArgs.registerClass("Telerik.Web.UI.RadTabStripEventArgs",Sys.EventArgs);
Telerik.Web.UI.RadTabStrip=function(a){Telerik.Web.UI.RadTabStrip.initializeBase(this,[a]);
this._childTypeName="Telerik.Web.UI.RadTab";
this._orientation=Telerik.Web.UI.TabStripOrientation.HorizontalTop;
this._align=Telerik.Web.UI.TabStripAlign.Left;
this._selectedIndex=-1;
this._selectedIndexes=[];
this._selectedIndexesJson="[]";
this._logEntriesJson="[]";
this._scrollState={};
this._scrollStateJson="{}";
this._multiPageID=null;
this._causesValidation=true;
this._validationGroup="";
this._postBackReference=null;
this._scrollChildren=false;
this._scrollButtonsPosition=Telerik.Web.UI.TabStripScrollButtonsPosition.Right;
this._perTabScrolling=false;
this._reorderTabsOnSelect=false;
this._rightToLeft=false;
this._skin=null;
this._isVertical=false;
};
Telerik.Web.UI.RadTabStrip._getTabGroups=function(c,e){var d=[];
var a=[];
a.size=0;
Array.add(d,a);
var f=$telerik.getChildrenByTagName(c,"li");
for(var b=0;
b<f.length;
b++){if(f[b].className=="rtsBreak"){a=[];
a.size=0;
Array.add(d,a);
continue;
}a.size+=f[b][e];
Array.add(a,f[b]);
}return d;
};
Telerik.Web.UI.RadTabStrip._reorder=function(b,d){var g=$get(b);
if(!g){return;
}var e=$telerik.getChildByClassName(g,"rtsLevel1");
if(!e){return;
}var a=$telerik.getFirstChildByTagName(e,"ul");
if(!a){return;
}var f=$telerik.getChildrenByClassName(a,"rtsLI");
var c=f[d];
if(!c){return;
}Telerik.Web.UI.RadTabStrip._reorderTabs(a,c);
};
Telerik.Web.UI.RadTabStrip._reorderTabs=function(c,e){var d=Telerik.Web.UI.RadTabStrip._getTabGroups(c);
if(d.length<2){return;
}var f=d[d.length-1];
var a=null;
for(var b=0;
b<d.length;
b++){if(Array.indexOf(d[b],e)>-1){a=d[b];
break;
}}if(!a||a==f){return;
}for(var b=0;
b<f.length;
b++){c.insertBefore(f[b],a[0]);
}for(var b=0;
b<a.length;
b++){c.appendChild(a[b]);
}};
Telerik.Web.UI.RadTabStrip._align=function(c,d,a){var b=$get(c);
if(d!=Telerik.Web.UI.TabStripAlign.Justify&&Telerik.Web.UI.TabStripOrientation.isHorizontal(a)){return;
}if(d==Telerik.Web.UI.TabStripAlign.Left||b._aligned){return;
}if(d==Telerik.Web.UI.TabStripAlign.Justify){Telerik.Web.UI.RadTabStrip._justifyTabStrip(b,a);
return;
}Telerik.Web.UI.RadTabStrip._verticalAlign(b,d,a);
};
Telerik.Web.UI.RadTabStrip._justifyTabStrip=function(f,b){var g=$telerik.getChildrenByTagName(f,"div");
if(g.length<1){return;
}for(var d=0;
d<g.length;
d++){var e=g[d];
var a=$telerik.getChildrenByTagName(e,"ul");
if(a.length<1){return;
}for(var c=0;
c<a.length;
c++){Telerik.Web.UI.RadTabStrip._justify(a[c],b);
}}};
Telerik.Web.UI.RadTabStrip._justify=function(b,a){var d="offsetWidth";
var c=function(e,f){e.style.width=f+"px";
};
if(Telerik.Web.UI.TabStripOrientation.isVertical(a)){d="offsetHeight";
c=function(g,e){g.firstChild.firstChild.firstChild.style.height=e+"px";
var f=g.offsetHeight-e;
if(f>0){g.firstChild.firstChild.firstChild.style.height=e-f+"px";
}};
}Telerik.Web.UI.RadTabStrip._justifyListElement(b,d,c);
};
Telerik.Web.UI.RadTabStrip._justifyListElement=function(e,j,g){var l=e.parentNode[j];
if(l<=0){return;
}var k=Telerik.Web.UI.RadTabStrip._getTabGroups(e,j);
for(var d=0;
d<k.length;
d++){var b=k[d];
if(b.size<=0){continue;
}var f=[];
for(var c=0;
c<b.length;
c++){f[c]=b[c][j]/b.size;
}var h=0;
var c=0;
for(;
c<b.length-1;
c++){var a=Math.round(l*f[c]);
g(b[c],a);
h+=a;
}g(b[c],l-h);
}};
Telerik.Web.UI.RadTabStrip._verticalAlign=function(f,e,a){var d=$telerik.getChildByClassName(f,"rtsLevel1");
if(!d){return;
}var b=$telerik.getChildByClassName(d,"rtsUL");
if(!b){return;
}var c=0;
if(e==Telerik.Web.UI.TabStripAlign.Center){c=(d.offsetHeight-b.offsetHeight)/2;
}if(e==Telerik.Web.UI.TabStripAlign.Right){c=d.offsetHeight-b.offsetHeight;
}if(c>0){b.style.marginTop=c+"px";
f._aligned=true;
}};
Telerik.Web.UI.RadTabStrip._createChildControls=function(e,f){var c=e.get_tabData();
if(!c){return;
}var g=$telerik.getChildrenByClassName(e.get_childListElement(),"rtsLI");
for(var a=0;
a<c.length;
a++){var b=new Telerik.Web.UI.RadTab();
f.add(b);
var d=a;
if(typeof(c[a].index)!=="undefined"){d=c[a].index;
}b._initialize(c[a],g[d]);
}};
Telerik.Web.UI.RadTabStrip.prototype={_initScrolling:function(){var c=this;
while(c){if(this._tabContainerRequiresScrolling(c)){if(c._scroller){c._scroller._showArrows();
var b=this._getScrollableSize(c);
var a=b-c._scroller._currentPosition;
if(a<0){c._scroller.set_currentPosition(b);
}c._scroller.setScrollingLimits(0,b);
c._scroller.repaint();
}else{this._initScrollingForTabContainer(c);
}}else{if(c._scroller){c._scroller._hideArrows();
c._scroller.set_currentPosition(0);
}}c=c.get_selectedTab();
}this.updateClientState();
},_initScrollingForTabContainer:function(a){a.get_levelElement().style.position="relative";
var b=Telerik.Web.UI.ScrollerOrientation.Horizontal;
if(this._isVertical){b=Telerik.Web.UI.ScrollerOrientation.Vertical;
}a._scroller=new Telerik.Web.UI.TabScroller(a,b);
a._scroller.initialize();
var c=-a._scroller._getMinScrollImageSize();
if(a._rightToLeft&&!this._isVertical){c=this._getScrollableSize(a)+a._scroller._getMaxScrollImageSize();
}if(a.get_childListElement().style.left){c=-parseInt(a.get_childListElement().style.left,10);
}if(this._isVertical&&a.get_childListElement().style.top){c=-parseInt(a.get_childListElement().style.top,10);
}a._scroller.setScrollingLimits(0,this._getScrollableSize(a));
a._scroller.set_currentPosition(c);
a._scroller._calculateInitialTab();
a._scroller._updateArrows();
this._updateScrollState(a,c);
},_getScrollableSize:function(a){if(this._isVertical){return this._getTabsSize(a,"offsetHeight")-a.get_levelElement().offsetHeight;
}return this._getTabsSize(a,"offsetWidth")-a.get_levelElement().offsetWidth;
},_getTabsSize:function(b,e){var c=Telerik.Web.UI.RadTabStrip._getTabGroups(b.get_childListElement(),e);
var a=0;
for(var d=0;
d<c.length;
d++){if(a<c[d].size){a=c[d].size;
}}return a;
},_tabContainerRequiresScrolling:function(a){if(!a._scrollChildren){return false;
}var b=a.get_levelElement();
if(!b){return false;
}if(this._isVertical){return b.offsetHeight<this._getTabsSize(this,"offsetHeight");
}return b.offsetWidth<this._getTabsSize(a,"offsetWidth");
},_createChildControls:function(){this._children=new Telerik.Web.UI.RadTabCollection(this);
Telerik.Web.UI.RadTabStrip._createChildControls(this,this._children);
},_getLevelElements:function(){if(!this._levelElements){this._levelElements=$telerik.getChildrenByTagName(this.get_element(),"div");
}return this._levelElements;
},_getListElementsForLevel:function(a){return this._listElementsPerLevel[a];
},_childInserting:function(b,c,a){if(!a._childControlsCreated){return;
}this._cachedSelectedTab=a.get_selectedTab();
},_childInserted:function(b,c,a){this._allTabs=null;
if(this._cachedSelectedTab){a._setSelectedIndex(this._cachedSelectedTab.get_index());
this._cachedSelectedTab=null;
}if(c._cachedSelected){a._setSelectedIndex(b);
c._cachedSelected=false;
}Telerik.Web.UI.RadTabStrip.callBaseMethod(this,"_childInserted",[b,c,a]);
if(c.get_isBreak()){var d=document.createElement("li");
d.className="rtsBreak";
a.get_childListElement().insertBefore(d,c.get_element().nextSibling);
}},_childRemoving:function(a){if(a.get_selected()){a.unselect();
}a._cleanElements();
Telerik.Web.UI.RadTabStrip.callBaseMethod(this,"_childRemoving",[a]);
},_childRemoved:function(b,a){this._allTabs=null;
var d=a.get_tabs().getTab(0);
if(d){d._updateAppearance();
}var c=a.get_tabs().getTab(a.get_tabs().get_count()-1);
if(c){c._updateAppearance();
}Telerik.Web.UI.RadTabStrip.callBaseMethod(this,"_childRemoved",[b,a]);
},_childrenCleared:function(a){this._allTabs=null;
a.get_tabs().forEach(function(b){b._cleanElements();
});
Telerik.Web.UI.RadTabStrip.callBaseMethod(this,"_childrenCleared",[a]);
},_destroyChildren:function(a){a.get_levelElement().removeChild(a.get_childListElement());
Array.remove(this._listElementsPerLevel[a._getLevelIndex()],a.get_childListElement());
if(this._listElementsPerLevel[a._getLevelIndex()].length<1){Array.removeAt(this._listElementsPerLevel,a._getLevelIndex());
Array.remove(this._levelElements,a.get_levelElement());
this.get_element().removeChild(a.get_levelElement());
a._levelElement=null;
}a._childListElement=null;
},_destroyChildListElement:function(){this._destroyChildren(this);
},_ensureElements:function(){if(!this.get_childListElement()){this._createChildListElement();
}},_createLevelElement:function(c){var a=document.createElement("div");
var b="rtsLevel";
if(this._align==Telerik.Web.UI.TabStripAlign.Center){b+=" rtsCenter";
}if(this._align==Telerik.Web.UI.TabStripAlign.Right){b+=" rtsRight";
}a.className=b+" rtsLevel"+c;
if(this._ascendingRendering()){Array.add(this._listElementsPerLevel,[]);
Array.add(this._levelElements,a);
this.get_element().appendChild(a);
}else{Array.insert(this._listElementsPerLevel,0,[]);
Array.insert(this._levelElements,0,a);
this.get_element().insertBefore(a,this.get_element().firstChild);
}return a;
},_createChildListElement:function(){var b=document.createElement("ul");
b.className="rtsUL";
var a=this._createLevelElement(1);
a.appendChild(b);
Array.add(this._listElementsPerLevel[this._getLevelIndex()],b);
return b;
},_initLevelElements:function(){this._listElementsPerLevel=[];
var a=this._getLevelElements();
for(var b=0;
b<a.length;
b++){Array.add(this._listElementsPerLevel,$telerik.getChildrenByTagName(a[b],"ul"));
}},_ascendingRendering:function(){return this._orientation!=Telerik.Web.UI.TabStripOrientation.HorizontalBottom;
},_getLevelIndex:function(){if(this._ascendingRendering()){return 0;
}return this._getLevelElements().length-1;
},_unregisterSelectedTab:function(a){Array.remove(this._selectedIndexes,a._getHierarchicalIndex());
this._updateSelectedState();
},_registerSelectedTab:function(a){Array.add(this._selectedIndexes,a._getHierarchicalIndex());
this._updateSelectedState();
},_updateSelectedState:function(){this._selectedIndexesJson=Sys.Serialization.JavaScriptSerializer.serialize(this._selectedIndexes);
this.updateClientState();
},_getHierarchicalIndex:function(){return"-1";
},_updateScrollState:function(a,b){this._scrollState[a._getHierarchicalIndex()]=-b;
this._scrollStateJson=Sys.Serialization.JavaScriptSerializer.serialize(this._scrollState);
this.updateClientState();
},_postback:function(a){if(!this._postBackReference){return;
}eval(String.format(this._postBackReference,a._getHierarchicalIndex()));
},_raiseCancelEvent:function(b,c,a){var d=new Telerik.Web.UI.RadTabStripCancelEventArgs(c,a);
this.raiseEvent(b,d);
return d.get_cancel();
},_raiseEvent:function(b,c,a){this.raiseEvent(b,new Telerik.Web.UI.RadTabStripEventArgs(c,a));
},_resize:function(a){if(!this._scrollInitInProgress){this._initScrolling();
}this.get_element()._aligned=null;
Telerik.Web.UI.RadTabStrip._align(this.get_id(),this._align,this._orientation);
},_doubleClick:function(b){var a=this._extractItemFromDomElement(b.eventMapTarget);
this._raiseEvent("doubleClick",a,b);
},_mouseOver:function(b){var a=this._extractItemFromDomElement(b.eventMapTarget);
if(this._highlightedTab==a){return;
}if(this._highlightedTab){this._highlightedTab._unhighlight();
}a._highlight();
this._highlightedTab=a;
this._raiseEvent("mouseOver",a,b);
},_mouseOut:function(a){if(!this._highlightedTab){return;
}if(!a.eventMapRelatedTarget){return;
}if($telerik.isDescendant(this._highlightedTab.get_element(),a.eventMapRelatedTarget)){return;
}this._highlightedTab._unhighlight();
this._raiseEvent("mouseOut",this._highlightedTab,a);
this._highlightedTab=null;
},_contextMenu:function(b){var a=this._extractItemFromDomElement(b.eventMapTarget);
this._raiseEvent("contextMenu",a,b);
},_click:function(c){if(this._eventMap.skipElement(c,"rtsLink")){return;
}var b=this._extractItemFromDomElement(c.eventMapTarget);
var a=b.get_linkElement();
if(a&&Sys.UI.DomElement.containsCssClass(a,"rtsClicked")){b.scrollIntoViewWhenNeeded();
}if(!b.click(c)){c.preventDefault();
}},_mouseDown:function(c){var b=this._extractItemFromDomElement(c.eventMapTarget);
if(!b){return;
}var a=b.get_linkElement();
if(a){Sys.UI.DomElement.addCssClass(a,"rtsClicked");
if($telerik.isSafari){a.focus();
}}},_focus:function(c){var b=this._extractItemFromDomElement(c.eventMapTarget);
if(!b){return;
}var a=b.get_linkElement();
if(a){if(!Sys.UI.DomElement.containsCssClass(a,"rtsClicked")){b.scrollIntoViewWhenNeeded();
}}else{b.scrollIntoViewWhenNeeded();
}},_blur:function(c){var b=this._extractItemFromDomElement(c.eventMapTarget);
if(!b){return;
}var a=b.get_linkElement();
if(a){Sys.UI.DomElement.removeCssClass(a,"rtsClicked");
}},_activate:function(b){if(!b.altKey){return;
}var a=this._extractItemFromDomElement(b.eventMapTarget);
a.click();
},_requiresRtl:function(){var a=this.get_element();
if(a.className.indexOf("RadTabStrip_rtl")>-1){return false;
}return $telerik.isRightToLeft(a);
},_applyRtl:function(){this.get_element().className=String.format("{0} RadTabStrip_rtl RadTabStrip_{1}_rtl",this.get_element().className,this._skin);
},initialize:function(){this._initLevelElements();
Telerik.Web.UI.RadTabStrip.callBaseMethod(this,"initialize");
Telerik.Web.UI.RadTabStrip._align(this.get_id(),this._align,this._orientation);
this._updateSelectedState();
this._eventMap.addHandlerForClassName("click","rtsLI",this._click);
this._eventMap.addHandlerForClassName("mousedown","rtsLI",this._mouseDown);
this._eventMap.addHandlerForClassName("focus","rtsLink",this._focus);
this._eventMap.addHandlerForClassName("activate","rtsLink",this._focus);
this._eventMap.addHandlerForClassName("blur","rtsLink",this._blur);
this._eventMap.addHandlerForClassName("deactivate","rtsLink",this._blur);
this._eventMap.addHandlerForClassName("mouseover","rtsLI",this._mouseOver);
this._eventMap.addHandlerForClassName("mouseout","rtsLI",this._mouseOut);
this._eventMap.addHandlerForClassName("contextmenu","rtsLI",this._contextMenu);
this._eventMap.addHandlerForClassName("dblclick","rtsLI",this._doubleClick);
if($telerik.isIE){this._eventMap.addHandlerForClassName("activate","rtsLI",this._activate);
}this._resizeDelegate=Function.createDelegate(this,this._resize);
$telerik.addHandler(window,"resize",this._resizeDelegate);
if($telerik.isRightToLeft(this._element)){this._rightToLeft=true;
}if(this._requiresRtl()){this._applyRtl();
}this._isVertical=this._orientation==Telerik.Web.UI.TabStripOrientation.VerticalRight||this._orientation==Telerik.Web.UI.TabStripOrientation.VerticalLeft;
this._initScrolling();
this.raiseEvent("load");
},repaint:function(){this._resize();
},dispose:function(){Telerik.Web.UI.RadTabStrip.callBaseMethod(this,"dispose");
$telerik.removeHandler(window,"resize",this._resizeDelegate);
if(this._scroller){this._scroller.dispose();
}},commitChanges:function(){this._logEntriesJson=this._log.serialize();
Telerik.Web.UI.RadTabStrip.callBaseMethod(this,"commitChanges");
},enable:function(){this.set_enabled(true);
},disable:function(){this.set_enabled(false);
},set_enabled:function(b){Telerik.Web.UI.RadTabStrip.callBaseMethod(this,"set_enabled",[b]);
if(!this.get_isInitialized()){return;
}this.get_element().disabled=!b;
var a=String.format("RadTabStrip_{0}_disabled",this._skin);
this.toggleCssClass(a);
},get_causesValidation:function(){return this._causesValidation;
},set_causesValidation:function(a){this._causesValidation=a;
},get_validationGroup:function(){return this._validationGroup;
},set_validationGroup:function(a){this._validationGroup=a;
},get_unselectChildren:function(){return this._unselectChildren==true;
},set_unselectChildren:function(a){this._unselectChildren=a;
},get_selectedIndexes:function(){return this._selectedIndexes;
},set_selectedIndexes:function(a){this._selectedIndexes=a;
},saveClientState:function(){return'{"selectedIndexes":'+this._selectedIndexesJson+',"logEntries":'+this._logEntriesJson+',"scrollState":'+this._scrollStateJson+"}";
},get_selectedTab:function(){return this.get_tabs().getTab(this.get_selectedIndex())||null;
},get_selectedIndex:function(){return this._selectedIndex;
},set_selectedIndex:function(a){if(a>-1){var b=this.get_tabs().getTab(a);
if(b){b.select();
}}else{var c=this.get_selectedTab();
if(c){c.unselect();
}}},_setSelectedIndex:function(a){this._selectedIndex=a;
},get_levelElement:function(){if(!this._levelElement){this._levelElement=this._getLevelElements()[this._getLevelIndex()]||null;
}return this._levelElement;
},get_childListElement:function(){if(!this.get_levelElement()){return null;
}if(!this._childListElement){this._childListElement=$telerik.getChildByClassName(this.get_levelElement(),"rtsUL");
}return this._childListElement;
},get_tabData:function(){return this._tabData;
},set_tabData:function(a){this._tabData=a;
},get_tabs:function(){return this._getChildren();
},get_clickSelectedTab:function(){return this._clickSelectedTab==true;
},set_clickSelectedTab:function(a){this._clickSelectedTab=a;
},findTabByText:function(a){return this._findItemByText(a);
},findTabByValue:function(a){return this._findItemByValue(a);
},findTabByAttribute:function(a,b){return this._findItemByAttribute(a,b);
},findTabByUrl:function(a){return this._findItemByUrl(a);
},findTabByAbsoluteUrl:function(a){return this._findItemByAbsoluteUrl(a);
},get_allTabs:function(){if(!this._allTabs){this._allTabs=this._getAllItems();
}return this._allTabs;
},get_multiPage:function(){if(!this.get_multiPageID()){return null;
}return $find(this.get_multiPageID());
},set_multiPageID:function(a){this._multiPageID=a;
},get_multiPageID:function(){return this._multiPageID;
},add_tabSelecting:function(a){this.get_events().addHandler("tabSelecting",a);
},remove_tabSelecting:function(a){this.get_events().removeHandler("tabSelecting",a);
},add_tabSelected:function(a){this.get_events().addHandler("tabSelected",a);
},remove_tabSelected:function(a){this.get_events().removeHandler("tabSelected",a);
},add_tabUnSelected:function(a){this.get_events().addHandler("tabUnSelected",a);
},remove_tabUnSelected:function(a){this.get_events().removeHandler("tabUnSelected",a);
},add_load:function(a){this.get_events().addHandler("load",a);
},remove_load:function(a){this.get_events().removeHandler("load",a);
},add_mouseOver:function(a){this.get_events().addHandler("mouseOver",a);
},remove_mouseOver:function(a){this.get_events().removeHandler("mouseOver",a);
},add_mouseOut:function(a){this.get_events().addHandler("mouseOut",a);
},remove_mouseOut:function(a){this.get_events().removeHandler("mouseOut",a);
},add_contextMenu:function(a){this.get_events().addHandler("contextMenu",a);
},remove_contextMenu:function(a){this.get_events().removeHandler("contextMenu",a);
},add_doubleClick:function(a){this.get_events().addHandler("doubleClick",a);
},remove_doubleClick:function(a){this.get_events().removeHandler("doubleClick",a);
}};
Telerik.Web.UI.RadTabStrip.registerClass("Telerik.Web.UI.RadTabStrip",Telerik.Web.UI.ControlItemContainer);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.TabScroller=function(a,b){this._owner=a;
this._tabStrip=this._owner.get_tabStrip?this._owner.get_tabStrip():this._owner;
this._childListElement=a.get_childListElement();
this._levelElement=a.get_levelElement();
this._scrollDirection=this._owner._rightToLeft?-1:1;
this._tabsWidth=this._tabStrip._getTabsSize(this._owner,"offsetWidth");
this._tabsWidth+=2;
Telerik.Web.UI.TabScroller.initializeBase(this,[a.get_childListElement(),a.get_levelElement(),b]);
this._sizeAttribute="offsetHeight";
this._scrollMultiplier=2;
if($telerik.isIE8){this._scrollMultiplier=3;
}if(this._orientation!=Telerik.Web.UI.ScrollerOrientation.Vertical){this._sizeAttribute="offsetWidth";
this._childListElement.style.width=this._tabsWidth+"px";
this._childListElement.style.height="auto";
}};
Telerik.Web.UI.TabScroller.prototype={scrollRelative:function(a){this.set_currentPosition(this.get_currentPosition()+a);
},get_currentPosition:function(){return this._currentPosition;
},set_currentPosition:function(a){this._scrollTo(Math.max(Math.min(this._maxPosition,a),this._minPosition));
},repaint:function(){if(this._orientation!=Telerik.Web.UI.ScrollerOrientation.Vertical){this._tabsWidth=this._tabStrip._getTabsSize(this._owner,"offsetWidth");
this._childListElement.style.width=this._tabsWidth+"px";
}if(($telerik.isIE6||$telerik.isIE7||$telerik.quirksMode)&&this._owner._rightToLeft){this._minPosition=-this._tabStrip._getScrollableSize(this._tabStrip)-this._getMaxScrollImageSize();
}else{this._maxPosition=this._tabStrip._getScrollableSize(this._tabStrip)+this._getMaxScrollImageSize();
}this._updateArrows();
},_scrollTo:function(b){var a="left";
if(this._orientation==Telerik.Web.UI.ScrollerOrientation.Vertical){a="top";
}this._currentPosition=b;
this._scrolledElement.style[a]=-b+"px";
this._raiseEvent("positionChanged",Sys.EventArgs.Empty);
},_createArrow:function(a){var b=document.createElement("a");
b.className=a;
b.href="#";
b.innerHTML="&nbsp;";
b.style.position="relative";
return b;
},_preventDefault:function(a){a.preventDefault();
},_onTick:function(){var a=this._currentPosition+this._direction*this._speed;
this.set_currentPosition(a);
if(this.isAtMinPosition(a)||this.isAtMaxPosition(a)){this.stopScroll();
}},_scrollForward:function(){if(this._owner._perTabScrolling){this._scrollToNextTab(this._scrollDirection);
}else{this.startScroll(Telerik.Web.UI.ScrollerSpeed.Fast,this._scrollDirection*this._scrollMultiplier);
}},_stopScroll:function(){this.stopScroll();
this._owner._getControl()._updateScrollState(this._owner,this._currentPosition);
},_scrollBackward:function(){if(this._owner._perTabScrolling){this._scrollToNextTab(-this._scrollDirection);
}else{this.startScroll(Telerik.Web.UI.ScrollerSpeed.Fast,-this._scrollDirection*this._scrollMultiplier);
}},_positionChanged:function(){this._updateArrows();
},_ensureArrows:function(){if($telerik.isIE6||$telerik.isIE7||$telerik.quirksMode){this._previousArrow.style.cssText=this._previousArrow.style.cssText;
this._nextArrow.style.cssText=this._nextArrow.style.cssText;
}},_updateArrows:function(){var a="rtsPrevArrow";
if(this.isAtMinPosition()){a="rtsPrevArrowDisabled";
}if(this._previousArrow.className!=a){this._previousArrow.className=a;
}a="rtsNextArrow";
if(this.isAtMaxPosition()){a="rtsNextArrowDisabled";
}if(this._nextArrow.className!=a){this._nextArrow.className=a;
}this._ensureArrows();
},_positionArrowsHorizontally:function(a){this._nextArrow.style.position="absolute";
this._previousArrow.style.position="absolute";
this._previousArrow.style.top="0";
this._nextArrow.style.top="0";
if(a==Telerik.Web.UI.TabStripScrollButtonsPosition.Right){this._element.appendChild(this._nextArrow);
this._element.appendChild(this._previousArrow);
this._nextArrow.style.right="0";
this._previousArrow.style.right=this._nextArrow.offsetWidth+"px";
}else{if(a==Telerik.Web.UI.TabStripScrollButtonsPosition.Left){this._element.appendChild(this._previousArrow);
this._element.appendChild(this._nextArrow);
this._previousArrow.style.left="0";
this._nextArrow.style.left=this._previousArrow.offsetWidth+"px";
}else{this._element.appendChild(this._previousArrow);
this._element.appendChild(this._nextArrow);
this._previousArrow.style.left="0";
this._nextArrow.style.right="0";
}}},_positionArrowsVertically:function(a){this._element.style.position="relative";
this._nextArrow.style.position="absolute";
this._previousArrow.style.position="absolute";
this._nextArrow.style.left="0";
this._previousArrow.style.left="0";
this._element.appendChild(this._previousArrow);
this._element.appendChild(this._nextArrow);
if(a==Telerik.Web.UI.TabStripScrollButtonsPosition.Right){this._nextArrow.style.bottom="0";
this._previousArrow.style.bottom=this._nextArrow.offsetHeight+"px";
}else{if(a==Telerik.Web.UI.TabStripScrollButtonsPosition.Left){this._previousArrow.style.top="0";
this._nextArrow.style.top=this._previousArrow.offsetHeight+"px";
}else{this._previousArrow.style.top="0";
this._nextArrow.style.bottom="0";
}}},_positionArrows:function(a){if(this._orientation==Telerik.Web.UI.ScrollerOrientation.Horizontal){this._positionArrowsHorizontally(a);
}else{this._positionArrowsVertically(a);
}},_hideArrows:function(){this._nextArrow.style.display="none";
this._previousArrow.style.display="none";
},_showArrows:function(){this._nextArrow.style.display="";
this._previousArrow.style.display="";
},_nextScrollPosition:function(c){var b=this._owner.get_tabs();
var a=c<0?b.getTab(Math.max(0,this._currentTabIndex+c)):b.getTab(this._currentTabIndex+(this._owner._rightToLeft?-c:0));
if(a){return this._currentPosition+c*a.get_element()[this._sizeAttribute];
}return this._currentPosition;
},setScrollingLimits:function(b,d){var a=b;
var c=d;
if(($telerik.isIE6||$telerik.isIE7||$telerik.quirksMode)&&this._owner._rightToLeft){c=-b+this._getMaxScrollImageSize();
a=-d-this._getMinScrollImageSize();
}else{a-=this._getMinScrollImageSize();
c+=this._getMaxScrollImageSize();
}Telerik.Web.UI.TabScroller.callBaseMethod(this,"setScrollingLimits",[a,c]);
},isAtMinPosition:function(a){if(!a){return this._currentPosition<=this._minPosition;
}else{return a<=this._minPosition;
}},isAtMaxPosition:function(a){if(!a){return this._currentPosition>=this._maxPosition;
}else{return a>=this._maxPosition;
}},_getMinScrollImageSize:function(){if(this._owner._scrollButtonsPosition==Telerik.Web.UI.TabStripScrollButtonsPosition.Left){return this._nextArrow[this._sizeAttribute]+this._previousArrow[this._sizeAttribute];
}if(this._owner._scrollButtonsPosition==Telerik.Web.UI.TabStripScrollButtonsPosition.Middle){return this._nextArrow[this._sizeAttribute];
}return 0;
},_getMaxScrollImageSize:function(){if(this._owner._scrollButtonsPosition==Telerik.Web.UI.TabStripScrollButtonsPosition.Right){return this._nextArrow[this._sizeAttribute]+this._previousArrow[this._sizeAttribute];
}if(this._owner._scrollButtonsPosition==Telerik.Web.UI.TabStripScrollButtonsPosition.Middle){return this._nextArrow[this._sizeAttribute];
}return 0;
},_scrollToNextTab:function(b){if(b>0&&this.isAtMaxPosition()){return;
}if(b<0&&this.isAtMinPosition()){return;
}var c=this._nextScrollPosition(b);
if(c==this._currentPosition){return;
}this.set_currentPosition(c);
var a=this._owner.get_tabs();
this._currentTabIndex+=(this._owner._rightToLeft?(a.get_count()>this._currentTabIndex?-b:0):b);
},_calculateInitialTab:function(){if(!this._owner._perTabScrolling){return;
}var c=0;
var b=this._owner.get_tabs();
var a;
if(this._owner._rightToLeft&&this._orientation!=Telerik.Web.UI.ScrollerOrientation.Vertical){a=this._tabsWidth-this._currentPosition;
}else{a=this._currentPosition;
}while(c<a){c+=b.getTab(this._currentTabIndex).get_element()[this._sizeAttribute];
this._currentTabIndex++;
}},initialize:function(){Telerik.Web.UI.TabScroller.callBaseMethod(this,"initialize");
this._childListElement.style.position="relative";
if(this._owner._perTabScrolling){this._currentTabIndex=0;
}this._positionChangedDelegate=Function.createDelegate(this,this._positionChanged);
this.add_positionChanged(this._positionChangedDelegate);
this._nextArrow=this._createArrow("rtsNextArrow");
this._previousArrow=this._createArrow("rtsPrevArrow");
this._positionArrows(this._owner._scrollButtonsPosition);
this._nextArrowClickDelegate=Function.createDelegate(this,this._preventDefault);
this._scrollForwardDelegate=Function.createDelegate(this,this._scrollForward);
this._nextArrowMouseUpDelegate=Function.createDelegate(this,this._stopScroll);
this._previousArrowClickDelegate=Function.createDelegate(this,this._preventDefault);
this._scrollBackwardDelegate=Function.createDelegate(this,this._scrollBackward);
this._previousArrowMouseUpDelegate=Function.createDelegate(this,this._stopScroll);
if(this._owner._rightToLeft&&this._orientation!=Telerik.Web.UI.ScrollerOrientation.Vertical){$telerik.addHandler(this._nextArrow,"click",this._previousArrowClickDelegate);
$telerik.addHandler(this._nextArrow,"mousedown",this._scrollBackwardDelegate);
$telerik.addHandler(this._nextArrow,"mouseup",this._previousArrowMouseUpDelegate);
}else{$telerik.addHandler(this._nextArrow,"click",this._nextArrowClickDelegate);
$telerik.addHandler(this._nextArrow,"mousedown",this._scrollForwardDelegate);
$telerik.addHandler(this._nextArrow,"mouseup",this._nextArrowMouseUpDelegate);
}if(this._owner._rightToLeft&&this._orientation!=Telerik.Web.UI.ScrollerOrientation.Vertical){$telerik.addHandler(this._previousArrow,"click",this._nextArrowClickDelegate);
$telerik.addHandler(this._previousArrow,"mousedown",this._scrollForwardDelegate);
$telerik.addHandler(this._previousArrow,"mouseup",this._nextArrowMouseUpDelegate);
}else{$telerik.addHandler(this._previousArrow,"click",this._previousArrowClickDelegate);
$telerik.addHandler(this._previousArrow,"mousedown",this._scrollBackwardDelegate);
$telerik.addHandler(this._previousArrow,"mouseup",this._previousArrowMouseUpDelegate);
}},dispose:function(){Telerik.Web.UI.TabScroller.callBaseMethod(this,"dispose");
if(this._owner._rightToLeft&&this._orientation!=Telerik.Web.UI.ScrollerOrientation.Vertical){$telerik.removeHandler(this._nextArrow,"click",this._previousArrowClickDelegate);
$telerik.removeHandler(this._nextArrow,"mousedown",this._scrollBackwardDelegate);
$telerik.removeHandler(this._nextArrow,"mouseup",this._previousArrowMouseUpDelegate);
}else{$telerik.removeHandler(this._nextArrow,"click",this._nextArrowClickDelegate);
$telerik.removeHandler(this._nextArrow,"mousedown",this._scrollForwardDelegate);
$telerik.removeHandler(this._nextArrow,"mouseup",this._nextArrowMouseUpDelegate);
}if(this._owner._rightToLeft&&this._orientation!=Telerik.Web.UI.ScrollerOrientation.Vertical){$telerik.removeHandler(this._previousArrow,"click",this._nextArrowClickDelegate);
$telerik.removeHandler(this._previousArrow,"mousedown",this._scrollForwardDelegate);
$telerik.removeHandler(this._previousArrow,"mouseup",this._nextArrowMouseUpDelegate);
}else{$telerik.removeHandler(this._previousArrow,"click",this._previousArrowClickDelegate);
$telerik.removeHandler(this._previousArrow,"mousedown",this._scrollBackwardDelegate);
$telerik.removeHandler(this._previousArrow,"mouseup",this._previousArrowMouseUpDelegate);
}this._nextArrow=null;
this._previousArrow=null;
}};
Telerik.Web.UI.TabScroller.registerClass("Telerik.Web.UI.TabScroller",Telerik.Web.UI.Scroller);
