Type.registerNamespace("Telerik.Web.UI");
$telerik.findDatePicker=$find;
$telerik.toDatePicker=function(a){return a;
};
Telerik.Web.UI.RadDatePicker=function(a){Telerik.Web.UI.RadDatePicker.initializeBase(this,[a]);
this._calendar=null;
this._dateInput=null;
this._popupButton=null;
this._validationInput=null;
this._popupDirection=Telerik.Web.RadDatePickerPopupDirection.BottomRight;
this._enableScreenBoundaryDetection=true;
this._zIndex=null;
this._enableShadows=true;
this._animationSettings={};
this._popupControlID=null;
this._popupButtonSettings=null;
this._focusedDate="";
this._minDate=new Date(1980,0,1);
this._maxDate=new Date(2099,11,31);
this._enabled=true;
this._originalDisplay=null;
this._showPopupOnFocus=false;
this._enableAriaSupport=false;
this._onPopupImageMouseOverDelegate=null;
this._onPopupImageMouseOutDelegate=null;
this._onPopupButtonClickDelegate=null;
this._onPopupButtonKeyPressDelegate=null;
this._onDateInputFocusDelegate=null;
};
Telerik.Web.UI.RadDatePicker.PopupInstances={};
Telerik.Web.UI.RadDatePicker.prototype={initialize:function(){Telerik.Web.UI.RadDatePicker.callBaseMethod(this,"initialize");
this._initializeDateInput();
this._initializeCalendar();
var b=$get(this.get_id()+"_wrapper");
if($telerik.isIE7||$telerik.quirksMode){if(b.style.display=="inline-block"){b.style.display="inline";
b.style.zoom=1;
}else{if(document.documentMode&&document.documentMode>7&&b.style.display=="inline"){b.style.display="inline-block";
this.get_dateInput().repaint();
}}}if($telerik.getCurrentStyle(b,"direction")=="rtl"){var a=this.get_dateInput()._skin!=""?String.format(" RadPickerRTL_{0}",this.get_dateInput()._skin):"";
b.className+=String.format(" RadPickerRTL{0}",a);
}this._refreshPopupShadowSetting();
this.CalendarSelectionInProgress=false;
this.InputSelectionInProgress=false;
if(this.get_enableAriaSupport()){this._initializeAriaSupport();
}},dispose:function(){if(this._calendar!=null){this.hidePopup();
this._calendar.dispose();
}if(this._popupButton!=null){var a=this.get__popupImage();
if(a!=null){if(this._onPopupImageMouseOverDelegate){try{$removeHandler(a,"mouseover",this._onPopupImageMouseOverDelegate);
}catch(b){}this._onPopupImageMouseOverDelegate=null;
}if(this._onPopupImageMouseOutDelegate){try{$removeHandler(a,"mouseout",this._onPopupImageMouseOutDelegate);
}catch(b){}this._onPopupImageMouseOutDelegate=null;
}}if(this._onPopupButtonClickDelegate){try{$removeHandler(this._popupButton,"click",this._onPopupButtonClickDelegate);
}catch(b){}this._onPopupButtonClickDelegate=null;
}if(this._onPopupButtonKeyPressDelegate){try{$removeHandler(this._popupButton,"keypress",this._onPopupButtonKeyPressDelegate);
}catch(b){}this._onPopupButtonKeyPressDelegate=null;
}}if(this._popupButton){this._popupButton._events=null;
}Telerik.Web.UI.RadDatePicker.callBaseMethod(this,"dispose");
},clear:function(){if(this._dateInput){this._dateInput.clear();
}if(this._calendar){this._calendar.unselectDates(this._calendar.get_selectedDates());
}},_clearHovers:function(){var a=this.get_popupContainer().getElementsByTagName("td");
for(var b=0;
b<a.length;
b++){if(a[b].className&&a[b].className.indexOf("rcHover")!=-1){a[b].className=a[b].className.replace("rcHover","");
}}},togglePopup:function(){if(this.isPopupVisible()){this.hidePopup();
}else{this.showPopup();
}return false;
},isPopupVisible:function(){if(!this._calendar){return false;
}return this.get__popup().IsVisible()&&(this.get__popup().Opener==this);
},showPopup:function(a,b){if(this.isPopupVisible()||!this._calendar){return;
}this._actionBeforeShowPopup();
this.get__popup().ExcludeFromHiding=this.get__PopupVisibleControls();
this.hidePopup();
var d=true;
var g=new Telerik.Web.UI.DatePickerPopupOpeningEventArgs(this._calendar,false);
this.raise_popupOpening(g);
if(g.get_cancel()==true){return;
}d=!g.get_cancelCalendarSynchronization();
this._clearHovers();
this.get__popup().Opener=this;
this.get__popup().Show(a,b,this.get_popupContainer());
if(d==true){var j=this._dateInput.get_selectedDate();
if(this.isEmpty()||(!j)){this._focusCalendar();
}else{this._setCalendarDate(j);
}}if(this._calendar&&!this._calendar._linksHandlersAdded){var e=this._calendar.get_element().getElementsByTagName("a");
for(var c=0,h=e.length;
c<h;
c++){var f=e[c];
$addHandlers(f,{click:Function.createDelegate(this,this._click)});
}this._calendar._linksHandlersAdded=true;
}if((this._calendar._enableKeyboardNavigation)&&(!this._calendar._enableMultiSelect)){this._calendar.CurrentViews[0].DomTable.tabIndex=100;
this._calendar.CurrentViews[0].DomTable.focus();
}},_click:function(c){var b=(c.srcElement)?c.srcElement:c.target;
if(b.tagName&&b.tagName.toLowerCase()=="a"){var a=b.getAttribute("href",2);
if(a=="#"||(location.href+"#"==a)){if(c.preventDefault){c.preventDefault();
}return false;
}}},isEmpty:function(){return this._dateInput.isEmpty();
},hidePopup:function(){if(!this.get_calendar()){return false;
}this._hideFastNavigationPopup(this);
if(this.get__popup().IsVisible()){var a=this.get__popup().Hide();
if(a==false){return false;
}}return true;
},getElementDimensions:function(a){return Telerik.Web.UI.Calendar.Utils.GetElementDimensions(a);
},getElementPosition:function(a){return $telerik.getLocation(a);
},get_calendar:function(){return this._calendar;
},set_calendar:function(a){this._calendar=a;
},get_popupButton:function(){return this._popupButton;
},get_dateInput:function(){return this._dateInput;
},set_dateInput:function(a){this._dateInput=a;
},get_textBox:function(){return this._dateInput._textBoxElement;
},get_popupContainer:function(){if((this._popupContainer==null)){if(this._popupContainerID){this._popupContainer=$get(this._popupContainerID);
}else{this._popupContainer=null;
}}return this._popupContainer;
},get_enabled:function(){return this._enabled;
},set_enabled:function(a){if(this._enabled!=a){var d=this.get_popupButton();
var b=this.get__popupImage();
if(a){this._enabled=true;
if(this._dateInput){this._dateInput.enable();
}if(this._calendar){this._calendar.set_enabled(true);
}if(d){Sys.UI.DomElement.removeCssClass(d,"rcDisabled");
d.setAttribute("href","#");
}if(this._onPopupButtonClickDelegate){$addHandler(d,"click",this._onPopupButtonClickDelegate);
}else{if(d){this._onPopupButtonClickDelegate=Function.createDelegate(this,this._onPopupButtonClickHandler);
$addHandler(d,"click",this._onPopupButtonClickDelegate);
}}if(this._onPopupButtonKeyPressDelegate){$addHandler(d,"keypress",this._onPopupButtonKeyPressDelegate);
}if(this._onPopupImageMouseOverDelegate){$addHandler(b,"mouseover",this._onPopupImageMouseOverDelegate);
}if(this._onPopupImageMouseOutDelegate){$addHandler(b,"mouseout",this._onPopupImageMouseOutDelegate);
}var c=$get(this.get_id()+"_wrapper");
if(c.attributes.disabled){c.removeAttribute("disabled");
}}else{this.hidePopup();
this._enabled=false;
if(this._dateInput){this._dateInput.disable();
}if(this._onPopupButtonClickDelegate){$removeHandler(d,"click",this._onPopupButtonClickDelegate);
}if(this._onPopupButtonKeyPressDelegate){$removeHandler(d,"keypress",this._onPopupButtonKeyPressDelegate);
}if(this._onPopupImageMouseOverDelegate){$removeHandler(b,"mouseover",this._onPopupImageMouseOverDelegate);
}if(this._onPopupImageMouseOutDelegate){$removeHandler(b,"mouseout",this._onPopupImageMouseOutDelegate);
}if(d){Sys.UI.DomElement.addCssClass(d,"rcDisabled");
d.removeAttribute("href");
}}this.raisePropertyChanged("enabled");
}},get_visible:function(){var a=$get(this.get_id()+"_wrapper");
if(a.style.display=="none"){return false;
}else{return true;
}},set_visible:function(b){var a=$get(this.get_id()+"_wrapper");
if(b==true&&this._originalDisplay!=null){a.style.display=this._originalDisplay;
this.repaint();
}else{if(b==false&&this.get_visible()){this._originalDisplay=a.style.display;
a.style.display="none";
}}},get_selectedDate:function(){return this._dateInput.get_selectedDate();
},set_selectedDate:function(a){this._dateInput.set_selectedDate(a);
},get_minDate:function(){return this._minDate;
},set_minDate:function(a){var d=this._cloneDate(a);
if(this._minDate.toString()!=d.toString()){if(!this._dateInput){this._minDate=d;
}else{var c=false;
if(this.isEmpty()){c=true;
}this._minDate=d;
this._dateInput.set_minDate(d);
if(this.get_focusedDate()<d){this.set_focusedDate(d);
}var b=[d.getFullYear(),(d.getMonth()+1),d.getDate()];
if(this._calendar){this._calendar.set_rangeMinDate(b);
}}this.updateClientState();
this.raisePropertyChanged("minDate");
}},get_minDateStr:function(){var a=this._minDate.getFullYear().toString();
while(a.length<4){a="0"+a;
}return parseInt(this._minDate.getMonth()+1)+"/"+this._minDate.getDate()+"/"+a+" "+this._minDate.getHours()+":"+this._minDate.getMinutes()+":"+this._minDate.getSeconds();
},get_maxDate:function(){return this._maxDate;
},set_maxDate:function(a){var c=this._cloneDate(a);
if(this._maxDate.toString()!=c.toString()){if(!this._dateInput){this._maxDate=c;
}else{this._maxDate=c;
this._dateInput.set_maxDate(c);
if(this.get_focusedDate()>c){this.set_focusedDate(c);
}var b=[c.getFullYear(),(c.getMonth()+1),c.getDate()];
if(this._calendar){this._calendar.set_rangeMaxDate(b);
}}this.updateClientState();
this.raisePropertyChanged("maxDate");
}},get_maxDateStr:function(){var a=this._maxDate.getFullYear().toString();
while(a.length<4){a="0"+a;
}return parseInt(this._maxDate.getMonth()+1)+"/"+this._maxDate.getDate()+"/"+a+" "+this._maxDate.getHours()+":"+this._maxDate.getMinutes()+":"+this._maxDate.getSeconds();
},get_focusedDate:function(){return this._focusedDate;
},set_focusedDate:function(b){var a=this._cloneDate(b);
if(this._focusedDate.toString()!=a.toString()){this._focusedDate=a;
this.raisePropertyChanged("focusedDate");
}},get_showPopupOnFocus:function(){return this._showPopupOnFocus;
},set_showPopupOnFocus:function(a){this._showPopupOnFocus=a;
},get_enableAriaSupport:function(){return this._enableAriaSupport;
},set_enableAriaSupport:function(a){if(this._enableAriaSupport!=a){this._enableAriaSupport=a;
}},repaint:function(){this._updatePercentageHeight();
},get_popupDirection:function(){return this._popupDirection;
},set_popupDirection:function(a){this._popupDirection=a;
},get_enableScreenBoundaryDetection:function(){return this._enableScreenBoundaryDetection;
},set_enableScreenBoundaryDetection:function(a){this._enableScreenBoundaryDetection=a;
},saveClientState:function(a){var e=["minDateStr","maxDateStr"];
if(a){for(var b=0,c=a.length;
b<c;
b++){e[e.length]=a[b];
}}var d={};
for(var b=0;
b<e.length;
b++){d[e[b]]=this["get_"+e[b]]();
}return Sys.Serialization.JavaScriptSerializer.serialize(d);
},_initializeDateInput:function(){if(this._dateInput!=null&&(!this._dateInput.get_owner)){var a=this;
this._dateInput.get_owner=function(){return a;
};
this._dateInput.Owner=this;
this._setUpValidationInput();
this._setUpDateInput();
this._propagateRangeValues();
this._initializePopupButton();
}this._updatePercentageHeight();
},_updatePercentageHeight:function(){var a=$get(this.get_id()+"_wrapper");
if(a.style.height.indexOf("%")!=-1&&a.offsetHeight>0){var b=0;
if(this.get_dateInput()._textBoxElement.currentStyle){b=parseInt(this.get_dateInput()._textBoxElement.currentStyle.borderTopWidth)+parseInt(this.get_dateInput()._textBoxElement.currentStyle.borderBottomWidth)+parseInt(this.get_dateInput()._textBoxElement.currentStyle.paddingTop)+parseInt(this.get_dateInput()._textBoxElement.currentStyle.paddingBottom);
}else{if(window.getComputedStyle){b=parseInt(window.getComputedStyle(this.get_dateInput()._textBoxElement,null).getPropertyValue("border-top-width"))+parseInt(window.getComputedStyle(this.get_dateInput()._textBoxElement,null).getPropertyValue("border-bottom-width"))+parseInt(window.getComputedStyle(this.get_dateInput()._textBoxElement,null).getPropertyValue("padding-top"))+parseInt(window.getComputedStyle(this.get_dateInput()._textBoxElement,null).getPropertyValue("padding-bottom"));
}}this.get_dateInput()._textBoxElement.style.height="1px";
this.get_dateInput()._textBoxElement.style.cssText=this.get_dateInput()._textBoxElement.style.cssText;
this.get_dateInput()._textBoxElement.style.height=a.offsetHeight-b+"px";
if(this.get_dateInput()._originalTextBoxCssText.search(/(^|[^-])height/)!=-1){this.get_dateInput()._originalTextBoxCssText=this.get_dateInput()._originalTextBoxCssText.replace(/(^|[^-])height(\s*):(\s*)([^;]+);/i,"$1height:"+(a.offsetHeight-b)+"px;");
}else{this.get_dateInput()._originalTextBoxCssText+="height:"+(a.offsetHeight-b)+"px;";
}}},_initializeCalendar:function(){if(this._calendar!=null){this._setUpCalendar();
this._calendar.set_enableMultiSelect(false);
this._calendar.set_useColumnHeadersAsSelectors(false);
this._calendar.set_useRowHeadersAsSelectors(false);
if(this._zIndex){this._calendar._zIndex=parseInt(this._zIndex,10)+2;
}this._calendar._enableShadows=this._enableShadows;
this._popupContainerID=this._calendar.get_id()+"_wrapper";
}},_propagateRangeValues:function(){if(this.get_minDate().toString()!=new Date(1980,0,1)){this._dateInput._minDate=this.get_minDate();
}if(this.get_maxDate().toString()!=new Date(2099,11,31)){this._dateInput._maxDate=this.get_maxDate();
}},_triggerDomChangeEvent:function(){this._dateInput._triggerDomEvent("change",this._validationInput);
},_initializeAriaSupport:function(){var a=document.getElementById(this.get_id()+"_wrapper");
a.setAttribute("aria-atomic","true");
var b=document.getElementById(this.get_id()+"_popupButton");
if(b){b.setAttribute("aria-controls",this.get_calendar().get_id()+"_wrapper");
}},_initializePopupButton:function(){this._popupButton=$get(this._popupControlID);
if(this._popupButton!=null){this._attachPopupButtonEvents();
}},_attachPopupButtonEvents:function(){var a=this.get__popupImage();
var b=this;
if(a!=null){if(!this._hasAttribute("onmouseover")){this._onPopupImageMouseOverDelegate=Function.createDelegate(this,this._onPopupImageMouseOverHandler);
$addHandler(a,"mouseover",this._onPopupImageMouseOverDelegate);
}if(!this._hasAttribute("onmouseout")){this._onPopupImageMouseOutDelegate=Function.createDelegate(this,this._onPopupImageMouseOutHandler);
$addHandler(a,"mouseout",this._onPopupImageMouseOutDelegate);
}}if(this._hasAttribute("href")!=null&&this._hasAttribute("href")!=""&&this._hasAttribute("onclick")==null){this._onPopupButtonClickDelegate=Function.createDelegate(this,this._onPopupButtonClickHandler);
$addHandler(this._popupButton,"click",this._onPopupButtonClickDelegate);
}if(this._popupButton){this._onPopupButtonKeyPressDelegate=Function.createDelegate(this,this._onPopupButtonKeyPressHandler);
$addHandler(this._popupButton,"keypress",this._onPopupButtonKeyPressDelegate);
}},_onPopupImageMouseOverHandler:function(a){this.get__popupImage().src=this._popupButtonSettings.ResolvedHoverImageUrl;
},_onPopupImageMouseOutHandler:function(a){this.get__popupImage().src=this._popupButtonSettings.ResolvedImageUrl;
},_onPopupButtonClickHandler:function(a){this.togglePopup();
a.stopPropagation();
a.preventDefault();
return false;
},_onPopupButtonKeyPressHandler:function(a){if(a.charCode==32){this.togglePopup();
a.stopPropagation();
a.preventDefault();
return false;
}},_hasAttribute:function(a){return this._popupButton.getAttribute(a);
},_calendarDateSelected:function(a){if(this.InputSelectionInProgress==true){return;
}if(a.IsSelected){if(this.hidePopup()==false){return;
}var b=this._getJavaScriptDate(a.get_date());
this.CalendarSelectionInProgress=true;
this._setInputDate(b);
}},_actionBeforeShowPopup:function(){for(var a in Telerik.Web.UI.RadDatePicker.PopupInstances){if(Telerik.Web.UI.RadDatePicker.PopupInstances.hasOwnProperty(a)){var b=Telerik.Web.UI.RadDatePicker.PopupInstances[a].Opener;
this._hideFastNavigationPopup(b);
Telerik.Web.UI.RadDatePicker.PopupInstances[a].Hide();
}}},_hideFastNavigationPopup:function(b){if(b){var a=b.get_calendar()._getFastNavigation().Popup;
if(a&&a.IsVisible()){a.Hide(true);
}}},_setInputDate:function(a){this._dateInput.set_selectedDate(a);
},_getJavaScriptDate:function(a){var b=new Date();
b.setFullYear(a[0],a[1]-1,a[2]);
return b;
},_onDateInputDateChanged:function(a,b){this._setValidatorDate(b.get_newDate());
this._triggerDomChangeEvent();
if(!this.isPopupVisible()){return;
}if(this.isEmpty()){this._focusCalendar();
}else{if(!this.CalendarSelectionInProgress){this._setCalendarDate(b.get_newDate());
}}},_focusCalendar:function(){this._calendar.unselectDates(this._calendar.get_selectedDates());
var a=[this.get_focusedDate().getFullYear(),this.get_focusedDate().getMonth()+1,this.get_focusedDate().getDate()];
this._calendar.navigateToDate(a);
},_setValidatorDate:function(a){var c="";
if(a!=null){var d=(a.getMonth()+1).toString();
if(d.length==1){d="0"+d;
}var b=a.getDate().toString();
if(b.length==1){b="0"+b;
}c=a.getFullYear()+"-"+d+"-"+b;
}this._validationInput.value=c;
},_setCalendarDate:function(a){var c=[a.getFullYear(),a.getMonth()+1,a.getDate()];
var b=(this._calendar.FocusedDate[1]!=c[1])||(this._calendar.FocusedDate[0]!=c[0]);
this.InputSelectionInProgress=true;
this._calendar.unselectDates(this._calendar.get_selectedDates());
this._calendar.selectDate(c,b);
this.InputSelectionInProgress=false;
},_cloneDate:function(a){var c=null;
if(!a){return null;
}if(typeof(a.setFullYear)=="function"){c=[];
c[c.length]=a.getFullYear();
c[c.length]=a.getMonth()+1;
c[c.length]=a.getDate();
c[c.length]=a.getHours();
c[c.length]=a.getMinutes();
c[c.length]=a.getSeconds();
c[c.length]=a.getMilliseconds();
}else{if(typeof(a)=="string"){c=a.split(/-/);
}}if(c!=null){var b=new Date();
b.setDate(1);
b.setFullYear(c[0]);
b.setMonth(c[1]-1);
b.setDate(c[2]);
b.setHours(c[3]);
b.setMinutes(c[4]);
b.setSeconds(c[5]);
b.setMilliseconds(0);
return b;
}return null;
},_setUpValidationInput:function(){this._validationInput=$get(this.get_id());
},_setUpDateInput:function(){this._onDateInputValueChangedDelegate=Function.createDelegate(this,this._onDateInputValueChangedHandler);
this._dateInput.add_valueChanged(this._onDateInputValueChangedDelegate);
this._onDateInputBlurDelegate=Function.createDelegate(this,this._onDateInputBlurHandler);
this._dateInput.add_blur(this._onDateInputBlurDelegate);
this._onDateInputKeyPressDelegate=Function.createDelegate(this,this._onDateInputKeyPressHandler);
this._dateInput.add_keyPress(this._onDateInputKeyPressDelegate);
this._onDateInputFocusDelegate=Function.createDelegate(this,this._onDateInputFocusHandler);
this._dateInput.add_focus(this._onDateInputFocusDelegate);
},_onDateInputValueChangedHandler:function(a,b){this._onDateInputDateChanged(a,b);
this.raise_dateSelected(b);
this.CalendarSelectionInProgress=false;
},_onDateInputBlurHandler:function(a,b){if(!a.get_selectedDate()){this._validationInput.value="";
}},_onDateInputFocusHandler:function(a,b){this._triggerDomEvent("focus",this._validationInput);
if(this._calendar&&this.get_showPopupOnFocus()){this.showPopup();
}},_triggerDomEvent:function(c,a){if(!c||c==""||!a){return;
}if(a.fireEvent&&document.createEventObject){var d=document.createEventObject();
a.fireEvent(String.format("on{0}",c),d);
}else{if(a.dispatchEvent){var b=true;
var d=document.createEvent("HTMLEvents");
d.initEvent(c,b,true);
a.dispatchEvent(d);
}}},_onDateInputKeyPressHandler:function(a,b){if(b.get_keyCode()==13){this._setValidatorDate(a.get_selectedDate());
}},_setUpCalendar:function(){this._onCalendarDateSelectedDelegate=Function.createDelegate(this,this._onCalendarDateSelectedHandler);
this._calendar.add_dateSelected(this._onCalendarDateSelectedDelegate);
},_onCalendarDateSelectedHandler:function(a,b){if(this.isPopupVisible()){this._calendarDateSelected(b.get_renderDay());
}},get__popupImage:function(){var a=null;
if(this._popupButton!=null){var b=this._popupButton.getElementsByTagName("img");
if(b.length>0){a=b[0];
}else{a=this._popupButton;
}}return a;
},_refreshPopupShadowSetting:function(){if(!this.get_calendar()){return;
}var a=Telerik.Web.UI.RadDatePicker.PopupInstances[this.get_calendar().get_id()];
if(a&&!$telerik.quirksMode){this.get__popup().EnableShadows=this._enableShadows;
}},get__popup:function(){var a=Telerik.Web.UI.RadDatePicker.PopupInstances[this.get_calendar().get_id()];
if(!a){a=new Telerik.Web.UI.Calendar.Popup();
if(this._zIndex){a.zIndex=this._zIndex;
}if(!this._enableShadows){a.EnableShadows=false;
}if(this._animationSettings){a.ShowAnimationDuration=this._animationSettings.ShowAnimationDuration;
a.ShowAnimationType=this._animationSettings.ShowAnimationType;
a.HideAnimationDuration=this._animationSettings.HideAnimationDuration;
a.HideAnimationType=this._animationSettings.HideAnimationType;
}Telerik.Web.UI.RadDatePicker.PopupInstances[this._calendar.get_id()]=a;
}return a;
},get__PopupVisibleControls:function(){var a=[this.get_textBox(),this.get_popupContainer()];
if(this._popupButton!=null){a[a.length]=this._popupButton;
}return a;
},get__PopupButtonSettings:function(){return this._popupButtonSettings;
},set__PopupButtonSettings:function(a){this._popupButtonSettings=a;
},add_dateSelected:function(a){this.get_events().addHandler("dateSelected",a);
},remove_dateSelected:function(a){this.get_events().removeHandler("dateSelected",a);
},raise_dateSelected:function(a){this.raiseEvent("dateSelected",a);
},add_popupOpening:function(a){this.get_events().addHandler("popupOpening",a);
},remove_popupOpening:function(a){this.get_events().removeHandler("popupOpening",a);
},raise_popupOpening:function(a){this.raiseEvent("popupOpening",a);
},add_popupClosing:function(a){this.get_events().addHandler("popupClosing",a);
},remove_popupClosing:function(a){this.get_events().removeHandler("popupClosing",a);
},raise_popupClosing:function(a){this.raiseEvent("popupClosing",a);
}};
Telerik.Web.UI.RadDatePicker.registerClass("Telerik.Web.UI.RadDatePicker",Telerik.Web.UI.RadWebControl);
