Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadMaskPart=function(){this.value="";
this.index=-1;
this.type=-1;
this.PromptChar="_";
};
Telerik.Web.UI.RadMaskPart.prototype={HandleKey:function(a){return false;
},HandleWheel:function(a){return true;
},SetController:function(a){this.controller=a;
},GetValue:function(){return this.value.toString();
},GetVisValue:function(){return"";
},SetValue:function(b,a){return true;
},CanHandle:function(b,a){return true;
},IsCaseSensitive:function(){return false;
},GetLength:function(){return 1;
},IsAlpha:function(a){return a.match(/[^\u005D\u005B\t\n\r\f\s\v\\!-@|^_`{-\u00BF]{1}/)!=null;
}};
Telerik.Web.UI.RadMaskPart.registerClass("Telerik.Web.UI.RadMaskPart");
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadDigitMaskPart=function(){Telerik.Web.UI.RadDigitMaskPart.initializeBase(this);
};
Telerik.Web.UI.RadDigitMaskPart.prototype={GetValue:function(){return this.value.toString();
},IsCaseSensitive:function(){return true;
},GetVisValue:function(){if(this.value.toString()==""){return this.PromptChar;
}return this.value.toString();
},CanHandle:function(b,a){if(isNaN(parseInt(b))){this.controller._OnChunkError(this,this.GetValue(),b);
return false;
}return true;
},SetValue:function(b,a){if(b==""||b==this.PromptChar||b==" "){this.value="";
return true;
}if(this.CanHandle(b,a)){this.value=parseInt(b);
}return true;
}};
Telerik.Web.UI.RadDigitMaskPart.registerClass("Telerik.Web.UI.RadDigitMaskPart",Telerik.Web.UI.RadMaskPart);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadEnumerationMaskPart=function(a){Telerik.Web.UI.RadEnumerationMaskPart.initializeBase(this);
this.SetOptions(a);
this.lastOffsetPunched=-1;
this.selectedForCompletion=0;
this.FlipDirection=0;
this.RebuildKeyBuff();
};
Telerik.Web.UI.RadEnumerationMaskPart.prototype={SetOptions:function(a){this.length=0;
this.Options=a;
this.optionsIndex=[];
for(var b=0;
b<this.Options.length;
b++){this.length=Math.max(this.length,this.Options[b].length);
this.optionsIndex[this.Options[b]]=b;
}},CanHandle:function(a,d){if(a==""){return true;
}d=Math.max(d-this.offset,0);
var e=[];
for(var b=0;
b<this.keyBuff.length;
b++){e[b]=this.keyBuff[b];
}e[d]=a;
var c=new Telerik.Web.UI.CompletionList(this.Options,this.PromptChar);
var f=c.GetCompletions(e,d);
if(f.length>0){return true;
}else{this.controller._OnChunkError(this,this.GetValue(),a);
return false;
}},SetController:function(a){this.controller=a;
this.InitializeSelection(a.get_allowEmptyEnumerations());
},InitializeSelection:function(a){if(a){this.value="";
this.selectedIndex=-1;
}else{this.value=this.Options[0];
this.selectedIndex=0;
}},RebuildKeyBuff:function(){this.keyBuff=[];
for(i=0;
i<this.length;
i++){this.keyBuff[i]="";
}this.keyBuffRebuilt=true;
},IsCaseSensitive:function(){return true;
},ResetCompletion:function(){this.selectedForCompletion=0;
},SelectNextCompletion:function(){this.selectedForCompletion++;
},Store:function(b,a){if(this.lastOffsetPunched==a){if(this.keyBuff[a]==b){this.SelectNextCompletion();
}else{this.RebuildKeyBuff();
}}else{this.ResetCompletion();
}this.lastOffsetPunched=a;
this.keyBuff[a]=b;
},SetNoCompletionValue:function(){if(this.controller.get_allowEmptyEnumerations()){this.SetOption(-1);
}},SetValue:function(a,e){if(a==""&&this.controller._clearing){this.value="";
this.SetNoCompletionValue();
return true;
}e=Math.max(0,e-this.offset);
this.Store(a,e);
var d=new Telerik.Web.UI.CompletionList(this.Options,this.PromptChar);
var b=d.GetCompletions(this.keyBuff,e);
if(b.length>0){var c=this.optionsIndex[b[this.selectedForCompletion%b.length]];
this.SetOption(c);
}else{this.SetNoCompletionValue();
if(a!==""&&a!==this.controller.get_promptChar()&&a!==this.controller.get_displayPromptChar()){this.controller._OnChunkError(this,this.GetValue(),a);
}}return true;
},GetVisValue:function(){var a=this.value;
while(a.length<this.length){a+=this.PromptChar;
}return a;
},GetLength:function(){return this.length;
},GetSelectedIndex:function(){return this.selectedIndex;
},SetOption:function(b,c){var a=this.value;
if(this.controller.get_allowEmptyEnumerations()){if(b<-1){b=this.Options.length+b+1;
this.FlipDirection=-1;
}else{if(b>=this.Options.length){b=b-this.Options.length-1;
this.FlipDirection=1;
}}}else{if(b<0){b=this.Options.length+b;
this.FlipDirection=-1;
}else{if(b>=this.Options.length){b=b-this.Options.length;
this.FlipDirection=1;
}}}this.selectedIndex=b;
this.value=b==-1?"":this.Options[b];
if(typeof(c)!="undefined"){if(c){this.controller._OnMoveUp(this,a,this.value);
}else{this.controller._OnMoveDown(this,a,this.value);
}}if(a!=this.value){this.controller._OnEnumChanged(this,a,this.value);
}this.FlipDirection=0;
},HandleKey:function(a){this.controller._calculateSelection();
var b=new Telerik.Web.UI.MaskedEventWrap(a,this.controller._textBoxElement);
if(b.IsDownArrow()){this.SetOption(this.selectedIndex+1,false);
this.controller._Visualise();
this.controller._FixSelection(b);
return true;
}else{if(b.IsUpArrow()){this.SetOption(this.selectedIndex-1,true);
this.controller._Visualise();
this.controller._FixSelection(b);
return true;
}}},HandleWheel:function(a){this.controller._calculateSelection();
var b=new Telerik.Web.UI.MaskedEventWrap(a,this.controller._textBoxElement);
this.SetOption(this.selectedIndex-a.rawEvent.wheelDelta/120);
this.controller._Visualise();
this.controller._FixSelection(b);
return false;
}};
Telerik.Web.UI.RadEnumerationMaskPart.registerClass("Telerik.Web.UI.RadEnumerationMaskPart",Telerik.Web.UI.RadMaskPart);
Telerik.Web.UI.CompletionList=function(b,a){this.options=b;
this.blankChar=a;
};
Telerik.Web.UI.CompletionList.prototype={GetCompletions:function(d,e){var a=this.options;
for(var c=0;
c<=e;
c++){var b=d[c].toLowerCase();
a=this.FilterCompletions(a,c,b);
}return a;
},FilterCompletions:function(g,d,e){var c=[];
for(var b=0;
b<g.length;
b++){var f=g[b];
var a=f.charAt(d).toLowerCase();
if(this.CharacterMatchesCompletion(e,a)){c[c.length]=f;
}}return c;
},CharacterMatchesCompletion:function(a,b){return a==this.blankChar||a==" "||a==b;
}};
Telerik.Web.UI.CompletionList.registerClass("Telerik.Web.UI.CompletionList");
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadFreeMaskPart=function(){Telerik.Web.UI.RadFreeMaskPart.initializeBase(this);
};
Telerik.Web.UI.RadFreeMaskPart.prototype={IsCaseSensitive:function(){return true;
},GetVisValue:function(){if(this.value.toString()==""){return this.PromptChar;
}return this.value;
},SetValue:function(b,a){this.value=b;
return true;
}};
Telerik.Web.UI.RadFreeMaskPart.registerClass("Telerik.Web.UI.RadFreeMaskPart",Telerik.Web.UI.RadMaskPart);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadLiteralMaskPart=function(a){Telerik.Web.UI.RadLiteralMaskPart.initializeBase(this);
if((Sys.Browser.agent===Sys.Browser.InternetExplorer&&(!document.documentMode||document.documentMode<9))||Sys.Browser.agent===Sys.Browser.Opera){this.ch=a;
}else{this.ch=a.replace(/\r\n|\r|\n/g,"\n");
}};
Telerik.Web.UI.RadLiteralMaskPart.prototype={GetVisValue:function(){return this.ch;
},GetLength:function(){return this.ch.length;
},GetValue:function(){return"";
},IsCaseSensitive:function(){if(this.NextChunk!=null){return this.NextChunk.IsCaseSensitive();
}},SetValue:function(b,a){a-=this.offset;
return b==this.ch.charAt(a)||!b;
},CanHandle:function(b,a){a-=this.offset;
if(b==this.ch.charAt(a)){return true;
}if(!b){return true;
}if(this.NextChunk!=null){return this.NextChunk.CanHandle(b,a+this.GetLength());
}}};
Telerik.Web.UI.RadLiteralMaskPart.registerClass("Telerik.Web.UI.RadLiteralMaskPart",Telerik.Web.UI.RadMaskPart);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadLowerMaskPart=function(){Telerik.Web.UI.RadLowerMaskPart.initializeBase(this);
};
Telerik.Web.UI.RadLowerMaskPart.prototype={CanHandle:function(b,a){if(!this.IsAlpha(b)){this.controller._OnChunkError(this,this.GetValue(),b);
return false;
}return true;
},GetVisValue:function(){if(this.value.toString()==""){return this.PromptChar;
}return this.value.toString();
},SetValue:function(b,a){if(b==""){this.value="";
return true;
}if(this.IsAlpha(b)){this.value=b.toLowerCase();
}else{this.controller._OnChunkError(this,this.GetValue(),b);
}return true;
}};
Telerik.Web.UI.RadLowerMaskPart.registerClass("Telerik.Web.UI.RadLowerMaskPart",Telerik.Web.UI.RadMaskPart);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadNumericRangeMaskPart=function(d,c,b,a){Telerik.Web.UI.RadNumericRangeMaskPart.initializeBase(this);
this.upperLimit=c;
this.lowerLimit=d;
this.length=Math.max(this.lowerLimit.toString().length,this.upperLimit.toString().length);
this.leftAlign=b;
this.zeroFill=a;
this.minusIncluded=this.lowerLimit<0||this.upperLimit<0;
this.value=d;
this.FlipDirection=0;
};
Telerik.Web.UI.RadNumericRangeMaskPart.prototype={SetController:function(a){this.controller=a;
this.GetVisValue();
},IsCaseSensitive:function(){return true;
},CanHandle:function(b,a){if((b=="-"||b=="+")&&this.lowerLimit<0){return true;
}if(isNaN(parseInt(b))){this.controller._OnChunkError(this,this.GetValue(),b);
return false;
}return true;
},InsertAt:function(b,a){return this.visValue.substr(0,a)+b.toString()+this.visValue.substr(a+1,this.visValue.length);
},ReplacePromptChar:function(b){var a=this.leftAlign?"":"0";
while(b.indexOf(this.PromptChar)>-1){b=b.replace(this.PromptChar,a);
}return b;
},SetValue:function(a,c){if(a==""){a=0;
}if(isNaN(parseInt(a))&&a!="+"&&a!="-"){return true;
}c-=this.offset;
var b=this.InsertAt(a,c);
b=this.ReplacePromptChar(b);
if(b.indexOf("-")!=-1&&b.indexOf("-")>0){b=b.replace("-","0");
}if(isNaN(parseInt(b))){b=0;
}if(this.controller.get_roundNumericRanges()){b=Math.min(this.upperLimit,b);
b=Math.max(this.lowerLimit,b);
this.setInternalValue(b);
}else{if(b<=this.upperLimit&&b>=this.lowerLimit){this.setInternalValue(b);
this.GetVisValue();
}else{return false;
}}this.GetVisValue();
return true;
},setInternalValue:function(b){var a=this.value;
this.value=b;
if(a!=b){this.controller._OnEnumChanged(this,a,b);
}if(a>b){this.controller._OnMoveDown(this,a,b);
}else{if(a<b){this.controller._OnMoveUp(this,a,b);
}}this.FlipDirection=0;
},GetVisValue:function(){var b="";
var c=Math.abs(this.value).toString();
if(this.leftAlign){if(this.value<0){b+=this.PromptChar;
}b+=c;
while(b.length<this.length){b+=this.controller.get_promptChar();
}}else{var a=this.zeroFill?"0":this.controller.get_promptChar();
if(this.value<0){c="-"+c;
}while(b.length<this.length-c.length){b+=a;
}b+=c;
}this.visValue=b;
return b;
},GetLength:function(){return this.length;
},HandleKey:function(a){this.controller._calculateSelection();
var b=new Telerik.Web.UI.MaskedEventWrap(a,this.controller._textBoxElement);
if(b.IsDownArrow()){this.MoveDown();
this.controller._FixSelection(b);
return true;
}else{if(b.IsUpArrow()){this.MoveUp();
this.controller._FixSelection(b);
return true;
}}},MoveUp:function(){var a=this.value;
a++;
if(a>this.upperLimit){a=this.lowerLimit;
this.FlipDirection=1;
}this.setInternalValue(a);
this.controller._Visualise();
},MoveDown:function(){var a=this.value;
a--;
if(a<this.lowerLimit){a=this.upperLimit;
this.FlipDirection=-1;
}this.setInternalValue(a);
this.controller._Visualise();
},HandleWheel:function(d){var a=this.value;
var b;
if(d.rawEvent.wheelDelta){b=d.rawEvent.wheelDelta/120;
if(window.opera){b=-b;
}}else{if(d.rawEvent.detail){b=-d.rawEvent.detail/3;
}}a=parseInt(a)+b;
var c=new Telerik.Web.UI.MaskedEventWrap(d,this.controller._textBoxElement);
if(a<this.lowerLimit){a=this.upperLimit-(this.lowerLimit-a-1);
this.FlipDirection=-1;
}if(a>this.upperLimit){a=this.lowerLimit+(a-this.upperLimit-1);
this.FlipDirection=1;
}this.setInternalValue(a);
this.controller._Visualise();
this.controller._FixSelection(c);
return false;
}};
Telerik.Web.UI.RadNumericRangeMaskPart.registerClass("Telerik.Web.UI.RadNumericRangeMaskPart",Telerik.Web.UI.RadMaskPart);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadUpperMaskPart=function(){Telerik.Web.UI.RadUpperMaskPart.initializeBase(this);
};
Telerik.Web.UI.RadUpperMaskPart.prototype={CanHandle:function(b,a){if(!this.IsAlpha(b)){this.controller._OnChunkError(this,this.GetValue(),b);
return false;
}return true;
},GetVisValue:function(){if(this.value.toString()==""){return this.PromptChar;
}return this.value.toString();
},SetValue:function(b,a){if(b==""){this.value="";
return true;
}if(this.IsAlpha(b)){this.value=b.toUpperCase();
}else{this.controller._OnChunkError(this,this.GetValue(),b);
}return true;
}};
Telerik.Web.UI.RadUpperMaskPart.registerClass("Telerik.Web.UI.RadUpperMaskPart",Telerik.Web.UI.RadMaskPart);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.MaskedEventWrap=function(b,a){if(b){this.event=b.rawEvent;
}this._selectionStart=a.selectionStart;
this._selectionEnd=a.selectionEnd;
this.fieldValue=a.value;
};
Telerik.Web.UI.MaskedEventWrap.prototype={IsUpArrow:function(){return this.event.keyCode==38;
},IsDownArrow:function(){return this.event.keyCode==40;
}};
Telerik.Web.UI.MaskedEventWrap.registerClass("Telerik.Web.UI.MaskedEventWrap");
Type.registerNamespace("Telerik.Web.UI");
$telerik.findMaskedTextBox=$find;
$telerik.toMaskedTextBox=function(a){return a;
};
Telerik.Web.UI.RadMaskedTextBox=function(a){Telerik.Web.UI.RadMaskedTextBox.initializeBase(this,[a]);
this._parts=[];
this._partIndex=[];
this._displayPartIndex=[];
this._value="";
this._lastState=null;
this._length=0;
this._displayLength=0;
this._internalValueUpdate=false;
this._projectedValue="";
this._isTextarea=false;
this._initialMasks=[];
this._initialDisplayMasks=[];
this._promptChar="_";
this._displayPromptChar="_";
this._displayFormatPosition=Telerik.Web.UI.DisplayFormatPosition.Left;
this._hideOnBlur=false;
this._resetCaretOnFocus=false;
this._roundNumericRanges=true;
this._allowEmptyEnumerations=false;
this._readOnly=false;
this._focusOnStartup=false;
this._onTextBoxMouseUpDelegate=null;
this._onTextBoxMouseDownDelegate=null;
this._onTextBoxPasteDelegate=null;
this._onTextBoxPropertyChangeDelegate=null;
this._onTextBoxInputDelegate=null;
this._onFormResetDelegate=null;
this._isInitialized=false;
this._originalValue="";
this.preventPostBackAfterBlur=false;
};
Telerik.Web.UI.RadMaskedTextBox.prototype={initialize:function(){Telerik.Web.UI.RadMaskedTextBox.callBaseMethod(this,"initialize");
if(this._focused){this._focusOnStartup=true;
}this._fixAbsolutePositioning();
this._setMask(this.get__initialMasks());
if(this.get__initialDisplayMasks().length){this._setDisplayMask(this.get__initialDisplayMasks());
}this._SetValue(this._textBoxElement.value);
this._textBoxElement._oldValue=this._textBoxElement.value;
this._isTextarea=this._textBoxElement.tagName.toLowerCase()=="textarea";
this._RecordInitialState();
this._isInitialized=true;
if(this._focusOnStartup){this._calculateSelection();
this._lastState=new Telerik.Web.UI.MaskedEventWrap(null,this._textBoxElement);
}},dispose:function(){if(this._onTextBoxMouseUpDelegate){$removeHandler(this._textBoxElement,"mouseup",this._onTextBoxMouseUpDelegate);
this._onTextBoxMouseUpDelegate=null;
}if(this._onTextBoxMouseDownDelegate){$removeHandler(this._textBoxElement,"mousedown",this._onTextBoxMouseDownDelegate);
this._onTextBoxMouseDownDelegate=null;
}if(this._onFormResetDelegate){if(this._textBoxElement.form){$removeHandler(this._textBoxElement.form,"reset",this._onFormResetDelegate);
}this._onFormResetDelegate=null;
}if(Sys.Browser.agent==Sys.Browser.InternetExplorer&&(!document.documentMode||document.documentMode<9)){if(this._onTextBoxPasteDelegate){$removeHandler(this._textBoxElement,"paste",this._onTextBoxPasteDelegate);
this._onTextBoxPasteDelegate=null;
}if(this._onTextBoxPropertyChangeDelegate){$removeHandler(this._textBoxElement,"propertychange",this._onTextBoxPropertyChangeDelegate);
this._onTextBoxPropertyChangeDelegate=null;
}}else{if(this._onTextBoxInputDelegate){$removeHandler(this._textBoxElement,"input",this._onTextBoxInputDelegate);
this._onTextBoxInputDelegate=null;
}}Telerik.Web.UI.RadMaskedTextBox.callBaseMethod(this,"dispose");
},isEmpty:function(){return this._value=="";
},resetCursor:function(){this.set_cursorPosition(0);
},inSelection:function(a){this._calculateSelection();
if(this._textBoxElement.selectionStart!=this._textBoxElement.selectionEnd){this._OnActivity(a);
return true;
}if(a.ctrlKey||a.altKey||Sys.Browser.agent==Sys.Browser.Safari){this._OnActivity(a);
return true;
}return false;
},updateDisplayValue:function(){if(this._isInitialized){if(this._focused){if((this.get_hideOnBlur()&&this.isEmpty())||this._displayParts){this._Visualise();
this._textBoxElement.select();
}if(this.get_resetCaretOnFocus()){this.resetCursor();
}}else{this._Visualise();
}}},updateHiddenValue:function(){var a=this._setHiddenValue(this.get_valueWithPromptAndLiterals());
if(this.isMultiLine()){this.updateClientState();
}return a;
},get_valueWithLiterals:function(){var a=[];
for(var b=0;
b<this._parts.length;
b++){a[b]=this._parts[b].ch||this._parts[b].GetValue();
}return a.join("");
},get_valueWithPromptAndLiterals:function(){return this._GetVisibleValues(this._parts);
},get_valueWithPrompt:function(){var c=[];
for(var b=0;
b<this._parts.length;
b++){var a=this._parts[b];
var d=a.GetValue();
if(d!=""){c.push(d);
}else{if(a.GetVisValue()==a.PromptChar){c.push(a.GetVisValue());
}}}return c.join("");
},get_prompt:function(){var c=new RegExp(".","g");
var a=[];
for(var b=0;
b<this._parts.length;
b++){a[b]=this._parts[b].ch||this._parts[b].GetVisValue().replace(c,this.get_promptChar());
}return a.join("");
},get_displayValue:function(){var a=this.get_valueWithPrompt();
while(a.length<this._displayLength){a+=this.get_promptChar();
}this._UpdateDisplayPartsInRange(a,0,this._displayLength);
if(this._displayParts){return this._GetVisibleValues(this._displayParts);
}else{return this._GetVisibleValues(this._parts);
}},set_cursorPosition:function(a){if(!this._focused){return;
}this._calculateSelection();
if(Sys.Browser.agent==Sys.Browser.InternetExplorer&&(!document.documentMode||document.documentMode<9)){this._textBoxElement.select();
sel=document.selection.createRange();
var b=this._textBoxElement.value.substr(0,a).split("\r\n").length-1;
sel.move("character",a-b);
sel.select();
}else{this._textBoxElement.selectionStart=a;
this._textBoxElement.selectionEnd=a;
}},get_value:function(){var a=[];
for(var b=0;
b<this._parts.length;
b++){a[b]=this._parts[b].GetValue();
}return a.join("");
},set_value:function(a){if(a===""){this._clearing=true;
}this._SetValue(a);
this._clearing=false;
if(this._ValueHasChanged()){this.raise_valueChanged();
if(this.get_autoPostBack()&&!this.preventPostBackAfterBlur&&this._canAutoPostBackAfterValidation()){this.raisePostBackEvent();
}}},get_promptChar:function(){return this._promptChar;
},set_promptChar:function(a){if(this._promptChar!=a){this._promptChar=a;
this.raisePropertyChanged("PromptChar");
}},get_displayPromptChar:function(){return this._displayPromptChar;
},set_displayPromptChar:function(a){if(this._displayPromptChar!=a){this._displayPromptChar=a;
this.raisePropertyChanged("DisplayPromptChar");
}},get_displayFormatPosition:function(){return this._displayFormatPosition;
},set_displayFormatPosition:function(a){if(this._displayFormatPosition!=a){this._displayFormatPosition=a;
this.raisePropertyChanged("DisplayFormatPosition");
}},get_hideOnBlur:function(){return this._hideOnBlur;
},set_hideOnBlur:function(a){if(this._hideOnBlur!=a){this._hideOnBlur=a;
this.raisePropertyChanged("HideOnBlur");
}},get_resetCaretOnFocus:function(){return this._resetCaretOnFocus;
},set_resetCaretOnFocus:function(a){if(this._resetCaretOnFocus!=a){this._resetCaretOnFocus=a;
this.raisePropertyChanged("ResetCaretOnFocus");
}},get_roundNumericRanges:function(){return this._roundNumericRanges;
},set_roundNumericRanges:function(a){if(this._roundNumericRanges!=a){this._roundNumericRanges=a;
this.raisePropertyChanged("RoundNumericRanges");
}},get_allowEmptyEnumerations:function(){return this._allowEmptyEnumerations;
},set_allowEmptyEnumerations:function(a){if(this._allowEmptyEnumerations!=a){this._allowEmptyEnumerations=a;
this.raisePropertyChanged("AllowEmptyEnumerations");
}},get_readOnly:function(){return this._readOnly;
},set_readOnly:function(a){if(this._readOnly!=a){this._readOnly=a;
this.raisePropertyChanged("ReadOnly");
}},saveClientState:function(){var a=[];
if(this.isMultiLine()){a[a.length]="valueWithPromptAndLiterals";
}return Telerik.Web.UI.RadMaskedTextBox.callBaseMethod(this,"saveClientState",[a]);
},_attachMouseEventHandlers:function(){Telerik.Web.UI.RadMaskedTextBox.callBaseMethod(this,"_attachMouseEventHandlers");
this._onTextBoxMouseDownDelegate=Function.createDelegate(this,this._onTextBoxMouseDownHandler);
if(!$telerik.isSafari){this._onTextBoxMouseUpDelegate=Function.createDelegate(this,this._onTextBoxMouseUpHandler);
$addHandler(this._textBoxElement,"mouseup",this._onTextBoxMouseUpDelegate);
}$addHandler(this._textBoxElement,"mousedown",this._onTextBoxMouseDownDelegate);
},_attachEventHandlers:function(){Telerik.Web.UI.RadMaskedTextBox.callBaseMethod(this,"_attachEventHandlers");
if(this._textBoxElement&&this._textBoxElement.form){this._onFormResetDelegate=Function.createDelegate(this,this._onFormResetHandler);
$addHandler(this._textBoxElement.form,"reset",this._onFormResetDelegate);
}if(Sys.Browser.agent==Sys.Browser.InternetExplorer&&(!document.documentMode||document.documentMode<9)){this._onTextBoxPasteDelegate=Function.createDelegate(this,this._onTextBoxPasteHandler);
this._onTextBoxPropertyChangeDelegate=Function.createDelegate(this,this._onTextBoxPropertyChangeHandler);
$addHandler(this._textBoxElement,"paste",this._onTextBoxPasteDelegate);
$addHandler(this._textBoxElement,"propertychange",this._onTextBoxPropertyChangeDelegate);
}else{this._onTextBoxInputDelegate=Function.createDelegate(this,this._onTextBoxInputHandler);
$addHandler(this._textBoxElement,"input",this._onTextBoxInputDelegate);
}if(Sys.Browser.agent==Sys.Browser.Opera){var a=this;
var b=function(){return a._ValueHandler({});
};
setInterval(b,10);
}},_SetValue:function(a){this._internalValueUpdate=true;
this._UpdatePartsInRange(a,0,this._length);
this._internalValueUpdate=false;
this._Visualise();
},_initializeHiddenElement:function(a){this._hiddenElement=$get(a+"_Value");
},_initializeValidationField:function(a){this._validationField=$get(a);
},_setValidationField:function(a){if(this.isEmpty()){this._validationField.value="";
}else{this._validationField.value=this.get_valueWithLiterals();
}},_getValidationField:function(a){return this._validationField;
},_onFormResetHandler:function(a){if(this._originalValue==null){this._originalValue="";
}this._setHiddenValue(this._originalValue);
this._SetValue(this._originalValue);
},_onTextBoxInputHandler:function(a){this._ValueHandler(a);
},_onMouseWheel:function(a){return this._OnMouseWheel(event);
},_onTextBoxPropertyChangeHandler:function(a){this._OnPropertyChange();
},_onTextBoxPasteHandler:function(a){if(this.get_readOnly()){return false;
}if($telerik.isIE&&document.documentMode>8&&this._textBoxElement.selectionStart!==this._textBoxElement.selectionEnd){this._textBoxElement.selectionEnd=this._textBoxElement.selectionStart;
}var b=this;
setTimeout(function(){b._FakeOnPropertyChange(a);
},1);
},_onTextBoxBlurHandler:function(a){this._focused=false;
this._hovered=false;
if(this._ValueHasChanged()){this.raise_valueChanged();
if(this.get_autoPostBack()&&this._canAutoPostBackAfterValidation()){this.raisePostBackEvent();
this.preventPostBackAfterBlur=true;
}}this.raise_blur(Sys.EventArgs.Empty);
this.updateDisplayValue();
this.updateCssClass();
},_onTextBoxMouseUpHandler:function(a){this._FakeOnPropertyChange(a);
this._ValueHandler(a);
this._ActivityHandler(a);
if(($telerik.isSafari||$telerik.isFirefox)&&this._allowApplySelection){this._allowApplySelection=false;
this._updateSelectionOnFocus();
a.preventDefault();
a.stopPropagation();
}},_onTextBoxMouseDownHandler:function(a){this._FakeOnPropertyChange(a);
this._ActivityHandler(a);
},_onTextBoxFocusHandler:function(b){this._allowApplySelection=true;
this._focused=true;
this.updateDisplayValue();
this.updateCssClass();
this._updateSelectionOnFocus();
this._FakeOnPropertyChange(b);
this._ActivityHandler(b);
this.raise_focus(Sys.EventArgs.Empty);
if(($telerik.isSafari||$telerik.isFirefox)&&this.get_selectionOnFocus()!=Telerik.Web.UI.SelectionOnFocus.None&&this.get_selectionOnFocus()!=Telerik.Web.UI.SelectionOnFocus.SelectAll){var a=this;
window.setTimeout(function(){a._triggerDomEvent("mouseup",a._textBoxElement);
},1);
}},_onTextBoxKeyUpHandler:function(a){this._FakeOnPropertyChange(a);
},_OnActivity:function(a){this._calculateSelection();
this._lastState=new Telerik.Web.UI.MaskedEventWrap(a,this._textBoxElement);
},_OnPropertyChange:function(){if(this._internalValueUpdate){return;
}if(event.propertyName=="value"){var c=event;
var a=this;
var b=function(){a._ValueHandler(c);
};
this._calculateSelection();
if(this._textBoxElement.selectionStart>0||this._textBoxElement.selectionEnd>0){b();
}else{setTimeout(b,1);
}}},_onTextBoxMouseWheelHandler:function(a){if(this.get_readOnly()){return false;
}this._calculateSelection();
var b=this._partIndex[this._textBoxElement.selectionStart];
if(b==null){return true;
}return b.HandleWheel(a);
},_updateSelectionOnFocus:function(){switch(this.get_selectionOnFocus()){case 0:break;
case 1:var a=0;
var b;
for(b=0;
b<this._partIndex.length;
b++){if(!this._partIndex[b].ch){a=b;
break;
}}this.set_caretPosition(a);
break;
case 2:if(this._textBoxElement.value.length>0){this.set_caretPosition(this._textBoxElement.value.length);
}break;
case 3:this.selectAllText();
break;
default:this.set_caretPosition(0);
break;
}},_onTextBoxKeyDownHandler:function(f){if(!this._focused){this._focused=true;
}if(f.keyCode==27&&!$telerik.isIE){var b=this;
window.setTimeout(function(){b.set_textBoxValue(b.get_editValue());
},0);
}this._FakeOnPropertyChange(f);
if(this.inSelection(f)){return true;
}var a=this._partIndex[this._textBoxElement.selectionStart];
if(this.get_readOnly()&&(f.keyCode==46||f.keyCode==8||f.keyCode==38||f.keyCode==40||f.keyCode==127)){f.preventDefault();
return false;
}else{if(f.keyCode==13){return true;
}else{if(a==null&&f.keyCode!=8){return true;
}else{if(a!=null){if(a.HandleKey(f)){f.preventDefault();
return false;
}}}}}var d=this._textBoxElement.selectionEnd;
var c=false;
if((f.keyCode==46||f.keyCode==127)&&d<this._textBoxElement.value.length){a.SetValue("",this._textBoxElement.selectionStart);
d++;
c=true;
f.preventDefault();
}else{if(f.keyCode==8&&d){this._partIndex[this._textBoxElement.selectionStart-1].SetValue("",this._textBoxElement.selectionStart-1);
d--;
c=true;
f.preventDefault();
}}if(c){return this._UpdateAfterKeyHandled(f,d);
}this._OnActivity(f);
return true;
},_onTextBoxKeyPressHandler:function(h){var a=true;
for(var c in Sys.UI.Key.prototype){if(h.charCode===Sys.UI.Key[c]){a=false;
break;
}}if(this.get_readOnly()&&a){h.preventDefault();
h.stopPropagation();
return false;
}var g=new Telerik.Web.UI.InputKeyPressEventArgs(h,h.charCode,String.fromCharCode(h.charCode));
this.raise_keyPress(g);
if(g.get_cancel()){h.stopPropagation();
h.preventDefault();
return false;
}if(this.inSelection(h)){return true;
}var f=this._partIndex[this._textBoxElement.selectionStart];
if(f==null){if(h.charCode==13){if(this._ValueHasChanged()){this.raise_valueChanged();
this.updateDisplayValue();
this.updateCssClass();
}if(this.get_autoPostBack()&&this._canAutoPostBackAfterValidation()){this.raisePostBackEvent();
}return true;
}else{if(h.charCode>47){h.stopPropagation();
h.preventDefault();
}return false;
}}if(Sys.Browser.agent==Sys.Browser.Firefox||Sys.Browser.agent==Sys.Browser.Opera){if(h.charCode==8){h.preventDefault();
h.stopPropagation();
return false;
}if(h.charCode==9){return true;
}if(!h.rawEvent.which){this._OnActivity(h);
h.stopPropagation();
return true;
}}var d=this._textBoxElement.selectionEnd;
if(h.charCode==13){if(this._ValueHasChanged()){this.raise_valueChanged();
this.updateDisplayValue();
this.updateCssClass();
}if(this.get_autoPostBack()&&this._canAutoPostBackAfterValidation()){this.raisePostBackEvent();
}return true;
}var b=String.fromCharCode(h.charCode);
if(f.CanHandle(b,d)){while(d<this._textBoxElement.value.length){if(this._partIndex[d].SetValue(b,d)){d++;
break;
}d++;
}}var i=this._UpdateAfterKeyHandled(h,d);
if(!i){h.preventDefault();
}h.stopPropagation();
return i;
},_OnEnumChanged:function(d,a,b){var c=new Telerik.Web.UI.MaskedTextBoxEventArgs(b,a,d);
this.raise_enumerationChanged(c);
},_OnMoveUp:function(d,a,b){var c=new Telerik.Web.UI.MaskedTextBoxEventArgs(b,a,d);
this.raise_moveUp(c);
},_OnMoveDown:function(d,a,b){var c=new Telerik.Web.UI.MaskedTextBoxEventArgs(b,a,d);
this.raise_moveDown(c);
},_OnValueChange:function(d,a,b){var c=new Telerik.Web.UI.MaskedTextBoxEventArgs(b,a,d);
this.raiseEvent("valueChanged",c);
},_OnChunkError:function(d,a,b){var c=new Telerik.Web.UI.MaskedTextBoxEventArgs(b,a,d);
this.raise_error(c);
},_fixAbsolutePositioning:function(){var b=this._textBoxElement;
if(b.previousSibling&&b.previousSibling.tagName.toLowerCase()=="label"&&b.style.position=="absolute"){b.style.position="static";
var a=b.parentNode;
a.style.position="absolute";
a.style.top=b.style.top;
a.style.left=b.style.left;
}},_RecordInitialState:function(){this.initialFieldValue=this._textBoxElement.value;
},_PartAt:function(a){return this._partIndex[a];
},_CreatePartCollection:function(a,d){var e;
var f=[];
var g=0;
for(var b=0;
b<a.length;
b++){e=a[b];
e.PromptChar=d;
e.SetController(this);
e.index=this._parts.length;
f[f.length]=e;
if(f.length>1){f[f.length-2].NextChunk=e;
}e.NextChunk=null;
var c=e.GetLength();
e.offset=g;
g+=c;
}return f;
},_setMask:function(d){this._parts=this._CreatePartCollection(d,this.get_promptChar());
for(var a=0;
a<this._parts.length;
a++){var c=this._parts[a].GetLength();
for(var b=this._length;
b<this._length+c;
b++){this._partIndex[b]=this._parts[a];
}this._length+=c;
}},_setDisplayMask:function(e){this._displayParts=this._CreatePartCollection(e,this.get_displayPromptChar());
for(var b=0;
b<this._displayParts.length;
b++){var a=this._displayParts[b];
var d=a.GetLength();
if(a.ch){continue;
}for(var c=this._displayLength;
c<this._displayLength+d;
c++){this._displayPartIndex[c]=this._displayParts[b];
}this._displayLength+=d;
}},_SafariSelectionFix:function(b){var a=this._StrCompare(this._lastState.fieldValue,b.fieldValue);
b._selectionStart=a[0];
b._selectionEnd=a[0];
this._lastState._selectionStart=a[1];
this._lastState._selectionEnd=a[2];
},_HandleValueChange:function(k){if(this.get_readOnly()){this._Visualise();
return false;
}if(this._lastState==null){return;
}var b,c;
if(!$telerik.isSafari2&&$telerik.isSafari){this._SafariSelectionFix(k);
}if(this._lastState.fieldValue.length>k.fieldValue.length){if(k._selectionStart==this._textBoxElement.value.length){this._partIndex[this._partIndex.length-1].SetValue("",this._partIndex.length-1);
}if(this._lastState._selectionEnd>k._selectionStart){b=this._lastState._selectionEnd;
while(b-->k._selectionStart){var f=this._partIndex[b];
if(f){f.SetValue("",b);
}}}else{b=this._lastState._selectionEnd+1;
while(b-->k._selectionStart){this._partIndex[b].SetValue("",b);
k._selectionEnd++;
}}}var d=this._lastState._selectionStart;
var h=Math.min(k._selectionStart,this._length);
var a=k.fieldValue.substr(d,h-d);
var l=this._UpdatePartsInRange(a,d,h);
this._Visualise();
k._selectionEnd+=l;
if($telerik.isIE){this._FixSelection(k);
}else{var g=this;
setTimeout(function(){g._FixSelection(k);
},0);
}},_SetPartValues:function(d,f,a,g,k){var e;
var b=0;
var c=g;
var h=0;
a=a.toString();
while(b<k-g&&c<f){e=a.charAt(b);
if(e==this.get_promptChar()){e="";
}if(d[c].SetValue(e,c)){b++;
}else{h++;
}c++;
}return h;
},_UpdateDisplayPartsInRange:function(a,b,c){this._SetPartValues(this._displayPartIndex,this._displayLength,a,b,c);
},_UpdatePartsInRange:function(a,c,d){var b=this._SetPartValues(this._partIndex,this._length,a,c,d);
return b;
},_FixSelection:function(a){this.set_cursorPosition(a._selectionEnd);
},_GetVisibleValues:function(b){var a=[];
for(var c=0;
c<b.length;
c++){a[c]=b[c].GetVisValue();
}return a.join("");
},_Visualise:function(){var b=this.get_valueWithPromptAndLiterals();
var a=this.get_value();
this._internalValueUpdate=true;
this._value=a;
this._Render(b);
this.updateCssClass();
this.updateHiddenValue();
this._internalValueUpdate=false;
this._projectedValue=this._textBoxElement.value;
},_Render:function(a){this._isEmptyMessage=false;
if(!this._focused){if(this.get_hideOnBlur()&&this.isEmpty()){this._isEmptyMessage=true;
this.set_textBoxValue(this.get_emptyMessage());
}else{if(this._displayParts&&this._displayParts.length){this.set_textBoxValue(this.get_displayValue());
}else{this.set_textBoxValue(a);
}}}else{this.set_textBoxValue(a);
}},_getResetValue:function(){var b="";
var a=this._parts[0];
while(a.NextChunk){if(a.GetVisValue()==a.GetValue()){b+=a.PromptChar;
}else{b+=a.GetVisValue();
}a=a.NextChunk;
}return b;
},_ValueHasChanged:function(){return this._textBoxElement.value!=this._textBoxElement._oldValue;
},_FakeOnPropertyChange:function(b){if($telerik.isIE&&document.documentMode>8){this._calculateSelection();
this._ValueHandler(b||{});
}else{if(document.createEventObject){if(event){var a=document.createEventObject(event);
}else{var a=document.createEventObject();
}a.propertyName="value";
this._textBoxElement.fireEvent("onpropertychange",a);
}}},_UpdateAfterKeyHandled:function(c,a){this._Visualise();
var b=new Telerik.Web.UI.MaskedEventWrap(c,this._textBoxElement);
b._selectionEnd=a;
this._FixSelection(b);
return false;
},_ValueHandler:function(b){if(this._internalValueUpdate){return true;
}if(!b){b=window.event;
}this._calculateSelection();
var a=new Telerik.Web.UI.MaskedEventWrap(b,this._textBoxElement);
if(a.fieldValue!=this._projectedValue){this._HandleValueChange(a);
}return true;
},_ActivityHandler:function(a){if(this._internalValueUpdate){return true;
}if(!a){a=window.event;
}this._OnActivity(a);
return true;
},_calculateSelection:function(){if((document.selection&&Sys.Browser.agent!=Sys.Browser.Opera)&&(typeof window.getSelection=="undefined")){var b;
try{b=document.selection.createRange();
}catch(a){return;
}if(b.parentElement()!=this._textBoxElement){return;
}var c=b.duplicate();
if(this._isTextarea){c.moveToElementText(this._textBoxElement);
}else{c.move("character",-this._textBoxElement.value.length);
}c.setEndPoint("EndToStart",b);
this._textBoxElement.selectionStart=c.text.length;
this._textBoxElement.selectionEnd=this._textBoxElement.selectionStart+b.text.length;
if(this._isTextarea){}}},_StrCompare:function(f,c){var b;
var a,e,d;
b=0;
while(f.charAt(b)==c.charAt(b)&&b<f.length){b++;
}e=b;
f=f.substr(e).split("").reverse().join("");
c=c.substr(e).split("").reverse().join("");
b=0;
while(f.charAt(b)==c.charAt(b)&&b<f.length){b++;
}a=e+c.length-b;
d=f.length-b+e;
return[a,e,d];
},get__initialMasks:function(){return this._initialMasks;
},set__initialMasks:function(a){this._initialMasks=a;
},get__initialDisplayMasks:function(){return this._initialDisplayMasks;
},set__initialDisplayMasks:function(a){this._initialDisplayMasks=a;
},raise_valueChanged:function(){this._triggerDomEvent("change",this._getValidationField());
var a=this._textBoxElement._oldValue;
this._textBoxElement._oldValue=this._textBoxElement.value;
this._OnValueChange(null,a,this._textBoxElement.value);
}};
Telerik.Web.UI.RadMaskedTextBox.registerClass("Telerik.Web.UI.RadMaskedTextBox",Telerik.Web.UI.RadInputControl);
