Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadListViewItemDrag=function(){Telerik.Web.UI.RadListViewItemDrag.initializeBase(this);
this._owner={};
this._documentMouseMoveDelegate=null;
this._documentMouseUpDelegate=null;
};
Telerik.Web.UI.RadListViewItemDrag.prototype={initialize:function(){Telerik.Web.UI.RadListViewItemDrag.callBaseMethod(this,"initialize");
this._documentMouseUpDelegate=$telerik.addMobileHandler(this,document,"mouseup",this._mouseUp,null,true);
this._documentMouseMoveDelegate=$telerik.addMobileHandler(this,document,"mousemove",this._mouseMove,null,true);
},dispose:function(){if(this._documentMouseUpDelegate){$telerik.removeMobileHandler(document,"mouseup",this._documentMouseUpDelegate,null,true);
this._documentMouseUpDelegate=null;
}if(this._documentMouseMoveDelegate){$telerik.removeMobileHandler(document,"mousemove",this._documentMouseMoveDelegate,null,true);
this._documentMouseMoveDelegate=null;
}Telerik.Web.UI.RadListViewItemDrag.callBaseMethod(this,"dispose");
},_getFirstParentByClassName:function(b,f,c){if(typeof(f)=="string"){f=[f];
}var d=b;
while(d){for(var a=0,e=f.length;
a<e;
a++){if(Sys.UI.DomElement.containsCssClass(d,f[a])&&(!c||c&&d.tagName.toLowerCase()==c)){return d;
}}if(d.tagName.toLowerCase()=="body"){return null;
}d=d.parentNode;
}},_dragHandleMouseDown:function(g,b){var a;
if(b==a||isNaN(b)||b==-1){return;
}var d=this._getCurrentElement(g);
if(!Sys.UI.DomElement.containsCssClass(d,"rlvDrag")){d=this._getFirstParentByClassName(d,["rlvDrag"]);
if(!d){return;
}}this._grabbedItem=this._getFirstParentByClassName(d,["rlvI","rlvA"]);
if(!this._grabbedItem){return;
}this._draggedItemIndex=b;
var c={itemIndex:this._draggedItemIndex,dataKeyValues:this.get_owner().get_clientDataKeyValue()[this._draggedItemIndex],domEvent:g};
var f=this._buildEventArgs(new Sys.CancelEventArgs(),c);
this.get_owner().raise_itemDragStarted(f);
if(f.get_cancel()){this._draggedItemIndex=null;
this._grabbedItem=null;
return;
}this._createDraggedItem(this._grabbedItem);
if(!this._draggedItem){return;
}this._canMoveItem=true;
if(g.stopPropagation){g.stopPropagation();
}if(g.preventDefault){g.preventDefault();
}return false;
},_getCurrentElement:function(a){if($telerik.isTouchDevice){return $telerik.getTouchTarget(a);
}else{if(!a){var a=window.event;
}return a.target||a.srcElement;
}},_createDraggedItem:function(f){this._draggedItem=document.createElement("div");
this._draggedItem.id=String.format("{0}_DraggedItem",this.get_owner().get_id());
this._draggedItem.className=this.get_owner().Skin!=""?"RadListView RadListView_"+this.get_owner().Skin+" rlvDraggedItem":"RadListView rlvDraggedItem";
this._draggedItem.style.position="absolute";
this._draggedItem.style.zIndex="99999";
this._draggedItem.style.display="none";
var d=f.tagName.toLowerCase();
if(d=="td"){var g=String.format(this._cloneNodeHtml(f.parentNode.parentNode.parentNode),"<tbody>{0}</tbody>");
var e=this._cloneNodeHtml(f.parentNode);
var b=this._cloneNodeHtml(f,true);
this._draggedItem.innerHTML=String.format(g,String.format(e,b));
}else{if(d=="tr"){var g=String.format(this._cloneNodeHtml(f.parentNode.parentNode),"<tbody>{0}</tbody>");
var e=this._cloneNodeHtml(f,true);
this._draggedItem.innerHTML=String.format(g,e);
}else{if(d=="li"){var h=this._cloneNodeHtml(f.parentNode);
var a=this._cloneNodeHtml(f,true);
this._draggedItem.innerHTML=String.format(h,a);
this._draggedItem.childNodes[0].style.listStyleType="none";
}else{this._draggedItem.innerHTML=this._cloneNodeHtml(f,true);
}}}var c=document.getElementsByTagName("form")[0];
c.appendChild(this._draggedItem);
},_cloneNodeHtml:function(a,d){var c=a.tagName.toLowerCase();
var e=a.className!=""?String.format(" class='{0}'",a.className):"";
var f=a.style.cssText!=""?String.format(" style='{0}'",a.style.cssText):"";
var g=String.format("<{0}{1}{2}>",c,e,f);
var b=String.format("</{0}>",c);
if(d){return g+a.innerHTML+b;
}return g+"{0}"+b;
},_mouseUp:function(h){this._canMoveItem=false;
if(this._draggedItemIndex!=null){var c=this._grabbedItem;
var b=this._draggedItemIndex;
var f=this._getCurrentElement(h);
this._cancelDragging();
if($telerik.isDescendantOrSelf(c,f)){return;
}var a={itemIndex:b,dataKeyValues:this.get_owner().get_clientDataKeyValue()[b],destinationElement:f,domEvent:h};
var g=this._buildEventArgs(new Sys.CancelEventArgs(),a);
this.get_owner().raise_itemDropping(g);
if(!g.get_cancel()){this.get_owner().raise_itemDropped(g);
var d=f&&f.id?b+","+f.id:b;
this.get_owner().fireCommand("ItemDrop",d);
}}},_cancelDragging:function(){if(this._draggedItem){this._draggedItem.parentNode.removeChild(this._draggedItem);
}this._draggedItem=null;
this._grabbedItem=null;
this._draggedItemIndex=null;
},_mouseMove:function(a){if(this._canMoveItem&&this._draggedItem){this.get_owner().raise_itemDragging(this._buildEventArgs(new Sys.EventArgs(),{domEvent:a}));
this._draggedItem.style.display="";
this._positionDragElement(this._draggedItem,a);
return false;
}},_buildEventArgs:function(d,c){for(var b in c){var e=b;
var a=c[b];
if(e.indexOf("et_")>0){d[e]=a;
continue;
}d["_"+e]=a;
d["get_"+e]=function(f){return function(){return this["_"+f];
};
}(e);
}return d;
},_positionDragElement:function(d,e){var c,a;
if($telerik.isTouchDevice){var b=$telerik.getTouchEventLocation(e);
c=b.x;
a=b.y;
}else{c=e.clientX;
a=e.clientY;
}d.style.top=a+document.documentElement.scrollTop+document.body.scrollTop+1+"px";
d.style.left=c+document.documentElement.scrollLeft+document.body.scrollLeft+1+"px";
if($telerik.isOpera||$telerik.isSafari2){d.style.top=parseInt(d.style.top)-document.body.scrollTop+"px";
}},get_owner:function(){return this._owner;
},set_owner:function(a){this._owner=a;
}};
Telerik.Web.UI.RadListViewItemDrag.registerClass("Telerik.Web.UI.RadListViewItemDrag",Sys.Component);
