Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.LightDialogsControllerClass=function(){this._activeDialog=null;
};
Telerik.Web.UI.LightDialogsControllerClass.initializeLightDialog=function(b){var d=b.ClientParameters._commandName;
var c=b.ClientParameters.editor;
var a=null;
if(d=="InsertLink"){a=c._insertLink;
if(!a){a=new Telerik.Web.UI.InsertLink(b);
b.set_title(c._localization[d.toLowerCase()]);
a.initialize();
c._insertLink=a;
}}if(d=="InsertImage"){a=c._insertImage;
if(!a){a=new Telerik.Web.UI.InsertImage(b);
b.set_title(c._localization[d.toLowerCase()]);
a.initialize();
c._insertImage=a;
}}if(d=="InsertTableLight"){a=c._insertTableLight;
if(!a){a=new Telerik.Web.UI.InsertTableLight(b);
b.set_title(c._localization.inserttable);
a.initialize();
c._insertTableLight=a;
}}Telerik.Web.UI.LightDialogsController._activeDialog=a;
a.set_clientParameters(b.ClientParameters);
a.cleanInputBoxes();
a.setInitialValues();
if(window.focus){window.focus();
}};
Telerik.Web.UI.LightDialogsControllerClass.registerClass("Telerik.Web.UI.LightDialogsControllerClass",null);
if(!Telerik.Web.UI.LightDialogsController){Telerik.Web.UI.LightDialogsController=new Telerik.Web.UI.LightDialogsControllerClass();
}Telerik.Web.UI.LightDialogBase=function(a){this._clientParameters=a.ClientParameters;
this._container=a;
this._editor=this._clientParameters.editor;
this._prefix=this._editor.get_id();
if(this._editor.get_toolProviderID()){this._prefix=this._editor.get_toolProviderID();
}this._insertButton=null;
this._cancelButton=null;
this._allPropButton=null;
this._inputsArray=null;
};
Telerik.Web.UI.LightDialogBase.prototype={initializeChildEvents:function(b,a){this._insertClickHandler=b;
if(this._allPropButton){$addHandlers(this._allPropButton,{click:a},this);
}if(this._insertButton){$addHandlers(this._insertButton,{click:b},this);
}if(this._cancelButton){$addHandlers(this._cancelButton,{click:this._cancelClickHandler},this);
}},set_clientParameters:function(a){this._clientParameters=a;
},cleanInputBoxes:function(){var c=this._inputsArray;
if(c){for(var b=0;
b<c.length;
b++){var a=c[b][0];
if(this[a]&&this[a].tagName.toLowerCase()=="input"){this[a].value="";
}}}},setUpChildren:function(e){var c=this._inputsArray;
var d=this._prefix;
if(c){for(var b=0;
b<c.length;
b++){var a=c[b][0];
this[a]=$get(d+c[b][1],e);
}}},dispose:function(){if(this._insertButton){$clearHandlers(this._insertButton);
}this._insertButton=null;
if(this._cancelButton){$clearHandlers(this._cancelButton);
}this._cancelButton=null;
if(this._allPropButton){$clearHandlers(this._allPropButton);
}this._allPropButton=null;
this._insertClickHandler=null;
},_cancelClickHandler:function(a){this._container.close();
}};
Telerik.Web.UI.LightDialogBase.registerClass("Telerik.Web.UI.LightDialogBase",null);
Telerik.Web.UI.InsertLink=function(a){Telerik.Web.UI.InsertLink.initializeBase(this,[a]);
this._linkUrlInput=null;
this._linkTextInput=null;
this._linkTargetCombo=null;
this._texTextBoxParentNode=null;
};
Telerik.Web.UI.InsertLink.prototype={initialize:function(){var a=$get(this._prefix+"_InsertLink");
if(!a){return;
}this._container.set_contentElement(a);
this._inputsArray=new Array(["_linkUrlInput","_LinkUrl"],["_linkTextInput","_LinkText"],["_linkTargetCombo","_LinkTargetCombo"],["_insertButton","_lmlInsertBtn"],["_cancelButton","_lmlCancelBtn"],["_allPropButton","_lmlAllProperties"],["_texTextBoxParentNode","_texTextBoxParentNode"]);
this.setUpChildren(a);
this.initializeChildEvents();
},dispose:function(){$clearHandlers(this._linkTargetCombo);
this._linkTargetCombo=null;
Telerik.Web.UI.InsertLink.callBaseMethod(this,"dispose");
},initializeChildEvents:function(){Telerik.Web.UI.InsertLink.callBaseMethod(this,"initializeChildEvents",[this._insertClickHandler,this._allPropertiesClickHandler]);
$addHandlers(this._linkTargetCombo,{change:this._linkTargetChangeHandler},this);
},cleanInputBoxes:function(){if(this._linkTargetCombo.options&&this._linkTargetCombo.options.length>0){this._linkTargetCombo.options[0].selected=true;
}Telerik.Web.UI.InsertLink.callBaseMethod(this,"cleanInputBoxes",[this._inputsArray]);
},_loadLinkProperties:function(){var c=this._clientParameters.get_value();
var a=c.getAttribute("href",2);
var b="http://";
if(c.href){b=a;
}this._linkUrlInput.value=b;
if(this._clientParameters.showText){this._linkTextInput.value=c.innerHTML;
if(this._texTextBoxParentNode){this._texTextBoxParentNode.style.display="";
}}else{if(this._texTextBoxParentNode){this._texTextBoxParentNode.style.display="none";
}}this._loadLinkTarget();
},_loadLinkTarget:function(){var e=this._clientParameters.get_value().target;
if(!e){return;
}var c=this._linkTargetCombo.getElementsByTagName("optgroup");
for(var a=0;
a<c.length;
a++){if(c[a].nodeName.toLowerCase()=="optgroup"){var b=c[a].getElementsByTagName("option");
for(var d=0;
d<b.length;
d++){if(b[d].nodeName.toLowerCase()=="option"&&b[d].value.toLowerCase()==e.toLowerCase()){b[d].selected=true;
return;
}}}}var f=document.createElement("option");
f.value=e;
f.text=e;
this._linkTargetCombo.options.add(f);
f.selected=true;
},setInitialValues:function(){this._loadLinkProperties();
this._loadLinkTarget();
},getModifiedLink:function(){var a=this._clientParameters.get_value();
a.href=this._linkUrlInput.value;
if(this._linkTargetCombo.value=="_none"){a.removeAttribute("target",0);
}else{a.target=this._linkTargetCombo.value;
}if(this._texTextBoxParentNode&&this._texTextBoxParentNode.style.display!="none"&&this._linkText){a.innerHTML=this._linkText.value;
}if(a.innerHTML.trim()==""||a.innerHTML.trim().length<this._linkTextInput.value.trim().length){a.innerHTML=this._linkTextInput.value.replace(/&/gi,"&amp;").replace(/</gi,"&lt;").replace(/>/gi,"&gt;");
}if(a.innerHTML.trim()==""){a.innerHTML=a.href;
}return a;
},_linkTargetChangeHandler:function(d){if(this._linkTargetCombo.value=="_custom"){var c="Type Custom Target Here";
var a=prompt(c,"CustomWindow");
if(a){var b=document.createElement("option");
b.innerHTML=a;
b.setAttribute("selected","selected");
b.setAttribute("value",a);
this._linkTargetCombo.getElementsByTagName("optgroup")[1].appendChild(b);
return;
}this._linkTargetCombo.selectedIndex=0;
}},_insertClickHandler:function(c){var b=this.getModifiedLink();
var a=new Telerik.Web.UI.EditorCommandEventArgs("InsertLink",null,b);
a.realLink=b;
this._container.close(a);
},_allPropertiesClickHandler:function(f){var d=this.getModifiedLink();
var c=new Telerik.Web.UI.EditorCommandEventArgs("LinkManager",null,d);
c.realLink=d;
c.set_value(d);
this._container.close();
c.selectedTabIndex=0;
c.showText=!(this._linkTextInput.value=="");
c.documentAnchors=Telerik.Web.UI.Editor.CommandList._getDocumentAnchors(this._editor.get_document());
if(d.name){c.documentAnchors[c.documentAnchors.length]=d;
}Telerik.Web.UI.Editor.CommandList._getDialogArguments(c,"A",this._editor,"LinkManager");
var a=this._editor;
var b=function(h,g){var e=g.get_value();
if(!e){e=g.Result;
}if(!e){e=g.realLink;
}a.pasteHyperLink(e,"LinkManager");
};
a.showDialog("LinkManager",c,b);
}};
Telerik.Web.UI.InsertLink.registerClass("Telerik.Web.UI.InsertLink",Telerik.Web.UI.LightDialogBase);
Telerik.Web.UI.InsertImage=function(a){Telerik.Web.UI.InsertImage.initializeBase(this,[a]);
this._imageWidth=null;
this._imageHeight=null;
this._imageAlt=null;
this._imageSrc=null;
this._originalImage=null;
};
Telerik.Web.UI.InsertImage.prototype={initialize:function(){var a=$get(this._prefix+"_InsertImage");
if(!a){return;
}this._container.set_contentElement(a);
this._inputsArray=new Array(["_imageWidth","_ImageWidth"],["_imageHeight","_ImageHeight"],["_imageAlt","_ImageAlt"],["_imageSrc","_ImageSrc"],["_insertButton","_iplInsertBtn"],["_cancelButton","_iplCancelBtn"],["_allPropButton","_iplAllProperties"]);
this.setUpChildren(a);
this.initializeChildEvents(this._insertClickHandler,this._allPropertiesClickHandler);
},_insertClickHandler:function(c){if(!this._originalImage&&this._imageSrc.value){this._originalImage=document.createElement("img");
}var a=this.getModifiedImage();
if(a){this._clearImgeDimensions(a);
var b=new Telerik.Web.UI.EditorCommandEventArgs("InsertImage",null,a);
this._container.close(b);
}else{$telerik.cancelRawEvent(c);
}},_allPropertiesClickHandler:function(f){var a=this._editor;
var g="SetImageProperties";
if(!this._originalImage&&this._imageSrc.value){this._originalImage=document.createElement("img");
}var c=this.getModifiedImage();
var d=new Telerik.Web.UI.EditorCommandEventArgs("SetImageProperties",null,c);
Telerik.Web.UI.Editor.CommandList._getDialogArguments(d,"IMG",a,g);
d.Element=c;
d.set_value(c);
this._container.close();
var b=function(i,h){var e=h.get_value?h.get_value():h.Result;
if(!e){return;
}if(c&&c.parentNode){c.parentNode.replaceChild(e,c);
}else{a.pasteHtml(Telerik.Web.UI.Editor.Utils.getOuterHtml(e),g);
}};
a.showDialog("ImageProperties",d,b);
},getModifiedImage:function(){if(this._originalImage==null){return null;
}var a=this._originalImage.cloneNode(true);
var b=this._imageSrcValue?this._imageSrcValue:this._imageSrc.value;
this._setAttribute(a,"src",b);
this._setDimensionAttribute(a,"width",this._imageWidth.value);
this._setDimensionAttribute(a,"height",this._imageHeight.value);
this._setAttribute(a,"alt",this._imageAlt.value);
return a;
},loadImageProperties:function(c){var g=this._originalImage=c;
var d=g.cloneNode(true);
var b=this._getOriginalDimension(g,"width",g.width,g.offsetWidth);
this._imageWidth.value=(b.indexOf("px")!=-1)?parseInt(b):b;
var e=this._getOriginalDimension(g,"height",g.height,g.offsetHeight);
this._imageHeight.value=(e.indexOf("px")!=-1)?parseInt(e):e;
this._ratio=parseInt(this._imageWidth.value)/parseInt(this._imageHeight.value);
var a=d.getAttribute("src",2);
if(this._imageSrc){this._imageSrc.value=a;
this._imageSrcValue=null;
}else{this._imageSrcValue=a;
}var f=d.getAttribute("alt");
this._imageAlt.value=f?f:"";
},setInitialValues:function(){var a=this._clientParameters;
if(!a.get_value){return;
}var b=a.get_value();
if(b){this.loadImageProperties(b);
}},cleanInputBoxes:function(){this._originalImage=null;
this._imageSrcValue=null;
Telerik.Web.UI.InsertImage.callBaseMethod(this,"cleanInputBoxes",[this._inputsArray]);
},_getOriginalDimension:function(a,d,b,e){if(!a){return"";
}var c;
if(a.style[d]){c=a.style[d];
}if(!c){c=a.getAttribute(d);
}if(!c){c=b;
}if(!c){c=e;
}return c==null?"":c+"";
},_getImageOriginalSize:function(a){var c=new Image();
c.src=a.getAttribute?a.getAttribute("src"):a.src;
var b={width:c.width,height:c.height};
return b;
},_setAttribute:function(b,c,a){if(a&&a.trim()){b.setAttribute(c,a);
}else{b.removeAttribute(c,false);
}},_setDimensionAttribute:function(c,e,b){if(!parseInt(b)){b="";
}c.removeAttribute(e);
if(!b){if(c.style.removeAttribute){c.style.removeAttribute(e,false);
}else{c.style[e]="";
}}else{var d=$telerik.parseUnit(b);
try{c.style[e]=d.size+d.type;
}catch(a){}}},_clearImgeDimensions:function(c){var d=this._getImageOriginalSize(c);
var e=d.width;
var a=this._getOriginalDimension(c,"width",c.width,c.offsetWidth);
if(a.indexOf("px")!=-1){a=parseInt(a);
}var b=d.height;
var f=this._getOriginalDimension(c,"height",c.height,c.offsetHeight);
if(f.indexOf("px")!=-1){f=parseInt(f);
}if((e==a&&(f==0||b==f))||(b==f&&(a==0||e==a))){c.style.width="";
c.style.height="";
}}};
Telerik.Web.UI.InsertImage.registerClass("Telerik.Web.UI.InsertImage",Telerik.Web.UI.LightDialogBase);
Telerik.Web.UI.InsertTableLight=function(a){Telerik.Web.UI.InsertTableLight.initializeBase(this,[a]);
this._alignmentSelectorTable=null;
this._rowsCount=null;
this._colsCount=null;
this._cellSpacing=null;
this._cellPadding=null;
this._borderWidth=null;
this._tableToModify=null;
this._originalRowsCount=null;
this._originalColsCount=null;
};
Telerik.Web.UI.InsertTableLight.prototype={initialize:function(){var a=$get(this._prefix+"_InsertTableLight");
if(!a){return;
}this._container.set_contentElement(a);
this._alignmentSelectorTable=this.createAlignmentSelector();
this._inputsArray=new Array(["_rowsCount","_Rows"],["_colsCount","_Columns"],["_cellSpacing","_CellSpacing"],["_cellPadding","_CellPadding"],["_borderWidth","_BorderWidth"],["_insertButton","_itlInsertBtn"],["_cancelButton","_itlCancelBtn"],["_allPropButton","_itlAllProperties"]);
this.setUpChildren(a);
this.initializeChildEvents(this._insertClickHandler,this._allPropertiesClickHandler);
},dispose:function(){this._tableToModify=null;
this._originalRowsCount=null;
this._originalColsCount=null;
this._alignmentSelectorTable.dispose();
},createAlignmentSelector:function(){var a=this._prefix+"_AlignmentSelectorTable";
var c=$find(a);
if(c==null){var b=$get(a);
Sys.UI.DomElement.addCssClass(b.parentNode,this._editor.get_skin());
c=$create(Telerik.Web.UI.Editor.AlignmentSelector,{addClickHandler:true,clientStateFieldID:a+"_ClientState",name:a,skin:this._editor.get_skin()},null,null,b);
c.setTagName("TABLE");
}return c;
},_insertClickHandler:function(b){var a=this.getModifiedTable(this._tableToModify);
if(!a){this._container.close();
}else{this._container.close({tableToModify:a});
}},_allPropertiesClickHandler:function(d){var b=this._clientParameters;
Telerik.Web.UI.Editor.CommandList._getDialogArguments(b,"TABLE",this._editor,"SetTableProperties");
var f=this.getModifiedTable(this._tableToModify);
if(!f){f=this._tableToModify=document.createElement("table");
this._originalRowsCount=0;
this._originalColsCount=0;
var a=parseInt(this._rowsCount.value);
var c=parseInt(this._colsCount.value);
if(isNaN(a)||a<=0){this.addRowsCols(f,0,2,true);
this._originalRowsCount=2;
}if(isNaN(c)||c<=0){this.addRowsCols(f,0,2,false);
this._originalColsCount=2;
}f=this.getModifiedTable(f);
}b.tableToModify=f;
var g=this._container.get_clientCallBackFunction();
b._name=b._commandName="SetTableProperties";
b.selectedTabIndex=1;
b.originalTable=f;
this._editor.showDialog("TableWizard",b,g);
this._container.close();
return false;
},cleanInputBoxes:function(){this._alignmentSelectorTable.updateValue("none");
Telerik.Web.UI.InsertTableLight.callBaseMethod(this,"cleanInputBoxes",[this._inputsArray]);
},setInitialValues:function(){this.loadTableProperties();
},_getRowColSpan:function(b,c){if(b){var a=parseInt(b.getAttribute(c));
if(isNaN(a)){a=1;
}return a;
}return 0;
},loadTableProperties:function(){var d=this._tableToModify=this._clientParameters.tableToModify;
if(d){var l=d.rows;
var f=l.length;
var h=0;
for(var b=0;
b<f;
b++){var g=0;
var k=l[b].cells;
var a=k.length;
for(var c=0;
c<a;
c++){g+=this._getRowColSpan(k[c],"colSpan");
}if(h<g){h=g;
}}this._rowsCount.value=this._originalRowsCount=f;
this._colsCount.value=this._originalColsCount=h;
this._cellSpacing.value=d.cellSpacing;
this._cellPadding.value=d.cellPadding;
this._alignmentSelectorTable.updateValue(d.align);
var e=parseInt(d.border);
this._borderWidth.value=isNaN(e)?"":e;
}},set_clientParameters:function(a){this._clientParameters=a;
},getModifiedTable:function(d){var c=parseInt(this._rowsCount.value);
var e=parseInt(this._colsCount.value);
if(!d&&!(isNaN(c)||isNaN(e))){d=document.createElement("table");
this._originalRowsCount=0;
this._originalColsCount=0;
}if(!d){return;
}var g=this._originalRowsCount;
var f=this._originalColsCount;
if(c>0&&c!=g){c>g?this.addRowsCols(d,g,c,true):this.removeRowsCols(d,g,c,true);
}if(e>0&&e!=f){e>f?this.addRowsCols(d,f,e,false):this.removeRowsCols(d,f,e,false);
}this._setAttribValue(d,"align",this._alignmentSelectorTable.getAlign());
var h=parseInt(this._cellSpacing.value);
if(!isNaN(parseInt(h))){this._setAttribValue(d,"cellSpacing",h>=0?h:"",(h>=0));
}var b=parseInt(this._cellPadding.value);
if(!isNaN(parseInt(b))){this._setAttribValue(d,"cellPadding",b>=0?b:"",(b>=0));
}var a=parseInt(this._borderWidth.value);
if(!isNaN(parseInt(a))){this._setAttribValue(d,"border",a>=0?a:"",(a>=0));
}return d;
},addRowsCols:function(c,b,e,a){for(var d=b;
d<e;
d++){if(a){this.addNewRow(c);
}else{this.addNewCol(c);
}}},removeRowsCols:function(c,b,e,a){for(var d=e;
d<b;
d++){if(a){this.deleteLastRow(c);
}else{this.deleteLastCol(c);
}}},addNewRow:function(d){var a=d.insertRow(-1);
var c=this._originalColsCount;
for(var b=0;
b<c;
b++){var e=a.insertCell(-1);
e.innerHTML="&nbsp;";
}},deleteLastRow:function(a){a.deleteRow(-1);
},addNewCol:function(b){var d=b.rows;
for(var a=0;
a<d.length;
a++){var c=d[a].insertCell(-1);
c.innerHTML="&nbsp;";
}},deleteLastCol:function(b){var c=b.rows;
for(var a=0;
a<c.length;
a++){c[a].deleteCell(-1);
}},_setAttribValue:function(d,a,b,c){if(b||(true==c)){d.setAttribute(a,b);
}else{d.removeAttribute(a,false);
}}};
Telerik.Web.UI.InsertTableLight.registerClass("Telerik.Web.UI.InsertTableLight",Telerik.Web.UI.LightDialogBase);
