Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.WindowManager");
$telerik.toWindowManager=function(a){return a;
};
$telerik.findWindowManager=$find;
function GetRadWindowManager(){return Telerik.Web.UI.WindowManager.Manager;
}window.radalert=function(e,c,b,f,d){var a=GetRadWindowManager();
return a.radalert(e,c,b,f,d);
};
window.radconfirm=function(f,e,d,c,b,g){var a=GetRadWindowManager();
return a.radconfirm(f,e,d,c,b,g);
};
window.radprompt=function(g,f,d,c,b,h,e){var a=GetRadWindowManager();
return a.radprompt(g,f,d,c,b,h,e);
};
window.radopen=function(a,c){var b=GetRadWindowManager();
return b.open(a,c);
};
window.radopenWithContainer=function(a,b){var d=GetRadWindowManager();
var c=$get(a);
if(!c){radalert("Content element with such ClientID not found!<br/> Make sure you have provided a correct ClientID!");
return;
}return d.open(null,b,c);
};
Telerik.Web.UI.RadWindowManager=function(a){Telerik.Web.UI.RadWindowManager.initializeBase(this,[a]);
this._windowIDs=[];
this._windows=[];
this._preserveClientState=false;
this.Open=this.open;
this.GetWindowByName=this.getWindowByName;
this.GetWindowById=this.getWindowById;
this.GetActiveWindow=this.getActiveWindow;
this.GetWindowObjects=this.get_windows;
this.GetWindows=this.get_windows;
this.Cascade=this.cascade;
this.Tile=this.tile;
this.RestoreAll=this.restoreAll;
this.MaximizeAll=this.maximizeAll;
this.MinimizeAll=this.minimizeAll;
this.ShowAll=this.showAll;
this.CloseAll=this.closeAll;
this.CloseActiveWindow=this.closeActiveWindow;
this.MinimizeActiveWindow=this.minimizeActiveWindow;
this.RestoreActiveWindow=this.restoreActiveWindow;
};
Telerik.Web.UI.RadWindowManager.prototype={get_zIndex:function(){return Telerik.Web.UI.RadWindowUtils._zIndex;
},set_zIndex:function(b){var a=parseInt(b);
if(isNaN(b)){return;
}Telerik.Web.UI.RadWindowUtils._zIndex=b;
},initialize:function(a){try{var b=this.get_element().style.zIndex;
if(b){this.set_zIndex(b);
}}catch(c){}this._initialize();
this._registerAsPageManager();
if(this.get_preserveClientState()){this.restoreState();
}},dispose:function(){var a=this.get_preserveClientState();
if(a){this.saveState();
}this._disposeWindows();
this._windows=null;
Telerik.Web.UI.RadWindowManager.callBaseMethod(this,"dispose");
},open:function(a,c,e){var d=this.getWindowByName(c);
if(!d){if(!c){c=this.get_id()+this._getUniqueId();
}d=this._createWindow(c,e);
var b=this.get_element().className;
if(b){d.set_cssClass(b.replace(/^ /,""));
}}else{if(e&&this.get_navigateUrl()){d._dockMode=false;
}}if(a&&!d.get_reloadOnShow()&&d._iframe&&d._iframe.src!=a){d.setUrl(a);
}else{if(a){d._navigateUrl=a;
}}d.show();
return d;
},radalert:function(e,c,b,f,d){var a=this._getStandardPopup("alert",e);
if(typeof(f)!="undefined"){a.set_title(f);
}a.setSize(c?c:280,b?b:200);
a.set_clientCallBackFunction(function(h,g){if(d){d(g);
}});
a.center();
a.show();
return a;
},radconfirm:function(f,e,d,c,b,g){var a=this._getStandardPopup("confirm",f);
if(typeof(g)!="undefined"){a.set_title(g);
}a.setSize(d?d:280,c?c:200);
a.set_clientCallBackFunction(function(j,h){if(e){e(h);
}});
a.center();
a.show();
return a;
},radprompt:function(h,g,d,c,b,j,f){var a=this._getStandardPopup("prompt",h,f);
if(typeof(j)!="undefined"){a.set_title(j);
}a.setSize(d?d:280,c?c:200);
a.set_clientCallBackFunction(function(l,k){if(g){g(k);
}});
a.center();
a.show();
if(f&&$telerik.isIE){var e=a.get_popupElement().getElementsByTagName("INPUT")[0];
if(e){e.value=f;
}}return a;
},getActiveWindow:function(){return Telerik.Web.UI.RadWindowController.get_activeWindow();
},getWindowById:function(b){var a=this.get_windows();
for(var d=0;
d<a.length;
d++){var c=a[d];
if(b==c.get_id()){return c;
}}return null;
},getWindowByName:function(d){var a=this.get_windows();
if(!a){return null;
}for(var b=0;
b<a.length;
b++){var c=a[b];
if(d==c.get_name()){return c;
}}return null;
},removeWindow:function(b){if(!b){return;
}var c=this.getWindowByName(b.get_name());
var a=this.get_windows();
if(c){Array.remove(a,c);
}},_getUniqueId:function(){return""+(new Date()-100);
},_initialize:function(){var a=this._windowIDs;
for(var b=0;
b<a.length;
b++){var d=a[b];
var c=$find(d);
if(!c){continue;
}c.set_windowManager(this);
this._windows[this._windows.length]=c;
}},_disposeWindows:function(){for(var a=0;
a<this._windows.length;
a++){var b=this._windows[a];
if(b.isCloned()){b.dispose();
}}this._windows=[];
},clearCloneCache:function(){this.__clonedProperties__=null;
},_createWindow:function(b,c){var a=this.clone(b);
a.set_modal(a.isModal());
a.set_name(b);
this._windows[this._windows.length]=a;
a.set_windowManager(this);
if(c){a.set_contentElement(c);
a._dockMode=true;
a.set_behaviors(a.get_behaviors()&~Telerik.Web.UI.WindowBehaviors.Reload);
}return a;
},_replaceLocalization:function(a,b){var e=/##LOC\[(.*?)\]##/;
while(a.match(e)){var d=this._getLocalizationString(RegExp.$1);
var c=d?d:"";
a=a.replace(e,c);
}return a;
},_getStandardPopup:function(b,e,h){var j=this._createWindow(b+this._getUniqueId(),false);
j.set_destroyOnClose(true);
j.set_restrictionZoneID(null);
j.set_modal(true);
e=e.replace(/\$/g,"$$$");
var c=document.getElementById(this.get_id()+"_"+b.toLowerCase()+"template");
var f=$telerik.isIE&&!$telerik.isIE9Mode?"''":"";
var a=this._stringFormat(c.innerHTML,j.get_id(),e,h?h:f);
a=this._replaceLocalization(a,Telerik.Web.UI.RadWindowUtils.Localization);
var g=document.createElement("div");
g.innerHTML=a;
g.id=j.get_id()+"_content";
j.set_behaviors(Telerik.Web.UI.WindowBehaviors.Close+Telerik.Web.UI.WindowBehaviors.Move);
j.set_visibleStatusbar(false);
j._isPredefined=true;
j.set_contentElement(g);
var d=j.get_contentElement().getElementsByTagName("INPUT")[0];
if(!d){d=j.get_contentElement().getElementsByTagName("A")[0];
}if(d&&d.focus){window.setTimeout(function(){var l=true;
if(d.setActive){try{d.setActive();
l=false;
}catch(k){}}if(l){d.focus();
}},0);
}return j;
},_stringFormat:function(a){for(var b=1;
b<arguments.length;
b++){a=a.replace(new RegExp("\\{"+(b-1)+"\\}","ig"),arguments[b]);
}return a;
},_registerAsPageManager:function(){var b=Telerik.Web.UI.WindowManager.Manager;
var a=this.get_id();
if(b&&b.get_id()==a){b.dispose();
Telerik.Web.UI.WindowManager.Manager=null;
}if(b&&!b.get_id()){Telerik.Web.UI.WindowManager.Manager=null;
}if(!Telerik.Web.UI.WindowManager.Manager){Telerik.Web.UI.WindowManager.Manager=this;
}},saveWindowState:function(b){if(!b||!b.isCreated()){return;
}var c=b.getWindowBounds();
var a=(b.isVisible()||b.isMinimized())+"@"+c.width+"@"+c.height+"@"+c.x+"@"+c.y+"@"+b.isMinimized();
this._setRadWindowCookie(b.get_id(),a);
},saveState:function(){var b=this.get_windows();
for(i=0;
i<b.length;
i++){var a=b[i];
if(a.isCloned()){this.saveWindowState(a);
}}},restoreState:function(){function d(g,f){var e=f.split("@");
if(e.length>1){if("true"==e[0]&&!g.isVisible()){g.show();
}window.setTimeout(function(){if(parseInt(e[1])>0){g.set_width(e[1]);
}if(parseInt(e[2])>0){g.set_height(e[2]);
}if("true"==e[0]){g.moveTo(parseInt(e[3]),parseInt(e[4]));
}if("true"==e[5]){g.minimize();
}},1);
}}var a=this.get_windows();
for(i=0;
i<a.length;
i++){var c=a[i];
var b=this._getRadWindowCookie(c.get_id());
if(b){d(c,b);
}}},_getOnlyCookie:function(){var a="RadWindowCookie";
var c=document.cookie.split("; ");
for(var b=0;
b<c.length;
b++){var d=c[b].split("=");
if(a==d[0]){return d[1];
}}return null;
},_setRadWindowCookie:function(c,a){c="["+c+"]";
var b=this._getOnlyCookie();
var f="";
var e="";
if(b){var g=b.split(c);
if(g&&g.length>1){f=g[0];
e=g[1].substr(g[1].indexOf("#")+1);
}else{e=b;
}}var d=new Date();
d.setFullYear(d.getFullYear()+10);
document.cookie="RadWindowCookie="+(f+c+"-"+a+"#"+e)+";path=/;expires="+d.toUTCString()+";";
},_getRadWindowCookie:function(a){var d=this._getOnlyCookie();
if(!d){return;
}var b=null;
a="["+a+"]";
var c=d.indexOf(a);
if(c>=0){var e=c+a.length+1;
b=d.substring(e,d.indexOf("#",e));
}return b;
},cascade:function(){var c=0;
var e=0;
var f=this._getWindowsSortedByZindex();
for(var b=0;
b<f.length;
b++){var a=f[b];
if(!a.isClosed()&&a.isVisible()){var d=a.restore();
a.moveTo(c,e);
a.setActive(true);
c+=25;
e+=25;
}}},tile:function(){var g=this._getWindowsSortedByZindex();
var l=0;
for(var h=0;
h<g.length;
h++){var n=g[h];
if(!n.isClosed()&&n.isVisible()){l++;
}}var j=5;
var k=0;
var a=1;
if(l<=j){k=l;
}else{var h=2;
while((l*h)<(j*(h+1))){h++;
if(h>6){break;
}}a=h;
k=Math.ceil(l/a);
}var d=$telerik.getClientBounds();
var m=Math.floor(d.width/k);
var c=Math.floor(d.height/a);
var e=document.documentElement.scrollLeft||document.body.scrollLeft;
var b=document.documentElement.scrollTop||document.body.scrollTop;
var f=0;
for(var h=0;
h<g.length;
h++){var n=g[h];
if(!n.isClosed()&&n.isVisible()){f++;
if((f-1)%(k)==0&&f>k){b+=c;
e=document.documentElement.scrollLeft||document.body.scrollLeft;
}n.restore();
n.moveTo(e,b);
n.setSize(m,c);
e+=m;
}}},closeActiveWindow:function(){this._executeActiveWindow("close");
},minimizeActiveWindow:function(){this._executeActiveWindow("minimize");
},restoreActiveWindow:function(){this._executeActiveWindow("restore");
},closeAll:function(){this._executeAll("close");
},showAll:function(){this._executeAll("show");
},minimizeAll:function(){this._executeAll("minimize");
},maximizeAll:function(){this._executeAll("maximize");
},restoreAll:function(){this._executeAll("restore");
},_getWindowsSortedByZindex:function(){var b=this._windows.concat([]);
var a=function(d,e){var f=d.get_zindex();
var c=e.get_zindex();
if(f==c){return 0;
}return(f<c?-1:1);
};
return b.sort(a);
},_executeAll:function(b){if(!this._windows){return;
}var c=this._windows.concat([]);
for(var a=0;
a<c.length;
a++){c[a][b]();
}},_executeActiveWindow:function(b){var a=this.getActiveWindow();
if(a&&"function"==typeof(a[b])){a[b]();
}},get_preserveClientState:function(){return this._preserveClientState;
},set_preserveClientState:function(a){if(this._preserveClientState!=a){this._preserveClientState=a;
}},set_windowControls:function(a){this._windowIDs=eval(a);
this._disposeWindows();
},set_child:function(a){},get_windowControls:function(){},get_windows:function(){return this._windows;
}};
Telerik.Web.UI.RadWindowManager.registerClass("Telerik.Web.UI.RadWindowManager",Telerik.Web.UI.RadWindow);
