Type.registerNamespace("Telerik.Web.UI.Scheduler.Views.Timeline.GroupedByDate");
(function(a){a.GroupedByDate.Model=function(b,c,d){a.GroupedByDate.Model.initializeBase(this,[b,c,d]);
};
a.GroupedByDate.Model.prototype={_getRawIndexFromDomElement:function(e){while(e&&(e.tagName.toUpperCase()!="TD")){e=e.parentNode;
}if(!e){return null;
}var d=e.cellIndex%this._resources.get_count();
var b={};
b.modelIndex=d;
var c;
if(this._isVertical){c=e.parentNode.rowIndex;
}else{c=Math.floor(e.cellIndex/this._resources.get_count());
}b.intervalIndex=c;
return b;
},_getTimeFromDomElement:function(c){var b=this._getRawIndexFromDomElement(c);
return this._timelineModels[0]._getTimeFromIndex(b);
},_getRenderer:function(){if(!this._renderer){this._renderer=new $TS.Rendering.DateGroupedTimelineViewRenderer(this);
}return this._renderer;
}};
a.GroupedByDate.Model.registerClass("Telerik.Web.UI.Scheduler.Views.Timeline.GroupedByDate.Model",a.GroupedByResource.Model);
})(Telerik.Web.UI.Scheduler.Views.Timeline);
