Type.registerNamespace("Telerik.Web.UI");
(function(){var c=$telerik.$;
var a=Telerik.Web.UI;
$telerik.toSlider=function(d){return d;
};
$telerik.findSlider=$find;
c.registerEnum(a,"SliderItemType",{None:1,Item:2,Tick:3});
c.registerEnum(a,"SliderTrackPosition",{Center:1,TopLeft:2,BottomRight:3});
c.registerEnum(a,"SliderThumbsInteractionMode",{Free:1,Lock:2,Push:3});
a.DecimalNumber={add:function(d,e,f){return b.parseDecimal((d+e),f);
},subtract:function(d,e,f){return b.parseDecimal((d-e),f);
},multiply:function(d,e,f){return b.parseDecimal((d*e),f);
},divide:function(d,e,f){return b.parseDecimal((d/e),f);
},remainder:function(d,e,f){d=Math.round(d*f);
e=Math.round(e*f);
return b.parseDecimal((d%e)/f,f);
},parseDecimal:function(d,g){if(typeof(d)=="undefined"){return Number.NaN;
}if(typeof(d)!="number"){try{d=parseFloat(d);
}catch(f){return Number.NaN;
}}if(isNaN(d)){return d;
}return(Math.round(d*g)/g);
}};
var b=a.DecimalNumber;
a.RadSlider=function(d){a.RadSlider.initializeBase(this,[d]);
this._minimumValue=0;
this._maximumValue=100;
this._value=0;
this._orientation=a.Orientation.Horizontal;
this._isHorizontal=true;
this._animationDuration=100;
this._showDecreaseHandle=true;
this._showIncreaseHandle=true;
this._showDragHandle=true;
this._enabled=true;
this._slideStep=1;
this._smallChange=1;
this._largeChange=0;
this._clickOffset=0;
this._trackMouseWheel=true;
this._width="";
this._height="";
this._skin="Default";
this._autoPostBack=false;
this._initializedInternal=false;
this._disposed=false;
this._firstValueOffset;
this._firstValueDragHandlePosition;
this._wrapperElement=null;
this._dragHandleElement=null;
this._mouseupHandler=null;
this._mouseWheelHandler=null;
this._documentKeyDownDelegate=null;
this._handleFocusDelegate=null;
this._handleBlurDelegate=null;
this._inSlidingMode=false;
this._dragText="Drag";
this._increaseText="Increase";
this._decreaseText="Decrease";
this._uniqueID=null;
this._resizeExtender=null;
this._selectionEnd=0;
this._isSelectionRangeEnabled=false;
this._endDragHandleElement=null;
this._endResizeExtender=null;
this._enableDragRange=false;
this._rangeResizeExtender=null;
this._children=null;
this._itemData=null;
this._childControlsCreated=false;
this._itemType=a.SliderItemType.None;
this._smallTickSize=0;
this._largeTickSize=0;
this._renderLargeTicks=false;
this._renderSmallTicks=false;
this._liveDrag=true;
this._liveDragValue;
this._liveDragHandleElement=null;
this._liveDragEndHandleElement=null;
this._trackPosition=a.SliderTrackPosition.Center;
this._isDirectionReversed=false;
this._enableServerSideRendering=false;
this._thumbsInteractionMode=a.SliderThumbsInteractionMode.Free;
this._rightToLeft=false;
this._precision=100;
this._accessKey="";
this._tabIndex=0;
this._valueBeforeAnimation=null;
this._selectionEndBeforeAnimation=null;
this.repaint=this.redraw;
this.Redraw=this.redraw;
};
a.RadSlider.prototype={initialize:function(){var e=this._minimumValue;
if(e>this._maximumValue){throw Error.argumentOutOfRange("_minimumValue",e,"MinimumValue should be smaller than MaximumValue");
}var f=this._value=this._getValueFromIndex(this._value);
if(this._isSelectionRangeEnabled){var h=this._selectionEnd=this._getValueFromIndex(this._selectionEnd);
var d=this._isDirectionReversed;
if((h<f&&!d)||(h>f&&d)){var g=this._selectionEnd;
this._selectionEnd=f;
this._value=g;
}}this.updateClientState();
if(this._enableServerSideRendering){this._initializeFields();
}a.RadSlider.callBaseMethod(this,"initialize");
this._initializeSliderControl();
c.raiseControlEvent(this,"load",{});
},_addParentVisibilityChangeHandler:function(d,e){if(d){if($telerik.isIE){$telerik.addHandler(d,"propertychange",e);
}else{d.addEventListener("DOMAttrModified",e,false);
}}},_removeParentVisibilityChangeHandler:function(d,e){if(d&&e){if($telerik.isIE){$telerik.removeHandler(d,"propertychange",e);
}else{d.removeEventListener("DOMAttrModified",e,false);
}}},_initializeSliderControl:function(i){if(i){var g=$telerik.isIE;
if(g){i=i.rawEvent;
}var f=(g&&i&&(i.propertyName=="style.display"||i.propertyName=="className"));
var d=(!g&&(i.attrName=="style"||i.attrName=="class"));
if(!(d||f)){return;
}}this._disposeParentVisibilityChangeHandler();
var h=$telerik.getInvisibleParent(this.get_element());
if(h){this._invisibleParent=h;
this._onParentVisibilityChangeDelegate=Function.createDelegate(this,this._initializeSliderControl);
this._addParentVisibilityChangeHandler(h,this._onParentVisibilityChangeDelegate);
}else{if(!this._initializedInternal){this._initializedInternal=true;
if(!this._wrapperElement){this._initializeLayout();
}else{this._setEnabled();
}this._setSliderElementsSize();
this._initializeSlider();
this._createChildControls();
this._setValuesForSlider();
}}},_disposeParentVisibilityChangeHandler:function(){if(this._invisibleParent&&this._onParentVisibilityChangeDelegate){this._removeParentVisibilityChangeHandler(this._invisibleParent,this._onParentVisibilityChangeDelegate);
this._invisibleParent=null;
this._onParentVisibilityChangeDelegate=null;
}},_initializeFields:function(){var g=this.get_id();
var f=this._wrapperElement=$get("RadSliderWrapper_"+g);
if(!f){return;
}f.setAttribute("unselectable","on");
$addHandler(this.get_element(),"click",$telerik.cancelRawEvent);
this._setRightToLeft();
var h=this._decreaseHandleElement=$get("RadSliderDecrease_"+g);
if(h){$addHandler(h,"mouseup",Function.createDelegate(h,this._clearFocus));
$addHandlers(h,{mousedown:this._onDecreaseMouseDown},this);
}var d=this._trackElement=$get("RadSliderTrack_"+g);
d.setAttribute("unselectable","on");
var e=this._selectedRegionElement=$get("RadSliderSelected_"+g);
e.setAttribute("unselectable","on");
this._dragHandleElement=$get("RadSliderDrag_"+g);
h=this._liveDragHandleElement=$get("liveDrag_RadSliderDrag_"+g);
if(h){$addHandler(h,"mouseup",Function.createDelegate(h,this._clearFocus));
}this._endDragHandleElement=$get("RadSliderEndDrag_"+g);
h=this._liveDragEndHandleElement=$get("liveDrag_RadSliderEndDrag_"+g);
if(h){$addHandler(h,"mouseup",Function.createDelegate(h,this._clearFocus));
}h=this._increaseHandleElement=$get("RadSliderIncrease_"+g);
if(h){$addHandler(h,"mouseup",Function.createDelegate(h,this._clearFocus));
$addHandlers(h,{mousedown:this._onIncreaseMouseDown},this);
}var i=this._listElement=$telerik.getElementByClassName(f,"rslItemsWrapper","ul");
if(i){i.setAttribute("unselectable","on");
$telerik.addMobileHandler(this,i,"mousedown",this._onTrackMouseDown);
}},_initializeLayout:function(){var j=this.get_element();
$addHandler(j,"click",$telerik.cancelRawEvent);
var i=j.className;
var e=this._skin;
if(i==""||i.indexOf("RadSlider")==-1){i="RadSlider "+("RadSlider_"+e);
Sys.UI.DomElement.addCssClass(j,i);
}this._setRightToLeft();
var h=this.get_id();
var g=this._wrapperElement=document.createElement("div");
j.appendChild(g);
g.id="RadSliderWrapper_"+h;
g.setAttribute("unselectable","on");
this._setWidth();
this._setHeight();
this._setOrientation();
this._setEnabled();
this._setTrackPosition();
this._setShowHandle(true);
var d=this._trackElement=document.createElement("div");
d.setAttribute("unselectable","on");
d.id="RadSliderTrack_"+h;
Sys.UI.DomElement.addCssClass(d,"rslTrack");
if(!this._showDecreaseHandle){d.style[this._getLocationProperty()]="0px";
}g.appendChild(d);
var f=this._selectedRegionElement=document.createElement("div");
f.setAttribute("unselectable","on");
f.id="RadSliderSelected_"+h;
Sys.UI.DomElement.addCssClass(f,"rslSelectedregion");
f.innerHTML="<!-- -->";
d.appendChild(f);
this._setEnableDragRange();
this._setShowDragHandle();
this._setShowHandle(false);
},_setRightToLeft:function(){var d=this.get_element();
if($telerik.isRightToLeft(d)){Sys.UI.DomElement.addCssClass(d,"RadSliderRTL");
Sys.UI.DomElement.addCssClass(d,"RadSliderRTL_"+this._skin);
this._rightToLeft=true;
}},_createHandleUI:function(e,d,i,f){var g=document.createElement("a");
g.id=e;
g.href="#";
Sys.UI.DomElement.addCssClass(g,i);
g.title=d;
if(!f){$addHandler(g,"mouseup",Function.createDelegate(g,this._clearFocus));
}var h=document.createElement("span");
h.innerHTML=d;
g.appendChild(h);
return g;
},_clearFocus:function(d){this.blur();
},_addDragHandleElement:function(d,i){var e=this._dragText;
var f="rslDraghandle";
var g=(i?"RadSliderEndDrag_":"RadSliderDrag_")+this.get_id();
var h=this._createHandleUI(g,e,f,true);
d.appendChild(h);
this[i?"_endDragHandleElement":"_dragHandleElement"]=h;
if(!this._liveDrag){var j=this._createHandleUI(("liveDrag_"+g),e,(f+" rslLiveDragHandle"));
d.appendChild(j);
this[i?"_liveDragEndHandleElement":"_liveDragHandleElement"]=j;
}},_setWidth:function(){var f=parseInt(this._width);
if(!isNaN(f)&&(f>0)){f+="px";
var e=this.get_element();
var d=this._wrapperElement;
if(e.style.width!=f){e.style.width=f;
}if(d.style.width!=f){d.style.width=f;
}}},_setHeight:function(){var d=parseInt(this._height);
if(!isNaN(d)&&(d>0)){d+="px";
var e=this.get_element();
var f=this._wrapperElement;
if(e.style.height!=d){e.style.height=d;
}if(f.style.height!=d){f.style.height=d;
}}},_setOrientation:function(){var f=this._wrapperElement;
var e=this._isHorizontal;
Sys.UI.DomElement.removeCssClass(f,(!e?"rslHorizontal":"rslVertical"));
Sys.UI.DomElement.addCssClass(f,(e?"rslHorizontal":"rslVertical"));
this._isHorizontal=!e;
var d=this._getTrackPositionClass(this._trackPosition);
this._isHorizontal=e;
Sys.UI.DomElement.removeCssClass(f,d);
this._setTrackPosition();
},_setEnabled:function(){var d=this._wrapperElement;
var e=this._isSelectionRangeEnabled;
if(this._enabled){Sys.UI.DomElement.removeCssClass(d,"rslDisabled");
this._createDragHandleExtender();
if(e){this._createDragHandleExtender(true);
this._setEnableDragRange();
}}else{Sys.UI.DomElement.addCssClass(d,"rslDisabled");
this._disposeObject("_resizeExtender");
if(e){this._disposeObject("_endResizeExtender");
this._disposeObject("_rangeResizeExtender");
}}},_getTrackPositionClass:function(d){var e=this._isHorizontal;
var f=(e)?"rslMiddle":"rslCenter";
if(d==a.SliderTrackPosition.TopLeft){f=(e)?"rslTop":"rslLeft";
}else{if(d==a.SliderTrackPosition.BottomRight){f=(e)?"rslBottom":"rslRight";
}}return f;
},_setTrackPosition:function(e){if(this._itemType==a.SliderItemType.None){return;
}var f=this._wrapperElement;
var d;
if(e!=null){d=this._getTrackPositionClass(e);
Sys.UI.DomElement.removeCssClass(f,d);
}d=this._getTrackPositionClass(this._trackPosition);
Sys.UI.DomElement.addCssClass(f,d);
},_setShowHandle:function(n){var h=n?"_showDecreaseHandle":"_showIncreaseHandle";
var d=n?"_decreaseHandleElement":"_increaseHandleElement";
var e=this._getLocationProperty();
var p=this._trackElement;
var g=this._listElement;
var k=this[h];
var j=this[d];
if(j){if(!k){clearTimeout(this[n?"_decreaseMDownInterval":"_increaseMDownInterval"]);
$clearHandlers(j);
j.parentNode.removeChild(j);
this[d]=null;
if(n){if(p){p.style[e]="0";
}if(g){g.style[e]="0";
}}}}else{if(k){if(n){if(p){p.style[e]="";
}if(g){g.style[e]="";
}}var m=n?"rslDecrease":"rslIncrease";
var f=this._isDirectionReversed;
var i=this[(n&&!f)||(!n&&f)?"_decreaseText":"_increaseText"];
var o=(n?"RadSliderDecrease_":"RadSliderIncrease_")+this.get_id();
var l=this[d]=this._createHandleUI(o,i,("rslHandle "+m));
this._wrapperElement.appendChild(l);
$addHandlers(l,{mousedown:this[n?"_onDecreaseMouseDown":"_onIncreaseMouseDown"]},this);
}}},_initializeDragHandle:function(d){this._addDragHandleElement(this._trackElement,d);
this._createDragHandleExtender(d);
},_disposeDragHandle:function(f){this._disposeObject(f?"_endResizeExtender":"_resizeExtender");
var e=this[f?"_endDragHandleElement":"_dragHandleElement"];
e.parentNode.removeChild(e);
this[f?"_endDragHandleElement":"_dragHandleElement"]=null;
if(!this._liveDrag){var d=this[f?"_liveDragEndHandleElement":"_liveDragHandleElement"];
d.parentNode.removeChild(d);
this[f?"_liveDragEndHandleElement":"_liveDragHandleElement"]=null;
}},_setShowEndDragHandle:function(){var d=this._isSelectionRangeEnabled;
var e=this._showDragHandle;
var f=this._endDragHandleElement;
if(f){if(!e||!d){if(!d&&(f.id=="RadSliderDrag_"+this.get_id())){this._isSelectionRangeEnabled=true;
this._switchDragHanldes();
this._isSelectionRangeEnabled=false;
}this._disposeDragHandle(true);
}}else{if(e&&d){this._initializeDragHandle(true);
}}},_setShowDragHandle:function(){var d=this._showDragHandle;
if(this._dragHandleElement){if(!d){this._disposeDragHandle();
this._setShowEndDragHandle();
this._handleInSlidingMode=null;
}}else{if(d){this._initializeDragHandle();
this._setShowEndDragHandle();
}}},_setEnableDragRange:function(){var e=this._enableDragRange;
var d=this._isSelectionRangeEnabled;
if(this._rangeResizeExtender){if(!e||!d){this._disposeObject("_rangeResizeExtender");
}}else{if(e&&d){this._createRangeExtender(this._selectedRegionElement);
}}},_createDragHandleExtender:function(g){if(!this._enabled){return;
}var f=this._liveDrag?this[g?"_endDragHandleElement":"_dragHandleElement"]:this[g?"_liveDragEndHandleElement":"_liveDragHandleElement"];
var h=g?"_endResizeExtender":"_resizeExtender";
if(f&&!this[h]){var d=$telerik.getCurrentStyle(f,"cursor","pointer");
var i={};
i[d]=f;
var e=this[h]=new a.ResizeExtender(this,f,i,null,null,d,false);
e.set_hideIframes(false);
}},_createRangeExtender:function(e){if(!this._enabled){return;
}if(e&&!this._rangeResizeExtender){var d=$telerik.getCurrentStyle(e,"cursor","pointer");
var f={};
f[d]=e;
var g=this._rangeResizeExtender=new a.ResizeExtender(this,e,f,null,null,d,false);
g.set_hideIframes(false);
}},_refreshLayout:function(){if($telerik.getInvisibleParent(this.get_element())){return;
}this._setSliderElementsSize();
this._setValuesForSlider();
},_setValuesForSlider:function(){this._setNewValue(this._value,true,true);
if(this._isSelectionRangeEnabled){this._setNewValue(this._selectionEnd,false,true);
}},_setSliderElementsSize:function(){if(!this._wrapperElement){return;
}var g=(this._showIncreaseHandle)?this._getIncreaseHandleBounds().width:0;
var m=(this._showDecreaseHandle)?this._getDecreaseHandleBounds().width:0;
var e=this.get_length()-m-g;
var h=this._trackElement;
h.style.width="";
h.style.height="";
var d=$telerik.getSize(h);
var j=this._isHorizontal;
var l=(j)?e:d.width;
var f=(!j)?e:d.height;
if(l>0&&f>0){$telerik.setSize(h,{width:l,height:f});
}var i=false;
if(this._itemsUICreated&&this._children&&this._itemType==a.SliderItemType.Tick){var k=this._checkRenderTicks();
var o=k.renderLargeTicks;
var n=k.renderSmallTicks;
if(this._renderLargeTicks!=o||this._renderSmallTicks!=n){this._children.clear();
this._itemsUICreated=false;
this._itemData=[];
this._renderLargeTicks=o;
this._renderSmallTicks=n;
this._createChildControls();
i=true;
}}if(!i){this._setItemsSize();
}this._setFirstValueOffset();
},_setFirstValueOffset:function(){var d=Math.floor(this._getHalfDragHandleSize());
if(this._itemType==a.SliderItemType.Tick){this._firstValueOffset=d;
this._firstValueDragHandlePosition=0;
}else{this._firstValueOffset=0;
this._firstValueDragHandlePosition=-d;
}},_initializeSlider:function(){this._initializeEventHandlers();
},_initializeEventHandlers:function(){this._mouseupHandler=Function.createDelegate(this,this._onMouseUp);
$telerik.addExternalHandler(document,"mouseup",this._mouseupHandler);
$telerik.addMobileHandler(this,this._trackElement,"mousedown",this._onTrackMouseDown);
this._setTrackMouseWheel();
var d=this._dragHandleElement;
if(d){this._applyAccessKey();
this._documentKeyDownDelegate=Function.createDelegate(this,this._onKeyDown);
$telerik.addExternalHandler(document,"keydown",this._documentKeyDownDelegate);
this._handleFocusDelegate=Function.createDelegate(this,this._handleFocus);
this._handleBlurDelegate=Function.createDelegate(this,this._handleBlur);
var f=this._tabIndex;
for(var e=0;
e<2;
e++){var g=(e==0)?d:this._endDragHandleElement;
if(g){$telerik.addExternalHandler(g,"focus",this._handleFocusDelegate);
$telerik.addExternalHandler(g,"blur",this._handleBlurDelegate);
if(f){g.tabIndex=f;
}}}}},_setTrackMouseWheel:function(){this._disposeTrackMouseWheelHandler();
if(!this._trackMouseWheel||this._isSelectionRangeEnabled){return;
}var d=this._trackElement;
this._mouseWheelHandler=Function.createDelegate(this,this._onMouseWheel);
$telerik.addExternalHandler(d,"mousewheel",this._mouseWheelHandler);
if($telerik.isFirefox){$telerik.addExternalHandler(d,"DOMMouseScroll",this._mouseWheelHandler);
}},_disposeTrackMouseWheelHandler:function(){var d=this._trackElement;
if(this._mouseWheelHandler&&d){$telerik.removeExternalHandler(d,"mousewheel",this._mouseWheelHandler);
if($telerik.isFirefox){$telerik.removeExternalHandler(d,"DOMMouseScroll",this._mouseWheelHandler);
}this._mouseWheelHandler=null;
}},dispose:function(){this._disposed=true;
this._animatedHandle=null;
this._handleInSlidingMode=null;
this._disposeHandlers();
this._disposeSlider();
a.RadSlider.callBaseMethod(this,"dispose");
},_disposeSlider:function(){this._disposeObject("_resizeExtender");
this._disposeObject("_endResizeExtender");
this._disposeObject("_rangeResizeExtender");
clearTimeout(this._increaseMDownInterval);
clearTimeout(this._decreaseMDownInterval);
clearTimeout(this._mDownInterval);
this._dragHandleElement=null;
this._endDragHandleElement=null;
this._decreaseHandleElement=null;
this._increaseHandleElement=null;
this._trackElement=null;
this._selectedRegionElement=null;
this._liveDragHandleElement=null;
this._liveDragEndHandleElement=null;
this._listElement=null;
this._wrapperElement=null;
},_disposeHandlers:function(){$clearHandlers(this.get_element());
if(this._trackElement){$clearHandlers(this._trackElement);
}if(this._listElement){$clearHandlers(this._listElement);
}if(this._decreaseHandleElement){$clearHandlers(this._decreaseHandleElement);
}if(this._increaseHandleElement){$clearHandlers(this._increaseHandleElement);
}if(this._selectedRegionElement){$clearHandlers(this._selectedRegionElement);
}if(this._mouseupHandler){$telerik.removeExternalHandler(document,"mouseup",this._mouseupHandler);
this._mouseupHandler=null;
}if(this._documentKeyDownDelegate){$telerik.removeExternalHandler(document,"keydown",this._documentKeyDownDelegate);
this._documentKeyDownDelegate=null;
}for(var d=0;
d<2;
d++){var e=(d==0)?this._dragHandleElement:this._endDragHandleElement;
if(e){$telerik.removeExternalHandler(e,"focus",this._handleFocusDelegate);
$telerik.removeExternalHandler(e,"blur",this._handleBlurDelegate);
}}this._handleFocusDelegate=null;
this._handleFocusDelegate=null;
if(this._accessKeyTextbox){$clearHandlers(this._accessKeyTextbox);
this._accessKeyTextbox.removeAttribute("accessKey");
this._accessKeyTextbox=null;
}this._disposeTrackMouseWheelHandler();
this._disposeParentVisibilityChangeHandler();
},_disposeObject:function(d){if(this[d]){this[d].dispose();
this[d]=null;
}},onDragStart:function(j){var i=j.element;
if(i===this._selectedRegionElement){return this._onDragStartRange(j);
}var k=parseInt($telerik.getCurrentStyle(i,"left",0));
if(isNaN(parseInt(i.style.left))){i.style.left=k+"px";
}var g=parseInt($telerik.getCurrentStyle(i,"top",0));
if(isNaN(parseInt(i.style.top))){i.style.top=g+"px";
}var m=this._isSelectionRangeEnabled;
var p=this._thumbsInteractionMode;
var d=m&&(a.SliderThumbsInteractionMode.Lock==p);
var r=m&&(a.SliderThumbsInteractionMode.Push==p);
var x=this._dragHandleElement;
var e=(i.id.indexOf(x.id)>-1);
var n=this._liveDrag;
if(!n){Sys.UI.DomElement.removeCssClass(i,"rslLiveDragHandle");
Sys.UI.DomElement.addCssClass(i,"rslLiveDragHandleActive");
if(d||r){this[e?"_liveDragEndHandleElement":"_liveDragHandleElement"].style.zIndex="";
i.style.zIndex="2";
}i=e?x:this._endDragHandleElement;
}this._handleInSlidingMode=i;
this._valueOnSlideStart=this._getActiveDragHandleValue(this._updateSelectionStart(null,i));
if(!n){this._liveDragValue=this._valueOnSlideStart;
}this._inSlidingMode=true;
var w=this._cachedDragHandleSize=$telerik.getSize(i);
var o=this._trackElement;
var s=$telerik.getBorderBox(o);
var v=$telerik.getSize(o);
v.width-=s.horizontal;
v.height-=s.vertical;
var l=this._firstValueDragHandlePosition;
var u=(e?this._endDragHandleElement:x);
var t=u?parseInt((u).style[this._getLocationProperty()]):0;
if(d||r){u.style.zIndex="";
i.style.zIndex="1";
if(d){var f=this._getSizeProperty();
v[f]=e?t+w[f]:(v[f]-t);
v[f]+=l;
}}var h=this._isHorizontal;
var q=new Sys.UI.Bounds((h?l:k),(!h?l:g),((h)?(v.width+(l==0?0:w.width)):w.width),((!h)?(v.height+(l==0?0:w.height)):w.height));
if(d&&!e){q[this._getPointProperty()]=t;
}this._cachedSliderBounds=q;
this.raiseEvent("slideStart");
return true;
},_onDragStartRange:function(n){var h=n.element;
var k=parseInt($telerik.getCurrentStyle(h,"left",0));
if(isNaN(parseInt(h.style.left))){h.style.left=k+"px";
}var l=parseInt($telerik.getCurrentStyle(h,"top",0));
if(isNaN(parseInt(h.style.top))){h.style.top=l+"px";
}var d=this._trackElement;
var j=$telerik.getBorderBox(d);
var f=$telerik.getSize(d);
f.width-=j.horizontal;
f.height-=j.vertical;
this._valuesOnSlideStart=[this._value,this._selectionEnd];
if(!this._liveDrag){this._liveDragValue=this._valuesOnSlideStart[0];
if(this._showDragHandle){var m=this._liveDragHandleElement;
Sys.UI.DomElement.removeCssClass(m,"rslLiveDragHandle");
Sys.UI.DomElement.addCssClass(m,"rslLiveDragHandleActive");
m.blur();
m=this._liveDragEndHandleElement;
Sys.UI.DomElement.removeCssClass(m,"rslLiveDragHandle");
Sys.UI.DomElement.addCssClass(m,"rslLiveDragHandleActive");
m.blur();
}}this._inSlidingMode=true;
var e=this._cachedRangeSize=$telerik.getSize(h);
var i=this._isHorizontal;
var g=new Sys.UI.Bounds((i?0:k),(!i?0:l),((i)?f.width:e.width),((!i)?f.height:e.height));
this._cachedSliderBounds=g;
this.raiseEvent("slideRangeStart");
return true;
},onDragEnd:function(k){var m=k.element;
if(m===this._selectedRegionElement){return this._onDragEndRange(k);
}var j=this._handleInSlidingMode;
var d=this._updateSelectionStart(null,j);
if(!this._liveDrag){Sys.UI.DomElement.removeCssClass(m,"rslLiveDragHandleActive");
Sys.UI.DomElement.addCssClass(m,"rslLiveDragHandle");
var f=this._liveDragValue;
var g=this._calculateDragHandleOffset(f);
var h=this._getLocationProperty();
var e=this._isDirectionReversed;
var p=this._value;
var o=this._selectionEnd;
var l=d&&((f>o&&!e)||(f<o&&e));
l=l||(!d&&((f<p&&!e)||(f>p&&e)));
var n=l&&this._isSelectionRangeEnabled&&(a.SliderThumbsInteractionMode.Push==this._thumbsInteractionMode);
var i=n&&this._setActiveDragHandleValue(f,!d);
if(!i){i=this._setActiveDragHandleValue(f,d);
}if(!i){if(n){var q=d?this._endDragHandleElement:this._dragHandleElement;
q.style[h]=g+"px";
this._updateRelativeLiveDragHandlePosition(q);
if(!d){this._selectedRegionElement.style[h]=g+"px";
}}j.style[h]=g+"px";
this._updateSelectedRegion(j,g);
}else{if(n){this._setActiveDragHandleValue((d?p:o),d,true,false);
}this._updateRelativeLiveDragHandlePosition(j);
}}else{this.updateClientState();
}this._cachedSliderBounds=null;
this._cachedDragHandleSize=null;
this._inSlidingMode=false;
this.raiseEvent("slideEnd");
if(this._autoPostBack&&this._valueOnSlideStart!=this._getActiveDragHandleValue(d)){this._raiseValueChangedServerEvent();
}},_onDragEndRange:function(m){var k=this._valuesOnSlideStart;
if(!this._liveDrag){var h=this._showDragHandle;
if(h){var l=this._liveDragHandleElement;
Sys.UI.DomElement.removeCssClass(l,"rslLiveDragHandleActive");
Sys.UI.DomElement.addCssClass(l,"rslLiveDragHandle");
l=this._liveDragEndHandleElement;
Sys.UI.DomElement.removeCssClass(l,"rslLiveDragHandleActive");
Sys.UI.DomElement.addCssClass(l,"rslLiveDragHandle");
}var e=this._liveDragValue;
var i=e+k[1]-k[0];
var d=this._setActiveDragHandleValue(i,false,null,null,true);
if(!d){d=this._setActiveDragHandleValue(e,true,null,null,true);
}var g=this._dragHandleElement;
var j=this._endDragHandleElement;
var f=this._getLocationProperty();
if(d){this._setActiveDragHandleValue(k[1],false,true,false,true);
this._selectedRegionElement.style[f]=this._calculateDragHandleOffset(k[0])+this._getHalfDragHandleSize();
if(h){this._updateRelativeLiveDragHandlePosition(g);
this._updateRelativeLiveDragHandlePosition(j);
}}else{if(h){g.style[f]=this._calculateDragHandleOffset(e)+"px";
j.style[f]=this._calculateDragHandleOffset(i)+"px";
}}}else{this.updateClientState();
}this._cachedSliderBounds=null;
this._cachedRangeSize=null;
this._inSlidingMode=false;
this.raiseEvent("slideRangeEnd");
if(this._autoPostBack&&k[0]!=this._value&&k[1]!=this._selectionEnd){this._raiseValueChangedServerEvent();
}},onDrag:function(i){var h=i.element;
if(h===this._selectedRegionElement){return this._onDragRange(i);
}var u=this._cachedDragHandleSize;
var m=this._cachedSliderBounds;
if(m.width<1||m.height<1){return false;
}var p=a.ResizeExtender.containsBounds(m,new Sys.UI.Bounds(i.x,i.y,u.width,u.height));
if(!p){if(i.x<=m.x){i.x=m.x;
}else{if(m.x+m.width<=i.x+u.width){i.x=m.x+m.width-u.width;
}}if(i.y<=m.y){i.y=m.y;
}else{if(m.y+m.height<=i.y+u.height){i.y=m.y+m.height-u.height;
}}p=true;
}var d=this._updateSelectionStart(null,h);
var l=this._calcValue(null,null,i,d);
var e=this._calculateDragHandleOffset(l);
var f=this._getPointProperty();
i[f]=e;
var n=this._liveDrag;
if(n&&this._getActiveDragHandleValue(d)!=l){var o=this._isDirectionReversed;
var r=this._value;
var q=this._selectionEnd;
var j=d&&((l>q&&!o)||(l<q&&o));
j=j||(!d&&((l<r&&!o)||(l>r&&o)));
var k=j&&this._isSelectionRangeEnabled&&(a.SliderThumbsInteractionMode.Push==this._thumbsInteractionMode);
var g=k&&this._setActiveDragHandleValue(l,!d,false,true);
if(!g){g=this._setActiveDragHandleValue(l,d,false,true);
}if(g){if(k){this._setActiveDragHandleValue((d?r:q),d,true,true);
}p=false;
}else{if(k){var t=this._getLocationProperty();
var s=d?this._endDragHandleElement:this._dragHandleElement;
s.style[t]=e+"px";
if(!d){this._selectedRegionElement.style[t]=e+"px";
}}this._updateSelectedRegion(h,e);
}}else{if(!n&&this._liveDragValue!=l){this._liveDragValue=l;
}else{p=false;
}}this.raiseEvent("slide");
return p;
},_onDragRange:function(l){var z=l.element;
var u=this._cachedRangeSize;
var D=this._cachedSliderBounds;
if(D.width<1||D.height<1){return false;
}var m=(this._children&&this._children.get_count()>0&&(this._itemType==a.SliderItemType.Item));
var p=this._smallChange;
var n=this._minimumValue+(m?p:0);
var i=this._maximumValue-(m?p:0);
var q=this._isHorizontal;
var h=this._valuesOnSlideStart;
var C=(h[1]-h[0]);
var o=null;
var g=a.ResizeExtender.containsBounds(D,new Sys.UI.Bounds(l.x,l.y,u.width,u.height));
if(!g){var t=this._isDirectionReversed;
var v=t?i:n;
var w=!t?i:n;
if(l.x<=D.x){l.x=D.x;
if(q){o={start:v,end:(v+C)};
}}else{if(D.x+D.width<=l.x+u.width){l.x=D.x+D.width-u.width;
if(q){o={start:(w-C),end:w};
}}}if(l.y<=D.y){l.y=D.y;
if(!q){o={start:v,end:(v+C)};
}}else{if(D.y+D.height<=l.y+u.height){l.y=D.y+D.height-u.height;
if(!q){o={start:(w-C),end:w};
}}}g=true;
}var x=this._getPointProperty();
var e=this._getHalfDragHandleSize();
if(!o){var d={};
d[x]=l[x]-e;
var k=this._calcValue(null,null,d,true);
k=Math.min(Math.max(k,n),i);
var j=k+C;
j=Math.max(Math.min(j,i),n);
k=j-C;
o={start:k,end:j};
}var E=this._calculateDragHandleOffset(o.start);
l[x]=E+e;
var y=this._liveDrag;
var B=this._liveDragValue;
var f={start:(y?this._value:B),end:(y?this._selectionEnd:(B+C))};
if(o.start!=f.start&&o.end!=f.end){var r=this._showDragHandle;
var A=this._getLocationProperty();
if(y){var s=this._setActiveDragHandleValue(o.end,false,false,true,true);
if(!s){s=this._setActiveDragHandleValue(o.start,true,false,true,true);
}if(s){this._setActiveDragHandleValue(f.end,false,true,true,true);
g=false;
}else{if(r){this._dragHandleElement.style[A]=E+"px";
this._endDragHandleElement.style[A]=this._calculateDragHandleOffset(o.end)+"px";
}}}else{this._liveDragValue=o.start;
if(r){this._liveDragHandleElement.style[A]=E+"px";
this._liveDragEndHandleElement.style[A]=this._calculateDragHandleOffset(o.end)+"px";
}}}else{g=false;
}this.raiseEvent("slideRange");
return g;
},_playAnimation:function(o,f){if(this._animationEnded==false){this._handleInSlidingMode=this._animatedHandle;
return;
}this._animationEnded=false;
var l=this;
var h=function(){l._setActiveDragHandleValue(o,f,true);
l._animationEnded=true;
};
var g=this._isHorizontal;
var i=this._animationDuration;
var e=this._calculateDragHandleOffset(o);
var d=this._getSelectionAnimationEndBounds(e,f);
var n=g?{width:d.width+"px",left:d.x+"px"}:{height:d.height+"px",top:d.y+"px"};
c(this._selectedRegionElement).stop().animate(n,i,null,h);
if(this._showDragHandle){var m=this._animatedHandle=f?this._dragHandleElement:this._endDragHandleElement;
var j=g?{left:e+"px"}:{top:e+"px"};
var k=Function.createDelegate(this,this._onDragHandleAnimationEnded);
c(m).stop().animate(j,i,null,k);
}},_getSelectionAnimationEndBounds:function(j,d){var g=this._getSelectedRegionBounds();
var e=Math.floor(j+this._getHalfDragHandleSize());
var k=this._getSizeProperty();
var i=this._getPointProperty();
if(this._isSelectionRangeEnabled){var h=g[i];
var f=h+g[k];
if(d){g[i]=e;
h=e;
}else{f=e;
}e=f-h;
}else{if(this._isDirectionReversed){g[i]=e;
e=this._getTrackBounds().width-e;
}}e=(e<0)?0:e;
g[k]=e;
return g;
},_onDragHandleAnimationEnded:function(){this._updateRelativeLiveDragHandlePosition(this._handleInSlidingMode);
},_ensureChildControls:function(){},_createChildControls:function(){if(this._itemsUICreated){return;
}if(!this._children){this._children=new a.RadSliderItemCollection(this);
}if(!this._wrapperElement){return;
}var e=this._itemData;
if(!e||e.length==0){if(this._itemType==a.SliderItemType.Tick){this._calculateTickSize();
var d=this._largeChange;
if(this._largeChange>0){this._calculateTickSize(true);
}if(this._smallTickSize>0&&((this._largeTickSize>0&&d>0)||d<=0)){var e=this._createItemDataForTicks();
if(!e||e.length==0){return;
}this._createChildControlsUI(e);
}}}else{this._createChildControlsUI(e);
}},_createChildControlsUI:function(g){if(this._itemsUICreated){return;
}this._itemsUICreated=true;
var h=this.get_childListElement();
var m=this._children;
var d=this._isDirectionReversed;
var o=$telerik.getChildrenByTagName(h,"li");
var j=o.length;
var e=g.length;
var n=!(j==e);
if(n){h.innerHTML="";
}this._childControlsCreated=n;
for(var f=0,k=g.length;
f<k;
f++){var p=new a.RadSliderItem();
var l=g[d?(e-1-f):f];
if(n){p._loadFromDictionary(l);
}else{p._initialize(l,o[f]);
}m.add(p);
}this._setItemsSize();
if(this._itemType==a.SliderItemType.Item){this._updateSelectedItemsStatus();
}this._childControlsCreated=true;
c.raiseControlEvent(this,"itemsCreated",{});
},_createChildListElement:function(){var e=document.createElement("ul");
e.className="rslItemsWrapper";
e.unselectable="on";
if(!this._showDecreaseHandle){e.style[this._getLocationProperty()]="0px";
}var d=this._trackElement;
d.parentNode.insertBefore(e,d);
$telerik.addMobileHandler(this,e,"mousedown",this._onTrackMouseDown);
this._listElement=e;
return e;
},_logInserted:function(d){},_clearSelection:function(){var f=this._children;
for(var d=0,e=f.get_count();
d<e;
d++){f.getItem(d)._updatedSelectedView(false);
}},_getItemOffset:function(f,i,o){var d=i;
if(!d){d=this._getUlSize()[this._getSizeProperty()];
}var e=this._children.get_count();
if(e<2){return{startPoint:0,endPoint:d};
}var m=0;
if(this._itemType==a.SliderItemType.Tick){var k=(this._getDragHandleBounds().width/2);
var g=k+Math.floor((d-2*k)/(2*(e-1)));
var j=g;
m=g;
if(this._isDirectionReversed){m+=o;
}else{j+=o;
}if(f==0){return{startPoint:0,endPoint:m};
}else{if(f==(e-1)){return{startPoint:(d-j),endPoint:d};
}}d-=(m+j);
e-=2;
f-=1;
if(d<0||e<=0){return{startPoint:0,endPoint:d};
}}var p=f/e;
var h=(f+1)/e;
var l=parseInt(p*d)+m;
var n=parseInt(h*d)+m;
return{startPoint:l,endPoint:n};
},_checkHitInItem:function(e,f){var d=this._getItemOffset(e);
if(f<d.startPoint){if(e<=0){return null;
}return this._checkHitInItem(e-1,f);
}else{if(f>d.endPoint){if(e>=this._children.get_count()-1){return null;
}return this._checkHitInItem(e+1,f);
}}return e;
},_getItemFromValue:function(e){var d=this._calculateDragHandleOffset(e)+this._firstValueOffset;
return this._getItemFromOffset(d);
},_getItemFromOffset:function(h){var g=this._children;
var e=g.get_count();
var d=this._getItemSize(0)[this._getSizeProperty()];
if(d>0){var f=Math.floor(h/d);
f=this._checkHitInItem(f,h);
if(f>=e){f=e-1;
}if(f>=0){return g.getItem(f);
}}return null;
},_updateSelectedItemsStatus:function(){var e=this._children;
if(e.get_count()>0){this._clearSelection();
var f=this._getItemFromValue(this._value);
if(f){f._updatedSelectedView(true);
}if(this._isSelectionRangeEnabled){var d=this._getItemFromValue(this._selectionEnd);
if(d){d._updatedSelectedView(true);
}}}},_getUlSize:function(){var d=this._trackElement;
var m=$telerik.getBorderBox(d);
var k=$telerik.getSize(d);
k.width-=m.horizontal;
k.height-=m.vertical;
var j=k;
var e=this._isHorizontal;
var g=parseInt(e?this._height:this._width);
var i=this._trackPosition;
if(i!=a.SliderTrackPosition.Center){g-=k[e?"height":"width"];
var f=i==a.SliderTrackPosition.TopLeft;
var n=e?(f?"top":"bottom"):(f?"left":"right");
var p=parseInt($telerik.getCurrentStyle(d,n));
if(!isNaN(p)){g-=p;
}var h=e?(f?"marginTop":"marginBottom"):(f?"marginLeft":"marginRight");
var l=parseInt($telerik.getCurrentStyle(d,h));
if(!isNaN(l)){g-=l;
}var o=parseInt($telerik.getCurrentStyle(this._listElement,h));
if(!isNaN(o)){g-=o;
}}if(g>=0){j[e?"height":"width"]=g;
}return j;
},_getItemSize:function(g,h,d){var f=h;
if(!f){f=this._getUlSize();
}var j={width:f.width,height:f.height};
var i=this._getSizeProperty();
var e=this._getItemOffset(g,f[i],d);
j[i]=e.endPoint-e.startPoint;
return j;
},_getAsymmetricAddOn:function(e){var n=0;
if(a.SliderItemType.Tick==this._itemType){var d=this._isDirectionReversed;
var m=this._maximumValue;
var j=this._minimumValue;
var l=this._children;
var f=d?0:(l.get_count()-1);
var g=l.getItem(f).get_isSmallTick();
var i=b.remainder((m-j),(g?this._smallChange:this._largeChange),this._precision);
if(i!=0){var h=d?(j+i):(m-i);
var k=this._calculateDragHandleOffset(h);
n=e-k-this._getDragHandleBounds().width;
}}return n;
},_setItemsSize:function(){if(!this._itemsUICreated){return;
}var e=this._children;
var d=e.get_count();
if(d==0){return;
}var s=(this._itemType==a.SliderItemType.Tick);
var f=this._isHorizontal;
var g=this._getSizeProperty();
var k=this._getUlSize();
var r=this._getAsymmetricAddOn(k[f?"width":"height"]);
var p={lastItemSize:0,asymmetricAddOn:r};
var j=0;
for(var o=0;
o<d;
o++){var q=e.getItem(o).get_element();
j=this._getItemSize(o,k,r);
$telerik.setSize(q,j);
if(o==d-1){p.lastItemSize=j[g];
}else{if(s&&(o>0)){var n=q.getElementsByTagName("SPAN");
var m=Math.max(j[g],12)+"px";
for(var l=0,h=n.length;
l<h;
l++){if(!f){n[l].style.lineHeight=m;
}else{n[l].style.lineHeight="";
}}}}}this._setEndTicksBackgroundPosition(p);
},get_childListElement:function(){var d=this._listElement;
if(!d){d=this._createChildListElement();
}return d;
},get_selectedItem:function(){var d=this.get_selectedItems();
if(d.length>0){return d[0];
}return null;
},get_selectedItems:function(){if(this._itemType!=a.SliderItemType.Item){return[];
}var h=this._children;
var e=h.get_count();
var d=this._isDirectionReversed;
var i=d?(e-1-this.get_selectionStart()):this.get_selectionStart();
var g=[h.getItem(i)];
if(this._isSelectionRangeEnabled){var f=d?(e-1-this.get_selectionEnd()):this.get_selectionEnd();
Array.add(g,h.getItem(f));
}return g;
},get_selectedValue:function(){var d=this.get_selectedItem();
if(d){return d.get_value();
}return"";
},_calculateDragHandleOffset:function(l){var i=this._minimumValue;
var k=this._maximumValue;
var e=this._getTrackBounds();
var f=this._firstValueDragHandlePosition;
if(f==0){e.width=(e.width-this._getDragHandleBounds().width);
}var g=k-i;
var j=(l-i)/g;
if(this._isDirectionReversed){j=1-j;
l=k+i-l;
}var h=parseInt(j*(e.width));
var d=(l==i)?f:(l==k)?(e.width+f):h+f;
return d;
},_getBoundsInternal:function(f,d){var g=$telerik.getBounds(f);
if(d){var e=$telerik.getBorderBox(f);
g.width-=e.horizontal;
g.height-=e.vertical;
g.x+=e.left;
g.y+=e.top;
}if(this._orientation==a.Orientation.Vertical){g={x:g.y,y:g.x,height:g.width,width:g.height};
}return g;
},_getHalfDragHandleSize:function(){return(this._getDragHandleBounds().width/2);
},_getTrackBounds:function(){return this._getBoundsInternal(this._trackElement,true);
},_getSelectedRegionBounds:function(){var f=$telerik.getContentSize(this._selectedRegionElement);
f.y=0;
f.x=0;
var e=this._isSelectionRangeEnabled;
if(e||(!e&&this._isDirectionReversed)){var d=this._getElementLocation(this._selectedRegionElement);
f[this._getPointProperty()]=d;
}return f;
},_getSelectedRegionPoints:function(){var e=this._getSelectedRegionBounds();
var d=e[this._getPointProperty()];
var f=d+e[this._getSizeProperty()];
return{startPoint:d,endPoint:f};
},_getDragHandleBounds:function(e){if(!this._showDragHandle){return{x:0,y:0,height:0,width:0};
}var d=e;
if(!d){d=this._dragHandleElement;
if(this._isSelectionRangeEnabled&&this._handleInSlidingMode){d=this._handleInSlidingMode;
}}return this._getBoundsInternal(d);
},_getDecreaseHandleBounds:function(){return this._getBoundsInternal(this._decreaseHandleElement);
},_getIncreaseHandleBounds:function(){return this._getBoundsInternal(this._increaseHandleElement);
},_getLocationProperty:function(){if(!this._locationProperty){this._locationProperty=this._isHorizontal?"left":"top";
}return this._locationProperty;
},_updateLocationProperty:function(){this._locationProperty=this._isHorizontal?"left":"top";
},_getSizeProperty:function(){if(!this._sizeProperty){this._sizeProperty=this._isHorizontal?"width":"height";
}return this._sizeProperty;
},_updateSizeProperty:function(){this._sizeProperty=this._isHorizontal?"width":"height";
},_getPointProperty:function(){if(!this._pointProperty){this._pointProperty=this._isHorizontal?"x":"y";
}return this._pointProperty;
},_updatePointProperty:function(){this._pointProperty=this._isHorizontal?"x":"y";
},_doSmallStep:function(f){var h=this._smallChange;
var d=this._isDirectionReversed;
if((!f&&!d)||(f&&d)){h*=-1;
}var e=true;
if(this._isSelectionRangeEnabled&&f){e=false;
}var g=this._getActiveDragHandleValue(e)+h;
g=this._calcValue(g,null,null,e);
this._setHandlePosition(g,null,e,null,true);
},_calcValue:function(l,i,k,d){var j;
var q=this._minimumValue;
var p=this._maximumValue;
var g=d?this._dragHandleElement:this._endDragHandleElement;
if(l!=null){if(!Number.isInstanceOfType(l)){try{l=parseFloat(l);
}catch(e){l=Number.NaN;
}}if(isNaN(l)){l=q;
}j=(l<q)?q:(l>p)?p:l;
}else{var h=this._getTrackBounds();
var r=this._getDragHandleBounds(g);
if(k){r.x=(k[this._getPointProperty()])+h.x;
}var f=this._firstValueOffset;
var o=(i!=null)?(i-f):(r.x+Math.floor(r.width/2)-h.x-f);
if(this._firstValueDragHandlePosition==0){h.width=(h.width-r.width);
}var n=o/h.width;
if(this._isDirectionReversed){o=h.width-o;
n=1-n;
}j=(o==0)?q:(o==h.width)?p:q+n*(p-q);
}j=this._getNearestStepValue(j);
j=(j<q)?q:(j>p)?p:j;
if(this._children&&this._children.get_count()>0&&(this._itemType==a.SliderItemType.Item)){var s=this._smallChange;
var m=this._getItemFromOffset(o);
if(m){j=this._getValueFromIndex(m.get_index());
}else{if(j%2==0){if(j<this._getActiveDragHandleValue(d)){j-=s;
}else{j+=s;
}j=(j<q)?q+s:(j>p)?p-s:j;
}}}return b.parseDecimal(j,this._precision);
},_setHandlePosition:function(f,i,d,j,g){if(!j&&this.raise_valueChanging(f,d)){return;
}var e=i;
if(!e){e=this._handleInSlidingMode;
}if((this._animationDuration>0)&&g){this._playAnimation(f,d);
}else{var h=this._calculateDragHandleOffset(f);
if(this._showDragHandle&&e){e.style[this._getLocationProperty()]=h+"px";
this._updateRelativeLiveDragHandlePosition(e);
}this._setActiveDragHandleValue(f,d,true);
this._updateSelectedRegion(e,h,d);
}},_setHandlePositionKeyboard:function(f,m,n){var l=this._isDirectionReversed;
var d=this._dragHandleElement;
var g=this._endDragHandleElement;
var q=f?d:g;
var h=!f?d:g;
var i=this._isSelectionRangeEnabled;
var e=this._thumbsInteractionMode;
var j=i&&(a.SliderThumbsInteractionMode.Lock==e);
var o=i&&(a.SliderThumbsInteractionMode.Push==e);
var k=i?this.get_selectionEnd():this._maximumValue;
var p=i?this.get_selectionStart():this._minimumValue;
m=Math.max(Math.min(m,this._maximumValue),this._minimumValue);
if(n){if(i&&(f&&!l)||(!f&&l)){if(j&&m>k){m=k;
}if(o&&m>k){this._setHandlePosition(m,h,!f);
}}this._setHandlePosition(m,q,f);
}else{if(i&&(!f&&!l)||(f&&l)){if(j&&m<p){m=p;
}if(o&&m<p){this._setHandlePosition(m,h,!f);
}}this._setHandlePosition(m,q,f);
}},_getNearestStepValue:function(f){var j=this._minimumValue;
var k=this._maximumValue;
var g=k-j;
if(g==0){return f;
}if(f>=k){return k;
}if(f<=j){return j;
}f-=j;
var d=this._smallChange;
var h=f%d;
if(h==0){return(f+j);
}var i=d-h;
if(h<d/2){i=-1*h;
}var e=f+i+j;
return e;
},_getRelativeLiveDragHandle:function(d){if(this._liveDrag||!this._showDragHandle){return null;
}if(this._updateSelectionStart(null,d)){return this._liveDragHandleElement;
}return this._liveDragEndHandleElement;
},_updateRelativeLiveDragHandlePosition:function(f){if(this._liveDrag||!this._showDragHandle){return;
}if(f){var e=this._getRelativeLiveDragHandle(f);
if(e){var d=this._getLocationProperty();
e.style[d]=f.style[d];
}}else{if(this._dragHandleElement){this._updateRelativeLiveDragHandlePosition(this._dragHandleElement);
if(this._isSelectionRangeEnabled&&this._endDragHandleElement){this._updateRelativeLiveDragHandlePosition(this._endDragHandleElement);
}}}},_getNearestDragHandle:function(g){var f=this._dragHandleElement;
if(this._isSelectionRangeEnabled&&g){var d=this._getSelectedRegionPoints();
var e=d.endPoint;
if((Math.abs(g-d.startPoint)>Math.abs(g-e))||g>e){f=this._endDragHandleElement;
}}return f;
},_getElementLocation:function(f){var d=this._getLocationProperty();
var e=parseInt(f.style[d]);
if(isNaN(e)){e=0;
}return e;
},_getActiveDragHandleValue:function(e){var f=e?this._dragHandleElement:this._endDragHandleElement;
if(!f&&this._showDragHandle){return this._minimumValue;
}var d=(e!=null)?e:this._updateSelectionStart(null,this._handleInSlidingMode);
return(d?this._value:this._selectionEnd);
},_setActiveDragHandleValue:function(m,k,f,i,e){var l=k?this._dragHandleElement:this._endDragHandleElement;
if(!l&&this._showDragHandle){return;
}var h=this._getActiveDragHandleValue(k);
if(!f&&this.raise_valueChanging(m,k)){return true;
}var d=this._isDirectionReversed;
var g=this._isSelectionRangeEnabled;
if(k){if(!e&&((m>this._selectionEnd&&g&&!d)||(m<this._selectionEnd&&g&&d))){this._value=this._selectionEnd;
var j=this._calculateDragHandleOffset(this._value);
this._selectedRegionElement.style[this._getLocationProperty()]=j+this._getHalfDragHandleSize()+"px";
this._switchDragHanldes();
this._selectionEnd=m;
}else{this._value=m;
}}else{if(!e&&((m<this._value&&g&&!d)||(m>this._value&&g&&d))){this._selectionEnd=this._value;
this._selectedRegionElement.style[this._getSizeProperty()]="0px";
this._switchDragHanldes();
this._value=m;
}else{this._selectionEnd=m;
}}if(this._itemType==a.SliderItemType.Item){this._updateSelectedItemsStatus();
}if(!i){this.updateClientState();
}if(m!=h){this.raise_valueChanged(h,m);
if(!this._inSlidingMode&&this._autoPostBack){this._raiseValueChangedServerEvent();
}}},_setNewValue:function(d,i,n){d=b.parseDecimal(d,this._precision);
if(isNaN(d)){var e=this._isSelectionRangeEnabled?(i?"SelectionStart":"SelectionEnd")+" should be of type decimal":"Value should be of type decimal";
throw Error(e);
}var l=this._minimumValue;
var h=this._maximumValue;
if(d<l){d=l;
}else{if(d>h){d=h;
}}if(!this._initializedInternal||!this._wrapperElement){if(this._initializedInternal){d=this._getNearestStepValue(d);
}this[i?"_value":"_selectionEnd"]=d;
this.updateClientState();
return;
}if(this._isSelectionRangeEnabled){var j=this._isDirectionReversed;
var f=this._value;
var k=this._selectionEnd;
if((d<f&&!i&&!j)||(d>f&&!i&&j)){i=true;
}else{if((d>k&&i&&!j)||(d<k&&i&&j)){i=false;
}}}var g=this._calcValue(d,null,null,i);
var m=this[i?"_dragHandleElement":"_endDragHandleElement"];
this._setHandlePosition(g,m,i,n);
},_getIndexFromValue:function(d){if(a.SliderItemType.Item!=this._itemType){return d;
}var i=0;
var h=this._children;
if(h){i=h.get_count();
}if(i==0){var f=this._itemData;
i=f?f.length:0;
}if(i>0){var e=this._minimumValue;
var g=i-1;
d=(d-this._smallChange)/2;
d=(d<e)?e:((d>g)?g:d);
}return d;
},_getValueFromIndex:function(j){if(a.SliderItemType.Item!=this._itemType){return j;
}var d=0;
var i=this._children;
if(i){d=i.get_count();
}if(d==0){var e=this._itemData;
d=e?e.length:0;
}if(d>0){var g=this._smallChange;
var f=this._minimumValue;
var h=d*2-g;
j=(2*j)+g;
j=(j<f)?f:((j>h)?h:j);
}return j;
},_switchDragHanldes:function(){if(!this._isSelectionRangeEnabled){return;
}var d=this._dragHandleElement;
this._dragHandleElement=this._endDragHandleElement;
this._endDragHandleElement=d;
if(!this._liveDrag){d=this._liveDragHandleElement;
this._liveDragHandleElement=this._liveDragEndHandleElement;
this._liveDragEndHandleElement=d;
}if(this._resizeExtender&&this._endResizeExtender){d=this._resizeExtender;
this._resizeExtender=this._endResizeExtender;
this._endResizeExtender=d;
}d=null;
},_updateSelectionStart:function(g,f){if(!this._isSelectionRangeEnabled){return true;
}var e=this._showDragHandle;
if(e&&f!=null){return(f.id==this._dragHandleElement.id);
}else{if(!e&&g!=null){var d=this._getSelectedRegionPoints();
return(Math.abs(g-d.startPoint)<Math.abs(g-d.endPoint));
}}return true;
},_isInIncreaseMode:function(h,f){var e=this._getSelectedRegionPoints();
var g=e.endPoint;
var i=this._isSelectionRangeEnabled;
var d=(!i&&(h<g))||(i&&(((h<g)&&!f)||((h<e.startPoint)&&f)));
if(this._isDirectionReversed){if(!i){d=h>e.startPoint;
}else{d=!d;
}}return d;
},_updateSelectedRegion:function(l,i,d){i+=this._getHalfDragHandleSize();
var k=i;
var j=this._selectedRegionElement;
var g=this._getSizeProperty();
var h=this._getLocationProperty();
if(this._isSelectionRangeEnabled){var f=this._getSelectedRegionBounds();
var e=f[this._getPointProperty()];
k=f[g];
if(d||this._updateSelectionStart(i,l)){j.style[h]=i+"px";
k=k+(e-Math.floor(i));
}else{k=(Math.floor(i)-e);
}}else{if(this._isDirectionReversed){j.style[h]=i+"px";
k=this._getTrackBounds().width-Math.floor(i);
}}if(!isNaN(k)&&k>=0){j.style[g]=k+"px";
}else{j.style[g]="";
}},_setEndTicksBackgroundPosition:function(m){if(this._itemType==a.SliderItemType.Tick){var j=this._showDragHandle;
var h=this._largeTickSize;
var g=this._smallTickSize;
var q=Math.ceil(this._getHalfDragHandleSize());
var k=Math.floor(h/2);
var l=Math.floor(g/2);
var f=this._children;
var e=f.getItem(0).get_element();
var i=f.getItem(f.get_count()-1).get_element();
var n=this._isDirectionReversed;
var p=m.asymmetricAddOn;
var o=n?p:0;
this._setBackgroundPosition(e,(o+(j?(q-k):0)),(o+(j?(q-l):0)));
var d=Math.ceil(m.lastItemSize)-q-(!n?p:0);
this._setBackgroundPosition(i,(d-(j?k:h)),(d-(j?l:g)));
}},_setBackgroundPosition:function(e,p,m){var r=(e.className.indexOf("rslLarge")>-1);
p=(p<0)?0:p;
m=(m<0)?0:m;
var q;
var j;
if(this._isHorizontal){q=(r?p:m)+"px";
j=this._getImageBackgroundPosition();
}else{j=(r?p:m)+"px";
q=this._getImageBackgroundPosition();
}e.style.backgroundPosition=q+" "+j;
if(r){var g=this._isHorizontal;
var h=this._getSizeProperty();
var d=(h=="width")?"height":"width";
var o=e.getElementsByTagName("SPAN");
var n=Math.max((2*p+this._largeTickSize),12)+"px";
for(var l=0,k=o.length;
l<k;
l++){var f=o[l];
f.style[d]="";
f.style[h]=n;
if(!g){f.style.lineHeight=n;
}else{f.style.lineHeight="";
}}}},_getImageBackgroundPosition:function(){var d=this._trackPosition;
var f=this._isHorizontal;
var e="center";
if(d==a.SliderTrackPosition.TopLeft){e=f?"top":"left";
}else{if(d==a.SliderTrackPosition.BottomRight){e=f?"bottom":"right";
}}return e;
},_calculateTickSize:function(f){var e=document.createElement("div");
e.className=f?"rslLargeTick":"rslSmallTick";
e.style.position="absolute";
e.style.top="-9999px";
this._wrapperElement.appendChild(e);
var d=this._isHorizontal?e.offsetWidth:e.offsetHeight;
e.parentNode.removeChild(e);
if(f){this._largeTickSize=d;
}else{this._smallTickSize=d;
}},_checkRenderTicks:function(){var f=this._largeChange;
var g=this._smallChange;
var h=(this._maximumValue-this._minimumValue)/g;
var j=(this._getTrackBounds().width)/h;
var e=Math.floor(j*(f/g));
j=Math.floor(j);
var i=((f>0)&&(e>=this._largeTickSize));
var d=(j>=this._smallTickSize&&f!=g);
return{renderLargeTicks:i,renderSmallTicks:d};
},_createItemDataForTicks:function(){var h=[];
var g=this._largeChange;
var l=this._smallChange;
var o=this._maximumValue;
var n=this._minimumValue;
var m=this._checkRenderTicks();
var p=this._renderLargeTicks=m.renderLargeTicks;
var d=this._renderSmallTicks=m.renderSmallTicks;
if(!p){g=Math.abs(n)+o+l;
}var k=this._precision;
for(var e=n;
e<=o;
e=b.add(e,g,k)){if(p){h[h.length]={text:e,value:e,tooltip:e,isLargeTick:true};
}if(d){var f=b.add(e,(p?l:0),k);
var q=(p&&((e+g)<=o))?b.add(e,g,k):b.add(o,b.divide(1,k,k),k);
for(;
f<q;
f=b.add(f,l,k)){h[h.length]={text:f,value:f,tooltip:f,isSmallTick:true};
}}}this._itemData=h;
return h;
},_clearSizePosition:function(d){if(!d){return;
}d.style.width="";
d.style.height="";
d.style.top="";
d.style.left="";
},_raiseValueChangedServerEvent:function(){setTimeout(Function.createDelegate(this,function(){__doPostBack(this._uniqueID);
}),0);
},_onMouseUp:function(d){this._trackMouseDownDone=true;
this._incdecreaseMouseDownDone=true;
},_onTrackMouseDown:function(o){if(!this._enabled||(!$telerik.isTouchDevice&&o.button!=0)){return;
}var s=o.target;
var t=(s==this._selectedRegionElement);
var e=(s==this._trackElement);
var n=this._listElement;
var u=s.parentNode;
var h=(n)?((u&&u==n)||(u.parentNode&&u.parentNode==n)):false;
if(!e&&!t&&!h){return;
}var j=this._getTrackBounds();
var i=$telerik.getTouchEventLocation(o);
var p=$telerik.isTouchDevice?{left:i.x,top:i.y}:$telerik.getDocumentRelativeCursorPosition(o);
var g=((this._isHorizontal)?p.left:p.top)-j.x;
var q=0;
if(this._firstValueDragHandlePosition==0){q=this._firstValueOffset;
}var r=j.width-q;
g=(g<q)?q:(g>r)?r:g;
var m=this._handleInSlidingMode=this._getNearestDragHandle(g);
var d=this._updateSelectionStart(g,m);
var f=this._calcValue(null,g,null,d);
if(this._largeChange==0){this._setHandlePosition(f,m,d,null,true);
}else{this._trackMouseDownDone=false;
var l=this._isInIncreaseMode(g,d);
var w=(this._children.get_count()>0&&(this._itemType==a.SliderItemType.Item));
var k=this;
function v(x){if(k._disposed){return;
}var A=k._isInIncreaseMode(g,d);
if(k._trackMouseDownDone||A!=l){clearTimeout(this._mDownInterval);
return;
}var y=k._largeChange;
if(w){y*=2;
}if(l){y*=-1;
}var z=k._getActiveDragHandleValue(d)+y;
z=k._calcValue(z,null,null,d);
if((!l&&(f<z))||(l&&(f>z))){z=f;
}k._setHandlePosition(z,m,d,null,true);
k._mDownInterval=setTimeout(v,(x)?x:100);
}v(300);
}},_onMouseWheel:function(g){if(!this._enabled){return;
}var e=this._getTrackBounds();
if(e.width<1||e.height<1){return;
}var h=(g.wheelDelta)?g.wheelDelta:g.detail;
if($telerik.isIE){h*=-1;
}var f=this._value;
var d=this._smallChange;
var i=f+((h>0)?d:(-1)*d);
i=this._calcValue(i,null,null,true);
this._setHandlePosition(i,this._dragHandleElement,true,null,true);
return $telerik.cancelRawEvent(g);
},_onDecreaseMouseDown:function(d){this._onIncreaseDecreaseMDown(d,false);
},_onIncreaseMouseDown:function(d){this._onIncreaseDecreaseMDown(d,true);
},_onIncreaseDecreaseMDown:function(h,d){if(!this._enabled){return;
}if(h.button!=0){return;
}this._handleInSlidingMode=this._dragHandleElement;
var g=true;
if(this._isSelectionRangeEnabled&&d){this._handleInSlidingMode=this._endDragHandleElement;
g=false;
}this._incdecreaseMouseDownDone=false;
this._inSlidingMode=true;
this._valueOnSlideStart=this._getActiveDragHandleValue(g);
var f=this;
function e(i){if(f._disposed){return;
}if(f._incdecreaseMouseDownDone){f._inSlidingMode=false;
clearTimeout(f._increaseMDownInterval);
if(f._valueOnSlideStart!=f._getActiveDragHandleValue(g)&&f._autoPostBack){f._raiseValueChangedServerEvent();
}return;
}f._doSmallStep(d);
f._increaseMDownInterval=setTimeout(e,(i)?i:50);
}e(300);
},_onKeyDown:function(l){var h=true;
var d=this._isDirectionReversed;
var f=this.get_value();
var n=this._dragHandleElement;
var i=false;
var j=this._endDragHandleElement;
if(j){if(j.getAttribute("hasFocus")){h=false;
f=d?this.get_selectionStart():this.get_selectionEnd();
n=j;
}else{f=d?this.get_selectionEnd():this.get_selectionStart();
}}if(!n||!n.getAttribute("hasFocus")){return;
}var o=null;
var m=true;
var k=l.keyCode?l.keyCode:l.rawEvent.keyCode;
switch(k){case Sys.UI.Key.up:case Sys.UI.Key.right:o=f+this._smallChange;
m=true;
i=true;
break;
case Sys.UI.Key.down:case Sys.UI.Key.left:o=f-this._smallChange;
m=false;
i=true;
break;
case Sys.UI.Key.home:o=this._minimumValue;
m=false;
break;
case Sys.UI.Key.end:o=this._maximumValue;
m=true;
break;
case Sys.UI.Key.pageUp:o=f+this._largeChange;
m=true;
break;
case Sys.UI.Key.pageDown:o=f-this._largeChange;
m=false;
break;
default:return true;
}if(this._itemType==a.SliderItemType.Item&&i){var g=m?this._smallChange:-this._smallChange;
o=this._getActiveDragHandleValue(h)+g;
o=this._calcValue(o,null,null,h);
}this._setHandlePositionKeyboard(h,o,m);
this._clearSizePosition(this._selectedRegionElement);
this._refreshLayout();
$telerik.cancelRawEvent(l);
return false;
},_applyAccessKey:function(){var f=this._accessKey;
if(f){if(!($telerik.isChrome||$telerik.isSafari)){this._dragHandleElement.setAttribute("accessKey",f);
}else{var e=document.createElement("div");
e.style.width="0px";
e.style.height="0px";
e.style.overflow="hidden";
this.get_element().appendChild(e);
var g=this._accessKeyTextbox=document.createElement("input");
g.setAttribute("type","text");
var d=this.get_id()+"SliderAccessKey";
g.setAttribute("name",d);
g.setAttribute("id",d);
g.setAttribute("accessKey",f);
e.appendChild(g);
$addHandlers(g,{focus:function(){this._dragHandleElement.focus();
}},this);
}}},_handleFocus:function(d){if(this.get_enabled()){var f=d.target?d.target:d.srcElement;
if(f){f.setAttribute("hasFocus","true");
}}},_handleBlur:function(d){var f=d.target?d.target:d.srcElement;
if(!f||($telerik.isOpera&&c(":focus").filter(f).size()>0)){return;
}f.removeAttribute("hasFocus");
},_getValuesBeforeAnimation:function(){return{selectionStart:this._valueBeforeAnimation,selectionEnd:this._selectionEndBeforeAnimation};
},add_loaded:function(d){this.add_load(d);
},remove_loaded:function(d){this.remove_load(d);
},add_valueChange:function(d){this.add_valueChanged(d);
},remove_valueChange:function(d){this.remove_valueChanged(d);
},raise_valueChange:function(d,e){this.raise_valueChanged(d,e);
},raise_valueChanged:function(d,e){d=this._getIndexFromValue(d);
e=this._getIndexFromValue(e);
c.raiseControlEvent(this,"valueChanged",{oldValue:d,newValue:e});
},add_beforeValueChange:function(d){this.add_valueChanging(d);
},remove_beforeValueChange:function(d){this.remove_valueChanging(d);
},raise_beforeValueChange:function(d,e){return this.raise_valueChanging(d,e);
},raise_valueChanging:function(f,d){var e=this._getActiveDragHandleValue(d);
e=this._getIndexFromValue(e);
f=this._getIndexFromValue(f);
if(this._isSelectionRangeEnabled){this._valueBeforeAnimation=d?f:this._value;
this._selectionEndBeforeAnimation=d?this._selectionEnd:f;
}else{this._valueBeforeAnimation=f;
}var g=c.raiseCancellableControlEvent(this,"valueChanging",{oldValue:e,newValue:f});
if(g){return true;
}return false;
},get_activeHandle:function(){if(!this._liveDrag){return this._getRelativeLiveDragHandle(this._handleInSlidingMode);
}return this._handleInSlidingMode;
},get_dragHandles:function(){return[this._dragHandleElement,this._endDragHandleElement];
},get_value:function(){var d=this._value;
if(this._isDirectionReversed&&this._isSelectionRangeEnabled){d=this._selectionEnd;
}return this._getIndexFromValue(d);
},set_value:function(d){if(this._initializedInternal&&this._wrapperElement){d=this._getValueFromIndex(d);
}this._setNewValue(d,true);
},get_selectionStart:function(){return this.get_value();
},set_selectionStart:function(d){if(this._isSelectionRangeEnabled){this.set_value(d);
}},get_selectionEnd:function(){var d=this._selectionEnd;
if(this._isDirectionReversed&&this._isSelectionRangeEnabled){d=this._value;
}return this._getIndexFromValue(d);
},set_selectionEnd:function(d){if(this._initializedInternal&&this._wrapperElement){d=this._getValueFromIndex(d);
}this._setNewValue(d,false);
},get_isSelectionRangeEnabled:function(){return this._isSelectionRangeEnabled;
},set_isSelectionRangeEnabled:function(d){if(this._isSelectionRangeEnabled!=d){this._isSelectionRangeEnabled=d;
if(this._initializedInternal&&this._wrapperElement){this._setShowEndDragHandle();
this._setTrackMouseWheel();
this._setEnableDragRange();
if(this._isSelectionRangeEnabled){var d=this._value;
var e=this._selectionEnd;
var f=this._isDirectionReversed;
if((d<e&&f)||(d>e&&!f)){this._switchDragHanldes();
var g=d;
this._value=e;
this._selectionEnd=g;
}}else{if(this._isDirectionReversed){var g=this._value;
this._value=this._selectionEnd;
this._selectionEnd=g;
}}this._clearSizePosition(this._selectedRegionElement);
this._refreshLayout();
}this.updateClientState();
}},get_enableDragRange:function(){return this._enableDragRange;
},set_enableDragRange:function(d){if(this._enableDragRange!=d){this._enableDragRange=d;
if(this._initializedInternal&&this._wrapperElement){this._setEnableDragRange();
}this.updateClientState();
}},get_isDirectionReversed:function(){return this._isDirectionReversed;
},set_isDirectionReversed:function(e){if(this._isDirectionReversed!=e){this._isDirectionReversed=e;
if(this._initializedInternal&&this._wrapperElement){if(this._isSelectionRangeEnabled){var d=this._value;
this._value=this._selectionEnd;
this._selectionEnd=d;
}this.repaint(true);
}this.updateClientState();
}},get_liveDrag:function(){return this._liveDrag;
},set_liveDrag:function(d){if(this._liveDrag!=d){this._liveDrag=d;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_minimumValue:function(){return this._minimumValue;
},set_minimumValue:function(d){d=b.parseDecimal(d,this._precision);
if(isNaN(d)){return;
}if(this._minimumValue!=d){this._minimumValue=d;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_maximumValue:function(){return this._maximumValue;
},set_maximumValue:function(d){d=b.parseDecimal(d,this._precision);
if(isNaN(d)){return;
}if(this._maximumValue!=d){this._maximumValue=d;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_orientation:function(){return this._orientation;
},set_orientation:function(d){if(this._orientation!=d){this._orientation=d;
this._isHorizontal=(this._orientation==a.Orientation.Horizontal);
this._updateLocationProperty();
this._updateSizeProperty();
this._updatePointProperty();
if(this._initializedInternal&&this._wrapperElement){this._setOrientation();
this._clearSizePosition(this._selectedRegionElement);
this._clearSizePosition(this._dragHandleElement);
this._clearSizePosition(this._endDragHandleElement);
if(!this._liveDrag){this._clearSizePosition(this._liveDragHandleElement);
this._clearSizePosition(this._liveDragEndHandleElement);
}this._refreshLayout();
if(!this._showDecreaseHandle){var e=this._trackElement;
var f=this._listElement;
var g=this._getLocationProperty();
var h=(g=="top")?"left":"top";
if(e){e.style[h]="";
e.style[g]="0";
}if(f){f.style[h]="";
f.style[g]="0";
}}}this.updateClientState();
}},get_animationDuration:function(){return this._animationDuration;
},set_animationDuration:function(d){if(isNaN(parseInt(d,10))||d<0){throw Error.argumentOutOfRange("value",d,"AnimationDuration should be positive integer");
}if(this._animationDuration!=d){this._animationDuration=d;
this.updateClientState();
}},get_length:function(){var d=parseInt((this._isHorizontal)?this._width:this._height);
if(isNaN(d)){d=200;
}return d;
},set_length:function(d){if(this._isHorizontal){this.set_width(d);
}else{this.set_height(d);
}},get_width:function(){return this._width;
},set_width:function(d){if(isNaN(parseInt(d,10))||d<1){throw Error.argumentOutOfRange("value",d,"Width should be an integer bigger than 1");
}if(this._width!=d){this._width=d;
if(this._initializedInternal&&this._wrapperElement){this._setWidth();
this._refreshLayout();
}this.updateClientState();
}},get_height:function(){return this._height;
},set_height:function(d){if(isNaN(parseInt(d,10))||d<1){throw Error.argumentOutOfRange("value",d,"Height should be an integer bigger than 1");
}if(this._height!=d){this._height=d;
if(this._initializedInternal&&this._wrapperElement){this._setHeight();
this._refreshLayout();
}this.updateClientState();
}},get_showDecreaseHandle:function(){return this._showDecreaseHandle;
},set_showDecreaseHandle:function(d){if(this._showDecreaseHandle!=d){this._showDecreaseHandle=d;
if(this._initializedInternal&&this._wrapperElement){this._setShowHandle(true);
this._refreshLayout();
}this.updateClientState();
}},get_showIncreaseHandle:function(){return this._showIncreaseHandle;
},set_showIncreaseHandle:function(d){if(this._showIncreaseHandle!=d){this._showIncreaseHandle=d;
if(this._initializedInternal&&this._wrapperElement){this._setShowHandle(false);
this._refreshLayout();
}this.updateClientState();
}},get_showDragHandle:function(){return this._showDragHandle;
},set_showDragHandle:function(d){if(this._showDragHandle!=d){this._showDragHandle=d;
if(this._initializedInternal&&this._wrapperElement){this._setShowDragHandle();
this._setFirstValueOffset();
if(this._children.get_count()>0){this._refreshLayout();
}this._setValuesForSlider();
}this.updateClientState();
}},get_trackMouseWheel:function(){return this._trackMouseWheel;
},set_trackMouseWheel:function(d){if(this._trackMouseWheel!=d){this._trackMouseWheel=d;
if(this._initializedInternal&&this._wrapperElement){this._setTrackMouseWheel();
}this.updateClientState();
}},get_largeChange:function(){return this._largeChange;
},set_largeChange:function(d){d=b.parseDecimal(d,this._precision);
if(isNaN(d)||d<0){throw Error.argumentOutOfRange("value",d,"LargeChange should be positive decimal");
}if(this._largeChange!=d){this._largeChange=d;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_smallChange:function(){return this._smallChange;
},set_smallChange:function(d){d=b.parseDecimal(d,this._precision);
if(isNaN(d)||d<=0){throw Error.argumentOutOfRange("value",d,"SmallChange should be decimal bigger than 0");
}if(this._smallChange!=d){this._smallChange=d;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_itemType:function(){return this._itemType;
},set_itemType:function(d){if(this._itemType!=d){this._itemType=d;
}},get_trackPosition:function(){return this._trackPosition;
},set_trackPosition:function(d){var l=this._trackPosition;
if(l!=d){this._trackPosition=d;
if(this._initializedInternal&&this._wrapperElement){this._setTrackPosition(l);
var g=(l==a.SliderTrackPosition.Center);
var h=(this._trackPosition==a.SliderTrackPosition.Center);
if((g||h)&&this._itemType==a.SliderItemType.Tick&&this._renderLargeTicks){var k=this._children;
var f=this._listElement;
var p=f.childNodes;
if($telerik.isIE){p=f.children;
}for(var e=0,n=p.length;
e<n;
e++){var m=p[e];
if(m.nodeType==1&&m.className.indexOf("rslLarge")>-1){var o=m.getElementsByTagName("SPAN");
if(o.length>1){var j=o[1];
if(h){j.style.display="";
}else{j.style.display="none";
}}else{if(h){var j=document.createElement("span");
j.className="rslBRItemText";
j.innerHTML=k.getItem(e).get_value();
m.appendChild(j);
}}}}}this._refreshLayout();
}this.updateClientState();
}},get_thumbsInteractionMode:function(){return this._thumbsInteractionMode;
},set_thumbsInteractionMode:function(d){if(this._thumbsInteractionMode!=d){this._thumbsInteractionMode=d;
this.updateClientState();
}},get_visibleItems:function(){var h=this._children;
var f=h.get_count();
var d=this._isDirectionReversed;
var g=[];
for(var e=0;
e<f;
e++){var j=h.getItem(d?(f-1-e):e);
if(j.get_visible()){Array.add(g,j);
}}return g;
},get_items:function(){var h=[];
var e=this._getChildren();
if(e){var g=e.get_count();
var d=this._isDirectionReversed;
for(var f=0;
f<g;
f++){var j=e.getItem(d?(g-1-f):f);
Array.add(h,j);
}}return h;
},set_items:function(d){this._children=d;
},get_itemData:function(){return this._itemData;
},set_itemData:function(d){this._itemData=d;
},get_enabled:function(){return this._enabled;
},set_enabled:function(e){if(this._enabled!=e){this._enabled=e;
if(this._initializedInternal&&this._wrapperElement){this._setEnabled();
if(this._accessKeyTextbox){var d=this._accessKeyTextbox;
d.removeAttribute("disabled");
if(!e){d.setAttribute("disabled","disabled");
}}}}},get_dragText:function(){return this._dragText;
},set_dragText:function(d){var e=this._dragText;
if(e!=d){this._dragText=d;
var f=this._dragHandleElement;
if(f){f.title=d;
}f=this._endDragHandleElement;
if(f){f.title=d;
}this.updateClientState();
}},get_skin:function(){return this._skin;
},redraw:function(d){if($telerik.getInvisibleParent(this.get_element())){return;
}this._handleInSlidingMode=null;
if(d){if(this._wrapperElement){var e=this._wrapperElement;
e.parentNode.removeChild(e);
this._wrapperElement=null;
if(this._children){this._children.clear();
this._itemsUICreated=false;
if(this._itemType==a.SliderItemType.Tick){this._itemData=[];
}}this._listElement=null;
this._disposeSlider();
}this._initializedInternal=false;
this._initializeSliderControl();
}else{if(!this._initializedInternal||!this._wrapperElement){this._initializeSliderControl();
}else{this._refreshLayout();
}}},saveClientState:function(){var d=["value","selectionStart","selectionEnd","isSelectionRangeEnabled","orientation","smallChange","largeChange","trackMouseWheel","showDragHandle","showDecreaseHandle","showIncreaseHandle","width","height","animationDuration","minimumValue","maximumValue","trackPosition","liveDrag","dragText","thumbsInteractionMode"];
var f={};
for(var e=0;
e<d.length;
e++){f[d[e]]=this["get_"+d[e]]();
}return Sys.Serialization.JavaScriptSerializer.serialize(f);
}};
c.registerControlEvents(a.RadSlider,["slideStart","slide","slideEnd","valueChanged","valueChanging","load","itemsCreated","slideRangeStart","slideRange","slideRangeEnd"]);
a.RadSlider.registerClass("Telerik.Web.UI.RadSlider",a.ControlItemContainer);
})();
Type.registerNamespace("Telerik.Web.UI");
$telerik.toSliderItem=function(a){return a;
};
$telerik.findSliderItem=$find;
Telerik.Web.UI.RadSliderItem=function(){Telerik.Web.UI.RadSliderItem.initializeBase(this);
this._imageUrl=null;
this._imageElement=null;
};
Telerik.Web.UI.RadSliderItem.prototype={set_visible:function(b){var a=this.get_visible()!=b;
if(!a){return;
}Telerik.Web.UI.RadSliderItem.callBaseMethod(this,"set_visible",[b]);
if(b){this.get_element().style.display="";
}else{this.get_element().style.display="none";
}},_updatedSelectedView:function(a){if(this.get_slider()._itemType==Telerik.Web.UI.SliderItemType.Item){var b=this.get_element();
if(a){Sys.UI.DomElement.addCssClass(b,"rslItemSelected");
}else{Sys.UI.DomElement.removeCssClass(b,"rslItemSelected");
}}},get_selected:function(){var c=false;
var a=this.get_slider();
var b=this.get_index();
if(a.get_isSelectionRangeEnabled()){if(a.get_selectionStart()==b||a.get_selectionEnd()==b){c=true;
}}else{if(a.get_value()==b){c=true;
}}return c;
},set_cssClass:function(a){this._properties.setValue("cssClass",a);
},get_cssClass:function(){return this._properties.getValue("cssClass","");
},set_tooltip:function(a){this._properties.setValue("tooltip",a);
},get_tooltip:function(){return this._properties.getValue("tooltip","");
},set_isLargeTick:function(a){this._properties.setValue("isLargeTick",a);
},get_isLargeTick:function(){return this._properties.getValue("isLargeTick",false);
},set_isSmallTick:function(a){this._properties.setValue("isSmallTick",a);
},get_isSmallTick:function(){return this._properties.getValue("isSmallTick",false);
},_loadFromDictionary:function(a){if(a.text!=null){this.set_text(a.text);
}if(a.value!=null){this.set_value(a.value);
}if(a.enabled!=null){this.set_enabled(a.enabled);
}if(a.cssClass){this.set_cssClass(a.cssClass);
}if(a.tooltip!=null){this.set_tooltip(a.tooltip);
}if(a.isLargeTick!=null){this.set_isLargeTick(a.isLargeTick);
}if(a.isSmallTick!=null){this.set_isSmallTick(a.isSmallTick);
}},_render:function(d){d[d.length]="<li unselectable='on' ";
var b=this.get_tooltip();
if(b.toString()!=""){d[d.length]='title="'+b+'" ';
}var c=this.get_index();
var j=this.get_slider();
var a=j.get_itemData().length;
d[d.length]="class='";
var f=j._itemType;
if(f==Telerik.Web.UI.SliderItemType.Item){var h=this.get_cssClass();
if(h!=""){h=" "+h;
}var i=(this.get_enabled())?"'>":" rslItemDisabled'>";
if(c==0){d[d.length]="rslItem rslItemFirst"+h+i;
}else{if(c==a-1){d[d.length]="rslItem rslItemLast"+h+i;
}else{d[d.length]="rslItem"+h+i;
}}d[d.length]="<span>";
d[d.length]=this.get_text();
d[d.length]="</span>";
}else{if(f==Telerik.Web.UI.SliderItemType.Tick){var e=this.get_isLargeTick();
if(c==0){if(e){d[d.length]="rslLargeTick rslLargeTickFirst'>";
}else{d[d.length]="rslSmallTick rslSmallTickFirst'>";
}}else{if(c==a-1){if(e){d[d.length]="rslLargeTick rslLargeTickLast'>";
}else{d[d.length]="rslSmallTick rslSmallTickLast'>";
}}else{if(e){d[d.length]="rslLargeTick'>";
}else{d[d.length]="rslSmallTick'>";
}}}if(e){var g=this.get_value();
d[d.length]="<span>";
d[d.length]=g;
d[d.length]="</span>";
if(j._trackPosition==Telerik.Web.UI.SliderTrackPosition.Center){d[d.length]="<span class='rslBRItemText'>";
d[d.length]=g;
d[d.length]="</span>";
}}else{d[d.length]="&nbsp;";
}}}d[d.length]="</li>";
},get_textElement:function(){return this.get_element();
},get_slider:function(){return this._parent;
},_createChildListElement:function(){var a=document.createElement("ul");
this.get_slider().get_dropDownElement().appendChild(a);
},_shouldInitializeChild:function(a){return false;
},_createChildControls:function(){},_getHierarchicalIndex:function(){return this.get_index();
}};
Telerik.Web.UI.RadSliderItem.registerClass("Telerik.Web.UI.RadSliderItem",Telerik.Web.UI.ControlItem);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadSliderItemCollection=function(a){Telerik.Web.UI.RadSliderItemCollection.initializeBase(this,[a]);
};
Telerik.Web.UI.RadSliderItemCollection.prototype={};
Telerik.Web.UI.RadSliderItemCollection.registerClass("Telerik.Web.UI.RadSliderItemCollection",Telerik.Web.UI.ControlItemCollection);
