Type.registerNamespace("Telerik.Web.UI.ImageEditor");
(function(c,a,b){b.AddText=function(d){b.AddText.initializeBase(this,[d]);
};
b.AddText.prototype={initialize:function(){b.AddText.callBaseMethod(this,"initialize");
this._textArea=this._getControlFromParent("textContent");
this._fontsDD=this._findControlFromParent("fontFamily");
this._sizeTxt=this._getControlFromParent("size");
this._colorTxt=this._getControlFromParent("color");
this._colorPicker=this._findControlFromParent("colorPicker");
this._xTxt=this._getControlFromParent("txtX");
this._yTxt=this._getControlFromParent("txtY");
this._btnApply=this._findControlFromParent("btnApply");
this._btnCancel=this._findControlFromParent("btnCancel");
this._createDraggableText();
this._attachEventHandlers(true);
this._setDefaultValues();
this.get_imageEditor().get_formDecorator().decorate($get(this.get_parentId()+"Table"));
},apply:function(){this.get_imageEditor().addTextToImage(this.get_x(),this.get_y(),this.get_textSettings());
},onOpen:function(){var d=c(this.get_imageEditor().get_viewport());
this._draggableText.set_position({x:d.scrollLeft(),y:d.scrollTop()});
this._draggableText.show();
},onClose:function(){this._draggableText.hide();
this._fontsDD.hideDropDown();
},dispose:function(){this._draggableText.dispose();
b.AddText.callBaseMethod(this,"dispose");
},set_position:function(d){this._draggableText.set_position(this._getScaledPosition(d,this._getImageZoom()));
this._setPositionInternal(d);
},get_position:function(){return this._draggableText.get_position();
},get_x:function(){return parseInt(this._xTxt.value);
},set_x:function(d){if(!d||isNaN(d)){return;
}this.set_position(c.extend(this.get_position(),{x:d}));
},get_y:function(){return parseInt(this._yTxt.value);
},set_y:function(d){if(!d||isNaN(d)){return;
}this.set_position(c.extend(this.get_position(),{y:d}));
},get_textToAdd:function(){return this._textArea.value;
},set_textToAdd:function(d){this._textArea.value=d;
this._draggableText.set_text(d);
},set_fontSize:function(d){if(!d||isNaN(d)||d<0){return;
}this._draggableText.set_fontSize(d*this._getImageZoom());
this._sizeTxt.value=d;
},get_textSettings:function(){var d=this._draggableText.get_textSettings();
d.set_fontSize(parseInt(this._sizeTxt.value));
return d;
},get_name:function(){return"AddText";
},updateUI:function(){this.set_fontSize(parseInt(this._sizeTxt.value));
this.set_position({x:this.get_x(),y:this.get_y()});
},_createDraggableText:function(){this._draggableText=new b.DraggableTextBox(this.get_imageEditor().get_viewport());
},_attachEventHandlers:function(d){if(d){this._changeTextDelegate=Function.createDelegate(this,this._changeTextHandler);
$telerik.addHandler(this._textArea,"keyup",this._changeTextDelegate);
this._changeFontSizeDelegate=Function.createDelegate(this,this._changeFontSizeHandler);
$telerik.addHandler(this._sizeTxt,"keyup",this._changeFontSizeDelegate);
this._changeXDelegate=Function.createDelegate(this,this._changeXHandler);
$telerik.addHandler(this._xTxt,"keyup",this._changeXDelegate);
this._changeYDelegate=Function.createDelegate(this,this._changeYHandler);
$telerik.addHandler(this._yTxt,"keyup",this._changeYDelegate);
this._fontFamilyChangedDelegate=Function.createDelegate(this,this._fontFamilyChangedHandler);
this._fontsDD.add_selectedIndexChanged(this._fontFamilyChangedDelegate);
this._colorChangeDelegate=Function.createDelegate(this,this._colorChangeHandler);
this._colorPicker.add_colorChange(this._colorChangeDelegate);
this._textBoundsChangedDelegate=Function.createDelegate(this,this._textBoundsChangedHandler);
this._draggableText.add_boundsChanged(this._textBoundsChangedDelegate);
this._applyBtnDelegate=Function.createDelegate(this,this._applyBtnHandler);
this._btnApply.add_clicked(this._applyBtnDelegate);
this._closeDelegate=Function.createDelegate(this,this.close);
this._btnCancel.add_clicked(this._closeDelegate);
}else{$telerik.removeHandler(this._textArea,"keyup",this._changeTextDelegate);
$telerik.removeHandler(this._sizeTxt,"keyup",this._changeXDelegate);
$telerik.removeHandler(this._xTxt,"keyup",this._changeXDelegate);
$telerik.removeHandler(this._yTxt,"keyup",this._changeYDelegate);
this._colorPicker.remove_colorChange(this._colorChangeDelegate);
this._draggableText.remove_boundsChanged(this._textBoundsChangedDelegate);
this._changeTextDelegate=this._changeFontSizeDelegate=this._changeXDelegate=this._changeYDelegate=this._colorChangeDelegate=this._textBoundsChangedDelegate=null;
}},_applyBtnHandler:function(d,e){this.apply();
this.close();
},_fontFamilyChangedHandler:function(d,f){var e=f.get_item();
this._draggableText.set_fontFamily(e.get_value());
},_colorChangeHandler:function(e,d){this._colorTxt.value=e.get_selectedColor();
this._draggableText.set_color(this._colorTxt.value);
},_textBoundsChangedHandler:function(){var d=this._draggableText.get_position();
this._setPositionInternal(this._getScaledPosition(d));
},_setPositionInternal:function(d){this._xTxt.value=d.x;
this._yTxt.value=d.y;
},_setDefaultValues:function(){var d=this._getDefaultTextSettings();
this.set_fontSize(d.get_fontSize());
this._colorPicker.set_selectedColor(d.get_color());
var e=this._fontsDD.findItemByValue(d.get_fontFamily());
if(e){e.select();
}d.set_fontSize(parseInt(d.get_fontSize()*this._getImageZoom()));
this._draggableText.set_textSettings(d);
this._textArea.value=d.get_text();
this.set_position({x:0,y:0});
},_getDefaultTextSettings:function(){var d=new b.ImageText();
d.set_fontFamily("verdana");
d.set_fontSize(12);
d.set_color("#000");
d.set_text(this.get_textToAdd());
return d;
},_getScaledPosition:function(d,e){var f=e||1/this._getImageZoom();
return{x:parseInt(d.x*f),y:parseInt(d.y*f)};
},_getImageZoom:function(){return this.get_imageEditor().getEditableImage().get_zoomLevel()/100;
},_changeTextHandler:function(){this._draggableText.set_text(this._textArea.value);
},_changeFontSizeHandler:function(d){this.set_fontSize(this._getInputValueHandler(d));
},_changeXHandler:function(d){this.set_x(this._getInputValueHandler(d));
},_changeYHandler:function(d){this.set_y(this._getInputValueHandler(d));
},_getInputValueHandler:function(e){var f=e.keyCode;
var d=e.target;
switch(f){case 38:$telerik.cancelRawEvent(e.rawEvent);
return this._incrementInputValue(d);
case 40:$telerik.cancelRawEvent(e.rawEvent);
return this._decrementInputValue(d);
case 27:$telerik.cancelRawEvent(e.rawEvent);
return;
default:if(this.isNumeric(f)||this.isBackspaceOrDelete(f)){return parseInt(d.value);
}}},_incrementInputValue:function(d,e){return parseInt(d.value)+1;
},_decrementInputValue:function(d,e){return parseInt(d.value)-1;
}};
b.AddText.registerClass("Telerik.Web.UI.ImageEditor.AddText",b.ToolWidget,b.IToolWidget);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.ImageEditor);
