Type.registerNamespace("Telerik.Web.UI.ImageEditor");
(function(c,a,b){b.Flip=function(d){b.Flip.initializeBase(this,[d]);
this._anchors=null;
};
b.Flip.prototype={initialize:function(){b.Flip.callBaseMethod(this,"initialize");
this._attachHandlers(true);
},dispose:function(){this._attachHandlers(false);
b.Flip.callBaseMethod(this,"dispose");
},flip:function(d){var e=this.get_imageEditor();
e.flipImage(d,true,true);
},get_table:function(){if(!this._table){this._table=this._getChildElement("Table");
}return this._table;
},_getChildElement:function(d,e){return $get(this.get_parentId()+d,e);
},get_allAnchors:function(){if(!this._anchors){this._anchors=this.get_table().getElementsByTagName("a");
}return this._anchors;
},get_activeAnchor:function(){if(!this._activeAnchor){var f=this.get_allAnchors();
var e=f.length;
for(var d=0;
d<e;
d++){if(f[d].className.indexOf("rieActiveThumbsLink")!=-1){this._activeAnchor=f[d];
return this._activeAnchor;
}}}return this._activeAnchor;
},_attachHandlers:function(d){var f=this.get_allAnchors();
if(d){if(f){this._anchorClickDelegate=Function.createDelegate(this,this._anchorClick);
var e=f.length;
for(var g=0;
g<e;
g++){$addHandler(f[g],"click",this._anchorClickDelegate);
}}}else{if(f){var e=f.length;
for(var g=0;
g<e;
g++){$removeHandler(f[g],"click",this._anchorClickDelegate);
}this._anchorClickDelegate=null;
}}},_anchorClick:function(e){var d=e.rawEvent.currentTarget;
if(!d){d=e.rawEvent.srcElement;
if(typeof(d.src)!="undefined"){d=d.parentNode;
}}this._activateAnchor(d);
this._UIupdated=true;
var f=this._getFlipDirectionFromId(d.id.substring(this.get_parentId().length));
this.flip(f);
$telerik.cancelRawEvent(e.rawEvent);
return false;
},_updateUI:function(){if(this._UIupdated){this._UIupdated=false;
return;
}var d=this.get_imageEditor().getEditableImage();
var g=d.get_flipDirection();
var f=d._getIsHorizontal();
var j=this._getAnchorID(d._getFlipDirections(g),f);
this._activateAnchor(this._getChildElement(j,this.get_table()));
var h=this.get_allAnchors();
var n=h.length;
for(var e=0;
e<n;
e++){var o=h[e].firstChild;
var l=$telerik.isIE&&!$telerik.isIE9Mode;
if(o.src!=d.getImage().src){o.src=d.getImage().src;
if(l){o.style.filter="flipH flipV progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=100) progid:DXImageTransform.Microsoft.Matrix(M11='1.0', sizingmethod='auto expand')";
o.filters.item("flipH").enabled=0;
o.filters.item("flipV").enabled=0;
}}var k=(e%2==1);
var m=e>1;
if(l){d._rotate(o,null);
}if(f){d._flip(o,k,m);
}else{d._flip(o,m,k);
}}},_activateAnchor:function(d){var e=this.get_activeAnchor();
if(e){c(e).removeClass("rieActiveThumbsLink");
}this._activeAnchor=d;
c(d).addClass("rieActiveThumbsLink");
},_getAnchorID:function(e,f){var d=f?e.flipH:e.flipV;
var g=f?e.flipV:e.flipH;
return g&&d?"FlipBoth":(g?"FlipVertical":(d?"FlipHorizontal":"FlipNone"));
},_getFlipDirectionFromId:function(d){return(d.indexOf("FlipB")!=-1)?b.FlipDirection.Both:(d.indexOf("FlipV")!=-1?b.FlipDirection.Vertical:(d.indexOf("FlipH")!=-1?b.FlipDirection.Horizontal:b.FlipDirection.None));
},_flipInternal:function(e,d,f){},get_name:function(){return"Flip";
},updateUI:function(){this._updateUI();
},onOpen:function(){b.Flip.callBaseMethod(this,"onOpen");
}};
b.Flip.registerClass("Telerik.Web.UI.ImageEditor.Flip",b.ToolWidget,b.IToolWidget);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.ImageEditor);
