Type.registerNamespace("Telerik.Web.UI.ImageEditor");
(function(c,a,b){b.InsertImage=function(d){b.InsertImage.initializeBase(this,[d]);
};
b.InsertImage.prototype={initialize:function(){b.InsertImage.callBaseMethod(this,"initialize");
this._xTxt=this._getControlFromParent("txtX");
this._yTxt=this._getControlFromParent("txtY");
this._widthTxt=this._getControlFromParent("txtWidth");
this._heightTxt=this._getControlFromParent("txtHeight");
this._insertBtn=this._findControlFromParent("btnInsert");
this._cancelBtn=this._findControlFromParent("btnCancel");
this._chooseBtn=this._findControlFromParent("btnChooseUrl");
this._constraintBtn=this._findControlFromParent("btnConstraint");
this._swapBtn=this._findControlFromParent("btnSwap");
this._okBtn=this._findControlFromParent("btnOk");
this._txtSrc=this._getControlFromParent("Url");
this._sizeRatio=null;
this._zoomLevel=this._getImageZoomLevel();
this._createImageBox();
this._updateControlsFromImageBox();
this._constraintBtnClick(this._constraintBtn);
this._attachHandlers(true);
this.get_imageEditor().get_formDecorator().decorate($get(this.get_parentId()+"Table"));
},dispose:function(){this._attachHandlers(false);
this._disposeImageBox();
b.InsertImage.callBaseMethod(this,"dispose");
},onClose:function(){this._imageBox.hide();
},onOpen:function(){try{this._imageBox.show();
var f=this._getViewportScroll();
this._xTxt.value=f.x;
this._yTxt.value=f.y;
this._updateImageBoxFromControls();
}catch(d){}},insertImage:function(f){var d=this._imageBox.get_src();
var e=[];
e[e.length]=new b.ResizeOperation(false,f.width,f.height);
this.get_imageEditor()._insertImage(f.x,f.y,d,e);
},set_width:function(d){var f=this.get_imageSize();
var e=this._imageBox.getBounds();
d=this._restrictValue(d,0,f.width-e.x);
d=this._applyWidthConstraintRatio(d,f.height-e.y);
this.set_inputValue(this._widthTxt,d);
},set_height:function(d){var f=this.get_imageSize();
var e=this._imageBox.getBounds();
d=this._restrictValue(d,0,f.height-e.y);
d=this._applyHeightConstraintRatio(d,f.width-e.y);
this.set_inputValue(this._heightTxt,d);
},set_x:function(d){var f=this.get_imageSize();
var e=this._imageBox.getBounds();
d=this._restrictValue(d,0,f.width-e.width);
this.set_inputValue(this._xTxt,d);
},set_y:function(d){var f=this.get_imageSize();
var e=this._imageBox.getBounds();
d=this._restrictValue(d,0,f.height-e.height);
this.set_inputValue(this._yTxt,d);
},set_inputValue:function(d,e){d.value=parseInt(e);
this._updateImageBoxFromControls();
},_restrictValue:function(d,e,f){return Math.max(e,Math.min(f,d));
},get_sizeRatio:function(){return this._sizeRatio;
},get_freshSizeRatio:function(){return parseInt(this._widthTxt.value)/parseInt(this._heightTxt.value);
},get_imageSize:function(){var d=this.get_imageEditor().getEditableImage();
return{width:d.get_width(),height:d.get_height()};
},_applyWidthConstraintRatio:function(d,e){if(this._constraintBtn.get_checked()){var f=this.get_sizeRatio();
var g=this._restrictValue(parseInt(d/f),0,e);
this._heightTxt.value=g;
if(g>=e){d=g*f;
}}return d;
},_applyHeightConstraintRatio:function(d,g){if(this._constraintBtn.get_checked()){var f=this.get_sizeRatio();
var e=this._restrictValue(d*f,0,g);
this._widthTxt.value=e;
if(e>=g){d=e/f;
}}return d;
},_attachHandlers:function(d){this._attachButtonHandler(this._insertBtn,"_insertBtnClick",d);
this._attachButtonHandler(this._cancelBtn,"_cancelBtnClick",d);
this._attachButtonHandler(this._constraintBtn,"_constraintBtnClick",d);
this._attachButtonHandler(this._swapBtn,"_swapBtnClick",d);
this._attachButtonHandler(this._okBtn,"_okBtnHandler",d);
if(d){this._changeXDelegate=Function.createDelegate(this,this._changeXHandler);
$telerik.addHandler(this._xTxt,"keyup",this._changeXDelegate);
this._changeYDelegate=Function.createDelegate(this,this._changeYHandler);
$telerik.addHandler(this._yTxt,"keyup",this._changeYDelegate);
this._changeWidthDelegate=Function.createDelegate(this,this._changeWidthHandler);
$telerik.addHandler(this._widthTxt,"keyup",this._changeWidthDelegate);
this._changeHeightDelegate=Function.createDelegate(this,this._changeHeightHandler);
$telerik.addHandler(this._heightTxt,"keyup",this._changeHeightDelegate);
this.updateImageBoxFromImageDelegate=Function.createDelegate(this,this._updateImageBoxFromImageHandler);
this.get_imageEditor().getEditableImage().add_imageReload(this.updateImageBoxFromImageDelegate);
}else{$telerik.removeHandler(this._xTxt,"keyup",this._changeXDelegate);
$telerik.removeHandler(this._yTxt,"keyup",this._changeYDelegate);
$telerik.removeHandler(this._widthTxt,"keyup",this._changeWidthDelegate);
$telerik.removeHandler(this._heightTxt,"keyup",this._changeHeightDelegate);
this._changeXDelegate=this._changeYDelegate=this._changeWidthDelegate=this._changeHeightDelegate=null;
this.get_imageEditor().getEditableImage().remove_imageReload(this.updateImageBoxFromImageDelegate);
delete this.updateImageBoxFromImageDelegate;
}},_attachButtonHandler:function(d,f,e){var h=f+"Delegate";
if(e){var g=this[h]=Function.createDelegate(this,this[f]);
d.add_clicked(g);
}else{d.remove_clicked(this[h]);
delete this[h];
}},_changeXHandler:function(d){this._changeDimensionHandler("set_x",d);
},_changeYHandler:function(d){this._changeDimensionHandler("set_y",d);
},_changeWidthHandler:function(d){this._changeDimensionHandler("set_width",d);
},_changeHeightHandler:function(d){this._changeDimensionHandler("set_height",d);
},_changeDimensionHandler:function(f,e){var d=this._getInputValueHandler(e);
if(!isNaN(d)){this[f](d);
}},_getInputValueHandler:function(e){var f=e.keyCode;
var d=e.target;
switch(f){case 38:$telerik.cancelRawEvent(e.rawEvent);
return this._incrementInputValue(d);
case 40:$telerik.cancelRawEvent(e.rawEvent);
return this._decrementInputValue(d);
case 27:case 13:$telerik.cancelRawEvent(e.rawEvent);
return;
default:if(this.isNumeric(f)||this.isBackspaceOrDelete(f)){return parseInt(d.value);
}}},_incrementInputValue:function(d,e){return parseInt(d.value)+1;
},_decrementInputValue:function(d,e){return parseInt(d.value)-1;
},_insertBtnClick:function(d,e){this.insertImage(this._collectBounds());
this.close();
},_cancelBtnClick:function(d,e){this.close();
},_swapBtnClick:function(d,e){this._setImageSize(this._heightTxt.value,this._widthTxt.value);
this._updateImageBoxFromControls();
},_constraintBtnClick:function(d,e){var f=d.get_checked()?this.get_freshSizeRatio():null;
this._setImageBoxRatio(f);
this._sizeRatio=f;
},_setImageBoxRatio:function(d){this._imageBox.set_sizeRatio(d);
},_chooseBtnClick:function(d,e){this._openChooseImageDialog();
},_openChooseImageDialog:function(){},_okBtnHandler:function(d,e){if(this._txtSrc.value){this._imageBox.set_src(this._txtSrc.value);
}this._updateControlsFromImageBox();
},_appendDialog:function(d){},_createImageBox:function(){if(this._imageBox){this._disposeImageBox();
}this._imageBox=new b.DraggableImageResizeBox(this._imageEditor.get_viewport());
this._imageBox.set_src(this.get_imageEditor().get_defaultInsertedImageUrl());
this._imageBoxBoundsChangedDelegate=Function.createDelegate(this,this._imageBoxBoundsChangedHandler);
this._imageBox.add_boundsChanged(this._imageBoxBoundsChangedDelegate);
this._setImageBoxConstraints();
},_setImageBoxConstraints:function(f){var d=this._imageEditor.getEditableImage();
var e=d.get_zoomLevel()/100;
this._imageBox.set_constraints(f||new Sys.UI.Bounds(0,0,parseInt(d.get_width()*e),parseInt(d.get_height()*e)));
},_zoomImageBox:function(){this._updateImageBoxFromControls();
},_disposeImageBox:function(){this._imageBoxBoundsChangedDelegate=this._imageBox.remove_boundsChanged(this._imageBoxBoundsChangedDelegate);
this._imageBox=this._imageBox.dispose();
},_setImageSize:function(d,e){this._widthTxt.value=d;
this._heightTxt.value=e;
},_updateImageBoxFromControls:function(){var d=this._toScaledBounds(this._collectBounds());
this._imageBox.setBounds(d);
},_collectBounds:function(){return new Sys.UI.Bounds(parseInt(this._xTxt.value),parseInt(this._yTxt.value),parseInt(this._widthTxt.value),parseInt(this._heightTxt.value));
},_updateControlsFromImageBox:function(){var d=this._fromScaledBounds(this._imageBox.getBounds());
this._updateControlsWithFixedBounds(d);
},_imageBoxBoundsChangedHandler:function(e,d){this._updateControlsWithBounds(d.getBounds());
if(d.get_value()===true){this._setImageBoxRatio(this._constraintBtn.get_checked()?this.get_freshSizeRatio():null);
}},_updateControlsWithBounds:function(e){var d=this._fromScaledBounds(e);
this._updateControlsWithFixedBounds(d);
},_updateControlsWithFixedBounds:function(e){for(var d in e){this["_"+d+"Txt"].value=e[d];
}},_updateImageBoxFromImageHandler:function(d){this._setImageBoxConstraints();
},_fromScaledBounds:function(d){return this._multiplyBounds(d,100/this._zoomLevel);
},_toScaledBounds:function(d){return this._multiplyBounds(d,this._zoomLevel/100);
},_multiplyBounds:function(e,d){return new Sys.UI.Bounds(Math.round(e.x*d),Math.round(e.y*d),Math.round(e.width*d),Math.round(e.height*d));
},_getImageZoomLevel:function(){return this.get_imageEditor().getEditableImage().get_zoomLevel();
},_getViewportScroll:function(){var d=this.get_imageEditor().get_viewport();
return{x:d.scrollLeft,y:d.scrollTop};
},get_name:function(){return"InsertImage";
},updateUI:function(){try{if(this._getImageZoomLevel()!=this._zoomLevel){this._zoomLevel=this._getImageZoomLevel();
this._updateImageBoxFromControls();
}else{this._updateControlsFromImageBox();
}this._setImageBoxConstraints();
}catch(d){}}};
b.InsertImage.registerClass("Telerik.Web.UI.ImageEditor.InsertImage",b.ToolWidget,b.IToolWidget);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.ImageEditor);
