Type.registerNamespace("Telerik.Web.UI.ImageEditor");
(function(c,a,b){b.Opacity=function(d){b.Opacity.initializeBase(this,[d]);
this._slider=null;
this._textbBox=null;
this._shouldChangeOpacity=true;
};
b.Opacity.prototype={initialize:function(){b.Opacity.callBaseMethod(this,"initialize");
this._attachHandlers(true);
this.get_imageEditor().get_formDecorator().decorate(this.get_textBox().parentNode);
var d=this;
window.setTimeout(function(){d.get_slider().repaint();
},0);
},dispose:function(){this._attachHandlers(false);
b.Opacity.callBaseMethod(this,"dispose");
},changeOpacity:function(e,f){if(this._shouldChangeOpacity){var d=this.get_imageEditor();
d._changeImageOpacity(e,f,false);
}this._shouldChangeOpacity=true;
},get_slider:function(){if(!this._slider){this._slider=$find(this.get_parentId()+"SliderOpacity");
}return this._slider;
},get_textBox:function(){if(!this._textBox){this._textBox=$get(this.get_parentId()+"TxtOpacity");
if(this._textBox){this._textBox.setAttribute("autoComplete","off");
}}return this._textBox;
},_attachHandlers:function(d){var e=this.get_slider();
var f=this.get_textBox();
if(d){if(e){this._sliderValueChangedDelegate=Function.createDelegate(this,this._sliderValueChanged);
e.add_valueChanged(this._sliderValueChangedDelegate);
this._sliderSlideEndDelegate=Function.createDelegate(this,this._sliderSlideEnd);
e.add_slideEnd(this._sliderSlideEndDelegate);
this._sliderSlideStartDelegate=Function.createDelegate(this,this._sliderSlideStart);
e.add_slideStart(this._sliderSlideStartDelegate);
}if(f){this._textBoxKeyDownDelegate=Function.createDelegate(this,this._textBoxKeyDown);
$addHandler(f,"keydown",this._textBoxKeyDownDelegate);
this._textBoxKeyUpDelegate=Function.createDelegate(this,this._textBoxKeyUp);
$addHandler(f,"keyup",this._textBoxKeyUpDelegate);
}}else{if(e){e.remove_valueChanged(this._sliderValueChangedDelegate);
this._sliderValueChangedDelegate=null;
e.remove_slideEnd(this._sliderSlideEndDelegate);
this._sliderSlideEndDelegate=null;
e.remove_slideStart(this._sliderSlideStartDelegate);
this._sliderSlideStartDelegate=null;
}if(f){$removeHandler(f,"keydown",this._textBoxKeyDownDelegate);
this._textBoxKeyDownDelegate=null;
$removeHandler(f,"keyup",this._textBoxKeyUpDelegate);
this._textBoxKeyUpDelegate=null;
}}},_sliderValueChanged:function(f,e){var d=f.get_value();
this.get_textBox().value=d;
this.changeOpacity(d,(!this._doNotAddToStack));
},_sliderSlideStart:function(){this._doNotAddToStack=true;
},_sliderSlideEnd:function(f,e){var d=f.get_value();
this.changeOpacity(d,true);
this._doNotAddToStack=false;
},_textBoxKeyDown:function(f){this._doNotAddToStack=true;
this._isTxtValueChanged=false;
var g=f.keyCode;
var h=this.get_textBox();
var e=this.get_slider();
if(g==38&&this.incrementValue(h,100)){e.set_value(h.value);
this._isTxtValueChanged=true;
}else{if(g==40&&this.decrementValue(h,0)){e.set_value(h.value);
this._isTxtValueChanged=true;
}}if(g==13){var d=this.checkValue(h,0,100);
if(d===false){d=e.get_value();
}else{if(d!=e.get_value()){this._isTxtValueChanged=true;
}e.set_value(d);
}h.value=d;
$telerik.cancelRawEvent(f.rawEvent);
return false;
}if(g==27){$telerik.cancelRawEvent(f.rawEvent);
return false;
}},_textBoxKeyUp:function(d){this._doNotAddToStack=false;
if(this._isTxtValueChanged){this.changeOpacity(this.get_textBox().value,true);
}},get_name:function(){return"Opacity";
},updateUI:function(){var e=this.get_imageEditor().getEditableImage();
var d=e?e.get_opacity():100;
this._updateTxtAndSlider(d);
},_updateTxtAndSlider:function(e){var d=this.get_slider();
this._shouldChangeOpacity=(e==d.get_value());
d.set_value(e);
this.get_textBox().value=e;
}};
b.Opacity.registerClass("Telerik.Web.UI.ImageEditor.Opacity",b.ToolWidget,b.IToolWidget);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.ImageEditor);
