Type.registerNamespace("Telerik.Web.UI.ImageEditor");
(function(c,a,b){b.Resize=function(d){b.Resize.initializeBase(this,[d]);
};
b.Resize.prototype={initialize:function(){b.Resize.callBaseMethod(this,"initialize");
this._attachHandlers(true);
this._editableImage=this.get_imageEditor().getEditableImage();
this._percentValue=this.get_percentTxt().value="100";
if(this._editableImage){this._originalWidth=this._editableImage.get_width();
this._originalHeight=this._editableImage.get_height();
this._updateCoefficients(this._originalWidth,this._originalHeight);
}this.get_imageEditor().get_formDecorator().decorate($get(this.get_parentId()+"Table"));
},dispose:function(){this._attachHandlers(false);
b.Resize.callBaseMethod(this,"dispose");
},resize:function(e,d){var f=this.get_imageEditor();
this._originalWidth=parseInt(e);
this._originalHeight=parseInt(d);
f._resizeImage(this._originalWidth,this._originalHeight,true,false);
},get_widthTxt:function(){if(!this._widthTxt){this._widthTxt=$get(this.get_parentId()+"TxtWidth");
if(this._widthTxt){this._widthTxt.setAttribute("autoComplete","off");
}}return this._widthTxt;
},get_heightTxt:function(){if(!this._heightTxt){this._heightTxt=$get(this.get_parentId()+"TxtHeight");
if(this._heightTxt){this._heightTxt.setAttribute("autoComplete","off");
}}return this._heightTxt;
},get_percentTxt:function(){if(!this._percentTxt){this._percentTxt=$get(this.get_parentId()+"TxtPercent");
if(this._percentTxt){this._percentTxt.setAttribute("autoComplete","off");
}}return this._percentTxt;
},get_resizeBtn:function(){if(!this._resizeBtn){this._resizeBtn=$find(this.get_parentId()+"BtnResize");
}return this._resizeBtn;
},get_cancelBtn:function(){if(!this._cancelBtn){this._cancelBtn=$find(this.get_parentId()+"BtnCancel");
}return this._cancelBtn;
},get_constraintBtn:function(){if(!this._constraintBtn){this._constraintBtn=$find(this.get_parentId()+"BtnConstraint");
}return this._constraintBtn;
},get_swapBtn:function(){if(!this._swapBtn){this._swapBtn=$find(this.get_parentId()+"BtnSwap");
}return this._swapBtn;
},get_comboSizes:function(){if(!this._comboSizes){this._comboSizes=$find(this.get_parentId()+"PresetSizes");
}return this._comboSizes;
},get_max:function(){return 9999;
},get_min:function(){return 0;
},IsConstrained:function(){return this.get_constraintBtn().get_checked();
},_attachHandlers:function(g){var e=this.get_resizeBtn();
var l=this.get_cancelBtn();
var d=this.get_widthTxt();
var i=this.get_heightTxt();
var h=this.get_percentTxt();
var f=this.get_comboSizes();
var j=this.get_constraintBtn();
var k=this.get_swapBtn();
if(g){this._resizeBtnClickDelegate=Function.createDelegate(this,this._resizeBtnClick);
if(e&&l){e.add_clicked(this._resizeBtnClickDelegate);
l.add_clicked(this._resizeBtnClickDelegate);
}if(d){this._widthKeyDownDelegate=Function.createDelegate(this,this._widthKeyDown);
$addHandler(d,"keydown",this._widthKeyDownDelegate);
this._widthKeyUpDelegate=Function.createDelegate(this,this._widthKeyUp);
$addHandler(d,"keyup",this._widthKeyUpDelegate);
}if(i){this._heightKeyDownDelegate=Function.createDelegate(this,this._heightKeyDown);
$addHandler(i,"keydown",this._heightKeyDownDelegate);
this._heightKeyUpDelegate=Function.createDelegate(this,this._heightKeyUp);
$addHandler(i,"keyup",this._heightKeyUpDelegate);
}if(h){this._percentTxtKeyDownDelegate=Function.createDelegate(this,this._percentTxtKeyDown);
$addHandler(h,"keydown",this._percentTxtKeyDownDelegate);
this._percentTxtKeyUpDelegate=Function.createDelegate(this,this._percentTxtKeyUp);
$addHandler(h,"keyup",this._percentTxtKeyUpDelegate);
}if(f){this._indexChangedDelegate=Function.createDelegate(this,this._indexChanged);
f.add_selectedIndexChanged(this._indexChangedDelegate);
}if(k){this._swapBtnClickDelegate=Function.createDelegate(this,this._swapBtnClick);
k.add_clicked(this._swapBtnClickDelegate);
}if(j){this._checkedChangedDelegate=Function.createDelegate(this,this._checkedChanged);
j.add_checkedChanged(this._checkedChangedDelegate);
}}else{if(e&&l){e.remove_clicked(this._resizeBtnClickDelegate);
l.remove_clicked(this._resizeBtnClickDelegate);
}this._resizeBtnClickDelegate=null;
if(d){$removeHandler(d,"keydown",this._widthKeyDownDelegate);
this._widthKeyDownDelegate=null;
$removeHandler(d,"keyup",this._widthKeyUpDelegate);
this._widthKeyUpDelegate=null;
}if(i){$removeHandler(i,"keydown",this._heightKeyDownDelegate);
this._heightKeyDownDelegate=null;
$removeHandler(i,"keyup",this._heightKeyUpDelegate);
this._heightKeyUpDelegate=null;
}if(h){$removeHandler(h,"keydown",this._percentTxtKeyDownDelegate);
this._percentTxtKeyDownDelegate=null;
$removeHandler(h,"keyup",this._percentTxtKeyUpDelegate);
this._percentTxtKeyUpDelegate=null;
}if(f){f.remove_selectedIndexChanged(this._indexChangedDelegate);
this._indexChangedDelegate=null;
}if(k){k.remove_clicked(this._swapBtnClickDelegate);
this._swapBtnClickDelegate=null;
}if(j){j.remove_checkedChanged(this._checkedChangedDelegate);
this._checkedChangedDelegate=null;
}}},_resizeBtnClick:function(d,e){if(e.get_commandName()=="Resize"){this.resize(this.get_widthTxt().value,this.get_heightTxt().value);
}else{this.get_imageEditor().closeToolsPanel();
}},_checkedChanged:function(d,e){if(d.get_checked()){this._updateCoefficients(this.get_widthTxt().value,this.get_heightTxt().value);
}},_widthKeyDown:function(d){return this._dimTxtsKeyDown(d,this.get_heightTxt(),this._ratioHW,true);
},_heightKeyDown:function(d){return this._dimTxtsKeyDown(d,this.get_widthTxt(),this._ratioWH,false);
},_dimTxtsKeyDown:function(j,f,i,e){var h=j.keyCode;
var g=j.target;
if(h==38&&this.incrementValue(g,this.get_max())){this._setValues(g,f,i,e);
}else{if(h==40&&this.decrementValue(g,this.get_min())){this._setValues(g,f,i,e);
}}if(h==13){var d=this.checkValue(g,this.get_min(),this.get_max());
if(d===false){g.value=e?this._width:this._height;
}else{this._setValues(g,f,i,e);
}$telerik.cancelRawEvent(j.rawEvent);
return false;
}if(h==27){$telerik.cancelRawEvent(j.rawEvent);
return false;
}return true;
},_widthKeyUp:function(f){var g=f.keyCode;
var e=f.target;
var h=this.isBackspaceOrDelete(g);
if(this.isNumeric(g)||h){var d=this.checkValue(e,this.get_min(),this.get_max(),h);
if(d===false&&!h){e.value=this._width;
}else{this._setValues(e,this.get_heightTxt(),this._ratioHW,true);
}}},_heightKeyUp:function(f){var g=f.keyCode;
var e=f.target;
var h=this.isBackspaceOrDelete(g);
if(this.isNumeric(g)||h){var d=this.checkValue(e,this.get_min(),this.get_max(),h);
if(d===false&&!h){e.value=this._height;
}else{this._setValues(e,this.get_widthTxt(),this._ratioWH,false);
}}},_setValues:function(d,f,g,e){if(this._selectedValueCombo!="custom"){this.get_comboSizes().findItemByValue("custom").select();
this._selectedValueCombo="custom";
}if(this.IsConstrained()){var h=Math.floor(parseInt(d.value)*g);
f.value=(isNaN(h)?0:h)+"";
}if(e){this._width=d.value;
}else{this._height=d.value;
}},_percentTxtKeyDown:function(f){var g=f.keyCode;
var e=f.target;
if(g==38&&this.incrementValue(e,100)){this._percentHelper(parseInt(e.value)/100,e);
}else{if(g==40&&this.decrementValue(e,0)){this._percentHelper(parseInt(e.value)/100,e);
}}if(g==13){var d=this.checkValue(e,0,100);
if(d===false){e.value=this._percentValue;
}else{this._percentHelper(d/100,e);
}$telerik.cancelRawEvent(f.rawEvent);
return false;
}if(g==27){$telerik.cancelRawEvent(f.rawEvent);
return false;
}},_percentTxtKeyUp:function(f){var g=f.keyCode;
var e=f.target;
var h=this.isBackspaceOrDelete(g);
if(this.isNumeric(g)||h){var d=this.checkValue(e,0,100,h);
if(d===false&&!h){e.value=this._percentValue;
}else{this._percentHelper(d/100,e);
}}},_percentHelper:function(e,d){if(this._selectedValueCombo!="custom"){this.get_comboSizes().findItemByValue("custom").select();
this._selectedValueCombo="custom";
}var f=Math.floor(this._originalWidth*e);
var g=Math.floor(this._originalHeight*e);
this._percentValue=parseInt(d.value);
this._applyWidthHeight(f,g);
},_indexChanged:function(f,e){var d=e.get_item().get_value();
this._selectedValueCombo=d;
if(d=="custom"){return;
}if(d=="original"){if(this._editableImage){this._setWidthHeight(this._editableImage.get_width(),this._editableImage.get_height(),true);
}}else{var g=d.split(",");
this._setWidthHeight(g[0],g[1],true);
}},_swapBtnClick:function(d,e){this._setWidthHeight(this.get_heightTxt().value,this.get_widthTxt().value,true);
},_setWidthHeight:function(f,d,e){this._applyWidthHeight(f,d);
if(e){this._updateCoefficients(f,d);
}},_applyWidthHeight:function(d,e){this._width=this.get_widthTxt().value=d;
this._height=this.get_heightTxt().value=e;
},_updateCoefficients:function(d,e){d=parseInt(d);
e=parseInt(e);
this._ratioWH=e==0?1:d/e;
this._ratioHW=d==0?1:e/d;
},get_name:function(){return"Resize";
},updateUI:function(){if(this._editableImage){this.get_comboSizes().get_items()._array[0].select();
this._originalWidth=this._editableImage.get_width();
this._originalHeight=this._editableImage.get_height();
this._updateCoefficients(this._originalWidth,this._originalHeight);
}}};
b.Resize.registerClass("Telerik.Web.UI.ImageEditor.Resize",b.ToolWidget,b.IToolWidget);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.ImageEditor);
