Type.registerNamespace("Telerik.Web.UI.ImageEditor");
(function(c,a,b){b.Rotate=function(d){b.Rotate.initializeBase(this,[d]);
this._rotateLeftBtn=null;
this._rotateRightBtn=null;
};
b.Rotate.prototype={initialize:function(){b.Rotate.callBaseMethod(this,"initialize");
this._attachHandlers(true);
},dispose:function(){this._attachHandlers(false);
b.Rotate.callBaseMethod(this,"dispose");
},get_ddlDegrees:function(){if(!this._ddlDegrees){this._ddlDegrees=$find(this.get_parentId()+"DdlDegrees");
}return this._ddlDegrees;
},get_rotateLeftBtn:function(){if(!this._rotateLeftBtn){this._rotateLeftBtn=$find(this.get_parentId()+"RotateLeft");
}return this._rotateLeftBtn;
},get_rotateRightBtn:function(){if(!this._rotateRightBtn){this._rotateRightBtn=$find(this.get_parentId()+"RotateRight");
}return this._rotateRightBtn;
},_attachHandlers:function(d){var e=this.get_rotateLeftBtn();
var f=this.get_rotateRightBtn();
var g=this.get_ddlDegrees();
if(d){this._btnClickDelegate=Function.createDelegate(this,this._btnClick);
if(e&&f){f.add_clicked(this._btnClickDelegate);
e.add_clicked(this._btnClickDelegate);
}if(g){this._degreeChangedDelegate=Function.createDelegate(this,this._degreeChanged);
g.add_selectedIndexChanged(this._degreeChangedDelegate);
}}else{if(e&&f){f.remove_clicked(this._btnClickDelegate);
e.remove_clicked(this._btnClickDelegate);
}this._btnClickDelegate=null;
if(g){g.remove_selectedIndexChanged(this._degreeChangedDelegate);
this._degreeChangedDelegate=null;
}}},_btnClick:function(e,d){var f=this.get_imageEditor();
if(d.get_commandName()=="RotateRight"){f.rotateRight90();
}else{f.rotateLeft90();
}},_degreeChanged:function(d,e){if(!this._alreadyRotated){this.get_imageEditor()._rotateImage(null,true,false,parseInt(e.get_item().get_value()));
}},get_name:function(){return"Rotate";
},updateUI:function(){var e=this.get_imageEditor().get_toolsPanel();
if(e.get_width()!=170){e.set_width(170);
e.repaint();
}var f=this.get_imageEditor().getEditableImage();
var g=parseInt(f?(f.get_rotationAngle()/90):0);
var d=this.get_ddlDegrees();
this._alreadyRotated=true;
d.get_items()._array[g].select();
this._alreadyRotated=false;
}};
b.Rotate.registerClass("Telerik.Web.UI.ImageEditor.Rotate",b.ToolWidget,b.IToolWidget);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.ImageEditor);
