Type.registerNamespace("Telerik.Web.UI.ImageEditor");
(function(c,a,b){b.Zoom=function(d){b.Zoom.initializeBase(this,[d]);
this._actualSizeBtn=null;
this._fitImageBtn=null;
this._zoomSlider=null;
};
b.Zoom.prototype={initialize:function(){b.Zoom.callBaseMethod(this,"initialize");
this._attachHandlers(true);
this.get_imageEditor().get_formDecorator().decorate(this.get_textBox().parentNode);
var d=this;
window.setTimeout(function(){d.get_zoomSlider().repaint();
},0);
},dispose:function(){this._attachHandlers(false);
b.Zoom.callBaseMethod(this,"dispose");
},zoom:function(d){var e=this.get_imageEditor();
e._zoomImage(d);
},get_textBox:function(){if(!this._textBox){this._textBox=$get(this.get_parentId()+"TxtZoom");
if(this._textBox){this._textBox.setAttribute("autoComplete","off");
}}return this._textBox;
},get_actualSizeBtn:function(){if(!this._actualSizeBtn){this._actualSizeBtn=$find(this.get_parentId()+"btnActualSize");
}return this._actualSizeBtn;
},get_fitImageBtn:function(){if(!this._fitImageBtn){this._fitImageBtn=$find(this.get_parentId()+"btnFitImage");
}return this._fitImageBtn;
},get_zoomSlider:function(){if(!this._zoomSlider){this._zoomSlider=$find(this.get_parentId()+"sliderZoom");
}return this._zoomSlider;
},get_max:function(){return 400;
},get_min:function(){return 25;
},_attachHandlers:function(d){var g=this.get_actualSizeBtn();
var f=this.get_fitImageBtn();
var h=this.get_zoomSlider();
var e=this.get_textBox();
if(d){this._buttonClickDelegate=Function.createDelegate(this,this._buttonClick);
if(g){g.add_clicked(this._buttonClickDelegate);
}if(f){f.add_clicked(this._buttonClickDelegate);
}if(h){this._valueChangedDelegate=Function.createDelegate(this,this._valueChanged);
h.add_valueChanged(this._valueChangedDelegate);
}if(e){this._textBoxKeyDownDelegate=Function.createDelegate(this,this._textBoxKeyDown);
$addHandler(e,"keydown",this._textBoxKeyDownDelegate);
}}else{if(g){g.remove_clicked(this._buttonClickDelegate);
}if(f){f.remove_clicked(this._buttonClickDelegate);
}this._buttonClickDelegate=null;
if(h){h.remove_valueChanged(this._valueChangedDelegate);
this._valueChangedDelegate=null;
}if(e){$removeHandler(e,"keydown",this._textBoxKeyDownDelegate);
this._textBoxKeyDownDelegate=null;
}}},_buttonClick:function(f,e){var d=this.get_zoomSlider();
if(e.get_commandName()=="ActualSize"){d.set_value(100);
}else{var g=this.get_imageEditor();
if(g){g.zoomBestFit();
}}},_valueChanged:function(d,e){this.zoom(d.get_value());
this.get_textBox().value=d.get_value();
},_textBoxKeyDown:function(f){var g=f.keyCode;
var h=this.get_textBox();
var e=this.get_zoomSlider();
if(g==38&&this.incrementValue(h,this.get_max())){e.set_value(h.value);
}else{if(g==40&&this.decrementValue(h,this.get_min())){e.set_value(h.value);
}}if(g==13){var d=this.checkValue(h,this.get_min(),this.get_max());
if(d===false){d=e.get_value();
}else{e.set_value(d);
}h.value=d;
$telerik.cancelRawEvent(f.rawEvent);
return false;
}if(g==27){$telerik.cancelRawEvent(f.rawEvent);
return false;
}},get_name:function(){return"Zoom";
},updateUI:function(){var g=this.get_imageEditor();
var e=g?g.getEditableImage():null;
var d=e?e.get_zoomLevel():100;
var f=this.get_zoomSlider();
f.set_value(d);
}};
b.Zoom.registerClass("Telerik.Web.UI.ImageEditor.Zoom",b.ToolWidget,b.IToolWidget);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.ImageEditor);
