Type.registerNamespace("Telerik.Web.UI.Scheduler");
(function(){var b=Telerik.Web.UI;
var e=Telerik.Web.UI.Scheduler;
var d=60000;
var a=d*60;
var f=a*24;
var c=5;
b.Scheduler.MultiDayModel=function(g){b.Scheduler.MultiDayModel.initializeBase(this,[g]);
this._settings=this._owner.get_multiDayViewSettings();
};
b.Scheduler.MultiDayModel.prototype={get_visibleRangeStart:function(){var h=this._owner;
var g=e.DateTime.getDate(h.get_selectedDate());
if(!h.get_showAllDayRow()){g=e.DateTime.add(g,this.get_effectiveDayStartTime());
}return g;
},get_visibleRangeEnd:function(){var h=this._owner;
var g=new e.DateTime(h.get_selectedDate()).get_date().add((this.get_numberOfDays()-1)*f).toDate();
if(!h.get_showAllDayRow()){g=e.DateTime.add(g,this.get_effectiveDayEndTime());
}else{g=e.DateTime.add(g,f);
}return g;
},get_numberOfDays:function(){return this._settings.numberOfDays||c;
},get_nextPeriodDate:function(){return e.DateTime.add(this._owner.get_selectedDate(),(this.get_numberOfDays()*f));
},get_previousPeriodDate:function(){return e.DateTime.add(this._owner.get_selectedDate(),-(this.get_numberOfDays()*f));
},_getFirstDayStart:function(){return new e.DateTime(this._owner.get_selectedDate()).get_date().add(this.get_effectiveDayStartTime()).toDate();
},_getTimeFromIndex:function(g){var i;
if(g.viewPartIndex==0){i=new e.DateTime(this._owner.get_selectedDate()).get_date().toDate();
}else{i=this._getFirstDayStart();
}var h=g.rowIndex*this._owner.get_minutesPerRow();
return new e.DateTime(i).add(g.cellIndex*f).add(h*d).toDate();
},_getRenderer:function(){if(!this._renderer){this._renderer=new b.Scheduler.Rendering.MultiDayViewRenderer(this);
}return this._renderer;
}};
b.Scheduler.MultiDayModel.registerClass("Telerik.Web.UI.Scheduler.MultiDayModel",b.Scheduler.WeekModel);
})();
