<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Companies.aspx.cs" Inherits="HRAnywhere.Server.Web.Admin.Companies" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" runat="server" LoadingPanelID="RadAjaxLoadingPanel1" >
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowAutomaticDeletes="True" 
    AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
    AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True" 
    AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" CellSpacing="0" 
    DataSourceID="SqlDataSource1" GridLines="None" ShowGroupPanel="True">
        <ClientSettings AllowDragToGroup="True">
        </ClientSettings>
<MasterTableView AutoGenerateColumns="False" DataKeyNames="CompanyId" 
            DataSourceID="SqlDataSource1" CommandItemDisplay="TopAndBottom">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column">
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="CompanyId" DataType="System.Int32" 
            FilterControlAltText="Filter CompanyId column" HeaderText="CompanyId" 
            ReadOnly="True" SortExpression="CompanyId" UniqueName="CompanyId">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="CompanyName" 
            FilterControlAltText="Filter CompanyName column" HeaderText="CompanyName" 
            SortExpression="CompanyName" UniqueName="CompanyName">
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
    <PagerStyle AlwaysVisible="True" />
</MasterTableView>

<FilterMenu EnableImageSprites="False">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</HeaderContextMenu>
    </telerik:RadGrid>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:HRAnywhereDbContext %>" 
    SelectCommand="SELECT * FROM [Companies]" 
        DeleteCommand="DELETE FROM [Companies] WHERE [CompanyId] = @CompanyId" 
        InsertCommand="INSERT INTO [Companies] ([CompanyName]) VALUES (@CompanyName)" 
        UpdateCommand="UPDATE [Companies] SET [CompanyName] = @CompanyName WHERE [CompanyId] = @CompanyId">
    <DeleteParameters>
        <asp:Parameter Name="CompanyId" Type="Int32" />
    </DeleteParameters>
    <InsertParameters>
        <asp:Parameter Name="CompanyName" Type="String" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="CompanyName" Type="String" />
        <asp:Parameter Name="CompanyId" Type="Int32" />
    </UpdateParameters>
    </asp:SqlDataSource>
    </telerik:RadAjaxPanel>
    <telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" Skin="Default">
    </telerik:RadAjaxLoadingPanel>
</asp:Content>
