<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Members.aspx.cs" Inherits="HRAnywhere.Server.Web.Admin.Members" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<telerik:RadAjaxPanel ID="RadAjaxPanel1" runat="server" LoadingPanelID="RadAjaxLoadingPanel1" >
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowFilteringByColumn="True" 
        AllowPaging="True" AllowSorting="True" CellSpacing="0" GridLines="None" 
        ShowGroupPanel="True" PageSize="50" DataSourceID="SqlDataSource1" 
        AllowAutomaticDeletes="True" AllowAutomaticInserts="True" 
        AllowAutomaticUpdates="True" AutoGenerateDeleteColumn="True" 
        AutoGenerateEditColumn="True">
        <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" 
            ReorderColumnsOnClient="True">
        </ClientSettings>
<MasterTableView DataSourceID="SqlDataSource1" AutoGenerateColumns="False" 
            DataKeyNames="MemberId" CommandItemDisplay="TopAndBottom">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column">
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="MemberId" DataType="System.Int32" 
            FilterControlAltText="Filter MemberId column" HeaderText="MemberId" 
            ReadOnly="True" SortExpression="MemberId" UniqueName="MemberId">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="CompanyId" 
            FilterControlAltText="Filter CompanyId column" HeaderText="CompanyId" 
            SortExpression="CompanyId" UniqueName="CompanyId" DataType="System.Int32">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="FirstName" 
            FilterControlAltText="Filter FirstName column" HeaderText="FirstName" 
            SortExpression="FirstName" UniqueName="FirstName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="LastName" 
            FilterControlAltText="Filter LastName column" HeaderText="LastName" 
            SortExpression="LastName" UniqueName="LastName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="UserName" 
            FilterControlAltText="Filter UserName column" HeaderText="UserName" 
            SortExpression="UserName" UniqueName="UserName">
        </telerik:GridBoundColumn>
        <telerik:GridCheckBoxColumn DataField="IsOnline" DataType="System.Boolean" 
            FilterControlAltText="Filter IsOnline column" HeaderText="IsOnline" 
            SortExpression="IsOnline" UniqueName="IsOnline">
        </telerik:GridCheckBoxColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
    <PagerStyle AlwaysVisible="True" />
</MasterTableView>

        <PagerStyle AlwaysVisible="True" />

<FilterMenu EnableImageSprites="False">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</HeaderContextMenu>
    </telerik:RadGrid>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:HRAnywhereDbContext %>" 
        
        SelectCommand="SELECT [MemberId], [CompanyId], [FirstName], [LastName], [UserName], [IsOnline] FROM [Members]" 
        DeleteCommand="DELETE FROM [Members] WHERE [MemberId] = @MemberId" 
        InsertCommand="INSERT INTO [Members] ([CompanyId], [FirstName], [LastName], [UserName], [IsOnline]) VALUES (@CompanyId, @FirstName, @LastName, @UserName, @IsOnline)" 
        UpdateCommand="UPDATE [Members] SET [CompanyId] = @CompanyId, [FirstName] = @FirstName, [LastName] = @LastName, [UserName] = @UserName, [IsOnline] = @IsOnline WHERE [MemberId] = @MemberId">
        <DeleteParameters>
            <asp:Parameter Name="MemberId" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="CompanyId" Type="Int32" />
            <asp:Parameter Name="FirstName" Type="String" />
            <asp:Parameter Name="LastName" Type="String" />
            <asp:Parameter Name="UserName" Type="String" />
            <asp:Parameter Name="IsOnline" Type="Boolean" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="CompanyId" Type="Int32" />
            <asp:Parameter Name="FirstName" Type="String" />
            <asp:Parameter Name="LastName" Type="String" />
            <asp:Parameter Name="UserName" Type="String" />
            <asp:Parameter Name="IsOnline" Type="Boolean" />
            <asp:Parameter Name="MemberId" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
        </telerik:RadAjaxPanel>
    <telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" Skin="Default">
    </telerik:RadAjaxLoadingPanel>
</asp:Content>
