if(!window.SyntaxHighlighter){var SyntaxHighlighter=function(){var a={defaults:{"class-name":"","first-line":1,"smart-tabs":true,"tab-size":4,gutter:true,collapse:false,"auto-links":true},config:{clipboardSwf:null,bloggerMode:false,stripBrs:false,tagName:"pre",strings:{expandSource:"expand source",viewSource:"view source",copyToClipboard:"copy to clipboard",copyToClipboardConfirmation:"The code is in your clipboard now",print:"print",help:"?",alert:"SyntaxHighlighter\n\n",noBrush:"Can't find brush for: ",brushNotHtmlScript:"Brush wasn't configured for html-script option: ",aboutDialog:'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>About SyntaxHighlighter</title></head><body style="font-family:Geneva,Arial,Helvetica,sans-serif;background-color:#fff;color:#000;font-size:1em;text-align:center;"><div style="text-align:center;margin-top:3em;"><div style="font-size:xx-large;">SyntaxHighlighter</div><div style="font-size:.75em;margin-bottom:4em;"><div>version 2.0.320 (May 03 2009)</div><div><a href="http://alexgorbatchev.com" target="_blank" style="color:#0099FF;text-decoration:none;">http://alexgorbatchev.com</a></div></div><div>JavaScript code syntax highlighter.</div><div>Copyright 2004-2009 Alex Gorbatchev.</div></div></body></html>'},debug:false},vars:{discoveredBrushes:null,spaceWidth:null,printFrame:null,highlighters:{}},brushes:{},regexLib:{multiLineCComments:/\/\*[\s\S]*?\*\//gm,singleLineCComments:/\/\/.*$/gm,singleLinePerlComments:/#.*$/gm,doubleQuotedString:/"(?:\.|(\\\")|[^\""\n])*"/g,singleQuotedString:/'(?:\.|(\\\')|[^\''\n])*'/g,multiLineDoubleQuotedString:/"(?:\.|(\\\")|[^\""])*"/g,multiLineSingleQuotedString:/'(?:\.|(\\\')|[^\''])*'/g,url:/\w+:\/\/[\w-.\/?%&=]*/g,phpScriptTags:{left:/(&lt;|<)\?=?/g,right:/\?(&gt;|>)/g},aspScriptTags:{left:/(&lt;|<)%=?/g,right:/%(&gt;|>)/g},scriptScriptTags:{left:/(&lt;|<)\s*script.*?(&gt;|>)/gi,right:/(&lt;|<)\/\s*script\s*(&gt;|>)/gi}},utils:{guid:function(b){return b+Math.round(Math.random()*1000000).toString();
},merge:function(d,b){var c={},e;
for(e in d){c[e]=d[e];
}for(e in b){c[e]=b[e];
}return c;
},toBoolean:function(b){switch(b){case"true":return true;
case"false":return false;
}return b;
},popup:function(g,h,f,b,d){var c=(screen.width-f)/2,e=(screen.height-b)/2;
d+=", left="+c+", top="+e+", width="+f+", height="+b;
d=d.replace(/^,/,"");
var i=window.open(g,h,d);
i.focus();
return i;
},addEvent:function(d,c,b){if(d.attachEvent){d["e"+c+b]=b;
d[c+b]=function(){d["e"+c+b](window.event);
};
d.attachEvent("on"+c,d[c+b]);
}else{d.addEventListener(c,b,false);
}},alert:function(b){alert(a.config.strings.alert+b);
},findBrush:function(d,e){var c=a.vars.discoveredBrushes,g=null;
if(c==null){c={};
for(var f in a.brushes){var h=a.brushes[f].aliases;
if(h==null){continue;
}for(var b=0;
b<h.length;
b++){c[h[b]]=f;
}}a.vars.discoveredBrushes=c;
}g=a.brushes[c[d]];
if(g==null&&e!=false){a.utils.alert(a.config.strings.noBrush+d);
}return g;
},eachLine:function(d,e){var b=d.split("\n");
for(var c=0;
c<b.length;
c++){b[c]=e(b[c]);
}return b.join("\n");
},trimFirstAndLastLines:function(b){return b.replace(/^[ ]*[\n]+|[\n]*[ ]*$/g,"");
},parseParams:function(g){var d,f={},b=new XRegExp("^\\[(?<values>(.*?))\\]$"),h=new XRegExp("(?<name>[\\w-]+)\\s*:\\s*(?<value>[\\w-%#]+|\\[.*?\\]|\".*?\"|'.*?')\\s*;?","g");
while((d=h.exec(g))!=null){var c=d.value.replace(/^['"]|['"]$/g,"");
if(c!=null&&b.test(c)){var e=b.exec(c);
c=e.values.length>0?e.values.split(/\s*,\s*/):[];
}f[d.name]=c;
}return f;
},decorate:function(b,c){if(b==null||b.length==0||b=="\n"){return b;
}b=b.replace(/</g,"&lt;");
b=b.replace(/ {2,}/g,function(e){var f="";
for(var d=0;
d<e.length-1;
d++){f+="&nbsp;";
}return f+" ";
});
if(c!=null){b=a.utils.eachLine(b,function(e){if(e.length==0){return"";
}var d="";
e=e.replace(/^(&nbsp;| )+/,function(f){d=f;
return"";
});
if(e.length==0){return d;
}return d+'<code style="'+getStyleFor(c)+'">'+e+"</code>";
});
}return b;
},padNumber:function(b,d){var c=b.toString();
while(c.length<d){c="0"+c;
}return c;
},measureSpace:function(){var j=document.createElement("div"),h,b=0,e=document.body,g=a.utils.guid("measureSpace"),f='<div style="',d="</div>",i="</span>";
j.innerHTML=f+'">'+f+getStyleFor("line")+'">'+f+getStyleFor("content")+'"><span style="'+getStyleFor("block")+'"><span id="'+g+'">&nbsp;'+i+i+d+d+d;
e.appendChild(j);
h=document.getElementById(g);
if(/opera/i.test(navigator.userAgent)){var c=window.getComputedStyle(h,null);
b=parseInt(c.getPropertyValue("width"));
}else{b=h.offsetWidth;
}e.removeChild(j);
return b;
},processTabs:function(c,e){var d="";
for(var b=0;
b<e;
b++){d+=" ";
}return c.replace(/\t/g,d);
},processSmartTabs:function(c,f){var h=c.split("\n"),d="\t",e="";
for(var b=0;
b<50;
b++){e+="                    ";
}function g(k,j,i){return k.substr(0,j)+e.substr(0,i)+k.substr(j+1,k.length);
}c=a.utils.eachLine(c,function(j){if(j.indexOf(d)==-1){return j;
}var i=0;
while((i=j.indexOf(d))!=-1){var k=f-i%f;
j=g(j,i,k);
}return j;
});
return c;
},fixInputString:function(b){var c=/<br\s*\/?>|&lt;br\s*\/?&gt;/gi;
if(a.config.bloggerMode==true){b=b.replace(c,"\n");
}if(a.config.stripBrs==true){b=b.replace(c,"");
}return b;
},trim:function(b){return b.replace(/\s*$/g,"").replace(/^\s*/,"");
},unindent:function(e){var f=a.utils.fixInputString(e).split("\n"),c=new Array(),h=/^\s*/,g=1000;
for(var b=0;
b<f.length&&g>0;
b++){var d=f[b];
if(a.utils.trim(d).length==0){continue;
}var j=h.exec(d);
if(j==null){return e;
}g=Math.min(j[0].length,g);
}if(g>0){for(var b=0;
b<f.length;
b++){f[b]=f[b].substr(g);
}}return f.join("\n");
},matchesSortCallback:function(b,c){if(b.index<c.index){return -1;
}else{if(b.index>c.index){return 1;
}else{if(b.length<c.length){return -1;
}else{if(b.length>c.length){return 1;
}}}}return 0;
},getMatches:function(b,f){function c(j,i){return[new a.Match(j[0],j.index,i.css)];
}var h=0,d=null,e=[],g=f.func?f.func:c;
while((d=f.regex.exec(b))!=null){e=e.concat(g(d,f));
}return e;
},processUrls:function(b){return b.replace(a.regexLib.url,function(c){return'<a href="'+c+'">'+c+"</a>";
});
}},highlight:function(c,b){function j(o){var p=[];
for(var q=0;
q<o.length;
q++){p.push(o[q]);
}return p;
}var n=b?[b]:j(document.getElementsByTagName(a.config.tagName)),l="innerHTML",e=null;
if(n.length===0){return;
}for(var d=0;
d<n.length;
d++){var g=n[d],k=a.utils.parseParams(g.className),f;
k=a.utils.merge(c,k);
f=k.brush;
if(f==null){continue;
}if(k["html-script"]=="true"){e=new a.HtmlScript(f);
}else{var h=a.utils.findBrush(f);
if(h){e=new h();
}else{continue;
}}e.highlight(g[l],k);
var m=e.div;
if(a.config.debug){m=document.createElement("textarea");
m.value=e.div.innerHTML;
m.style.width="70em";
m.style.height="30em";
}g.parentNode.replaceChild(m,g);
}},all:function(b){a.utils.addEvent(window,"load",function(){a.highlight(b);
});
}};
a.Match=function(b,d,c){this.value=b;
this.index=d;
this.length=b.length;
this.css=c;
};
a.Match.prototype.toString=function(){return this.value;
};
a.HtmlScript=function(c){var g=a.utils.findBrush(c),f=new a.brushes.Xml(),d=null;
if(g==null){return;
}g=new g();
this.xmlBrush=f;
if(g.htmlScript==null){a.utils.alert(a.config.strings.brushNotHtmlScript+c);
return;
}f.regexList.push({regex:g.htmlScript.code,func:b});
function e(h,k){for(var i=0;
i<h.length;
i++){h[i].index+=k;
}}function b(k,m){var j=k.code,l=[],o=g.regexList,n=k.index+k.left.length,p=g.htmlScript,q;
for(var h=0;
h<o.length;
h++){q=a.utils.getMatches(j,o[h]);
e(q,n);
l=l.concat(q);
}if(p.left!=null&&k.left!=null){q=a.utils.getMatches(k.left,p.left);
e(q,k.index);
l=l.concat(q);
}if(p.right!=null&&k.right!=null){q=a.utils.getMatches(k.right,p.right);
e(q,k.index+k[0].lastIndexOf(k.right));
l=l.concat(q);
}return l;
}};
a.HtmlScript.prototype.highlight=function(c,b){this.xmlBrush.highlight(c,b);
this.div=this.xmlBrush.div;
};
a.Highlighter=function(){};
a.Highlighter.prototype={getParam:function(d,c){var b=this.params[d];
return a.utils.toBoolean(b==null?c:b);
},create:function(b){return document.createElement(b);
},findMatches:function(b,d){var c=[];
if(b!=null){for(var e=0;
e<b.length;
e++){c=c.concat(a.utils.getMatches(d,b[e]));
}}c=c.sort(a.utils.matchesSortCallback);
return c;
},removeNestedMatches:function(){var f=this.matches;
for(var b=0;
b<f.length;
b++){if(f[b]===null){continue;
}var e=f[b],d=e.index+e.length;
for(var c=b+1;
c<f.length&&f[b]!==null;
c++){var g=f[c];
if(g===null){continue;
}else{if(g.index>d){break;
}else{if(g.index==e.index&&g.length>e.length){this.matches[b]=null;
}else{if(g.index>=e.index&&g.index<d){this.matches[c]=null;
}}}}}}},createDisplayLines:function(c){var j=c.split(/\n/g),f=parseInt(this.getParam("first-line")),l=(f+j.length).toString().length;
c="";
for(var b=0;
b<j.length;
b++){var e=j[b],h=/^(&nbsp;|\s)+/.exec(e),d="line alt"+(b%2==0?1:2),m=a.utils.padNumber(f+b,l),g=null;
if(h!=null){g=h[0].toString();
e=e.substr(g.length);
g=g.replace(/&nbsp;/g," ");
h=a.vars.spaceWidth*g.length;
}else{h=0;
}e=a.utils.trim(e);
if(e.length==0){e="&nbsp;";
}var k=this.getParam("gutter")!=false?'<code style="'+getStyleFor("number")+'">'+m+".</code>":"";
c+='<div style="'+getStyleFor(d)+'">'+k+'<span style="'+getStyleFor("content")+'">'+(g!=null?'<code style="'+getStyleFor("spaces")+'">'+g.replace(/\s/g,"&nbsp;")+"</code>":"")+'<span style="'+getStyleFor("block")+"margin-left: "+h+'px !important;">'+e+"</span></span></div>";
}return c;
},processMatches:function(c,f){var h=0,g="",d=a.utils.decorate;
for(var b=0;
b<f.length;
b++){var e=f[b];
if(e===null||e.length===0){continue;
}g+=d(c.substr(h,e.index-h),"plain")+d(e.value,e.css);
h=e.index+e.length;
}g+=d(c.substr(h),"plain");
return g;
},highlight:function(g,c){var h=a.config,b=a.vars,e,d,f,i="important";
this.params={};
this.div=null;
this.code=null;
this.bar=null;
this.id=a.utils.guid("highlighter_");
b.highlighters[this.id]=this;
if(g===null){g="";
}if(b.spaceWidth===null){b.spaceWidth=a.utils.measureSpace();
}this.params=a.utils.merge(a.defaults,c||{});
this.div=e=this.create("DIV");
className="syntaxhighlighter";
e.id=this.id;
if(this.getParam("collapse")){className+=" collapsed";
}if(this.getParam("gutter")==false){className+=" nogutter";
}className+=" "+this.getParam("class-name");
e.className=className;
this.originalCode=g;
this.code=a.utils.trimFirstAndLastLines(g).replace(/\r/g," ");
f=this.getParam("tab-size");
this.code=this.getParam("smart-tabs")==true?a.utils.processSmartTabs(this.code,f):a.utils.processTabs(this.code,f);
this.code=a.utils.unindent(this.code);
this.matches=this.findMatches(this.regexList,this.code);
this.removeNestedMatches();
g=this.processMatches(this.code,this.matches);
g=this.createDisplayLines(a.utils.trim(g));
if(this.getParam("auto-links")){g=a.utils.processUrls(g);
}e.innerHTML=g;
},getKeywords:function(b){b=b.replace(/^\s+|\s+$/g,"").replace(/\s+/g,"\\b|\\b");
return"\\b"+b+"\\b";
},forHtmlScript:function(b){this.htmlScript={left:{regex:b.left,css:"script"},right:{regex:b.right,css:"script"},code:new XRegExp("(?<left>"+b.left.source+")(?<code>.*?)(?<right>"+b.right.source+")","sgi")};
}};
return a;
}();
}if(!Array.indexOf){Array.prototype.indexOf=function(a,b){b=Math.max(b||0,0);
for(var c=b;
c<this.length;
c++){if(this[c]==a){return c;
}}return -1;
};
}if(!window.XRegExp){(function(){var e={exec:RegExp.prototype.exec,match:String.prototype.match,replace:String.prototype.replace,split:String.prototype.split},b={part:/(?:[^\\([#\s.]+|\\(?!k<[\w$]+>|[pP]{[^}]+})[\S\s]?|\((?=\?(?!#|<[\w$]+>)))+|(\()(?:\?(?:(#)[^)]*\)|<([$\w]+)>))?|\\(?:k<([\w$]+)>|[pP]{([^}]+)})|(\[\^?)|([\S\s])/g,replaceVar:/(?:[^$]+|\$(?![1-9$&`']|{[$\w]+}))+|\$(?:([1-9]\d*|[$&`'])|{([$\w]+)})/g,extended:/^(?:\s+|#.*)+/,quantifier:/^(?:[?*+]|{\d+(?:,\d*)?})/,classLeft:/&&\[\^?/g,classRight:/]/g},d=function(f,j,h){for(var g=h||0;
g<f.length;
g++){if(f[g]===j){return g;
}}return -1;
},a=/()??/.exec("")[1]!==undefined,c={};
XRegExp=function(p,f){if(p instanceof RegExp){if(f!==undefined){throw TypeError("can't supply flags when constructing one RegExp from another");
}return p.addFlags();
}var f=f||"",k=f.indexOf("s")>-1,l=f.indexOf("x")>-1,q=false,o=[],i=[],g=b.part,n,m,h,j,r;
g.lastIndex=0;
while(n=e.exec.call(g,p)){if(n[2]){if(!b.quantifier.test(p.slice(g.lastIndex))){i.push("(?:)");
}}else{if(n[1]){o.push(n[3]||null);
if(n[3]){q=true;
}i.push("(");
}else{if(n[4]){j=d(o,n[4]);
i.push(j>-1?"\\"+(j+1)+(isNaN(p.charAt(g.lastIndex))?"":"(?:)"):n[0]);
}else{if(n[5]){i.push(c.unicode?c.unicode.get(n[5],n[0].charAt(1)==="P"):n[0]);
}else{if(n[6]){if(p.charAt(g.lastIndex)==="]"){i.push(n[6]==="["?"(?!)":"[\\S\\s]");
g.lastIndex++;
}else{m=XRegExp.matchRecursive("&&"+p.slice(n.index),b.classLeft,b.classRight,"",{escapeChar:"\\"})[0];
i.push(n[6]+m+"]");
g.lastIndex+=m.length+1;
}}else{if(n[7]){if(k&&n[7]==="."){i.push("[\\S\\s]");
}else{if(l&&b.extended.test(n[7])){h=e.exec.call(b.extended,p.slice(g.lastIndex-1))[0].length;
if(!b.quantifier.test(p.slice(g.lastIndex-1+h))){i.push("(?:)");
}g.lastIndex+=h-1;
}else{i.push(n[7]);
}}}else{i.push(n[0]);
}}}}}}}r=RegExp(i.join(""),e.replace.call(f,/[sx]+/g,""));
r._x={source:p,captureNames:q?o:null};
return r;
};
XRegExp.addPlugin=function(f,g){c[f]=g;
};
RegExp.prototype.exec=function(h){var k=e.exec.call(this,h),j,f,g;
if(k){if(a&&k.length>1){g=new RegExp("^"+this.source+"$(?!\\s)",this.getNativeFlags());
e.replace.call(k[0],g,function(){for(f=1;
f<arguments.length-2;
f++){if(arguments[f]===undefined){k[f]=undefined;
}}});
}if(this._x&&this._x.captureNames){for(f=1;
f<k.length;
f++){j=this._x.captureNames[f-1];
if(j){k[j]=k[f];
}}}if(this.global&&this.lastIndex>(k.index+k[0].length)){this.lastIndex--;
}}return k;
};
})();
}RegExp.prototype.getNativeFlags=function(){return(this.global?"g":"")+(this.ignoreCase?"i":"")+(this.multiline?"m":"")+(this.extended?"x":"")+(this.sticky?"y":"");
};
RegExp.prototype.addFlags=function(a){var b=new XRegExp(this.source,(a||"")+this.getNativeFlags());
if(this._x){b._x={source:this._x.source,captureNames:this._x.captureNames?this._x.captureNames.slice(0):null};
}return b;
};
RegExp.prototype.call=function(b,a){return this.exec(a);
};
RegExp.prototype.apply=function(a,b){return this.exec(b[0]);
};
XRegExp.cache=function(b,c){var a="/"+b+"/"+(c||"");
return XRegExp.cache[a]||(XRegExp.cache[a]=new XRegExp(b,c));
};
XRegExp.escape=function(a){return a.replace(/[-[\]{}()*+?.\\^$|,#\s]/g,"\\$&");
};
XRegExp.matchRecursive=function(h,i,u,b,r){var r=r||{},l=r.escapeChar,k=r.valueNames,b=b||"",a=b.indexOf("g")>-1,c=b.indexOf("i")>-1,s=b.indexOf("m")>-1,o=b.indexOf("y")>-1,b=b.replace(/y/g,""),i=i instanceof RegExp?(i.global?i:i.addFlags("g")):new XRegExp(i,"g"+b),u=u instanceof RegExp?(u.global?u:u.addFlags("g")):new XRegExp(u,"g"+b),j=[],e=0,q=0,p=0,v=0,g,m,t,f,n,d;
if(l){if(l.length>1){throw SyntaxError("can't supply more than one escape character");
}if(s){throw TypeError("can't supply escape character when using the multiline flag");
}n=XRegExp.escape(l);
d=new RegExp("^(?:"+n+"[\\S\\s]|(?:(?!"+i.source+"|"+u.source+")[^"+n+"])+)+",c?"i":"");
}while(true){i.lastIndex=u.lastIndex=p+(l?(d.exec(h.slice(p))||[""])[0].length:0);
t=i.exec(h);
f=u.exec(h);
if(t&&f){if(t.index<=f.index){f=null;
}else{t=null;
}}if(t||f){q=(t||f).index;
p=(t?i:u).lastIndex;
}else{if(!e){break;
}}if(o&&!e&&q>v){break;
}if(t){if(!e++){g=q;
m=p;
}}else{if(f&&e){if(!--e){if(k){if(k[0]&&g>v){j.push([k[0],h.slice(v,g),v,g]);
}if(k[1]){j.push([k[1],h.slice(g,m),g,m]);
}if(k[2]){j.push([k[2],h.slice(m,q),m,q]);
}if(k[3]){j.push([k[3],h.slice(q,p),q,p]);
}}else{j.push(h.slice(m,q));
}v=p;
if(!a){break;
}}}else{i.lastIndex=u.lastIndex=0;
throw Error("subject data contains unbalanced delimiters");
}}if(q===p){p++;
}}if(a&&!o&&k&&k[0]&&h.length>v){j.push([k[0],h.slice(v),v,h.length]);
}i.lastIndex=u.lastIndex=0;
return j;
};
SyntaxHighlighter.brushes.AS3=function(){var b="class interface function package";
var a="-Infinity ...rest Array as AS3 Boolean break case catch const continue Date decodeURI decodeURIComponent default delete do dynamic each else encodeURI encodeURIComponent escape extends false final finally flash_proxy for get if implements import in include Infinity instanceof int internal is isFinite isNaN isXMLName label namespace NaN native new null Null Number Object object_proxy override parseFloat parseInt private protected public return set static String super switch this throw true try typeof uint undefined unescape use void while with";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/\b([\d]+(\.[\d]+)?|0x[a-f0-9]+)\b/gi,css:"value"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"color3"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"keyword"},{regex:new RegExp("var","gm"),css:"variable"},{regex:new RegExp("trace","gm"),css:"color1"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.scriptScriptTags);
};
SyntaxHighlighter.brushes.AS3.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.AS3.aliases=["actionscript3","as3"];
SyntaxHighlighter.brushes.Bash=function(){var a="if fi then elif else for do done until while break continue case function return in eq ne gt lt ge le";
var b="alias apropos awk bash bc bg builtin bzip2 cal cat cd cfdisk chgrp chmod chown chrootcksum clear cmp comm command cp cron crontab csplit cut date dc dd ddrescue declare df diff diff3 dig dir dircolors dirname dirs du echo egrep eject enable env ethtool eval exec exit expand export expr false fdformat fdisk fg fgrep file find fmt fold format free fsck ftp gawk getopts grep groups gzip hash head history hostname id ifconfig import install join kill less let ln local locate logname logout look lpc lpr lprint lprintd lprintq lprm ls lsof make man mkdir mkfifo mkisofs mknod more mount mtools mv netstat nice nl nohup nslookup open op passwd paste pathchk ping popd pr printcap printenv printf ps pushd pwd quota quotacheck quotactl ram rcp read readonly renice remsync rm rmdir rsync screen scp sdiff sed select seq set sftp shift shopt shutdown sleep sort source split ssh strace su sudo sum symlink sync tail tar tee test time times touch top traceroute trap tr true tsort tty type ulimit umask umount unalias uname unexpand uniq units unset unshar useradd usermod users uuencode uudecode v vdir vi watch wc whereis which who whoami Wget xargs yes";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLinePerlComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"keyword"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"functions"}];
};
SyntaxHighlighter.brushes.Bash.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Bash.aliases=["bash","shell"];
SyntaxHighlighter.brushes.Cpp=function(){var a="ATOM BOOL BOOLEAN BYTE CHAR COLORREF DWORD DWORDLONG DWORD_PTR DWORD32 DWORD64 FLOAT HACCEL HALF_PTR HANDLE HBITMAP HBRUSH HCOLORSPACE HCONV HCONVLIST HCURSOR HDC HDDEDATA HDESK HDROP HDWP HENHMETAFILE HFILE HFONT HGDIOBJ HGLOBAL HHOOK HICON HINSTANCE HKEY HKL HLOCAL HMENU HMETAFILE HMODULE HMONITOR HPALETTE HPEN HRESULT HRGN HRSRC HSZ HWINSTA HWND INT INT_PTR INT32 INT64 LANGID LCID LCTYPE LGRPID LONG LONGLONG LONG_PTR LONG32 LONG64 LPARAM LPBOOL LPBYTE LPCOLORREF LPCSTR LPCTSTR LPCVOID LPCWSTR LPDWORD LPHANDLE LPINT LPLONG LPSTR LPTSTR LPVOID LPWORD LPWSTR LRESULT PBOOL PBOOLEAN PBYTE PCHAR PCSTR PCTSTR PCWSTR PDWORDLONG PDWORD_PTR PDWORD32 PDWORD64 PFLOAT PHALF_PTR PHANDLE PHKEY PINT PINT_PTR PINT32 PINT64 PLCID PLONG PLONGLONG PLONG_PTR PLONG32 PLONG64 POINTER_32 POINTER_64 PSHORT PSIZE_T PSSIZE_T PSTR PTBYTE PTCHAR PTSTR PUCHAR PUHALF_PTR PUINT PUINT_PTR PUINT32 PUINT64 PULONG PULONGLONG PULONG_PTR PULONG32 PULONG64 PUSHORT PVOID PWCHAR PWORD PWSTR SC_HANDLE SC_LOCK SERVICE_STATUS_HANDLE SHORT SIZE_T SSIZE_T TBYTE TCHAR UCHAR UHALF_PTR UINT UINT_PTR UINT32 UINT64 ULONG ULONGLONG ULONG_PTR ULONG32 ULONG64 USHORT USN VOID WCHAR WORD WPARAM WPARAM WPARAM char bool short int __int32 __int64 __int8 __int16 long float double __wchar_t clock_t _complex _dev_t _diskfree_t div_t ldiv_t _exception _EXCEPTION_POINTERS FILE _finddata_t _finddatai64_t _wfinddata_t _wfinddatai64_t __finddata64_t __wfinddata64_t _FPIEEE_RECORD fpos_t _HEAPINFO _HFILE lconv intptr_t jmp_buf mbstate_t _off_t _onexit_t _PNH ptrdiff_t _purecall_handler sig_atomic_t size_t _stat __stat64 _stati64 terminate_function time_t __time64_t _timeb __timeb64 tm uintptr_t _utimbuf va_list wchar_t wctrans_t wctype_t wint_t signed";
var b="break case catch class const __finally __exception __try const_cast continue private public protected __declspec default delete deprecated dllexport dllimport do dynamic_cast else enum explicit extern if for friend goto inline mutable naked namespace new noinline noreturn nothrow register reinterpret_cast return selectany sizeof static static_cast struct switch template this thread throw true false try typedef typeid typename union using uuid virtual void volatile whcar_t while";
var c="assert isalnum isalpha iscntrl isdigit isgraph islower isprintispunct isspace isupper isxdigit tolower toupper errno localeconv setlocale acos asin atan atan2 ceil cos cosh exp fabs floor fmod frexp ldexp log log10 modf pow sin sinh sqrt tan tanh jmp_buf longjmp setjmp raise signal sig_atomic_t va_arg va_end va_start clearerr fclose feof ferror fflush fgetc fgetpos fgets fopen fprintf fputc fputs fread freopen fscanf fseek fsetpos ftell fwrite getc getchar gets perror printf putc putchar puts remove rename rewind scanf setbuf setvbuf sprintf sscanf tmpfile tmpnam ungetc vfprintf vprintf vsprintf abort abs atexit atof atoi atol bsearch calloc div exit free getenv labs ldiv malloc mblen mbstowcs mbtowc qsort rand realloc srand strtod strtol strtoul system wcstombs wctomb memchr memcmp memcpy memmove memset strcat strchr strcmp strcoll strcpy strcspn strerror strlen strncat strncmp strncpy strpbrk strrchr strspn strstr strtok strxfrm asctime clock ctime difftime gmtime localtime mktime strftime time";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/^ *#.*/gm,css:"preprocessor"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"color1 bold"},{regex:new RegExp(this.getKeywords(c),"gm"),css:"functions bold"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"keyword bold"}];
};
SyntaxHighlighter.brushes.Cpp.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Cpp.aliases=["cpp","c"];
SyntaxHighlighter.brushes.CSharp=function(){var b="abstract as base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach get goto if implicit in int interface internal is lock long namespace new null object operator out override params partial private protected public readonly ref return sbyte sealed set short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using virtual void while";
function a(e,c){var d=(e[0].indexOf("///")==0)?"color1":"comments";
return[new SyntaxHighlighter.Match(e[0],e.index,d)];
}this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,func:a},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/^\s*#.*/gm,css:"preprocessor"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"keyword"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.aspScriptTags);
};
SyntaxHighlighter.brushes.CSharp.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.CSharp.aliases=["c#","c-sharp","csharp","cs"];
SyntaxHighlighter.brushes.CSS=function(){function c(f){return"\\b([a-z_]|)"+f.replace(/ /g,"(?=:)\\b|\\b([a-z_\\*]|\\*|)")+"(?=:)\\b";
}function d(f){return"\\b"+f.replace(/ /g,"(?!-)(?!:)\\b|\\b()")+":\\b";
}var b="ascent azimuth background-attachment background-color background-image background-position background-repeat background baseline bbox border-collapse border-color border-spacing border-style border-top border-right border-bottom border-left border-top-color border-right-color border-bottom-color border-left-color border-top-style border-right-style border-bottom-style border-left-style border-top-width border-right-width border-bottom-width border-left-width border-width border bottom cap-height caption-side centerline clear clip color content counter-increment counter-reset cue-after cue-before cue cursor definition-src descent direction display elevation empty-cells float font-size-adjust font-family font-size font-stretch font-style font-variant font-weight font height left letter-spacing line-height list-style-image list-style-position list-style-type list-style margin-top margin-right margin-bottom margin-left margin marker-offset marks mathline max-height max-width min-height min-width orphans outline-color outline-style outline-width outline overflow padding-top padding-right padding-bottom padding-left padding page page-break-after page-break-before page-break-inside pause pause-after pause-before pitch pitch-range play-during position quotes right richness size slope src speak-header speak-numeral speak-punctuation speak speech-rate stemh stemv stress table-layout text-align top text-decoration text-indent text-shadow text-transform unicode-bidi unicode-range units-per-em vertical-align visibility voice-family volume white-space widows width widths word-spacing x-height z-index";
var e="above absolute all always aqua armenian attr aural auto avoid baseline behind below bidi-override black blink block blue bold bolder both bottom braille capitalize caption center center-left center-right circle close-quote code collapse compact condensed continuous counter counters crop cross crosshair cursive dashed decimal decimal-leading-zero default digits disc dotted double embed embossed e-resize expanded extra-condensed extra-expanded fantasy far-left far-right fast faster fixed format fuchsia gray green groove handheld hebrew help hidden hide high higher icon inline-table inline inset inside invert italic justify landscape large larger left-side left leftwards level lighter lime line-through list-item local loud lower-alpha lowercase lower-greek lower-latin lower-roman lower low ltr marker maroon medium message-box middle mix move narrower navy ne-resize no-close-quote none no-open-quote no-repeat normal nowrap n-resize nw-resize oblique olive once open-quote outset outside overline pointer portrait pre print projection purple red relative repeat repeat-x repeat-y rgb ridge right right-side rightwards rtl run-in screen scroll semi-condensed semi-expanded separate se-resize show silent silver slower slow small small-caps small-caption smaller soft solid speech spell-out square s-resize static status-bar sub super sw-resize table-caption table-cell table-column table-column-group table-footer-group table-header-group table-row table-row-group teal text-bottom text-top thick thin top transparent tty tv ultra-condensed ultra-expanded underline upper-alpha uppercase upper-latin upper-roman url visible wait white wider w-resize x-fast x-high x-large x-loud x-low x-slow x-small x-soft xx-large xx-small yellow";
var a="[mM]onospace [tT]ahoma [vV]erdana [aA]rial [hH]elvetica [sS]ans-serif [sS]erif [cC]ourier mono sans serif";
this.regexList=[{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/\#[a-fA-F0-9]{3,6}/g,css:"value"},{regex:/(-?\d+)(\.\d+)?(px|em|pt|\:|\%|)/g,css:"value"},{regex:/!important/g,css:"color3"},{regex:new RegExp(c(b),"gm"),css:"keyword"},{regex:new RegExp(d(e),"g"),css:"value"},{regex:new RegExp(this.getKeywords(a),"g"),css:"color1"}];
this.forHtmlScript({left:/(&lt;|<)\s*style.*?(&gt;|>)/gi,right:/(&lt;|<)\/\s*style\s*(&gt;|>)/gi});
};
SyntaxHighlighter.brushes.CSS.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.CSS.aliases=["css"];
SyntaxHighlighter.brushes.Delphi=function(){var a="abs addr and ansichar ansistring array as asm begin boolean byte cardinal case char class comp const constructor currency destructor div do double downto else end except exports extended false file finalization finally for function goto if implementation in inherited int64 initialization integer interface is label library longint longword mod nil not object of on or packed pansichar pansistring pchar pcurrency pdatetime pextended pint64 pointer private procedure program property pshortstring pstring pvariant pwidechar pwidestring protected public published raise real real48 record repeat set shl shortint shortstring shr single smallint string then threadvar to true try type unit until uses val var varirnt while widechar widestring with word write writeln xor";
this.regexList=[{regex:/\(\*[\s\S]*?\*\)/gm,css:"comments"},{regex:/{(?!\$)[\s\S]*?}/gm,css:"comments"},{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/\{\$[a-zA-Z]+ .+\}/g,css:"color1"},{regex:/\b[\d\.]+\b/g,css:"value"},{regex:/\$[a-zA-Z0-9]+\b/g,css:"value"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"keyword"}];
};
SyntaxHighlighter.brushes.Delphi.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Delphi.aliases=["delphi","pascal"];
SyntaxHighlighter.brushes.Diff=function(){this.regexList=[{regex:/^\+\+\+.*$/gm,css:"color2"},{regex:/^\-\-\-.*$/gm,css:"color2"},{regex:/^\s.*$/gm,css:"color1"},{regex:/^@@.*@@$/gm,css:"variable"},{regex:/^\+[^\+]{1}.*$/gm,css:"string"},{regex:/^\-[^\-]{1}.*$/gm,css:"comments"}];
};
SyntaxHighlighter.brushes.Diff.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Diff.aliases=["diff","patch"];
SyntaxHighlighter.brushes.Groovy=function(){var c="as assert break case catch class continue def default do else extends finally if in implements import instanceof interface new package property return switch throw throws try while public protected private static";
var b="void boolean byte char short int long float double";
var d="null";
var a="allProperties count get size collect each eachProperty eachPropertyName eachWithIndex find findAll findIndexOf grep inject max min reverseEach sort asImmutable asSynchronized flatten intersect join pop reverse subMap toList padRight padLeft contains eachMatch toCharacter toLong toUrl tokenize eachFile eachFileRecurse eachB yte eachLine readBytes readLine getText splitEachLine withReader append encodeBase64 decodeBase64 filterLine transformChar transformLine withOutputStream withPrintWriter withStream withStreams withWriter withWriterAppend write writeLine dump inspect invokeMethod print println step times upto use waitForOrKill getText";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/""".*"""/g,css:"string"},{regex:new RegExp("\\b([\\d]+(\\.[\\d]+)?|0x[a-f0-9]+)\\b","gi"),css:"value"},{regex:new RegExp(this.getKeywords(c),"gm"),css:"keyword"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"color1"},{regex:new RegExp(this.getKeywords(d),"gm"),css:"constants"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"functions"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.aspScriptTags);
};
SyntaxHighlighter.brushes.Groovy.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Groovy.aliases=["groovy"];
SyntaxHighlighter.brushes.Java=function(){var a="abstract assert boolean break byte case catch char class const continue default do double else enum extends false final finally float for goto if implements import instanceof int interface long native new null package private protected public return short static strictfp super switch synchronized this throw throws true transient try void volatile while";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/\b([\d]+(\.[\d]+)?|0x[a-f0-9]+)\b/gi,css:"value"},{regex:/(?!\@interface\b)\@[\$\w]+\b/g,css:"color1"},{regex:/\@interface\b/g,css:"color2"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"keyword"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.aspScriptTags);
};
SyntaxHighlighter.brushes.Java.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Java.aliases=["java"];
SyntaxHighlighter.brushes.JavaFX=function(){var a="Boolean Byte Character Double Duration Float Integer Long Number Short String Void";
var b="abstract after and as assert at before bind bound break catch class continue def delete else exclusive extends false finally first for from function if import in indexof init insert instanceof into inverse last lazy mixin mod nativearray new not null on or override package postinit protected public public-init public-read replace return reverse sizeof step super then this throw true try tween typeof var where while with attribute let private readonly static trigger";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:/(-?\.?)(\b(\d*\.?\d+|\d+\.?\d*)(e[+-]?\d+)?|0x[a-f\d]+)\b\.?/gi,css:"color2"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"variable"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"keyword"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.aspScriptTags);
};
SyntaxHighlighter.brushes.JavaFX.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.JavaFX.aliases=["jfx","javafx"];
SyntaxHighlighter.brushes.JScript=function(){var a="break case catch continue default delete do else false  for function if in instanceof new null return super switch this throw true try typeof var while with";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/\s*#.*/gm,css:"preprocessor"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"keyword"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.scriptScriptTags);
};
SyntaxHighlighter.brushes.JScript.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.JScript.aliases=["js","jscript","javascript"];
SyntaxHighlighter.brushes.Perl=function(){var a="abs accept alarm atan2 bind binmode chdir chmod chomp chop chown chr chroot close closedir connect cos crypt defined delete each endgrent endhostent endnetent endprotoent endpwent endservent eof exec exists exp fcntl fileno flock fork format formline getc getgrent getgrgid getgrnam gethostbyaddr gethostbyname gethostent getlogin getnetbyaddr getnetbyname getnetent getpeername getpgrp getppid getpriority getprotobyname getprotobynumber getprotoent getpwent getpwnam getpwuid getservbyname getservbyport getservent getsockname getsockopt glob gmtime grep hex index int ioctl join keys kill lc lcfirst length link listen localtime lock log lstat map mkdir msgctl msgget msgrcv msgsnd oct open opendir ord pack pipe pop pos print printf prototype push quotemeta rand read readdir readline readlink readpipe recv rename reset reverse rewinddir rindex rmdir scalar seek seekdir select semctl semget semop send setgrent sethostent setnetent setpgrp setpriority setprotoent setpwent setservent setsockopt shift shmctl shmget shmread shmwrite shutdown sin sleep socket socketpair sort splice split sprintf sqrt srand stat study substr symlink syscall sysopen sysread sysseek system syswrite tell telldir time times tr truncate uc ucfirst umask undef unlink unpack unshift utime values vec wait waitpid warn write";
var b="bless caller continue dbmclose dbmopen die do dump else elsif eval exit for foreach goto if import last local my next no our package redo ref require return sub tie tied unless untie until use wantarray while";
this.regexList=[{regex:new RegExp("#[^!].*$","gm"),css:"comments"},{regex:new RegExp("^\\s*#!.*$","gm"),css:"preprocessor"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:new RegExp("(\\$|@|%)\\w+","g"),css:"variable"},{regex:new RegExp(this.getKeywords(a),"gmi"),css:"functions"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"keyword"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.phpScriptTags);
};
SyntaxHighlighter.brushes.Perl.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Perl.aliases=["perl","Perl","pl"];
SyntaxHighlighter.brushes.Php=function(){var c="abs acos acosh addcslashes addslashes array_change_key_case array_chunk array_combine array_count_values array_diff array_diff_assoc array_diff_key array_diff_uassoc array_diff_ukey array_fill array_filter array_flip array_intersect array_intersect_assoc array_intersect_key array_intersect_uassoc array_intersect_ukey array_key_exists array_keys array_map array_merge array_merge_recursive array_multisort array_pad array_pop array_product array_push array_rand array_reduce array_reverse array_search array_shift array_slice array_splice array_sum array_udiff array_udiff_assoc array_udiff_uassoc array_uintersect array_uintersect_assoc array_uintersect_uassoc array_unique array_unshift array_values array_walk array_walk_recursive atan atan2 atanh base64_decode base64_encode base_convert basename bcadd bccomp bcdiv bcmod bcmul bindec bindtextdomain bzclose bzcompress bzdecompress bzerrno bzerror bzerrstr bzflush bzopen bzread bzwrite ceil chdir checkdate checkdnsrr chgrp chmod chop chown chr chroot chunk_split class_exists closedir closelog copy cos cosh count count_chars date decbin dechex decoct deg2rad delete ebcdic2ascii echo empty end ereg ereg_replace eregi eregi_replace error_log error_reporting escapeshellarg escapeshellcmd eval exec exit exp explode extension_loaded feof fflush fgetc fgetcsv fgets fgetss file_exists file_get_contents file_put_contents fileatime filectime filegroup fileinode filemtime fileowner fileperms filesize filetype floatval flock floor flush fmod fnmatch fopen fpassthru fprintf fputcsv fputs fread fscanf fseek fsockopen fstat ftell ftok getallheaders getcwd getdate getenv gethostbyaddr gethostbyname gethostbynamel getimagesize getlastmod getmxrr getmygid getmyinode getmypid getmyuid getopt getprotobyname getprotobynumber getrandmax getrusage getservbyname getservbyport gettext gettimeofday gettype glob gmdate gmmktime ini_alter ini_get ini_get_all ini_restore ini_set interface_exists intval ip2long is_a is_array is_bool is_callable is_dir is_double is_executable is_file is_finite is_float is_infinite is_int is_integer is_link is_long is_nan is_null is_numeric is_object is_readable is_real is_resource is_scalar is_soap_fault is_string is_subclass_of is_uploaded_file is_writable is_writeable mkdir mktime nl2br parse_ini_file parse_str parse_url passthru pathinfo readlink realpath rewind rewinddir rmdir round str_ireplace str_pad str_repeat str_replace str_rot13 str_shuffle str_split str_word_count strcasecmp strchr strcmp strcoll strcspn strftime strip_tags stripcslashes stripos stripslashes stristr strlen strnatcasecmp strnatcmp strncasecmp strncmp strpbrk strpos strptime strrchr strrev strripos strrpos strspn strstr strtok strtolower strtotime strtoupper strtr strval substr substr_compare";
var a="and or xor array as break case cfunction class const continue declare default die do else elseif enddeclare endfor endforeach endif endswitch endwhile extends for foreach function include include_once global if new old_function return static switch use require require_once var while abstract interface public implements extends private protected throw";
var b="__FILE__ __LINE__ __METHOD__ __FUNCTION__ __CLASS__";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/\$\w+/g,css:"variable"},{regex:new RegExp(this.getKeywords(c),"gmi"),css:"functions"},{regex:new RegExp(this.getKeywords(b),"gmi"),css:"constants"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"keyword"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.phpScriptTags);
};
SyntaxHighlighter.brushes.Php.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Php.aliases=["php"];
SyntaxHighlighter.brushes.Plain=function(){};
SyntaxHighlighter.brushes.Plain.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Plain.aliases=["text","plain"];
SyntaxHighlighter.brushes.PowerShell=function(){var b="Add-Content Add-History Add-Member Add-PSSnapin Clear(-Content)? Clear-Item Clear-ItemProperty Clear-Variable Compare-Object ConvertFrom-SecureString Convert-Path ConvertTo-Html ConvertTo-SecureString Copy(-Item)? Copy-ItemProperty Export-Alias Export-Clixml Export-Console Export-Csv ForEach(-Object)? Format-Custom Format-List Format-Table Format-Wide Get-Acl Get-Alias Get-AuthenticodeSignature Get-ChildItem Get-Command Get-Content Get-Credential Get-Culture Get-Date Get-EventLog Get-ExecutionPolicy Get-Help Get-History Get-Host Get-Item Get-ItemProperty Get-Location Get-Member Get-PfxCertificate Get-Process Get-PSDrive Get-PSProvider Get-PSSnapin Get-Service Get-TraceSource Get-UICulture Get-Unique Get-Variable Get-WmiObject Group-Object Import-Alias Import-Clixml Import-Csv Invoke-Expression Invoke-History Invoke-Item Join-Path Measure-Command Measure-Object Move(-Item)? Move-ItemProperty New-Alias New-Item New-ItemProperty New-Object New-PSDrive New-Service New-TimeSpan New-Variable Out-Default Out-File Out-Host Out-Null Out-Printer Out-String Pop-Location Push-Location Read-Host Remove-Item Remove-ItemProperty Remove-PSDrive Remove-PSSnapin Remove-Variable Rename-Item Rename-ItemProperty Resolve-Path Restart-Service Resume-Service Select-Object Select-String Set-Acl Set-Alias Set-AuthenticodeSignature Set-Content Set-Date Set-ExecutionPolicy Set-Item Set-ItemProperty Set-Location Set-PSDebug Set-Service Set-TraceSource Set(-Variable)? Sort-Object Split-Path Start-Service Start-Sleep Start-Transcript Stop-Process Stop-Service Stop-Transcript Suspend-Service Tee-Object Test-Path Trace-Command Update-FormatData Update-TypeData Where(-Object)? Write-Debug Write-Error Write(-Host)? Write-Output Write-Progress Write-Verbose Write-Warning";
var a="ac asnp clc cli clp clv cpi cpp cvpa diff epal epcsv fc fl ft fw gal gc gci gcm gdr ghy gi gl gm gp gps group gsv gsnp gu gv gwmi iex ihy ii ipal ipcsv mi mp nal ndr ni nv oh rdr ri rni rnp rp rsnp rv rvpa sal sasv sc select si sl sleep sort sp spps spsv sv tee cat cd cp h history kill lp ls mount mv popd ps pushd pwd r rm rmdir echo cls chdir del dir erase rd ren type % \\?";
this.regexList=[{regex:/#.*$/gm,css:"comments"},{regex:/\$[a-zA-Z0-9]+\b/g,css:"value"},{regex:/\-[a-zA-Z]+\b/g,css:"keyword"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:new RegExp(this.getKeywords(b),"gmi"),css:"keyword"},{regex:new RegExp(this.getKeywords(a),"gmi"),css:"keyword"}];
};
SyntaxHighlighter.brushes.PowerShell.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.PowerShell.aliases=["powershell","ps"];
SyntaxHighlighter.brushes.Python=function(){var a="and assert break class continue def del elif else except exec finally for from global if import in is lambda not or pass print raise return try yield while";
var b="None True False self cls class_";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLinePerlComments,css:"comments"},{regex:/^\s*@\w+/gm,css:"decorator"},{regex:/(['\"]{3})([^\1])*?\1/gm,css:"comments"},{regex:/"(?!")(?:\.|\\\"|[^\""\n])*"/gm,css:"string"},{regex:/'(?!')(?:\.|(\\\')|[^\''\n])*'/gm,css:"string"},{regex:/\+|\-|\*|\/|\%|=|==/gm,css:"keyword"},{regex:/\b\d+\.?\w*/g,css:"value"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"keyword"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"color1"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.aspScriptTags);
};
SyntaxHighlighter.brushes.Python.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Python.aliases=["py","python"];
SyntaxHighlighter.brushes.Ruby=function(){var b="alias and BEGIN begin break case class def define_method defined do each else elsif END end ensure false for if in module new next nil not or raise redo rescue retry return self super then throw true undef unless until when while yield";
var a="Array Bignum Binding Class Continuation Dir Exception FalseClass File::Stat File Fixnum Fload Hash Integer IO MatchData Method Module NilClass Numeric Object Proc Range Regexp String Struct::TMS Symbol ThreadGroup Thread Time TrueClass";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLinePerlComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/\b[A-Z0-9_]+\b/g,css:"constants"},{regex:/:[a-z][A-Za-z0-9_]*/g,css:"color2"},{regex:/(\$|@@|@)\w+/g,css:"variable bold"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"keyword"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"color1"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.aspScriptTags);
};
SyntaxHighlighter.brushes.Ruby.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Ruby.aliases=["ruby","rails","ror"];
SyntaxHighlighter.brushes.Scala=function(){var b="val sealed case def true trait implicit forSome import match object null finally super override try lazy for var catch throw type extends class while with new final yield abstract else do if return protected private this package false";
var a="[_:=><%#@]+";
this.regexList=[{regex:SyntaxHighlighter.regexLib.singleLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineCComments,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineSingleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.multiLineDoubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.singleQuotedString,css:"string"},{regex:/0x[a-f0-9]+|\d+(\.\d+)?/gi,css:"value"},{regex:new RegExp(this.getKeywords(b),"gm"),css:"keyword"},{regex:new RegExp(a,"gm"),css:"keyword"}];
};
SyntaxHighlighter.brushes.Scala.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Scala.aliases=["scala"];
SyntaxHighlighter.brushes.Sql=function(){var c="abs avg case cast coalesce convert count current_timestamp current_user day isnull left lower month nullif replace right session_user space substring sum system_user upper user year";
var a="absolute action add after alter as asc at authorization begin bigint binary bit by cascade char character check checkpoint close collate column commit committed connect connection constraint contains continue create cube current current_date current_time cursor database date deallocate dec decimal declare default delete desc distinct double drop dynamic else end end-exec escape except exec execute false fetch first float for force foreign forward free from full function global goto grant group grouping having hour ignore index inner insensitive insert instead int integer intersect into is isolation key last level load local max min minute modify move name national nchar next no numeric of off on only open option order out output partial password precision prepare primary prior privileges procedure public read real references relative repeatable restrict return returns revoke rollback rollup rows rule schema scroll second section select sequence serializable set size smallint static statistics table temp temporary then time timestamp to top transaction translation trigger true truncate uncommitted union unique update values varchar varying view when where with work";
var b="all and any between cross in join like not null or outer some";
this.regexList=[{regex:/--(.*)$/gm,css:"comments"},{regex:SyntaxHighlighter.regexLib.multiLineDoubleQuotedString,css:"string"},{regex:SyntaxHighlighter.regexLib.multiLineSingleQuotedString,css:"string"},{regex:new RegExp(this.getKeywords(c),"gmi"),css:"color2"},{regex:new RegExp(this.getKeywords(b),"gmi"),css:"color1"},{regex:new RegExp(this.getKeywords(a),"gmi"),css:"keyword"}];
};
SyntaxHighlighter.brushes.Sql.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Sql.aliases=["sql"];
SyntaxHighlighter.brushes.Vb=function(){var a="AddHandler AddressOf AndAlso Alias And Ansi As Assembly Auto Boolean ByRef Byte ByVal Call Case Catch CBool CByte CChar CDate CDec CDbl Char CInt Class CLng CObj Const CShort CSng CStr CType Date Decimal Declare Default Delegate Dim DirectCast Do Double Each Else ElseIf End Enum Erase Error Event Exit False Finally For Friend Function Get GetType GoSub GoTo Handles If Implements Imports In Inherits Integer Interface Is Let Lib Like Long Loop Me Mod Module MustInherit MustOverride MyBase MyClass Namespace New Next Not Nothing NotInheritable NotOverridable Object On Option Optional Or OrElse Overloads Overridable Overrides ParamArray Preserve Private Property Protected Public RaiseEvent ReadOnly ReDim REM RemoveHandler Resume Return Select Set Shadows Shared Short Single Static Step Stop String Structure Sub SyncLock Then Throw To True Try TypeOf Unicode Until Variant When While With WithEvents WriteOnly Xor";
this.regexList=[{regex:/'.*$/gm,css:"comments"},{regex:SyntaxHighlighter.regexLib.doubleQuotedString,css:"string"},{regex:/^\s*#.*$/gm,css:"preprocessor"},{regex:new RegExp(this.getKeywords(a),"gm"),css:"keyword"}];
this.forHtmlScript(SyntaxHighlighter.regexLib.aspScriptTags);
};
SyntaxHighlighter.brushes.Vb.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Vb.aliases=["vb","vbnet"];
SyntaxHighlighter.brushes.Xml=function(){function a(c,f){var g=SyntaxHighlighter.Match,b=c[0],e=new XRegExp("(&lt;|<)[\\s\\/\\?]*(?<name>[:\\w-\\.]+)","xg").exec(b),i=[];
if(c.attributes!=null){var h,d=new XRegExp("(?<name> [\\w:\\-\\.]+)\\s*=\\s*(?<value> \".*?\"|'.*?'|\\w+)","xg");
while((h=d.exec(b))!=null){i.push(new g(h.name,c.index+h.index,"color1"));
i.push(new g(h.value,c.index+h.index+h[0].indexOf(h.value),"string"));
}}if(e!=null){i.push(new g(e.name,c.index+e[0].indexOf(e.name),"keyword"));
}return i;
}this.regexList=[{regex:new XRegExp("(\\&lt;|<)\\!\\[[\\w\\s]*?\\[(.|\\s)*?\\]\\](\\&gt;|>)","gm"),css:"color2"},{regex:new XRegExp("(\\&lt;|<)!--\\s*.*?\\s*--(\\&gt;|>)","gm"),css:"comments"},{regex:new XRegExp("(&lt;|<)[\\s\\/\\?]*(\\w+)(?<attributes>.*?)[\\s\\/\\?]*(&gt;|>)","sg"),func:a}];
};
SyntaxHighlighter.brushes.Xml.prototype=new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Xml.aliases=["xml","xhtml","xslt","html","xhtml"];
var stylesConversion={alt1:"background-color: #fff;",alt2:"background-color: #F8F8F8;",bold:"font-weight: bold;",color1:"color: #808080;",color2:"color: #ff1493;",color3:"color: red;",comments:"color: #008200;",constants:"color: #0066CC;",functions:"color: #ff1493;",keyword:"color: #069;font-weight: bold;",plain:"color: #000;",preprocessor:"color: gray;",string:"color: blue;",script:"background-color: yellow;",value:"color: #090;",variable:"color: #a70;",number:"color:#5C5C5C;float:left;width:3em;padding-right:.3em;text-align:right;display:block;",line:" ",content:" ",block:" ",spaces:" "};
function getStyleFor(c){var e=c.split(" ");
var b="";
for(var a=0;
a<e.length;
a++){var d=e[a];
if(stylesConversion[d]){b+=stylesConversion[d];
}}return b;
}