Type.registerNamespace("Telerik.Web.UI");
(function(b,a){$telerik.toSocialShare=function(c){return c;
};
$telerik.findSocialShare=$find;
a.RadSocialShare=function(c){a.RadSocialShare.initializeBase(this,[c]);
this._mainButtons=null;
this._compactButtons=null;
this._addFbScript=false;
this._addGoogleScript=false;
this._addTwitterScript=false;
this._uniqueId=false;
this._ulElement=null;
this._compactPopup=null;
this._emailPopup=null;
this._comboBox=null;
this._emailButton=null;
this._compactButton=null;
this._trackerSet=false;
this._fbLikeWithSend=false;
this._standardClickDelegate=null;
this._toggleCompactDelegate=null;
this._toggleEmailDelegate=null;
this._sendMailDelegate=null;
this._tryAgainDelegate=null;
};
a.RadSocialShare.prototype={initialize:function(){a.RadSocialShare.callBaseMethod(this,"initialize");
var e=this.get_element();
if($telerik.isRightToLeft(e)){Sys.UI.DomElement.addCssClass(e,"sshRtl");
}this._ulElement=this.get_element().getElementsByTagName("ul")[0];
if(this._addFbScript||this._addTwitterScript||this._addGoogleScript){if(this._addFbScript){this._addScriptBlock(this._getStandardButtonUrl("facebookscript"));
}if(this._addGoogleScript){this._addScriptBlock(this._getStandardButtonUrl("googlescript"));
}if(this._addTwitterScript){this._addScriptBlock(this._getStandardButtonUrl("twitterscript"));
}setTimeout(Function.createDelegate(this,this.parseGeneratedButtons),100);
}var c=$get(this.get_id()+"_IEHack");
if($telerik.isIE&&c){c.parentNode.removeChild(c);
}if(this.get_gaEnabled()){var d=("https:"==document.location.protocol)?"https://ssl":"http://www";
this._addScriptBlock(d+this._getStandardButtonUrl("ga"));
}this.configureButtons(true);
this.configureCompactPopup();
this.configureEmailPopup();
},dispose:function(){var c=this.get_mainButtons();
if(c&&c.length>0){this._disposeButtons(c);
}var d=this.get_compactButtons();
if(d&&d.length>0){this._disposeButtons(d);
}if(this._emailPopup){this.setupEmailElements(null,true);
}this._standardClickDelegate=null;
this._toggleEmailDelegate=null;
this._toggleCompactDelegate=null;
a.RadSocialShare.callBaseMethod(this,"dispose");
},_disposeButtons:function(e){for(var c=0;
c<e.length;
c++){var d=e[c]._element;
if(d){b(d).unbind();
}}},configureButtons:function(n){var j=(!n&&this._comboBox)?this._comboBox.get_childListElement().parentNode:this._ulElement;
var h=(!n&&this._comboBox)?$telerik.getChildrenByClassName(this._comboBox.get_childListElement(),"rcbItem"):$telerik.getChildrenByClassName(j,"sshListItem");
var m=n?this.get_mainButtons():this.get_compactButtons();
var l=this.get_compactPopup()?this.get_compactPopup().get_id():null;
if(!m){return;
}this._standardClickDelegate=Function.createDelegate(this,this._clickHandler);
this._toggleCompactDelegate=Function.createDelegate(this,this.toggleCompactPopup);
this._toggleEmailDelegate=Function.createDelegate(this,this.toggleEmailPopup);
var c=location.href;
for(var d=0;
d<m.length;
d++){var g=m[d];
if(!h[d]){return;
}g._element=h[d].firstChild;
var e=g[0];
if(g[1]){g[2]=g[2]?g[2]:g[1];
}else{var f=document.title?document.title:document.location.href;
g[2]=g[2]?g[2]:f;
}g[1]=g[1]?g[1]:c;
var k=this._getStandardButtonUrl(e);
if(k){g[1]=encodeURIComponent(g[1]);
b(g._element).bind("click",{button:g},this._standardClickDelegate);
}else{if(n){if(!this._fbLikeWithSend){this._fbLikeWithSend=(m[d][0]=="FacebookLike"||m[d][0]=="FacebookRecommend")&&(m[d+1]&&m[d+1][0]=="FacebookSend");
}if(e.indexOf("Facebook")>-1&&e!="ShareOnFacebook"){this.configureFbButton(g,n);
}if(e=="Twitter"){this.configureTwitterButton(g);
}if(e=="GooglePlusOne"){this.configureGoogleButton(g);
}}if(e=="CompactButton"){b(g._element).bind("click",{button:g},this._toggleCompactDelegate);
this._compactButton=g;
}if(e=="SendEmail"){b(g._element).bind("click",{button:g},this._toggleEmailDelegate);
this._emailButton=g;
}}}},configureCompactPopup:function(){this._compactPopup=$find(this.get_id()+"_compactPopup");
if(!this._compactPopup){return;
}this._comboBox=$find(this._compactPopup.get_id()+"_C_comboBox");
this._compactPopup._comboBox=this._comboBox;
this._compactPopup.add_show(Function.createDelegate(this,this._showCompactPopupHandler));
this.configureButtons(false);
this._comboBox.add_selectedIndexChanged(this.comboBoxSelectionChanged);
this._comboBox.add_dropDownClosing(function(c,d){d.set_cancel(true);
});
this._compactPopup.add_beforeClose(this._closeCompactPopupHandler);
},configureEmailPopup:function(){this._emailPopup=$find(this.get_id()+"_emailPopup");
if(!this._emailPopup){return;
}this._emailPopup.add_show(Function.createDelegate(this,this._showEmailPopupHandler));
this._emailPopup.add_beforeClose(this._closeEmailPopupHandler);
this._emailPopup._createUI();
if(!this.get_hideIframesOnDialogMove()&&this._emailPopup._resizeExtender){this._emailPopup._resizeExtender.set_hideIframes(false);
}this.setupEmailElements(this._emailPopup.get_contentElement());
},_addScriptBlock:function(d){d=d.replace("[p]",document.location.protocol);
var e=document.getElementsByTagName("script");
for(var c=0;
c<e.length;
c++){if(e[c].getAttribute("src")==d){return;
}}var f=document.getElementsByTagName("head")[0];
var h=document.createElement("script");
h.setAttribute("async",true);
h.type="text/javascript";
h.src=d;
h.parsetags="explicit";
h.onload=Function.createDelegate(this,this.parseGeneratedButtons);
if(d.indexOf("connect.facebook.net")>=0){var g=$get("fb-root");
if(!g){g=document.createElement("div");
g.setAttribute("id","fb-root");
g.appendChild(h);
}document.body.appendChild(g);
}else{f.appendChild(h);
}},parseGeneratedButtons:function(){if(this._addFbScript){try{if(!window.fbAsyncInit){window.fbAsyncInit=Function.createDelegate(this,function(){FB.init({appId:this.get_fbAppId(),status:true,cookie:true,xfbml:true});
});
}else{if(!this._fbEventsAdded){FB.Event.subscribe("edge.create",Function.createDelegate(this,this._fbLike));
FB.Event.subscribe("edge.remove",Function.createDelegate(this,this._fbUnLike));
FB.Event.subscribe("message.send",Function.createDelegate(this,this._fbSend));
this._fbEventsAdded=true;
}}}catch(c){}}if(this._addTwitterScript&&typeof(twttr)!="undefined"&&twttr){twttr.widgets.load();
if(!this._twEventsAdded){twttr.events.bind("tweet",Function.createDelegate(this,this._tweet));
this._twEventsAdded=true;
}}if(this._addGoogleScript&&typeof(gapi)!="undefined"&&gapi){gapi.plusone.go(this.get_element());
}},_closeCompactPopupHandler:function(c,d){c._comboBox.clearSelection();
},_showCompactPopupHandler:function(f,h){var c=this._comboBox;
c._removeEmTagsFromAllItems();
c.setAllItemsVisible(true);
if(!c.get_dropDownVisible()){c.showDropDown();
var d=c.get_dropDownElement();
var g=d.parentNode;
f.get_contentElement().appendChild(g);
Sys.UI.DomElement.addCssClass(g,"sshComboDropDown");
Sys.UI.DomElement.addCssClass(c.get_element(),"sshComboWrapper");
}if(!this.get_hideIframesOnDialogMove()&&f._resizeExtender){f._resizeExtender.set_hideIframes(false);
}setTimeout(function(){c.get_inputDomElement().focus();
},10);
var e=new a.SocialDialogEventArgs(f,this._compactButton);
this.raiseEvent("clicked",e);
f.autoSize();
},_closeEmailPopupHandler:function(g,k){var h=g.get_contentElement();
var j=h.getElementsByTagName("*");
for(var c=0;
c<j.length;
c++){var d=j[c];
var e=d.tagName.toLowerCase();
if((e=="input"&&d.getAttribute("type")=="text")||e=="textarea"){d.value="";
Sys.UI.DomElement.removeCssClass(d,"sshWrongEmail");
}else{var f=d.id;
if(f){if(f.indexOf("emailForm")>-1){d.style.display="";
}else{if(f.indexOf("error")>-1||f.indexOf("success")>-1){d.style.display="none";
}}}}}__doPostBack(g._captchaRefresh.id,"");
},_showEmailPopupHandler:function(e,d){var c=this.get_compactPopup();
if(c&&c.isVisible()){c.close();
}this._url.value=decodeURIComponent(this._emailButton[1]);
this._subject.value="[Your email] has shared a link with you";
e.autoSize();
setTimeout(function(){e._toInput.focus();
},10);
var f=new a.SocialDialogEventArgs(e,this._emailButton);
this.raiseEvent("clicked",f);
},configureFbButton:function(f){var h=f[0].toLowerCase().replace("facebook","");
var c=(h=="like"||h=="recommend")?"fb:like":"fb:send";
f._element.style.display="none";
var e=h!="share"?document.createElement(c):document.createElement("a");
if(this._fbLikeWithSend){if(h=="like"||h=="recommend"){e.setAttribute("send",true);
}else{if(h=="send"){return;
}}}var g=f[1];
var i=this._getFbBtnSetting(f[4]);
e.setAttribute("action",h);
e.setAttribute("show_faces",f[3]!==undefined?f[3]:true);
e.setAttribute("layout",i);
e.setAttribute("colorscheme",f[5]!==undefined?f[5].toLowerCase():"light");
if(f[6]!=""){e.setAttribute("width",f[6]+"px");
}e.setAttribute("font",this._getFbBtnSetting(f[7]));
if(f[8]!=""){e.setAttribute("ref",f[8]);
}var d=f._element.parentNode;
if(h=="share"){e.setAttribute("name","fb_share");
e.setAttribute("share_url",g);
e.setAttribute("type",i);
}else{e.setAttribute("href",g);
}e.setAttribute("parentSsh",this.get_id());
d.appendChild(e);
if(h=="share"){setTimeout(Function.createDelegate(this,function(){this._addScriptBlock(this._getStandardButtonUrl("share"));
}),600);
}},configureTwitterButton:function(c){var d=a.RadSocialShare.SocialNetUrls.ShareOnTwitter.replace("[u]",c[1]).replace("[t]",encodeURIComponent(c[2]));
var e=c._element;
e.parentNode.setAttribute("parentSsh",this.get_id());
Sys.UI.DomElement.addCssClass(e,"twitter-share-button");
e.setAttribute("href",d);
e.setAttribute("data-count",c[3]!==undefined?c[3].toLowerCase():"none");
},configureGoogleButton:function(c){var d=document.createElement("g:plusone");
window[this.get_id()+"plusoneHandler"]=Function.createDelegate(this,this._gPlusOne);
d.setAttribute("callback",this.get_id()+"plusoneHandler");
d.setAttribute("href",decodeURIComponent(c[1]));
d.setAttribute("size",c[3]!==undefined?c[3].toLowerCase():"standard");
d.setAttribute("annotation",c[4]!==undefined?c[4].toLowerCase():"none");
if(c[5]!==undefined){d.setAttribute("width",c[5]);
}c._element.parentNode.appendChild(d);
c._element.style.display="none";
},_getStandardButtonUrl:function(c){return a.RadSocialShare.SocialNetUrls[c];
},_getFbBtnSetting:function(c){switch(c){case"IconLink":c="icon_link";
break;
case"BoxCount":c="box_count";
break;
case"ButtonCount":c="button_count";
break;
case"LucidaGrande":c="lucida grande";
break;
case"SegoeUI":c="segoe ui";
break;
case"TrebuchetMS":c="trebuchet ms";
break;
default:c="";
break;
}return c.toLowerCase();
},_clickHandler:function(n){var q=n.data.button;
var j=q[1];
var i=encodeURIComponent(q[2]);
var c=a.RadSocialShare.SocialNetUrls[q[0]].replace("[u]",j).replace("[t]",i);
var r=q[3];
var l=q[4];
var f=$telerik.getViewPortSize();
var d=q[5]?q[5]:(f.height-l)/2;
var h=q[6]?q[6]:(f.width-r)/2;
var m=new a.SocialDialogCancelEventArgs(q);
this.raiseEvent("clicking",m);
if(m.get_cancel()){return;
}var o=(q[0]=="MailTo")?"_self":"sharer";
var p=window.open(c,o,"resizable,scrollbars=1,toolbar=0,status=0,width="+r+",height="+l+",top="+d+",left="+h);
$telerik.cancelRawEvent(n);
var g=new a.SocialDialogEventArgs(p,q);
this.raiseEvent("clicked",g);
if(this.get_gaEnabled()){this._trackSocial(q[0].replace("ShareOn",""),"share",q[1]);
}var k=this.get_compactPopup();
if(k&&k.isVisible()){k.close();
}},_fbLike:function(d,c){if(c.dom._element.getAttribute("parentSsh")!=this.get_id()){return;
}this._onSocialAction("fbLike",d,"facebook");
},_fbUnLike:function(d,c){if(c.dom._element.getAttribute("parentSsh")!=this.get_id()){return;
}this._onSocialAction("fbUnLike",d,"facebook");
},_fbSend:function(d,c){if(c.dom.parentElement._element.getAttribute("parentSsh")!=this.get_id()){return;
}this._onSocialAction("fbSend",d,"facebook");
},_onSocialAction:function(e,c,f){c=decodeURIComponent(c);
var d=Sys.EventArgs.Empty;
d._url=c;
d.get_url=function(){return this._url;
};
this.raiseEvent(e,d);
if(f&&this.get_gaEnabled()){this._trackSocial(f,e.replace("fb","").toLowerCase(),c);
}},_setUpGAAccount:function(){window._gaq=window._gaq||[];
var d=this.get_trackerId();
var c=_gat._getTrackers();
if(c.length==0){_gaq.push([(d+"._setAccount"),this.get_gaID()]);
_gaq.push([d+"._trackPageview"]);
}else{for(var e=0;
e<c.length;
e++){if(c[e]._getName()==d){continue;
}_gaq.push([(d+"._setAccount"),this.get_gaID()]);
_gaq.push([d+"._trackPageview"]);
}}this._trackerSet=true;
},_tweet:function(c){var d=c.target;
if(!(d&&d.parentNode.getAttribute("parentSsh")==this.get_id())){return;
}url=d.src.split("&url=")[1];
this._onSocialAction("tweet",url,"twitter");
},_gPlusOne:function(e){var c=e.href;
var d=e.state+"Plusone";
this._onSocialAction(d,c,"Google");
},_trackSocial:function(c,e,f){if(!this._trackerSet){this._setUpGAAccount();
}if(c=="Google"){var g=e.replace("Plusone","");
var d=this.get_trackerId()+"._trackEvent";
_gaq.push([d,c,g,f]);
}else{if(c=="Twitter"){e="tweet";
}var d=this.get_trackerId()+"._trackSocial";
_gaq.push([d,c,e,f]);
}},comboBoxSelectionChanged:function(e,d){var c=d.get_item().get_element().firstChild;
$telerik.$(c).trigger("click");
},toggleCompactPopup:function(c){this.togglePopup(this.get_compactPopup(),c);
},toggleEmailPopup:function(c){this.togglePopup(this.get_emailPopup(),c);
},togglePopup:function(d,f){if(!d){return;
}if(!d.isVisible()){var c=new a.SocialDialogCancelEventArgs(f.data.button);
this.raiseEvent("clicking",c);
if(c.get_cancel()){return;
}d.show();
}else{d.close();
}$telerik.cancelRawEvent(f);
},setupEmailElements:function(e,d){var g=["_url","_from","_to","_comments","_subject","_emailForm","_errorValidation","_success","_error","_errorCaptcha","_sendBtn","_ok","_tryAgain","_cancel"];
for(var c=0;
c<g.length;
c++){field=g[c];
if(d){b(this[field]).unbind();
this[field]=null;
this._sendMailDelegate=null;
this._tryAgainDelegate=null;
this._fromBlurDelegate=null;
}this[field]=$get(this.get_id()+field,e);
}if(!d){this._sendMailDelegate=Function.createDelegate(this,this.sendMail);
this._tryAgainDelegate=Function.createDelegate(this,this._tryAgainHandler);
this._fromBlurDelegate=Function.createDelegate(this,this._fromBlur);
if(this._sendBtn){b(this._sendBtn).bind("click",this._sendMailDelegate);
}if(this._ok){b(this._ok).bind("click",this._toggleEmailDelegate);
}if(this._cancel){b(this._cancel).bind("click",this._toggleEmailDelegate);
}if(this._tryAgain){b(this._tryAgain).bind("click",this._tryAgainDelegate);
}if(this._from){b(this._from).bind("blur",this._fromBlurDelegate);
}var f=this.get_id()+"_emailPopup_C_"+this.get_id()+"_captcha";
this._captchaTb=$get(f+"_CaptchaTextBox",e);
this._emailPopup._captchaRefresh=$get(f+"_CaptchaLinkButton",e);
this._emailPopup._toInput=this._to;
}},sendMail:function(c){$telerik.cancelRawEvent(c);
var d=this.validateEmails();
if(!d){this._errorValidation.style.display="";
this._emailPopup.autoSize();
}else{this._errorValidation.style.display="none";
WebForm_DoCallback(this._uniqueId,"sendMail&"+this._from.value+"&"+this._to.value+"&"+encodeURIComponent(this._subject.value)+"&"+encodeURIComponent(this._comments.value)+"<br/> "+encodeURIComponent("<a href='"+this._url.value+"'>"+this._url.value+"</a>")+"&"+this._captchaTb.value,Function.createDelegate(this,this.success),"context",Function.createDelegate(this,this.error));
}},success:function(){this._emailForm.style.display="none";
this._success.style.display="";
this._emailPopup.autoSize();
},error:function(d){var c=this._errorCaptcha;
if(d.indexOf("email captha failed!")<0){this._emailForm.style.display="none";
c=this._error;
}c.style.display="";
this._emailPopup.autoSize();
},validateEmail:function(f,c){var d=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,4}$/;
var e=d.test(f);
if(e){Sys.UI.DomElement.removeCssClass(c,"sshWrongEmail");
}else{Sys.UI.DomElement.addCssClass(c,"sshWrongEmail");
}return e;
},validateEmails:function(){var d=this.validateEmail(this._from.value.replace(/[ ,;]/g,""),this._from);
var e=true;
var f=this._to.value;
if(f.indexOf(",")<0&&f.indexOf(";")<0){e=this.validateEmail(f.replace(/ /g,""),this._to);
}else{var c=f.replace(/[ ]/g,"").split(/[,;]+/);
for(var g=0;
g<c.length;
g++){if(c[g]!=""){e=e&&this.validateEmail(c[g],this._to);
}}}return d&&e;
},_tryAgainHandler:function(){this._closeEmailPopupHandler(this._emailPopup);
this._showEmailPopupHandler(this._emailPopup);
},_fromBlur:function(){if(this._subject.value.indexOf("has shared a link with you")>-1){this._subject.value=this._from.value+" has shared a link with you";
}},get_mainButtons:function(){return this._mainButtons;
},set_mainButtons:function(c){if(!c){this._mainButtons=[];
}else{this._mainButtons=eval(c);
}},get_compactButtons:function(){return this._compactButtons;
},set_compactButtons:function(c){if(!c){this._compactButtons=[];
}else{this._compactButtons=eval(c);
}},get_compactPopup:function(){return this._compactPopup;
},get_emailPopup:function(){return this._emailPopup;
},get_gaEnabled:function(){return this.get_gaID()!="";
},get_trackerId:function(){return"tracker_"+this.get_gaID();
}};
b.registerControlProperties(a.RadSocialShare,{gaID:"",fbAppId:"",hideIframesOnDialogMove:true});
b.registerControlEvents(a.RadSocialShare,["clicking","clicked","fbLike","fbUnLike","fbSend","tweet","onPlusone","offPlusone"]);
Telerik.Web.UI.RadSocialShare.registerClass("Telerik.Web.UI.RadSocialShare",a.RadWebControl);
if(!a.RadSocialShare.SocialNetUrls){a.RadSocialShare.SocialNetUrls={ShareOnTwitter:"http://twitter.com/intent/tweet?url=[u]&text=[t]",GoogleBookmarks:"https://www.google.com/bookmarks/mark?op=add&bkmk=[u]&title=[t]",LinkedIn:"http://www.linkedin.com/shareArticle?mini=true&url=[u]&title=[t]",Delicious:"http://delicious.com/save?url=[u]&amp;title=[t]",Blogger:"http://www.blogger.com/blog_this.pyra?t=&u=[u]&n=[t]",Digg:"http://digg.com/submit?url=[u]&amp;title=[t]",Reddit:"http://www.reddit.com/submit?url=[u]&amp;title=[t]",StumbleUpon:"http://www.stumbleupon.com/submit?url=[u]&amp;title=[t]",MySpace:"http://www.myspace.com/Modules/PostTo/Pages/?u=[u]&amp;t=[t]",Tumblr:"http://www.tumblr.com/share/link?url=[u]&name=[t]",MailTo:"mailto:?body=[u]&subject=[t]",ShareOnFacebook:"http://www.facebook.com/sharer.php?u=[u]&t=[t]",share:"http://static.ak.fbcdn.net/connect.php/js/FB.Share",facebookscript:"[p]//connect.facebook.net/en_US/all.js#xfbml=1",googlescript:"https://apis.google.com/js/plusone.js",twitterscript:"http://platform.twitter.com/widgets.js",ga:".google-analytics.com/ga.js"};
}Telerik.Web.UI.SocialDialogEventArgs=function(d,c){Telerik.Web.UI.SocialDialogEventArgs.initializeBase(this);
this._dialog=d;
this._socialNetType=c[0];
this._button=c;
};
Telerik.Web.UI.SocialDialogEventArgs.prototype={get_dialog:function(){return this._dialog;
},get_socialNetType:function(){return this._socialNetType;
},get_url:function(){return decodeURIComponent(this._button[1]);
}};
Telerik.Web.UI.SocialDialogEventArgs.registerClass("Telerik.Web.UI.SocialDialogEventArgs",Sys.EventArgs);
Telerik.Web.UI.SocialDialogCancelEventArgs=function(c){Telerik.Web.UI.SocialDialogCancelEventArgs.initializeBase(this);
this._socialNetType=c[0];
this._button=c;
};
Telerik.Web.UI.SocialDialogCancelEventArgs.prototype={get_socialNetType:function(){return this._socialNetType;
},get_url:function(){return decodeURIComponent(this._button[1]);
}};
Telerik.Web.UI.SocialDialogCancelEventArgs.registerClass("Telerik.Web.UI.SocialDialogCancelEventArgs",Sys.CancelEventArgs);
})($telerik.$,Telerik.Web.UI);
