Type.registerNamespace("Telerik.Web.UI.Editor");
Telerik.Web.UI.Editor.AjaxSpellCheck=function(a){Telerik.Web.UI.Editor.AjaxSpellCheck.initializeBase(this,[a]);
this._language="";
this._editor=null;
this._originalHtml=null;
this._protectedData=[];
this._ignoreTags=new RegExp("<(!--)([\\s\\S]*?)(--)>","gi");
this._ignoreOtherTags=new RegExp("<(object|style|textarea)([\\s\\S]*?)(\\/\\1)>","gi");
this._ignoreOtherTagsIE=new RegExp("<(marquee)([\\s\\S]*?)(\\/\\1)>","gi");
};
Telerik.Web.UI.Editor.AjaxSpellCheck.prototype={initialize:function(){var a=this.get_editor();
this._finalCheckMessage=a.getLocalizedString("SpellCheckEnd","Finish spellchecking");
this._completeMessage=a.getLocalizedString("SpellCheckComplete","Spellchecking complete!");
this._cancelMessage=a.getLocalizedString("CancelButton","Cancel");
this._addWordSuccessMessage=a.getLocalizedString("AddCustomWordSuccess");
this._spellingInProgressMessage=a.getLocalizedString("SpellingInProgress");
this._spellingModeMessage=a.getLocalizedString("SpellingMode");
this._noSpellingMistakesMessage=a.getLocalizedString("NoSpellingMistakes","No mistakes found.");
this._loadingIconCss="reLoading";
this._createUI();
},get_editor:function(){return this._editor;
},set_editor:function(a){this._editor=a;
},get_language:function(){return this._language;
},set_language:function(a){this._language=a;
},getSpellService:function(){var b=this.get_editor().get_spellCheckService();
var a=this.get_language();
if(a){b.set_language(a);
}return b;
},dispose:function(){if(this._cancelButton){this._cancelButton.Parent=null;
this._cancelButton.onclick=null;
}this._cancelButton=null;
if(this._finishButton){this._finishButton.Parent=null;
this._finishButton.onclick=null;
}this._finishButton=null;
if(this._spellEngine){this._spellEngine.dispose();
}this._editor=null;
this._topElement=null;
this._protectedData=null;
},raiseEvent:function(b,c){var a=this.get_events().getHandler(b);
if(a){if(!c){c=Sys.EventArgs.Empty;
}a(this,c);
}},add_spellCheckStart:function(a){this.get_events().addHandler("spellCheckStart",a);
},remove_spellCheckStart:function(a){this.get_events().removeHandler("spellCheckStart",a);
},add_spellCheckEnd:function(a){this.get_events().addHandler("spellCheckEnd",a);
},remove_spellCheckEnd:function(a){this.get_events().removeHandler("spellCheckEnd",a);
},spellCheck:function(){if(!this._spellEngine){this._spellEngine=new Telerik.Web.UI.Editor.SpellEngineUI(this.get_editor(),this);
this._spellEngine.onSpellCheckComplete=Function.createDelegate(this,function(){this.finishSpellCheck();
alert(this._completeMessage);
});
this._spellEngine.onAddCustomWord=Function.createDelegate(this,function(c){this.addCustomWord(c);
});
}if(this._spellEngine._spellcheckComplete){this.finishSpellCheck(false);
}this._setVisible(true);
this._setLoadingIconVisible(true);
this._enableButtons(false);
this._originalHtml=this.get_editor().get_contentArea().innerHTML;
var b=this.getSpellService();
var a=Function.createDelegate(this,function(c,d){b.remove_complete(a);
this.beginSpellCheck(d);
});
b.add_complete(a);
this._saveSpecialContent();
b.spellCheck(this._spellEngine._escapeNewLines(this._originalHtml));
},beginSpellCheck:function(a){this._setLoadingIconVisible(false);
this._enableButtons(true);
this.raiseEvent("spellCheckStart");
if(a.badWords.length==0){alert(this._noSpellingMistakesMessage);
this.finishSpellCheck();
}else{this._spellEngine.initialize(a,this._originalHtml);
}},finishSpellCheck:function(a){this._setVisible(false);
this._spellEngine.finalize();
this.restoreSavedContent();
this._originalHtml=null;
if(false!=a){this.raiseEvent("spellCheckEnd");
}},cancelSpellCheck:function(){this._setVisible(false);
this._spellEngine.finalize(false);
if(null!=this._originalHtml){Telerik.Web.UI.Editor.Utils.setElementInnerHtml(this.get_editor().get_contentArea(),this._originalHtml);
this._originalHtml=null;
}this.restoreSavedContent();
var b=this.get_editor().get_commandsManager();
var a=b.get_commands();
b.removeCommandAt(a.length-1);
this.raiseEvent("spellCheckEnd");
this.get_editor().raiseEvent("selectionChange",Sys.EventArgs.Empty);
},_saveSpecialContent:function(){this._protectedData=[];
var a=Function.createDelegate(this,function(d,e,f,c,g,b){Array.add(this._protectedData,"<"+e+f+c+">");
return"<radeditorformatted_"+this._protectedData.length+"></radeditorformatted_"+this._protectedData.length+">";
});
this._originalHtml=this._originalHtml.replace(this._ignoreTags,a);
this._originalHtml=this._originalHtml.replace(this._ignoreOtherTags,a);
if($telerik.isIE){this._originalHtml=this._originalHtml.replace(this._ignoreOtherTagsIE,a);
}},restoreSavedContent:function(){if(this._protectedData&&this._protectedData.length>0){var b=this.get_editor().get_contentArea().innerHTML;
for(var a=0;
a<this._protectedData.length;
a++){var c=new RegExp("<radeditorformatted_"+(a+1)+"\\s*>","i");
b=b.replace(c,this._protectedData[a]);
}var d=new RegExp("<\\/radeditorformatted_[^>]+>","i");
b=b.replace(d,"");
Telerik.Web.UI.Editor.Utils.setElementInnerHtml(this.get_editor().get_contentArea(),b);
this._protectedData=[];
}},addCustomWord:function(a){var e=this.getSpellService();
var b=this._spellEngine;
var c=this._addWordSuccessMessage;
var d=function(h,g){e.remove_complete(d);
alert(a+" "+c);
b.clearWrongWords(a,a);
var f=b.isHighlightedRemaining();
if(!f){b._suggestionDropdown.hide();
b.onSpellCheckComplete();
return;
}b.moveToNextWrongWord();
};
e.add_complete(d);
e.addCustomWord(a);
},_createUI:function(){var d=document;
var b=d.createElement("table");
b.cellSpacing=2;
b.cellPadding=0;
b.className="reAjaxspell_wrapper";
b.style.width="100%";
b.style.backgroundColor="#ffffcc";
b.style.clear="both";
b.style.borderBottom="1px solid #adadad";
b.insertRow(-1);
var a=b.rows[0].insertCell(-1);
a.style.width="100%";
var c=d.createElement("button");
c.className="reAjaxspell_button";
a=b.rows[0].insertCell(-1);
this._finishButton=c.cloneNode(true);
this._finishButton.Parent=this;
this._finishButton.innerHTML=this._finalCheckMessage;
this._finishButton.onclick=new Function("this.Parent.finishSpellCheck();return false;");
a.appendChild(this._finishButton);
a=b.rows[0].insertCell(-1);
this._cancelButton=c.cloneNode(true);
this._cancelButton.Parent=this;
this._cancelButton.innerHTML=this._cancelMessage;
this._cancelButton.onclick=new Function("this.Parent.cancelSpellCheck();return false;");
a.appendChild(this._cancelButton);
this._topElement=b;
this.get_element().appendChild(this._topElement);
},_setVisible:function(a){this._topElement.style.display=a?"":"none";
},_enableButtons:function(b){var a=this._topElement.getElementsByTagName("button");
for(var c=0;
c<a.length;
c++){a[c].disabled=!b;
}},_setLoadingIconVisible:function(a){var c=this._topElement.rows[0].cells[0];
c.innerHTML="";
if(a){var b=document.createElement("span");
b.className=this._loadingIconCss;
c.appendChild(b);
c.innerHTML+="<label>"+this._spellingInProgressMessage+"</label>";
}else{c.innerHTML="<label>"+this._spellingModeMessage+"</label>";
}}};
Telerik.Web.UI.Editor.AjaxSpellCheck.registerClass("Telerik.Web.UI.Editor.AjaxSpellCheck",Sys.UI.Control);
Telerik.Web.UI.Editor.SpellEngineUI=function(b,a){this._editor=b;
this._parentControl=a;
this._suggestionDropdown=null;
this._suggestionBox=null;
this._wrongWordCounter=0;
this._wrongWordsArray=null;
this._spanId="RadESpellError_";
this._selectedEditorElement=null;
this._spellcheckComplete=true;
this._automaticAdvance=true;
this._localizedCommandName=this._editor.getLocalizedString("spellCheck","Check spelling");
this._localizedName=this._editor.getLocalizedString("SpellingChange","Spelling Change");
this._noSuggestionsString=this._editor.getLocalizedString("NoSuggestions","(no suggestions)");
this._changeWordString=this._editor.getLocalizedString("ChangeWordString","Change");
this._ignoreAllString=this._editor.getLocalizedString("IgnoreAllString","Ignore All");
this._ignoreString=this._editor.getLocalizedString("IgnoreString","Ignore");
this._moreThanOnceMessage=this._editor.getLocalizedString("MoreThanOnceMessage","This word occurs more than once in the text. Would you like to replace all instances?");
this._undoDisabledMessage=this._editor.getLocalizedString("UndoDisabledMessage","You cannot undo further while in spellcheck mode. Please finish spellchecking first.");
this._addToDictionaryString=this._editor.getLocalizedString("AddToDictionary","Add to dictionary");
this._addIconCss="reAjaxspell_addicon";
this._okIconCss="reAjaxspell_okicon";
this._ignoreIconCss="reAjaxspell_ignoreicon";
};
Telerik.Web.UI.Editor.SpellEngineUI.prototype={onAddCustomWord:function(a){},onSpellCheckComplete:function(){},dispose:function(){this._editor=null;
this.onSpellCheckComplete=null;
},_configureUndo:function(a){if(a){this._editor.enableEditing(true);
var e=this._editor.get_commandsManager();
var c=e.get_commands();
var b=this._currentUndoIndex;
while(b<c.length){e.removeCommandAt(c.length-1);
}this._editor.executeCommand(this.SaveStateCmd);
if(this._onCommandExecutingDelegate){this._editor.remove_commandExecuting(this._onCommandExecutingDelegate);
}this._onCommandExecutingDelegate=null;
}else{var d=this._editor.get_commandsManager();
this._currentUndoIndex=d.getCommandsToUndo().length;
this._onCommandExecutingDelegate=Function.createDelegate(this,function(g,f){var h=f.get_commandName();
if(h=="Undo"&&this._currentUndoIndex>=d.getCommandsToUndo().length){alert(this._undoDisabledMessage);
f.set_cancel(true);
}});
this._editor.add_commandExecuting(this._onCommandExecutingDelegate);
this._editor.enableEditing(false,Telerik.Web.UI.EditingOptions.All,{Undo:true,Redo:true,AjaxSpellCheck:true});
}},finalize:function(b){if(true!=this._initialized){return;
}if(false!=b){this.clearWrongWords();
}if(this._parentControl){this._parentControl.restoreSavedContent();
this._parentControl=null;
}var a=this._editor;
if(this.OnMouseHandler){a.detachEventHandler("click",this.OnMouseHandler);
}if(this.OnKeyDownHandler){a.detachEventHandler("keydown",this.OnKeyDownHandler);
}if(this.OnContextMenu){a.detachEventHandler("contextmenu",this.OnContextMenu);
}if(this.OnEditorSubmit){a.remove_submit(this.OnEditorSubmit);
}this._configureUndo(true);
a.setFocus();
a.raiseEvent("selectionChange",Sys.EventArgs.Empty);
this._wrongWordsArray=null;
this._spellcheckComplete=true;
this._initialized=false;
},initialize:function(d,a){this._initialized=true;
this._wrongWordsArray=d.badWords;
this._wordOffsets=d.wordOffsets;
var b=this._editor;
this.SaveStateCmd=new Telerik.Web.UI.Editor.GenericCommand(this._localizedCommandName,b.get_contentWindow(),this._editor);
this.markWrongWords(a);
this._spellcheckComplete=false;
this._wrongWordCounter=0;
var c=this;
this.OnEditorSubmit=function(){c.finalize();
};
this._editor.add_submit(this.OnEditorSubmit);
this.OnMouseHandler=function(f){c._showSuggestionDropdown();
return $telerik.cancelRawEvent(f);
};
this.OnKeyDownHandler=function(j){if(j.keyCode==9){c.moveToNextWrongWord();
return $telerik.cancelRawEvent(j);
}var h=false;
if(c._suggestionDropdown){var f=c._suggestionDropdown;
var i=(f.isExpanded());
var g=j.keyCode;
if(i){if(38==g){f.selectPreviousItem();
h=true;
}else{if(40==g){f.selectNextItem();
h=true;
}else{if(13==g){f.hide();
if(f.get_activeIndex){f.set_selectedIndex(f.get_activeIndex());
}c._onDropDownValueSelected(f);
try{j.keyCode=123;
}catch(j){}h=true;
}else{if(27==g){f.hide();
}}}}h=true;
}}if(h){return $telerik.cancelRawEvent(j);
}};
this.OnContextMenu=function(f){if(this._editor.isIE){c.OnMouseHandler(f);
}f.cancelBubble=true;
if(this._editor.isIE){return false;
}};
window.setTimeout(function(){var f=c._editor;
f.attachEventHandler("click",c.OnMouseHandler);
f.attachEventHandler("keydown",c.OnKeyDownHandler);
f.attachEventHandler("contextmenu",Function.createDelegate(c,c.OnContextMenu));
if(c._automaticAdvance){f.setFocus();
if(f.isIE){try{var h=f.getSelection().getRange();
if(h){h.moveToElementText(f.get_contentArea());
h.collapse();
h.select();
}}catch(g){}}c.moveToNextWrongWord();
}},50);
this._configureUndo(false);
},moveToNextWrongWord:function(){var l=-1;
var k=this._editor.getSelection();
var d=k.getParentElement();
var m=null;
if(this.isHighlightedWord(d)&&!this._editor.getSelectionHtml()){m=d;
}else{k.collapse();
var c=this._editor;
var i=this;
var a=null;
function h(){var o=c.get_contentArea().getElementsByTagName("SPAN");
var e=0;
var p=o[e];
a=c.getSelection().getRange();
while(p!=null){if(i.isHighlightedWord(p)){var n=null;
if(c.isIE){if(a.duplicate){tempRange=a.duplicate();
}else{tempRange=c.get_contentArea().createTextRange();
}if(tempRange.moveToElementText){tempRange.moveToElementText(p);
}if(!a.compareEndPoints){break;
}n=a.compareEndPoints("EndToStart",tempRange);
if(0==n){m=p;
break;
}}else{if(a){tempRange=a.cloneRange();
tempRange.selectNodeContents(p);
n=a.compareBoundaryPoints(Range.END_TO_START,tempRange);
}}if(l==n){m=p;
break;
}}e++;
p=o[e];
}return p;
}var m=h();
if(!m){var g=c.get_contentArea();
if(g&&g.createTextRange){var f=g.createTextRange();
f.moveToElementText(g);
f.collapse(true);
f.select();
}else{var j=c.get_contentArea().getElementsByTagName("SPAN")[0];
if(j){c.selectElement(j);
}}try{var a=c.getSelection().getRange();
if(a&&a.moveStart){a.moveStart("character",-1);
a.select();
}}catch(b){}c.getSelection().collapse(true);
m=h();
}}if(m){this._editor.selectElement(m);
$telerik.scrollIntoView(m);
this._showSuggestionDropdown();
}},clearWrongWords:function(b,e){var d=this._editor.get_contentArea().getElementsByTagName("SPAN");
for(var a=0;
a<d.length;
a++){var c=d[a];
if(this.isHighlightedWord(c)){if(b){if(c.innerHTML==b){this.clearHighlightedElement(c,e);
a--;
}continue;
}else{this.clearHighlightedElement(c);
}a--;
}}},isHighlightedRemaining:function(){var b=this._editor.get_contentArea().getElementsByTagName("SPAN");
for(var a=0;
a<b.length;
a++){var c=b[a];
if(this.isHighlightedWord(c)){return true;
}}return false;
},getCurrentWrongWord:function(){var a=this._selectedEditorElement;
var b=a.innerHTML.replace(/<\/?[^>]*>/ig,"");
return b;
},isHighlightedWord:function(b){if(!b||!b.getAttribute){return false;
}var a=b.getAttribute("id");
if(a&&a.indexOf(this._spanId)>-1){return true;
}return false;
},clearHighlightedElement:function(c,h,a){var b=true;
if(c!=this._selectedEditorElement){b=false;
}var i=h?h:c.innerHTML.replace(/<\/?[^>]*>/ig,"");
var j=h?true:false;
this._editor.selectElement(c,false);
var f=new Telerik.Web.UI.Editor.GenericCommand(this._localizedName,this._editor.get_contentWindow(),this._editor);
var d=this._editor.get_document().createTextNode(i);
c.parentNode.replaceChild(d,c);
var g=this._editor.isIE;
if(g&&!i&&!h&&!a){return;
}if(g){if(a){this._editor.setActive();
}else{try{range=this._editor.get_contentArea().createTextRange();
range.findText(d.data);
range.select();
}catch(e){return;
}}}else{this._editor.selectElement(d,false);
}this._editor.getSelection().collapse();
if(j){this._editor.executeCommand(f);
}if(b){this._selectedEditorElement=null;
}},markWrongWords:function(a){var c=function(e,f,g,d){this.badWords=e;
this._wordOffsets=f;
this._spanId=g;
this.Content=d;
this.CurrentWordIndex=0;
this.Result=null;
};
c.prototype={GetSplitContent:function(){var e=new Array(this.badWords.length*2+1);
for(var d=0;
d<this.badWords.length;
d++){var f=d*2;
e[f]=this.GetBeforeText(d);
e[f+1]=this.badWords[d].wordString;
}e[e.length-1]=this.GetLastText();
return e;
},GetMarkedSplitContent:function(e){for(var d=1;
d<e.length;
d+=2){e[d]=this.GetMarkedWord(e[d]);
this.CurrentWordIndex++;
}return e;
},GetBeforeText:function(f){var e=0;
var d=this.GetWordStartIndex(this.badWords[f]);
if(f!=0){badWordBefore=this.badWords[f-1];
e=this.GetWordEndCharIndex(badWordBefore);
}return this.Content.substring(e,d);
},GetLastText:function(){var f=this.badWords[this.badWords.length-1];
var e=this.GetWordEndCharIndex(f);
var d=this.Content.length;
return this.GetSubContent(e,d);
},GetWordEndCharIndex:function(d){return this.GetWordStartIndex(d)+d.wordString.length;
},GetSubContent:function(e,d){return this.Content.substring(e,d);
},GetWordStartIndex:function(d){return this._wordOffsets[d.textOffset];
},GetMarkedWord:function(d){return"<span class='RadEWrongWord' id='"+this._spanId+this.CurrentWordIndex+"'>"+d+"</span>";
},GetResult:function(){if(this.Result==null){this.Result=this.GetMarkedSplitContent(this.GetSplitContent()).join("");
}return this.Result;
}};
var b=new c(this._wrongWordsArray,this._wordOffsets,this._spanId,this._escapeNewLines(a));
Telerik.Web.UI.Editor.Utils.setElementInnerHtml(this._editor.get_contentArea(),this._unescapeNewLines(b.GetResult()));
},_escapeNewLines:function(b){var a=b.replace(/\n/gi,"<telerikcr />");
a=a.replace(/\r/gi,"<teleriklf />");
return a;
},_unescapeNewLines:function(b){var a=b.replace(/\<telerikcr\s*\/\>/gi,"\n");
var a=a.replace(/\<teleriklf\s*\/\>/gi,"\r");
return a;
},_getSuggestionsForWord:function(f){var e=this._wrongWordsArray;
for(var a=0;
a<e.length;
a++){var c=e[a].wordString;
if(c==f){var d=e[a].suggestionsString;
if(d.length==0){return[["",this._noSuggestionsString]];
}else{d=d.concat([]);
for(var b=0;
b<d.length;
b++){d[b]=[d[b],d[b]];
}}return d;
}}return[];
},_get_footerItems:function(b){var a=[];
if(this._editor.get_spellAllowAddCustom()){a.splice(0,0,["reAdd_to_dictionary",this._addToDictionaryString,this._addIconCss]);
}a.splice(0,0,["reChange",this._changeWordString,this._okIconCss]);
if(this._occursMoreThanOnce(b)){a.splice(0,0,["reIgnore_all",this._ignoreAllString,this._ignoreIconCss]);
}a.splice(0,0,["",this._ignoreString,this._ignoreIconCss]);
return a;
},_occursMoreThanOnce:function(c){var d=this._editor.get_text();
var b=new RegExp("(\\b)"+c+"(\\b)","g");
var a=d.match(b);
return(a&&a.length>1);
},fire:function(h,g){var e=g.SelectedValue;
var b=this._selectedEditorElement&&this._selectedEditorElement.innerHTML?this._selectedEditorElement.innerHTML:"";
if(e=="reAdd_to_dictionary"){if(b.length>0){this.onAddCustomWord(this.getCurrentWrongWord());
}}else{if(e=="reIgnore_all"){this.clearWrongWords(b,"");
}else{if(e=="reChange"){this._showSuggestionBox(this._selectedEditorElement);
return;
}else{var c=false;
if(e){var d=this._occursMoreThanOnce(b);
if(d){var a=confirm(this._moreThanOnceMessage);
if(a){this.clearWrongWords(b,e);
c=true;
}}}if(!c){this.clearHighlightedElement(this._selectedEditorElement,e,true);
}}}}var f=this.isHighlightedRemaining();
if(!f){this.onSpellCheckComplete();
return;
}this._editor.raiseEvent("selectionChange",Sys.EventArgs.Empty);
if(this._automaticAdvance){this.moveToNextWrongWord();
}},_onDropDownValueSelected:function(b,c){var a=b.get_selectedItem();
this.fire("",{SelectedValue:a});
},_onDropDownBeforeShow:function(c,b){var a=this.getCurrentWrongWord();
var d=this._getSuggestionsForWord(a);
c.set_items(d);
},_showSuggestionDropdown:function(){var a=this._editor;
var c=a.getSelection().getParentElement();
if(!this.isHighlightedWord(c)){return;
}this._selectedEditorElement=c;
var d=this.getCurrentWrongWord();
if(!this._suggestionDropdown){this._onDropDownValueSelectedDelegate=Function.createDelegate(this,this._onDropDownValueSelected);
this._onDropDownBeforeShowDelegate=Function.createDelegate(this,this._onDropDownBeforeShow);
var b={valueSelected:this._onDropDownValueSelectedDelegate,show:this._onDropDownBeforeShowDelegate};
var f={};
f.popupwidth="160px";
f.parentElement=a.get_contentAreaElement();
f.skin=a.get_skin();
f.sizetofit=true;
var e=$create(Telerik.Web.UI.EditorSpellSuggestionBox,f,b,null,document.createElement("span"));
this._suggestionDropdown=e;
}var e=this._suggestionDropdown;
e.hide();
e.set_footerItems(this._get_footerItems(d));
e.set_wrongWordWrapper(c);
e.show();
e.selectNextItem();
if(a.isIE){a.setFocus();
}},_onTextboxValueSelected:function(c,b){var a=c.get_selectedItem();
this._editor.setFocus();
this.fire("",{SelectedValue:a});
},_showSuggestionBox:function(d){var b=this._editor;
if(!this._suggestionBox){this._onTextboxValueSelectedDelegate=Function.createDelegate(this,this._onTextboxValueSelected);
var c={valueSelected:this._onTextboxValueSelectedDelegate};
var g={};
g.parentElement=b.get_contentAreaElement();
g.skin=b.get_skin();
g.sizetofit=true;
var f=$create(Telerik.Web.UI.EditorAjaxSpellTextbox,g,c,null,document.createElement("span"));
this._suggestionBox=f;
}var a=this._suggestionBox;
var e=this.getCurrentWrongWord();
window.setTimeout(function(){a.set_wrongWordWrapper(d);
a.show();
a.setValue(e);
},10);
}};
Telerik.Web.UI.EditorSpellSuggestionBox=function(a){Telerik.Web.UI.EditorSpellSuggestionBox.initializeBase(this,[a]);
this._parentElement=null;
this._wrongWordWrapper=null;
this._maxItemSize=5;
};
Telerik.Web.UI.EditorSpellSuggestionBox.prototype={dispose:function(){this._wrongWordWrapper=null;
Telerik.Web.UI.EditorSpellSuggestionBox.callBaseMethod(this,"dispose");
},initialize:function(){this.set_popupclassname("reAjaxSpellCheck");
},set_footerItems:function(a){this._footerItems=a;
},renderChildren:function(){Telerik.Web.UI.EditorSpellSuggestionBox.callBaseMethod(this,"renderChildren");
var c=20;
var j=this._items.length>this._maxItemSize?this._maxItemSize:this._items.length;
var a=j>1?(j*c):25;
var d=document.createElement("div");
d.style.overflow="auto";
d.style.height=a+"px";
d.className="reAjaxSpellCheckSuggestions";
var f=this._itemRootElement;
f.cellSpacing="0";
var g=f.parentNode;
g.removeChild(f);
d.appendChild(f);
d.style.overflowX="hidden";
d.style.width="100%";
var k=this.renderItemRoot();
k.cellSpacing="0";
g.appendChild(k);
this.renderNewRow();
var l=this.renderItemContainer();
l.appendChild(d);
var h=document.createElement("div");
h.className="reAjaxSpellCheckSeparator";
l.appendChild(h);
var m=this._items.length;
for(var b=0;
b<this._footerItems.length;
b++){this.renderNewRow();
var e=this.renderItemContainer();
this.markItemContainer(e,m);
this.renderChild(e,this._footerItems[b],m);
m++;
}this._items=this._items.concat(this._footerItems);
},configurePopupPropertiesBeforeShow:function(){var d=this._popupBehavior;
d.set_positioningMode(Telerik.Web.PositioningMode.Absolute);
var a=this.get_parentElement();
if(a){if(a.tagName&&a.tagName.toLowerCase()!="iframe"){a=a.ownerDocument.body;
}d.set_parentElement(a);
}var c=this.get_wrongWordWrapper();
if(c){var e=$telerik.getBounds(c);
d.set_x(e.x);
var b=e.y+e.height;
if($telerik.isIE&&$telerik.quirksMode){b-=document.body.scrollTop;
}else{if(a.contentDocument){if($telerik.isIE){b-=a.contentDocument.getElementsByTagName("HTML")[0].scrollTop;
}else{if($telerik.isSafari){b-=a.contentDocument.body.scrollTop;
}}}else{if($telerik.isSafari||$telerik.isOpera){b+=this.get_parentElement().scrollTop;
}}}d.set_y(b);
}},get_parentElement:function(){return this._parentElement;
},set_parentElement:function(a){this._parentElement=a;
},get_maxItemSize:function(){return this._maxItemSize;
},set_maxItemSize:function(a){this._maxItemSize=a;
},get_wrongWordWrapper:function(){return this._wrongWordWrapper;
},set_wrongWordWrapper:function(a){this._wrongWordWrapper=a;
}};
Telerik.Web.UI.EditorSpellSuggestionBox.registerClass("Telerik.Web.UI.EditorSpellSuggestionBox",Telerik.Web.UI.EditorSplitButton);
Telerik.Web.UI.EditorAjaxSpellTextbox=function(a){Telerik.Web.UI.EditorAjaxSpellTextbox.initializeBase(this,[a]);
};
Telerik.Web.UI.EditorAjaxSpellTextbox.prototype={dispose:function(){if(null!=this._element){this._element.onchange=null;
this._element.onkeypress=null;
this._element.onclick=null;
this._element.Parent=null;
}this._element=null;
Telerik.Web.UI.EditorAjaxSpellTextbox.callBaseMethod(this,"dispose");
},setValue:function(a){if(this._textElement){this._textElement.value=a;
}var c=this._textElement;
try{if(c){c.focus();
}if(c&&c.setActive){c.setActive();
var b=document.selection.createRange();
b.moveStart("word",1);
b.select();
b.collapse();
}}catch(d){}},get_selectedItem:function(){return this._textElement.value;
},fire:function(){this.hide();
this.raiseEvent("valueSelected");
},attachEventHandlers:function(){},show:function(){if(!this._rendered){this.render();
}this._show();
},configurePopupPropertiesBeforeShow:function(){Telerik.Web.UI.EditorAjaxSpellTextbox.callBaseMethod(this,"configurePopupPropertiesBeforeShow");
var a=this._popupBehavior;
var b=this.get_wrongWordWrapper();
if(b){var c=$telerik.getBounds(b);
a.set_y(c.y);
}},renderChildren:function(){},renderItemRoot:function(){this._createBox();
this._itemRootElement=this._element;
return this._itemRootElement;
},_createBox:function(){var d=document.createElement("input");
d.setAttribute("size","20");
d.Parent=this;
var a=function(h,g,f){if(f){if(g.Executed){g.Executed=false;
return $telerik.cancelRawEvent(h);
}}g.Executed=true;
g.Parent.fire();
return $telerik.cancelRawEvent(h);
};
d.onclick=new Function("this.focus();");
d.onkeypress=function(f){if(!f){f=window.event;
}if(f&&f.keyCode==13){return a(f,this);
}};
this._textElement=d;
var c=document.createElement("div");
var b=document.createElement("button");
b.onmousedown=new Function("e","return false;");
b.onclick=new Function("e","this.parentNode.getElementsByTagName('input')[0].Parent.fire();return false;");
b.className="reAjaxspell_okicon";
c.appendChild(d);
c.appendChild(b);
this._element=c;
return this._element;
}};
Telerik.Web.UI.EditorAjaxSpellTextbox.registerClass("Telerik.Web.UI.EditorAjaxSpellTextbox",Telerik.Web.UI.EditorSpellSuggestionBox);
