Type.registerNamespace("Telerik.Web.UI");
(function(){var a=Telerik.Web.UI;
a.RadEditor=function(b){a.RadEditor.initializeBase(this,[b]);
this._textArea=null;
this._saveContentDelegate=null;
this._contentSaved=null;
};
a.RadEditor.prototype={initialize:function(){a.RadEditor.callBaseMethod(this,"initialize");
this._textArea=$get(this.get_id()+"TextArea");
this._registerPostBackHandlers();
if(this._textArea&&this._textArea.value){this._contentSaved=false;
var b=this.decodePostbackContent(this._textArea.value);
this.set_html(b);
}},dispose:function(){if(this._textArea&&this._textArea.form&&this._saveContentDelegate){$telerik.removeExternalHandler(this._textArea.form,"submit",this._saveContentDelegate);
}a.RadEditor.callBaseMethod(this,"dispose");
},saveContent:function(b,c){if(this._saveContentDelegate&&this._textArea&&!this._contentSaved){htmlValue=this.get_html();
this._textArea.value=this.encodePostbackContent(htmlValue);
this._contentSaved=true;
}},_registerPostBackHandlers:function(){this._saveContentDelegate=Function.createDelegate(this,this.saveContent);
var f=this._textArea.form;
if(f){$telerik.addExternalHandler(f,"submit",this._saveContentDelegate);
}if(typeof(__doPostBack)!="undefined"){var g=this._saveContentDelegate;
var h=__doPostBack;
__doPostBack=function(j,k){g();
h(j,k);
};
}if(typeof(Sys.WebForms)!="undefined"&&typeof(Sys.WebForms.PageRequestManager)!="undefined"){var d=Sys.WebForms.PageRequestManager.getInstance();
if(d){if(null!=d._originalDoPostBack){var e=this._saveContentDelegate;
var b=d._originalDoPostBack;
d._originalDoPostBack=function(j,k){e();
b(j,k);
};
}if(null!=d._onSubmitStatements&&!$telerik.isIE){var c=this;
var i={};
Array.add(d._onSubmitStatements,function(){c.saveContent(null,i);
return true;
});
}else{d.add_initializeRequest(this._saveContentDelegate);
}}d=null;
}f=null;
},get_mode:function(){},set_mode:function(b){},get_textArea:function(){return this._textArea;
},set_html:function(b){var c=b.replace(/\n?\<br[^\>]*?>/gi,"\n");
if(!(/\<[^\>]+\>/gi).test(c)){b=c;
}this.get_textArea().value=b;
},get_html:function(c){var b=this.get_textArea().value;
if(!(/\<[^\>]+\>/gi).test(b)){b=b.replace(/\n/g,"\n<br/>");
}return b;
},get_text:function(){return this.get_textArea().value;
},setSize:function(c,b){},pasteHtml:function(c,f,d,e,b){},get_contentArea:function(){return this.get_textArea();
},get_document:function(){return this.get_element().document;
},_encodeHtmlContent:function(c,b){var e=new Array("%","<",">","!",'"',"#","$","&","'","(",")",",",":",";","=","?","[","]","\\","^","`","{","|","}","~","+");
var d=c;
var f;
if(b){for(f=0;
f<e.length;
f++){d=d.replace(new RegExp("\\x"+e[f].charCodeAt(0).toString(16),"ig"),"%"+e[f].charCodeAt(0).toString(16));
}}else{for(f=e.length-1;
f>=0;
f--){d=d.replace(new RegExp("%"+e[f].charCodeAt(0).toString(16),"ig"),e[f]);
}}return d;
},encodePostbackContent:function(b){return this._encodeHtmlContent(b,true);
},decodePostbackContent:function(b){return this._encodeHtmlContent(b,false);
},setActive:function(){},set_editable:function(b){},get_editable:function(){},get_initialContent:function(){},add_firstShow:function(b){},remove_firstShow:function(b){},add_pasteHtml:function(b){},remove_pasteHtml:function(b){},add_editReady:function(b){},remove_editReady:function(b){},add_submit:function(b){},remove_submit:function(b){},add_commandExecuted:function(b){},remove_commandExecuted:function(b){},add_commandExecuting:function(b){},remove_commandExecuting:function(b){},add_selectionChange:function(b){},remove_selectionChange:function(b){},add_init:function(b){},remove_init:function(b){},add_load:function(b){},remove_load:function(b){},add_modeChange:function(b){},remove_modeChange:function(b){},add_toggleScreenMode:function(b){},remove_toggleScreenMode:function(b){},add_spellCheckLoaded:function(b){},remove_spellCheckLoaded:function(b){}};
a.RadEditor.registerClass("Telerik.Web.UI.RadEditor",a.RadWebControl);
})();
