Type.registerNamespace("Telerik.Web");
Type.registerNamespace("Telerik.Web.UI");
(function(){var b=$telerik.$;
var a=Telerik.Web.UI;
$telerik.toColorPicker=function(c){return c;
};
$telerik.findColorPicker=$find;
b.registerEnum(a,"PaletteModes",{WebPalette:1,RGBSliders:2,HSB:4,HSV:8,All:(1+2+4+8)});
a.ColorPickerColorChangeEventArgs=function(c){a.ColorPickerColorChangeEventArgs.initializeBase(this);
this._oldColor=c;
};
a.ColorPickerColorChangeEventArgs.prototype={get_oldColor:function(){return this._oldColor;
}};
a.ColorPickerColorChangeEventArgs.registerClass("Telerik.Web.UI.ColorPickerColorChangeEventArgs",Sys.EventArgs);
a.ColorPickerColorPreviewEventArgs=function(c){a.ColorPickerColorPreviewEventArgs.initializeBase(this);
this._color=c;
};
a.ColorPickerColorPreviewEventArgs.prototype={get_color:function(){return this._color;
}};
a.ColorPickerColorPreviewEventArgs.registerClass("Telerik.Web.UI.ColorPickerColorPreviewEventArgs",Sys.EventArgs);
a.ColorPickerColorSelectingEventArgs=a.ColorPickerColorPreviewEventArgs;
a.RadColorPicker=function(c){a.RadColorPicker.initializeBase(this,[c]);
this._selectedColor=null;
this._selectedColorName="";
this._autoPostBack=false;
this._enabled=true;
this._previewColor=true;
this._showIcon=false;
this._showEmptyColor=true;
this._lastPreviewColor="";
this._elementsByColor=[];
this._indexByColor=[];
this._mouseUpHandler=null;
this._localization=null;
this._popupBehavior=null;
this._paletteDisplayed=false;
this._uniqueID=null;
this._columns=18;
this._items=null;
this._width=0;
this._skin="Default";
this._overlay=false;
this._keepInScreenBounds=true;
this._paletteModes=a.PaletteModes.WebPalette;
this._selectedTab=null;
this._selectedContainer=null;
this._tabStrip=null;
this._multiPage=null;
this._webPalettePageView=null;
this._rgbPageView=null;
this._millionColorsPageView=null;
this._header=null;
this._rgbSlidersDefaultValue=255;
this._rgbSlidersDefaultSize=217;
this._redInput=null;
this._greenInput=null;
this._blueInput=null;
this._hexColorInput=null;
this._applyButton=null;
this._defaultRGBWidth=270;
this._rgbSlidersMinSize=115;
this._eventStartedInControl=false;
this._inputAvoidRecursion=false;
this._sliderAvoidRecursion=false;
this._millionColorsPalette=null;
this._millionColorsHandle=null;
this._millionColorsSliderWidth="22px";
this._millionColorsSliderHeight="162px";
this._defaultHSBWidth=345;
this._defaultHSVWidth=249;
this._millionColorsInputs=null;
this._millionColorsResizeExtender=null;
this._millionColorsAvoidRecursion=false;
this._millionColorsSliderAvoidRecursion=false;
this._hsbPaletteRange={x:255,y:159};
this._customPaletteRange={x:255,y:159};
this._hsvPalettePoints={x:159,y:159};
this._rightToLeft=false;
this._enableCustomColor=false;
this._customColorOkButton=null;
this._customColorCancelButton=null;
this._customColorPalette=null;
this._customColorPopupBehavior=null;
this._customColorModalExtender=null;
this._customColorPreviewElement=null;
this._hexCustomColorInput=null;
this._millionCustomColorsPalette=null;
this._millionCustomColorsHandle=null;
this._millionCustomColorsInputs={r:null,g:null,b:null,h:null,s:null,l:null};
this._millionCustomColorsResizeExtender=null;
this._showRecentColors=false;
this._recentColorsWrapper=null;
this._recentColors=[];
this._recentElementsByColor=[];
this._accessKey="";
this._tabIndex=0;
this._iconLink=null;
this._paletteSizes={};
this.ShowPalette=this.showPalette;
this.HidePalette=this.hidePalette;
this.GetIconContainer=this.getIconContainer;
this.GetPaletteContainer=this.getPaletteContainer;
};
a.RadColorPicker.prototype={initialize:function(){a.RadColorPicker.callBaseMethod(this,"initialize");
var c=this.get_element();
if($telerik.isRightToLeft(c)){Sys.UI.DomElement.addCssClass(c,"RadColorPickerRTL");
Sys.UI.DomElement.addCssClass(c,"RadColorPickerRTL_"+this._skin);
this._rightToLeft=true;
}this._initializeFields();
this._localization=eval(this._localization);
if(!this._showIcon){this._paletteDisplayed=true;
this._initializeColorElementsArray();
this._setElementsSize();
this._setRightRoundedCornerAndShadowHeight(this._paletteWrapperElement);
}this._initializeEventHandlers();
this._applyAccessKey();
this.set_selectedColor(this._selectedColor,false,true);
if(this._items){this._items=eval(this._items);
}this.raiseEvent("load");
},_initializeFields:function(){var q=this.get_id();
this._wrapperElement=$get(q);
this._previewElement=$get(q+"_preview");
this._emptyColorElement=$get(q+"_emptycolor");
this._iconElement=$get(q+"_icon");
var k=this._iconWrapperElement=$get(q+"_label");
if(k){this._iconLink=$telerik.getChildrenByTagName(k,"a")[0];
}var c=this._paletteWrapperElement=$get(q+"_palette");
if(c){var p=this._tabStrip=$telerik.getChildByClassName(c,"rcpTabs");
this._multiPage=$telerik.getChildByClassName(c,"rcpViews");
var e=this._webPalettePageView=$get(q+"_webPalette");
this._webPaletteWrapper=(e)?$telerik.getChildByClassName(e,"rcpWebPalette"):null;
var m=this._rgbPageView=$get(q+"_rgbSliders");
this._millionColorsPageView=$get(q+"_millionColors");
this._selectedContainer=(e)?e:(m?m:this._millionColorsPageView);
if(p){var l=p.getElementsByTagName("a");
for(var g=0,h=l.length;
g<h;
g++){this._initializeTabHandler(l[g]);
}this._selectedTab=$telerik.getElementByClassName(p,"rcpSelectedTab","li");
}this._recentColorsWrapper=$get(q+"_recentColors");
var d=this._header=$telerik.getChildByClassName(c,"rcpHeader");
if(d){var o=this._applyButton=$telerik.getChildByClassName(d,"rcpApplyButton");
if(o){this._initializeApplyHandler(o);
}var j=this._customColorButton=$telerik.getChildByClassName(d,"rcpCustomColorButton");
if(j){this._initializeCustomColorHandler(j);
}}}this._redInput=$get(q+"_redInput");
this._greenInput=$get(q+"_greenInput");
this._blueInput=$get(q+"_blueInput");
var n=this._hexColorInput=$get(q+"_hexInput");
if(this.get_redSlider()){this._initializeRgbInputHandler(this._redInput);
this._initializeRgbInputHandler(this._greenInput);
this._initializeRgbInputHandler(this._blueInput);
this._initializeRgbSliderHandler(this.get_redSlider());
this._initializeRgbSliderHandler(this.get_greenSlider());
this._initializeRgbSliderHandler(this.get_blueSlider());
}if(n){this._initializeHexHandler(n);
}this._millionColorsPalette=$get(q+"_millionColorsPalette");
this._initializeMillionColorsPaletteHandler();
this._millionColorsHandle=$get(q+"_millionColorsHandle");
this._createHandleResizeExtender();
this._initializeMillionColorsSliderHandler();
var f=this._millionColorsInputs={r:$get(q+"_rInput"),g:$get(q+"_gInput"),b:$get(q+"_bInput"),h:$get(q+"_hInput"),s:$get(q+"_sInput"),l:$get(q+"_lInput"),v:$get(q+"_vInput")};
this._initializeMillionColorsRgbInputHandler(f.r);
this._initializeMillionColorsRgbInputHandler(f.g);
this._initializeMillionColorsRgbInputHandler(f.b);
this._initializeMillionColorsInputHandler(f.h);
this._initializeMillionColorsInputHandler(f.s);
this._initializeMillionColorsInputHandler(f.l);
this._initializeMillionColorsInputHandler(f.v);
},dispose:function(){this._disposeControl("_millionColorsResizeExtender");
this._disposeControl("_popupBehavior");
this._disposeControl("_customColorPopupBehavior");
this._disposeControl("_customColorModalExtender");
this._disposeControl("_millionCustomColorsResizeExtender");
this._disposeHandlers();
this._selectedTab=null;
this._selectedContainer=null;
var e=this._tabStrip;
if(e){var f=e.getElementsByTagName("a");
for(var d=0,h=f.length;
d<h;
d++){$clearHandlers(f[d]);
}}var j=this._accessKeyTextbox;
if(j){$clearHandlers(j);
j.removeAttribute("accessKey");
this._accessKeyTextbox=null;
}this._tabStrip=null;
this._multiPage=null;
this._webPaletteWrapper=null;
this._webPalettePageView=null;
this._rgbPageView=null;
this._millionColorsPageView=null;
this._header=null;
this.set_redSlider(null);
this.set_greenSlider(null);
this.set_blueSlider(null);
this.set_hiddenSlider(null);
this._clearHandlers("_redInput");
this._clearHandlers("_greenInput");
this._clearHandlers("_blueInput");
this._clearHandlers("_hexColorInput");
this._clearHandlers("_applyButton");
this._clearHandlers("_customColorButton");
this._millionColorsPalette=null;
this._millionColorsHandle=null;
this.set_millionColorsSlider(null);
var g=this._millionColorsInputs;
this._clearHandlers(null,g.r);
this._clearHandlers(null,g.g);
this._clearHandlers(null,g.b);
this._clearHandlers(null,g.h);
this._clearHandlers(null,g.s);
this._clearHandlers(null,g.l);
this._clearHandlers(null,g.v);
this._millionColorsInputs=null;
this._paletteSizes=null;
this._elementsByColor=null;
this._indexByColor=null;
this._recentColors=null;
this._recentElementsByColor=null;
this._clearHandlers("_recentColorsWrapper");
this._customColorPreviewElement=null;
this._clearHandlers("_customColorOkButton");
this._clearHandlers("_customColorCancelButton");
this._clearHandlers("_hexCustomColorInput");
this._millionCustomColorsPalette=null;
this._millionCustomColorsHandle=null;
this.set_millionCustomColorsSlider(null);
g=this._millionCustomColorsInputs;
this._clearHandlers(null,g.r);
this._clearHandlers(null,g.g);
this._clearHandlers(null,g.b);
this._clearHandlers(null,g.h);
this._clearHandlers(null,g.s);
this._clearHandlers(null,g.l);
this._millionCustomColorsInputs=null;
var c=this._customColorPalette;
if(c){if(c.parentNode){c.parentNode.removeChild(c);
}this._customColorPalette=null;
}a.RadColorPicker.callBaseMethod(this,"dispose");
},repaint:function(){this._setElementsSize();
var c=this._paletteWrapperElement;
if(c){this._setRightRoundedCornerAndShadowHeight(c);
}},_disposeControl:function(d){var c=this[d];
if(c){c.dispose();
this[d]=null;
}},_clearHandlers:function(f,e){var d=(!e);
var c=d?this[f]:e;
if(c){$clearHandlers(c);
if(d){this[f]=null;
}}},_initializeColorElementsArray:function(){var j=this._webPaletteWrapper;
if(!j){return;
}var h=[];
var g=[];
var e=j.getElementsByTagName("a");
for(var c=0,f=e.length;
c<f;
c++){var d=e[c];
if(this._getColorBoxElement(d)){var k=this._getElementColor(d);
h[k]=d;
g[k]=c;
if(c>0){d.setAttribute("tabindex","-1");
}}}this._elementsByColor=h;
this._indexByColor=g;
},_setElementsSize:function(){if($telerik.getInvisibleParent(this.get_element())){return;
}var h=this._selectedContainer;
var j=a.PaletteModes.WebPalette;
var d="_setWebPaletteSize";
if(h==this._rgbPageView){j=a.PaletteModes.RGBSliders;
d="_setRGBSize";
}else{if(h==this._millionColorsPageView){j=(a.PaletteModes.HSB+a.PaletteModes.HSV);
d="_setMillionColorsSize";
}}var k=this._showIcon;
var f=k?this._paletteWrapperElement:this._wrapperElement;
if(!f){return;
}var i=this._getElementsSize(j);
var g=i.width;
if(parseInt(f.style.width)!=g){f.style.width=g+"px";
}this[d](i);
if(!k){var e=this._tabStrip;
if(e){var c=$telerik.getSize(e).height-1;
if(c>0&&parseInt(f.style.paddingBottom)!=c){f.style.paddingBottom=c+"px";
}}}},_setWebPaletteSize:function(m){var k=this._webPaletteWrapper;
if(!k){return;
}if(this.isModeEnabled(a.PaletteModes.WebPalette)){var f=m.colorBoxSize;
var c=$telerik.isOpera;
var d=m.colorBoxSizeOpera;
var n=k.getElementsByTagName("li");
for(var e=0,h=n.length;
e<h;
e++){var j=n[e];
var g=j.getElementsByTagName("span");
if(g.length>0){var l=g[0];
if(parseInt(l.style.width)!=f){l.style.width=f+"px";
l.style.height=f+"px";
}}if(c){j.style.width=d+"px";
}}}},_setRecentColorsSize:function(){var c=this._recentColorsWrapper;
if(this._showRecentColors&&c){c.style.height=this._getRecentColorWrapperSize()+"px";
}},_setRGBSize:function(c){var d=c.sliderSize;
this.get_redSlider().set_width(d);
this.get_greenSlider().set_width(d);
this.get_blueSlider().set_width(d);
},_setMillionColorsSize:function(c){},_getElementsSize:function(c){var s=this._paletteSizes;
var t=this._width;
var u=(t>0);
var k=this.getElementContentBox(this._paletteWrapperElement).horizontal;
var r=this._showIcon;
var n=r?k:this.getElementBox(this._wrapperElement).horizontal;
var p=k+this.getElementContentBox(this._multiPage).horizontal;
if(!r){p+=n;
}var h=p+this._getMinimumPaletteWidth();
var l,q,f;
if(this.isModeEnabled(a.PaletteModes.WebPalette)&&(c==a.PaletteModes.WebPalette)){var g=this._getWebPaletteElemenentsSize(t,h,p);
l=g.colorSize;
q=g.colorSizeOpera;
t=g.width-n;
s.webPalette=t;
}else{if(this.isModeEnabled(a.PaletteModes.RGBSliders)&&(c==a.PaletteModes.RGBSliders)){var v=this._defaultRGBWidth;
var d=Math.max(this._rgbSlidersMinSize,h);
if(!u){t=v;
}if(t<d){t=d;
}f=this._getRGBElemenentsSize(t,p);
t-=n;
s.rgbSliders=t;
}else{var i=this.isModeEnabled(a.PaletteModes.HSB)&&(c&a.PaletteModes.HSB);
if(i||(this.isModeEnabled(a.PaletteModes.HSV)&&(c&a.PaletteModes.HSV))){var m=Math.max(this._defaultHSBWidth,h);
var o=t;
if(!u||(u&&t<m)){o=m;
}o-=n;
s.hsb=o;
var j=Math.max(this._defaultHSVWidth,h);
var e=t;
if(!u||(u&&t<j)){e=j;
}e-=n;
s.hsv=e;
t=i?o:e;
}}}this._paletteSizes=s;
return{colorBoxSize:l,colorBoxSizeOpera:q,sliderSize:f,width:t};
},_getMinimumPaletteWidth:function(){var c=0;
var g=this._header;
if(g){c+=this.getElementBox(g).horizontal;
b(g).children(":visible").each(function(i,h){c+=h.offsetWidth+$telerik.getMarginBox(h).horizontal;
});
}var f=0;
var e=this._tabStrip;
if(e){f+=this.getElementBox(e).horizontal;
var d=parseInt($telerik.getCurrentStyle(e,"left",0));
if(!isNaN(d)){f+=d;
}b(e).children("ul").children(":visible").each(function(i,h){f+=h.offsetWidth+$telerik.getMarginBox(h).horizontal;
});
}return Math.max(0,Math.max(c,f));
},_getRecentColorWrapperSize:function(){var e=0;
var c=this._recentColorsWrapper;
if(c&&this._showRecentColors){var d=c.getElementsByTagName("li");
if(d.length>1&&c.style.height){return c.style.height;
}var g;
if(d.length==1){var f=d[0].getElementsByTagName("span");
if(f.length==1&&((b.trim(f[0].innerHTML)=="")||(b.trim(f[0].innerHTML)=="&nbsp;"))){g=d[0];
}}if(!g){g=this._createColorElement({},true);
c.appendChild(g);
}e=$telerik.getContentSize(c).height;
c.removeChild(g);
}return e;
},_getWebPaletteElemenentsSize:function(c,e,d){d+=this.getElementContentBox(this._webPalettePageView).horizontal;
return this._getColorBoxSize(c,e,d,this._webPaletteWrapper);
},_getColorBoxSize:function(o,e,m,j){var g=0;
var n=0;
var q=j;
if(q){m+=this.getElementContentBox(q).horizontal;
var i=$telerik.getFirstChildByTagName(q,"li");
if(i){n=$telerik.getOuterSize(i).width;
g+=this.getElementContentBox(i).horizontal;
var l=$telerik.getFirstChildByTagName(i,"a");
if(l){g+=this.getElementContentBox(l).horizontal;
var c=$telerik.getFirstChildByTagName(l,"span");
g+=this.getElementContentBox(c).horizontal;
}}}var h=this._columns;
var p=o;
if(!p){o=m+h*n;
}o=Math.max(e,o);
if(p){var f=o-m;
f=(f<1)?1:f;
n=parseInt(f/h);
n=(n<1)?1:n;
}var d=n;
var k=n-g;
k=(k<1)?1:k;
return{colorSize:k,colorSizeOpera:d,width:o};
},_getRGBElemenentsSize:function(e,h){h+=this.getElementContentBox(this._rgbPageView).horizontal;
var g=this._rgbSlidersDefaultSize-h;
var c=this._defaultRGBWidth;
if(e!=c){var f=this._redInput;
var d=$telerik.getChildrenByTagName(f.parentNode,"label")[0];
g=e-h;
g-=$telerik.getOuterSize(f).width;
g-=$telerik.getOuterSize(d).width;
if(g<50){g=50;
}}return g;
},_createPalette:function(h){if(this._webPaletteWrapper){return;
}var j=this._webPaletteWrapper=this._createElement("ul",null,{className:"rcpWebPalette"});
h.appendChild(j);
var e=0;
var l=this._columns;
var k=this._items;
if(this._tabIndex&&k.length>0){k[0].tabIndex=this._tabIndex;
}for(var d=0,f=k.length;
d<f;
d++){if(e==l){e=0;
var g=this._createElement("li",null,{className:"rcpBreakLine"});
j.appendChild(g);
}e++;
var c=this._createColorElement(k[d]);
j.appendChild(c);
}},_createColorElement:function(h,g){var e=(this._selectedColor==h.value)&&!g?"rcpSelectedColor":"rcpColorBox";
var c=this._createElement("li");
var d=this._createA(h.title,e,null,h.value);
if(h.tabIndex){d.setAttribute("tabindex",h.tabIndex);
}var f=this._createElement("span",h.value);
d.appendChild(f);
c.appendChild(d);
return c;
},_createHeader:function(k,e){if(!k){return;
}var g=this.isModeEnabled(a.PaletteModes.WebPalette);
var j=(this.isModeEnabled(a.PaletteModes.RGBSliders)||this.isModeEnabled(a.PaletteModes.HSB)||this.isModeEnabled(a.PaletteModes.HSV));
var c="rcpHeader";
var i=this._enableCustomColor;
if(!e){if(!this._previewColor&&!this._showEmptyColor&&!(g&&i)&&g){c+=" rcpEmptyHeader";
}}var l=e?$telerik.getChildByClassName(k,"rcpHeader"):this._header;
if(!l){l=this._createDiv(c);
k.appendChild(l);
if(!e){this._header=l;
}}this._createPreviewElement(l,e);
if(!e){this._createEmptyColorElement(l);
if(g&&i&&!this._customColorButton){var h=this._localization[14];
var d=this._customColorButton=this._createA(h,"rcpImageButton rcpCustomColorButton");
if(this._tabIndex){d.setAttribute("tabindex",this._tabIndex);
}l.appendChild(d);
this._initializeCustomColorHandler(d);
var f=this._createElement("span",h);
d.appendChild(f);
}this._createApplyButton((!g&&j),l);
}else{if(this._customColorOkButton){return;
}var d=this._customColorCancelButton=this._createA(null,"rcpButton rcpCancelButton");
l.appendChild(d);
$addHandler(d,"click",Function.createDelegate(this,this._cancelClick));
var f=this._createElement("span",this._localization[17]);
d.appendChild(f);
d=this._customColorOkButton=this._createA(null,"rcpButton rcpOkButton");
l.appendChild(d);
$addHandler(d,"click",Function.createDelegate(this,this._okClick));
f=this._createElement("span",this._localization[16]);
d.appendChild(f);
}},_createApplyButton:function(e,g){if(e&&!this._applyButton){var f=g?g:this._header;
if(!f){return;
}var c=this._applyButton=this._createA(null,"rcpButton rcpApplyButton");
if(this._tabIndex){c.setAttribute("tabindex",this._tabIndex);
}f.appendChild(c);
this._initializeApplyHandler(c);
var d=this._createElement("span",this._localization[7]);
c.appendChild(d);
}},_createRoundedCornersAndShadow:function(e,c){var d=this._createDiv("rcpRoundedRight");
e.appendChild(d);
d=this._createDiv("rcpRoundedBottomRight");
e.appendChild(d);
d=this._createDiv("rcpRoundedBottomLeft");
e.appendChild(d);
if($telerik.isIE6){return;
}if(c||this._showIcon){d=this._createDiv("rcpRightShadow");
e.appendChild(d);
d=this._createDiv("rcpCornerShadow");
e.appendChild(d);
d=this._createDiv("rcpBottomShadow");
e.appendChild(d);
}},_setRightRoundedCornerAndShadowHeight:function(c){var d=$telerik.getContentSize(c).height+"px";
b(c).children(".rcpRoundedRight").css("height",d);
b(c).children(".rcpRightShadow").css("height",d);
},_createRgbSliders:function(f){if(this.get_redSlider()){return;
}var e=this._createElement("ul");
f.appendChild(e);
var c=this.get_id();
var g=c+"_redSlider";
var d=c+"_redInput";
this._createRgbSliderWithInput(g,"rcpSlider rcpRedSlider","_redSlider",d,"rcpInput rcpRedInput","_redInput","R:",e);
g=c+"_greenSlider";
d=c+"_greenInput";
this._createRgbSliderWithInput(g,"rcpSlider rcpGreenSlider","_greenSlider",d,"rcpInput rcpGreenInput","_greenInput","G:",e);
g=c+"_blueSlider";
d=c+"_blueInput";
this._createRgbSliderWithInput(g,"rcpSlider rcpBlueSlider","_blueSlider",d,"rcpInput rcpBlueInput","_blueInput","B:",e);
this._updateRgbSlidersUI(this._getRgbFromHex());
},_createRgbSliderWithInput:function(f,g,c,l,h,k,j,n){var e=this._createElement("li");
n.appendChild(e);
var i=this._createElement("label",j,{htmlFor:l});
e.appendChild(i);
var d=this._createDiv(g,f);
e.appendChild(d);
this[c]=this._createSlider(d);
var m=this._createInput(h,this._rgbSlidersDefaultValue,l);
if(this._tabIndex){m.setAttribute("tabindex",this._tabIndex);
}e.appendChild(m);
this._initializeRgbInputHandler(m);
this[k]=m;
},_createSlider:function(e){var c=this._rgbSlidersDefaultValue;
var g=this._rgbSlidersDefaultSize+"px";
var d={itemData:[],_width:g,_skin:this._skin,maximumValue:c,value:c,_increaseText:this._localization[8],_decreaseText:this._localization[9],_tabIndex:-1,showIncreaseHandle:false,showDecreaseHandle:false,_dragText:this._localization[10]};
var f=$create(a.RadSlider,d,null,null,e);
this._initializeRgbSliderHandler(f);
return f;
},_rgbValuesToHex:function(g,c,f){var e="#";
var d=function(h){var i=parseInt(h,10).toString(16);
e=e+(i.length==1?"0"+i:i);
};
d(g);
d(c);
d(f);
d=null;
return e;
},_createHexColorInput:function(g,c){var d=c?null:this._selectedColor;
if(!d){var e=this._rgbSlidersDefaultValue;
d=this._rgbValuesToHex(e,e,e);
}var f=c?"_hexCustomColorInput":"_hexColorInput";
var h=this[f]=this._createInput("rcpHexInput",d);
if(this._tabIndex){h.setAttribute("tabindex",this._tabIndex);
}h.setAttribute("title",this._localization[18]);
g.appendChild(h);
if(!c&&this.isModeEnabled(a.PaletteModes.WebPalette)){h.readOnly="readonly";
}this._initializeHexHandler(h,c);
},_createMillionColors:function(n,g){if(this[g?"get_millionCustomColorsSlider":"get_millionColorsSlider"]()){return;
}var m=this.get_id();
var i=this[g?"_millionCustomColorsPalette":"_millionColorsPalette"]=this._createDiv("rcpMillionColorsPalette",(m+(g?"_millionCustomColorsPalette":"_millionColorsPalette")));
n.appendChild(i);
this._initializeMillionColorsPaletteHandler(g);
var f=this[g?"_millionCustomColorsHandle":"_millionColorsHandle"]=this._createElement("div","<!-- / -->",{className:"rcpMillionColorsHandle"},{top:"0px",left:"0px"});
i.appendChild(f);
this._createHandleResizeExtender(g);
var d=this._createDiv("rcpMillionColorsSlider",(m+(g?"_millionCustomColorsSlider":"_millionColorsSlider")));
n.appendChild(d);
var c=(g||this._isModeSelected(a.PaletteModes.HSB))?this._localization[11]:this._localization[12];
var k=0;
var h={itemData:[],_height:this._millionColorsSliderHeight,_width:this._millionColorsSliderWidth,_skin:this._skin,maximumValue:100,value:k,orientation:1,showIncreaseHandle:false,showDecreaseHandle:false,_tabIndex:-1,_dragText:c};
this[g?"set_millionCustomColorsSlider":"set_millionColorsSlider"]($create(a.RadSlider,h,null,null,d));
this._initializeMillionColorsSliderHandler(g);
var e=this._createDiv("rcpInputsWrapper");
n.appendChild(e);
var l=this._createElement("ul");
e.appendChild(l);
var j=g?"InputCustom":"Input";
this._createListItemWithInput((m+"_r"+j),"rcpInput rcpRedInput","r","R:","_initializeMillionColorsRgbInputHandler",l,null,g);
this._createListItemWithInput((m+"_g"+j),"rcpInput rcpGreenInput","g","G:","_initializeMillionColorsRgbInputHandler",l,null,g);
this._createListItemWithInput((m+"_b"+j),"rcpInput rcpBlueInput","b","B:","_initializeMillionColorsRgbInputHandler",l,null,g);
l=this._createElement("ul",null,{className:"rcpMillionColorsInputs"});
e.appendChild(l);
this._createListItemWithInput((m+"_h"+j),"rcpInput rcpHInput","h","H:","_initializeMillionColorsInputHandler",l,null,g);
this._createListItemWithInput((m+"_s"+j),"rcpInput rcpSInput","s","S:","_initializeMillionColorsInputHandler",l,null,g);
if(g||this.isModeEnabled(a.PaletteModes.HSB)){this._createListItemWithInput((m+"_l"+j),"rcpInput rcpLInput","l","B:","_initializeMillionColorsInputHandler",l,"rcpLInputWrapper",g);
}if(!g&&this.isModeEnabled(a.PaletteModes.HSV)){this._createListItemWithInput((m+"_v"+j),"rcpInput rcpVInput","v","V:","_initializeMillionColorsInputHandler",l,"rcpVInputWrapper");
}},_createListItemWithInput:function(k,e,j,i,h,m,c,f){var d=this._createElement("li",null,{className:c});
m.appendChild(d);
var g=this._createElement("label",i,{htmlFor:k});
d.appendChild(g);
var l=this._createInput(e,0,k);
if(this._tabIndex){l.setAttribute("tabindex",this._tabIndex);
}d.appendChild(l);
this[h](l,f);
this[f?"_millionCustomColorsInputs":"_millionColorsInputs"][j]=l;
},_createHandleResizeExtender:function(d){var c=this[d?"_millionCustomColorsHandle":"_millionColorsHandle"];
var e=this[d?"_millionCustomColorsPalette":"_millionColorsPalette"];
if(!c||!e){return;
}var g=$telerik.getCurrentStyle(e,"cursor","crosshair");
var f={};
f[g]=e;
this[d?"_millionCustomColorsResizeExtender":"_millionColorsResizeExtender"]=new a.ResizeExtender(this,c,f,null,null,g,false,true);
},_createCustomColorPalette:function(){var f=this._customColorPalette=this._createDiv(this.get_element().className+" rcpCustomColorWrapper");
var e=this.get_element();
var d=$telerik.getCurrentStyle(e,"zIndex",4000);
d=isNaN(d)?parseInt(e.style.zIndex):d;
d=isNaN(d)?4000:d;
f.style.zIndex=d+2;
f.style.position="absolute";
document.body.appendChild(f);
var g=this._createDiv("rcpPalette");
f.appendChild(g);
this._createRoundedCornersAndShadow(g,true);
this._createHeader(g,true);
var c=this._createDiv("rcpPageView rcpMillionColorsPageView rcpHsbPageView");
g.appendChild(c);
this._createMillionColors(c,true);
this._setRightRoundedCornerAndShadowHeight(g);
return f;
},_rgbSliderValueChanged:function(f,e){if(this._sliderAvoidRecursion){return;
}var c=this.get_redSlider().get_value();
var g=this.get_greenSlider().get_value();
var d=this.get_blueSlider().get_value();
this._sliderAvoidRecursion=true;
this._updateHexPreview(c,g,d);
this._updateRgbInputUI(f);
this._sliderAvoidRecursion=false;
},_millionColorsSliderValueChanged:function(f,d){if(this._sliderAvoidRecursion||this._millionColorsSliderAvoidRecursion){return;
}var c=(f===this.get_millionCustomColorsSlider());
var e=this._getMillionColorsCoordinates(c);
this._sliderAvoidRecursion=true;
this._updateMillionColorsInputsUI(e.x,e.y,c);
this._sliderAvoidRecursion=false;
},_hexColorChange:function(h,d){if(!h){return;
}if(!d&&this._isModeSelected(a.PaletteModes.WebPalette)){return;
}var g=h.target||h.srcElement;
if(!g){return;
}var i=g.value;
if(!this._validateHexValue(i)){this._previewCurrentColor((d?"#FFFFFF":this._selectedColor),null,null,d);
return;
}if(this._inputAvoidRecursion){return;
}if(d||this._selectedContainer){var f=this._getRgbFromHex(i);
var c=(d||this._isModeSelected(a.PaletteModes.HSB))?"_updateHslPaletteElementsUI":(this._isModeSelected(a.PaletteModes.RGBSliders)?"_updateRgbSlidersUI":"_updateHsvPaletteElementsUI");
this._inputAvoidRecursion=true;
this[c](f,null,d);
this._inputAvoidRecursion=false;
}},_hexCustomColorChange:function(c){this._hexColorChange(c,true);
},_rgbInputValueChange:function(g){if(!g){return;
}var h=g.target||g.srcElement;
if(!this._validateDecInput(h,0,255)){h.value=this._getSliderFromInput(h).get_value();
return;
}if(this._inputAvoidRecursion){return;
}var c=parseInt(this._redInput.value);
var f=parseInt(this._greenInput.value);
var d=parseInt(this._blueInput.value);
this._inputAvoidRecursion=true;
this._updateHexPreview(c,f,d);
this._updateRgbSliderUI(null,null,h);
this._inputAvoidRecursion=false;
},_millionColorsInputValueChange:function(j,d){if(!j){return;
}var h=j.target||j.srcElement;
var i=d||this._isMillionColorsTabSelected().HSB;
var k=this[d?"_millionCustomColorsInputs":"_millionColorsInputs"];
var l=(h.id==k.h.id)?360:100;
if(!this._validateDecInput(h,0,l)){var c=i?"_resetHslInputValue":"_resetHsvInputValue";
this[c](h,d);
return;
}if(this._inputAvoidRecursion){return;
}var f=i?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI";
var g=parseInt(k.h.value);
var m={h:((g==360)?0:g),s:parseInt(k.s.value)/100,l:(k.l?parseInt(k.l.value)/100:null),v:(k.v?parseInt(k.v.value)/100:null),hueValue:g};
this._inputAvoidRecursion=true;
this[f](null,m,d);
this._inputAvoidRecursion=false;
},_millionCustomColorsInputValueChange:function(c){return this._millionColorsInputValueChange(c,true);
},_millionColorsRgbInputValueChange:function(h,c){if(!h){return;
}var g=h.target||h.srcElement;
if(!this._validateDecInput(g,0,255)){this._resetRgbInputValue(g,c);
return;
}if(this._inputAvoidRecursion){return;
}if(c||this._selectedContainer){var i=this[c?"_millionCustomColorsInputs":"_millionColorsInputs"];
var d={r:parseInt(i.r.value),g:parseInt(i.g.value),b:parseInt(i.b.value)};
var f=(c||this._isMillionColorsTabSelected().HSB)?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI";
this._inputAvoidRecursion=true;
this[f](d,null,c);
this._inputAvoidRecursion=false;
}},_millionCustomColorsRgbInputValueChange:function(c){return this._millionColorsRgbInputValueChange(c,true);
},_onMillionColorsPaletteMouseDown:function(l,h){if(!this._enabled){return;
}if(this._millionColorsAvoidRecursion){return;
}var n=this[h?"_millionCustomColorsPalette":"_millionColorsPalette"];
var j=$telerik.getLocation(n);
var f=$telerik.getContentSize(n);
var k={x:f.width-1,y:f.height-1};
var c=$telerik.getBorderBox(n);
var i=$telerik.getTouchEventLocation(l);
var d=$telerik.isTouchDevice?{left:i.x,top:i.y}:$telerik.getDocumentRelativeCursorPosition(l);
var m=Math.round(d.left-j.x-c.left);
var g=Math.round(d.top-j.y-c.top);
m=(m<0)?0:(m>k.x?k.x:m);
g=(g<0)?0:(g>k.y?k.y:g);
this._updateMillionColorsHandleUI(m,g,h);
this._millionColorsAvoidRecursion=true;
this._updateMillionColorsInputsUI(m,g,h);
this._millionColorsAvoidRecursion=false;
},_onMillionCustomColorsPaletteMouseDown:function(c){this._onMillionColorsPaletteMouseDown(c,true);
},onDragStart:function(h){if(!this._enabled){return false;
}var d=h.element;
var f=this._cachedMillionColorsHandleSize=$telerik.getSize(d);
var g=Math.floor(f.width/2);
var j=Math.floor(f.height/2);
var e=this._cachedIsCustomColor=(d===this._millionCustomColorsHandle);
var i=e?this._millionCustomColorsPalette:this._millionColorsPalette;
var c=$telerik.getContentSize(i);
this._cachedMillionColorsPaletteBounds=new Sys.UI.Bounds(-g,-j,(c.width+g*2),(c.height+j*2));
this._eventStartedInControl=true;
return true;
},onDragEnd:function(f){var c=f.element;
var d=this._cachedIsCustomColor;
var e=this._cachedMillionColorsHandleSize;
this._updateMillionColorsInputsUI(parseInt(c.style.left)+Math.floor(e.width/2),parseInt(c.style.top)+Math.floor(e.height/2),d);
this._cachedMillionColorsHandleSize=null;
this._cachedMillionColorsPaletteBounds=null;
this._cachedIsCustomColor=null;
},onDrag:function(e){var c=this._cachedMillionColorsHandleSize;
var f=this._cachedMillionColorsPaletteBounds;
if(f.width<1||f.height<1){return false;
}e.width=c.width;
e.height=c.height;
var d=a.ResizeExtender.containsBounds(f,e);
if(!d){if(e.x<=f.x){e.x=f.x;
}else{if(f.x+f.width<=e.x+c.width){e.x=f.x+f.width-c.width;
}}if(e.y<=f.y){e.y=f.y;
}else{if(f.y+f.height<=e.y+c.height){e.y=f.y+f.height-c.height;
}}d=true;
}if(d){this._updateMillionColorsInputsUI(e.x+Math.floor(c.width/2),e.y+Math.floor(c.height/2),this._cachedIsCustomColor);
}return d;
},_updateRgbSlidersUI:function(c){if(!c){return;
}this._updateRgbSliderUI(this.get_redSlider(),c.r);
this._updateRgbSliderUI(this.get_greenSlider(),c.g);
this._updateRgbSliderUI(this.get_blueSlider(),c.b);
},_updateRgbSliderUI:function(d,c,e){var g=d;
var f=c;
if(!g){if(!e){return;
}g=this._getSliderFromInput(e);
f=parseInt(e.value);
}g.set_value(f);
},_updateRgbInputUI:function(c){if(!c){return;
}this._getInputFromSlider(c).value=c.get_value();
},_updateMillionColorsHandleUI:function(g,d,f){var c=this[f?"_millionCustomColorsHandle":"_millionColorsHandle"];
var e=$telerik.getSize(c);
$telerik.setLocation(c,{x:g-Math.floor(e.width/2),y:d-Math.floor(e.height/2)});
},_updateMillionColorsInputsUI:function(c,d,e){if(this._inputAvoidRecursion){return;
}var h=this._isMillionColorsTabSelected();
var g=e||h.HSB;
if(!g&&!h.HSV){return;
}var i=this[g?"_getHslFromCoordinates":"_getHsvFromCoordinates"](c,d,e);
var f=this[g?"_hslToRgb":"_hsvToRgb"](i.h,i.s,i[g?"l":"v"]);
this[g?"_updateHslSliderBackground":"_updateHsvPaletteBackground"](i,e);
this._updateMillionColorsInputsValues(f,i,e);
this._updateHexPreview(f.r,f.g,f.b,e);
},_updateMillionColorsInputsValues:function(f,e,c){var d=this[c?"_millionCustomColorsInputs":"_millionColorsInputs"];
if(f){d.r.value=f.r;
d.g.value=f.g;
d.b.value=f.b;
}d.h.value=Math.round(e.hueValue);
d.s.value=Math.round(e.s*100);
if(e.l!=null){d.l.value=Math.round(e.l*100);
}if(e.v!=null){d.v.value=Math.round(e.v*100);
}},_updateHslPaletteElementsUI:function(f,h,e){if(!f&&!h){return;
}var g=(f)?f:this._hslToRgb(h.h,h.s,h.l);
var i=(h)?h:this._rgbToHsl(f);
this._updateHexPreview(g.r,g.g,g.b,e);
this._updateMillionColorsInputsValues(g,i,e);
this._updateHslSliderBackground(i,e);
var c=e?this._customPaletteRange:this._hsbPaletteRange;
this._updateMillionColorsHandleUI(Math.round(i.h*c.x/360),c.y-Math.round(i.s*c.y),e);
var d=e?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
d.set_value(100-Math.round(i.l*100));
},_updateHslSliderBackground:function(f,d){var c=this._hslToRgb(f.h,f.s,0.5);
var e=d?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
e._trackElement.style.backgroundColor=this._rgbValuesToHex(c.r,c.g,c.b);
},_updateHsvPaletteElementsUI:function(g,d){if(!g&&!d){return;
}var e=(g)?g:this._hsvToRgb(d.h,d.s,d.v);
var c=(d)?d:this._rgbToHsv(g);
this._updateHexPreview(e.r,e.g,e.b);
this._updateMillionColorsInputsValues(e,c);
this._updateHsvPaletteBackground(c);
var f=this._hsvPalettePoints;
this._updateMillionColorsHandleUI(Math.round(c.s*f.x),f.y-Math.round(c.v*f.y));
this.get_millionColorsSlider().set_value(100-Math.round(c.h*100/360));
},_updateHsvPaletteBackground:function(d){var c=this._hsvToRgb(d.h,1,1);
this._millionColorsPalette.style.backgroundColor=this._rgbValuesToHex(c.r,c.g,c.b);
},_updateHexPreview:function(f,e,c,g){var d=this._rgbValuesToHex(f,e,c);
this._previewCurrentColor(d,true,null,g);
},_getRgbFromHex:function(c){var d=c;
if(!d){var e=this._selectedColor;
d=(e)?e:"#FFFFFF";
}return this._hexToRgb(d);
},_resetRgbInputValue:function(e,c){var g;
var f=this[c?"_hexCustomColorInput":"_hexColorInput"];
if(f){g=this._getRgbFromHex(f.value);
}else{var d=this._getMillionColorsCoordinates(c);
if(c||this._isModeSelected(a.PaletteModes.HSB)){var i=this._getHslFromCoordinates(d.x,d.y,c);
rgb=this._hslToRgb(i.h,i.s,i.l);
}else{if(this._isModeSelected(a.PaletteModes.HSV)){var h=this._getHsvFromCoordinates(d.x,d.y);
rgb=this._hsvToRgb(h.h,h.s,h.v);
}}}var j=this[c?"_millionCustomColorsInputs":"_millionColorsInputs"];
e.value=(e===j.r)?g.r:(e===j.g?g.g:g.b);
},_resetHslInputValue:function(d,c){var e=this._getMillionColorsCoordinates(c);
var f=this._getHslFromCoordinates(e.x,e.y,c);
this._updateMillionColorsInputsValues(null,f,c);
},_resetHsvInputValue:function(c){var e=this._getMillionColorsCoordinates();
var d=this._getHsvFromCoordinates(e.x,e.y);
this._updateMillionColorsInputsValues(null,d);
},_validateDecInput:function(c,f,e){var g=parseInt(c.value);
var d=(!isNaN(g));
if(d){d=(g>=f&&g<=e);
}return d;
},_validateHexValue:function(c){var d=/^#?(([0-9a-f]{3})|([0-9a-f]{6}))$/i;
return d.test(c);
},_getSliderFromInput:function(c){var d=this._getColorElementPrefix(c.id.toLowerCase());
return this[d+"Slider"];
},_getInputFromSlider:function(d){var c=this._getColorElementPrefix(d.get_id().toLowerCase());
return this[c+"Input"];
},_getColorElementPrefix:function(c){var d="";
if(!c){return d;
}if(c.indexOf("red")>-1){d="_red";
}else{if(c.indexOf("green")>-1){d="_green";
}else{if(c.indexOf("blue")>-1){d="_blue";
}}}return d;
},_getMillionColorsCoordinates:function(d){var c=this[d?"_millionCustomColorsHandle":"_millionColorsHandle"];
if(!c){return{x:0,y:0};
}var e=$telerik.getSize(c);
var g=parseInt(c.style.left)+Math.floor(e.width/2);
var f=parseInt(c.style.top)+Math.floor(e.height/2);
return{x:g,y:f};
},_getHslFromCoordinates:function(d,e,f){var c=f?this._customPaletteRange:this._hsbPaletteRange;
var h=(d/c.x*360);
var k=(d==c.x)?0:h;
var j=1-e/c.y;
var i=f?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
var g=1-(i.get_value()/100);
return{h:k,s:j,l:g,hueValue:h};
},_getHsvFromCoordinates:function(d,e){var h=this.get_millionColorsSlider().get_value();
var g=360*(1-h/100);
var j=(h==0)?0:g;
var f=this._hsvPalettePoints;
var i=d/f.x;
var c=1-e/f.y;
return{h:j,s:i,v:c,hueValue:g};
},_hexToRgb:function(c){if(!c){return null;
}var e={r:0,g:0,b:0};
if(c.indexOf("#")!=-1){c=c.substring(1,c.length);
}if(c.length==3){var d=function(f){return(f+f);
};
c=c.replace(/([0-9a-f])/gi,d);
}e.r=parseInt(c.substring(0,2),16);
e.g=parseInt(c.substring(2,4),16);
e.b=parseInt(c.substring(4,6),16);
return e;
},_hslToRgb:function(d,g,f){var h=this._hueToRgb(d);
h=this._addRgbVectors(this._multiplyRgbVectorByNum(g,h),this._multiplyRgbVectorByNum((1-g),{r:128,g:128,b:128}));
if(f!=0.5){var e=(f<0.5)?{r:0,g:0,b:0}:{r:255,g:255,b:255};
var c=2*Math.abs(0.5-f);
h=this._addRgbVectors(this._multiplyRgbVectorByNum(c,e),this._multiplyRgbVectorByNum((1-c),h));
}return h;
},_hsvToRgb:function(h,g,c){var e={r:0,g:0,b:0};
if(g==0){e={r:c,g:c,b:c};
}else{var f=(1-g)*c;
var d=c*g*(h%60)/60;
if(h<60){e={r:c,g:(f+d),b:f};
}else{if(h<120){e={r:c-d,g:c,b:f};
}else{if(h<180){e={r:f,g:c,b:f+d};
}else{if(h<240){e={r:f,g:c-d,b:c};
}else{if(h<300){e={r:f+d,g:f,b:c};
}else{if(h<360){e={r:c,g:f,b:c-d};
}}}}}}}return this._multiplyRgbVectorByNum(255,e);
},_hueToRgb:function(f){var c={};
var d=f/60;
var e=d-Math.floor(d);
if(d<1){c={r:1,g:e,b:0};
}else{if(d<2){c={r:(1-e),g:1,b:0};
}else{if(d<3){c={r:0,g:1,b:e};
}else{if(d<4){c={r:0,g:(1-e),b:1};
}else{if(d<5){c={r:e,g:0,b:1};
}else{c={r:1,g:0,b:(1-e)};
}}}}}return this._multiplyRgbVectorByNum(255,c);
},_rgbToHsl:function(d){var e={};
var c=Math.min(Math.min(d.r,d.g),d.b);
var h=Math.max(Math.max(d.r,d.g),d.b);
var f=(h+c);
var g=h-c;
e.l=f/(2*255);
if(g==0){e.h=0;
e.s=0;
}else{e.s=g/((e.l<=0.5)?f:(2*255-f));
e.h=this._rgbToHue(d,g);
}e.hueValue=e.h;
return e;
},_rgbToHsv:function(g){var c={};
var f=Math.max(Math.max(g.r,g.g),g.b);
var e=Math.min(Math.min(g.r,g.g),g.b);
var d=f-e;
c.v=(f/255);
if(d==0){c.h=0;
c.s=0;
}else{c.s=(d/f);
c.h=this._rgbToHue(g,d);
}c.hueValue=c.h;
return c;
},_rgbToHue:function(e,c){var d=0;
if(e.r>=e.g&&e.g>=e.b){d=60*(e.g-e.b)/c;
}else{if(e.g>=e.r&&e.r>=e.b){d=60+60*(e.g-e.r)/c;
}else{if(e.g>=e.b&&e.b>=e.r){d=120+60*(e.b-e.r)/c;
}else{if(e.b>=e.g&&e.g>=e.r){d=180+60*(e.b-e.g)/c;
}else{if(e.b>=e.r&&e.r>=e.g){d=240+60*(e.r-e.g)/c;
}else{if(e.r>=e.b&&e.b>=e.g){d=300+60*(e.r-e.b)/c;
}}}}}}return Math.round(d);
},_isModeSelected:function(g,h,c){var d=false;
var f=h?h:this._selectedContainer;
if(f){if(g==a.PaletteModes.WebPalette){d=(this._webPalettePageView===f);
}else{if(g==a.PaletteModes.RGBSliders){d=(this._rgbPageView===f);
}else{var i=c?c:this._selectedTab;
var e=this._isMillionColorsTabSelected(i);
d=(g==a.PaletteModes.HSB)?e.HSB:e.HSV;
}}}return d;
},_isMillionColorsTabSelected:function(c){var d=c;
if(!d){d=this._selectedTab;
}if(d){var e=d.getElementsByTagName("span")[0].innerHTML;
return{HSB:(e==this._localization[5]),HSV:(e==this._localization[6])};
}else{return{HSB:this.isModeEnabled(a.PaletteModes.HSB),HSV:this.isModeEnabled(a.PaletteModes.HSV)};
}},_fixInRgbRange:function(d,c){if(c){d=Math.round(d);
}if(d<0){d=0;
}else{if(d>255){d=255;
}}return d;
},_addRgbVectors:function(d,c){return{r:this._fixInRgbRange(d.r+c.r),g:this._fixInRgbRange(d.g+c.g),b:this._fixInRgbRange(d.b+c.b)};
},_multiplyRgbVectorByNum:function(d,c){return{r:this._fixInRgbRange(c.r*d,true),g:this._fixInRgbRange(c.g*d,true),b:this._fixInRgbRange(c.b*d,true)};
},isModeEnabled:function(c){return c&this._paletteModes?true:false;
},_createTabStrip:function(){if(this._multiPage){return;
}var m=this.get_element();
var e=this.get_id();
var o=this._showIcon;
var q=this._paletteWrapperElement=this._createDiv("rcpPalette",(e+"_palette"));
if(o){if(!$telerik.isIE6){q.style.position="absolute";
}q.style.visibility="hidden";
}m.appendChild(q);
this._createRoundedCornersAndShadow(q);
if(o){var n=$telerik.getCurrentStyle(m,"zIndex",4000);
n=isNaN(n)?parseInt(m.style.zIndex):n;
n=isNaN(n)?4000:n;
q.style.zIndex=n+1;
}var c=this.isModeEnabled(a.PaletteModes.WebPalette);
var j=this.isModeEnabled(a.PaletteModes.RGBSliders);
var g=this.isModeEnabled(a.PaletteModes.HSB);
var d=this.isModeEnabled(a.PaletteModes.HSV);
var h=this.get_id();
var l=null;
if(c&&j||c&&g||c&&d||j&&g||j&&d||g&&d){var r=this._tabStrip=this._createDiv("rcpTabs");
q.appendChild(r);
l=this._createElement("ul");
r.appendChild(l);
}this._createHeader(q);
var s=this._multiPage=this._createElement("div",null,{className:"rcpViews"});
q.appendChild(s);
var k=h+"_webPalette";
var f="rcpPageView";
var i=true;
if(c){this._createTabWithContainer(i,f,s,"_webPalettePageView","_createPalette",this._localization[3],l,k);
i=false;
}if(j){k=h+"_rgbSliders";
this._createTabWithContainer(i,(f+" rcpRGBPageView"),s,"_rgbPageView","_createRgbSliders",this._localization[4],l,k);
i=false;
}if(g){k=h+"_millionColors";
var p=f+" rcpMillionColorsPageView rcpHsbPageView";
this._createTabWithContainer(i,p,s,"_millionColorsPageView","_createMillionColors",this._localization[5],l,k);
i=false;
}if(d){k=h+"_millionColors";
var p=f+" rcpMillionColorsPageView rcpHsvPageView";
this._createTabWithContainer(i,p,s,"_millionColorsPageView","_createMillionColors",this._localization[6],l,k);
}this._setElementsSize();
this._initializeColorElementsArray();
this._initializePalleteEventHandlers();
if(this._recentColors&&this._recentColors.length>0){this._updateRecentColors();
}if(!this._popupBehavior){this._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:e+"PopupBehavior",parentElement:this._iconWrapperElement,overlay:this._overlay,keepInScreenBounds:this._keepInScreenBounds,manageVisibility:false},null,null,q);
}this._setRightRoundedCornerAndShadowHeight(q);
},_createRecentColors:function(h){if(!this._showRecentColors||!h||this._recentColorsWrapper){return;
}var d=document.createElement("div");
h.appendChild(d);
var f=this.get_id()+"_recentColors";
var e=this._localization[15];
if(e){var i=this._createElement("span",e,{className:"rcpRecentColorsLabel"});
d.appendChild(i);
}var g=this._recentColorsWrapper=this._createElement("ul",null,{className:"rcpRecentColors",id:f});
d.appendChild(g);
this._setRecentColorsSize();
this._setRightRoundedCornerAndShadowHeight(this._paletteWrapperElement);
if($telerik.isIE6){var c=this.get_element();
c.style.cssText=c.style.cssText;
}$addHandlers(g,{mouseover:this._onBoxMouseOver,mouseup:this._onRecentBoxClick,mouseout:this._onBoxMouseOut,click:$telerik.cancelRawEvent,selectstart:$telerik.cancelRawEvent,keydown:this._recentColorsKeyDown},this);
},_createTabWithContainer:function(e,c,f,i,h,g,j,k){if(j){var d=this._createTab(g,k);
j.appendChild(d);
}var l=this[i];
if(!l){l=this[i]=this._createDiv(c,k,null,(e?null:"none"));
f.appendChild(l);
}if(e){this._updateTabSelection(d,l);
this[h](l);
}},_createTab:function(g,c){var e=this._createElement("li");
var d=this._createA(g,null,c);
if(this._tabIndex){d.setAttribute("tabindex",this._tabIndex);
}this._initializeTabHandler(d);
e.appendChild(d);
var f=this._createElement("span",g);
d.appendChild(f);
return e;
},_createEmptyColorElement:function(c){if(!this._showEmptyColor||this._emptyColorElement){return;
}var d=this._localization[2];
var e=this._emptyColorElement=this._createA(d,"rcpImageButton rcpEmptyColor");
e.id=this.get_id()+"_emptycolor";
if(this._tabIndex){e.setAttribute("tabindex",this._tabIndex);
}c.appendChild(e);
var f=this._createElement("span",d);
e.appendChild(f);
},_createPreviewElement:function(h,d){if(!d&&!this._previewColor){return;
}var e=d?"#fff":this._selectedColor;
if(!e){e="#fff";
}var g=d?"_customColorPreviewElement":"_previewElement";
if(this[g]){return;
}var c=this.get_id()+(d?"_customColorPreview":"_preview");
var f=this[g]=this._createDiv("rcpColorPreview",c,e,null,"<!-- / -->");
h.appendChild(f);
this._createHexColorInput(h,d);
},_tabClicked:function(m){if(this._enabled){var d=(m.target||m.srcElement);
var o=this._getParentByTagName(d,"li");
var j=this._getParentByTagName(d,"a");
if(!j){return;
}var r=j.getAttribute("rel");
var h=$get(r);
if(!o||!h){return;
}var g=this._isModeSelected(a.PaletteModes.RGBSliders,h);
var l=this._isModeSelected(a.PaletteModes.HSB,h,o);
var p=l||this._isModeSelected(a.PaletteModes.HSV,h,o);
var c="webPalette";
this._updateHeader(g||p);
this._updateTabSelection(o,h);
if(this._isModeSelected(a.PaletteModes.WebPalette,h)){this._createPalette(h);
}else{if(g){this._createRgbSliders(h);
c="rgbSliders";
}else{if(p){this._createMillionColors(h);
c=l?"hsb":"hsv";
var n=this.get_millionColorsSlider();
l?n.set_dragText(this._localization[11]):n.set_dragText(this._localization[12]);
}}}this._setElementsSize();
var q=this._paletteSizes[c];
var k=this._paletteWrapperElement;
var i=this._showIcon?k:this._wrapperElement;
if(i&&(parseInt(i.style.width)!=q)){i.style.width=q+"px";
}this._setRightRoundedCornerAndShadowHeight(k);
this.set_selectedColor(this._selectedColor,false,true);
this._updateOverlaySize();
if($telerik.isIE){var f=this.get_element();
f.style.cssText=f.style.cssText;
}}return $telerik.cancelRawEvent(m);
},_updateTabSelection:function(f,g){if(f&&g){var c=this._isMillionColorsTabSelected(f);
if(c.HSB){Sys.UI.DomElement.removeCssClass(g,"rcpHsvPageView");
Sys.UI.DomElement.addCssClass(g,"rcpHsbPageView");
}else{if(c.HSV){Sys.UI.DomElement.removeCssClass(g,"rcpHsbPageView");
Sys.UI.DomElement.addCssClass(g,"rcpHsvPageView");
}}var e=this._selectedTab;
var d=this._selectedContainer;
if(e&&d){Sys.UI.DomElement.removeCssClass(e,"rcpSelectedTab");
d.style.display="none";
}Sys.UI.DomElement.addCssClass(f,"rcpSelectedTab");
g.style.display="";
}this._selectedTab=f;
this._selectedContainer=g;
},_updateHeader:function(c){if(c&&!this._applyButton){this._createApplyButton(c);
}var g=this._applyButton;
if(g){g.style.display=c?"":"none";
}var e=this._customColorButton;
if(e){e.style.display=c?"none":"";
}var f=this._hexColorInput;
if(f){f.readOnly=c?"":"readonly";
}var d=this._header;
if(d){Sys.UI.DomElement.removeCssClass(d,"rcpEmptyHeader");
if(!c&&!e&&!f&&!this._emptyColorElement){Sys.UI.DomElement.addCssClass(d,"rcpEmptyHeader");
}}},_updateOverlaySize:function(){var c=this._paletteWrapperElement;
var d=c._hideWindowedElementsIFrame;
if(!d){return;
}$telerik.setSize(d,$telerik.getOuterSize(c));
},_initializeTabHandler:function(c){$addHandler(c,"click",Function.createDelegate(this,this._tabClicked));
},_initializeApplyHandler:function(c){$addHandler(c,"click",Function.createDelegate(this,this._applyClick));
},_initializeCustomColorHandler:function(c){$addHandler(c,"click",Function.createDelegate(this,this._customColorClick));
},_initializeHexHandler:function(e,d){if(!d){if(!this.isModeEnabled(a.PaletteModes.RGBSliders)&&!this.isModeEnabled(a.PaletteModes.HSB)&&!this.isModeEnabled(a.PaletteModes.HSV)){return;
}}var c=d?"_hexCustomColorChange":"_hexColorChange";
var f=d?"_hexCustomKeyDown":"_hexKeyDown";
$addHandlers(e,{blur:this[c],keydown:this[f]},this);
},_initializeRgbInputHandler:function(c){$addHandlers(c,{blur:this._rgbInputValueChange,keydown:this._rgbInputKeyDown},this);
},_initializeRgbSliderHandler:function(c){var e=this;
var f=function(g,h){e._rgbSliderValueChanged(g,h);
};
var d=function(g,h){e._eventStartedInControl=true;
};
c.add_valueChanged(f);
if(this._showIcon){c.add_slideStart(d);
}},_initializeMillionColorsRgbInputHandler:function(e,d){if(!e){return;
}var c=d?"_millionCustomColorsRgbInputValueChange":"_millionColorsRgbInputValueChange";
var f=d?"_millionCustomColorsRgbInputKeyDown":"_millionColorsRgbInputKeyDown";
$addHandlers(e,{blur:this[c],keydown:this[f]},this);
},_initializeMillionColorsInputHandler:function(e,d){if(!e){return;
}var c=d?"_millionCustomColorsInputValueChange":"_millionColorsInputValueChange";
var f=d?"_millionCustomColorsInputKeyDown":"_millionColorsInputKeyDown";
$addHandlers(e,{blur:this[c],keydown:this[f]},this);
},_initializeMillionColorsSliderHandler:function(f){var c=f?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
if(!c){return;
}var e=this;
var g=function(h,i){e._millionColorsSliderValueChanged(h,i);
};
var d=function(h,i){e._eventStartedInControl=true;
};
c.add_valueChanged(g);
if(this._showIcon){c.add_slideStart(d);
}},_initializeMillionColorsPaletteHandler:function(d){var c=this[d?"_millionCustomColorsPalette":"_millionColorsPalette"];
if(c){$telerik.addMobileHandler(this,c,"mousedown",this[d?"_onMillionCustomColorsPaletteMouseDown":"_onMillionColorsPaletteMouseDown"]);
}},_createElement:function(d,e,j,k){var h=document.createElement(d);
for(var i in j){var c=j[i];
if(c!=null&&c.toString()!=""){h[i]=c;
}}for(var g in k){var f=k[g];
if(f!=null&&f.toString()!=""){h.style[g]=f;
}}if(e){h.innerHTML=e;
}return h;
},_createA:function(f,e,c,d){return this._createElement("a",null,{className:e,href:"#",title:f,rel:c},{backgroundColor:d});
},_createDiv:function(f,d,g,c,e){return this._createElement("div",e,{className:f,id:d},{background:g,display:c});
},_createInput:function(e,d,c){return this._createElement("input",null,{className:e,id:c,type:"text",value:d});
},getElementBox:function(e){var f={horizontal:0,vertical:0};
if(e){var d=$telerik.getBorderBox(e);
var c=$telerik.getPaddingBox(e);
f.horizontal=d.horizontal+c.horizontal;
f.vertical=d.vertical+c.vertical;
}return f;
},getElementContentBox:function(d){var e=this.getElementBox(d);
if(d){var c=$telerik.getMarginBox(d);
e.horizontal=e.horizontal+c.horizontal;
e.vertical=e.vertical+c.vertical;
}return e;
},showPalette:function(){if(this._paletteDisplayed){return;
}this._createTabStrip();
var g=this._popupBehavior;
var c=g._firstPopup;
g.set_x(0);
g.set_y($telerik.getSize(this._iconWrapperElement).height);
g.show();
var h=this._paletteWrapperElement;
h.style.visibility="";
if(c&&this._selectedContainer){var e=this._paletteSizes;
var i=this._isModeSelected(a.PaletteModes.WebPalette)?e.webPalette:(this._isModeSelected(a.PaletteModes.RGBSliders)?e.rgbSliders:(this._isModeSelected(a.PaletteModes.HSB)?e.hsb:e.hsv));
var d=this._showIcon?h:this._wrapperElement;
if(d&&(parseInt(d.style.width)!=i)){d.style.width=i+"px";
}}var f=this._applyButton;
var j=this._customColorButton;
if($telerik.isIE6&&(f||j)){if(f){f.style.visibility="visible";
}if(j){j.style.visibility="visible";
}setTimeout(Function.createDelegate(this,function(){if(f){f.style.visibility="";
}if(j){j.style.visibility="";
}}),0);
}this.set_selectedColor(this._selectedColor,false,true);
this._paletteDisplayed=true;
this.raiseEvent("popUpShow",Sys.EventArgs.Empty);
},hidePalette:function(){var c=this._popupBehavior;
if(c){var d=this._paletteWrapperElement;
d.style.top="-9999px";
d.style.left="-9999px";
c.hide();
}this._paletteDisplayed=false;
},getIconContainer:function(){return this._iconWrapperElement;
},getPaletteContainer:function(){return this._paletteWrapperElement;
},get_selectedColor:function(){return this._selectedColor;
},set_selectedColor:function(c,g,j){if(!c||(c.toString().toLowerCase()=="null")){c=null;
}else{if(!this._validateHexValue(c)){return;
}if(c.indexOf("#")!=-1){c=c.substring(1,c.length);
}if(c.length==3){var f=function(o){return(o+o);
};
c=c.replace(/([0-9a-f])/gi,f);
}c="#"+c;
}var e=this._selectedColor;
if(!e){e=null;
}if(c!=null){c=c.toUpperCase();
}if(c!=e){var h=b.raiseCancellableControlEvent(this,"colorChanging",{oldColor:e,newColor:c});
if(h){var l=this._getBoxElementByColor(e);
if(l!=null){l.focus();
}var i=this._getBoxElementByColor(c);
if(i!=null){i.blur();
}return;
}}this._selectedColor=c;
this._previewCurrentColor(c);
if(this._showIcon){this._setIconColor(c);
}if(!g&&this._selectedContainer){if(this._isModeSelected(a.PaletteModes.WebPalette)){var m=this._emptyColorElement;
var d=this._getMarkedElement();
if(d!=null){if(d!=m){d.className="rcpColorBox";
}}d=this._getBoxElementByColor(c);
if(d!=null){this._setMarkedElement(d);
if(d!=m){d.className="rcpSelectedColor";
}}}else{var k=this._isModeSelected(a.PaletteModes.RGBSliders)?"_updateRgbSlidersUI":(this._isModeSelected(a.PaletteModes.HSB)?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI");
this._millionColorsSliderAvoidRecursion=true;
this[k](this._getRgbFromHex(c));
this._millionColorsSliderAvoidRecursion=false;
}}if(!j){this._updateRecentColors(c);
}this.updateClientState();
if(this._selectedColor!=e){var n=new a.ColorPickerColorChangeEventArgs(e);
this.raiseEvent("colorChange",n);
if(this._autoPostBack){this._raiseColorChangedServerEvent();
}}},get_selectedColorTitle:function(){var c=this._getBoxElementByColor(this._selectedColor);
if(c!=null){return c.getAttribute("title");
}return this._selectedColor;
},get_enabled:function(){return this._enabled;
},set_enabled:function(c){if(this._enabled==c){return;
}this._enabled=c;
if(!this._wrapperElement){return;
}var h=[this.get_redSlider(),this.get_greenSlider(),this.get_blueSlider(),this.get_millionColorsSlider()];
for(var d=0,k=h.length;
d<k;
d++){var f=h[d];
if(f&&f.set_enabled){f.set_enabled(c);
}}var j=[this._hexColorInput,this._redInput,this._greenInput,this._blueInput,this._accessKeyTextbox];
var l=this._millionColorsInputs;
if(l){j=j.concat([l.r,l.g,l.b,l.h,l.s,l.l,l.v]);
}var e=this.get_element();
if(c){Sys.UI.DomElement.removeCssClass(e,"rcpDisabled");
e.removeAttribute("disabled");
for(var d=0,k=j.length;
d<k;
d++){var g=j[d];
if(g){g.removeAttribute("disabled");
}}}else{Sys.UI.DomElement.addCssClass(e,"rcpDisabled");
e.setAttribute("disabled","disabled");
for(var d=0,k=j.length;
d<k;
d++){var g=j[d];
if(g){g.setAttribute("disabled","disabled");
}}}},get_overlay:function(){return this._overlay;
},set_overlay:function(c){this._overlay=c;
var d=this._customColorPopupBehavior;
if(d){d.set_overlay(c);
}var e=this._popupBehavior;
if(e){e.set_overlay(c);
if(this._showIcon&&this._paletteDisplayed){e.show();
}}},get_keepInScreenBounds:function(){return this._keepInScreenBounds;
},set_keepInScreenBounds:function(c){this._keepInScreenBounds=c;
var d=this._customColorPopupBehavior;
if(d){d.set_keepInScreenBounds(c);
}var e=this._popupBehavior;
if(e){e.set_keepInScreenBounds(c);
if(this._showIcon&&this._paletteDisplayed){e.show();
}}},_initializeEventHandlers:function(){this._initializePalleteEventHandlers();
if(this._showIcon){$addHandlers(this._iconLink,{click:this._onIconMouseUp,keydown:this._iconKeyDown},this);
$addHandlers(this.get_element(),{mousedown:this._onWrapperMouseDown},this);
this._mouseUpHandler=Function.createDelegate(this,this._onMouseUp);
$telerik.addExternalHandler(document,"mouseup",this._mouseUpHandler);
}},_applyAccessKey:function(){if(!this._accessKey){return;
}if($telerik.isChrome||$telerik.isSafari){var e=document.createElement("div");
e.style.width="0px";
e.style.height="0px";
e.style.overflow="hidden";
this.get_element().appendChild(e);
var d=this._accessKeyTextbox=document.createElement("input");
d.setAttribute("type","text");
var c=this.get_id()+"ColorPickerAccessKey";
d.setAttribute("name",c);
d.setAttribute("id",c);
d.setAttribute("accessKey",this._accessKey);
e.appendChild(d);
$addHandlers(d,{focus:this._accessKeyPressed},this);
}},_accessKeyPressed:function(c){var d=this._iconLink;
if(!d){d=this._getFirstChildByTagName(this._tabStrip,"a");
if(!d){d=this._getFirstChildByTagName(this._webPaletteWrapper,"a");
if(!d){d=this._redInput;
if(!d&&this._millionColorsInputs){d=this._millionColorsInputs.r;
}}}}if(d){d.focus();
}},_getFirstChildByTagName:function(d,c){if(d){var e=d.getElementsByTagName(c);
if(e&&e.length>0){return e[0];
}}return null;
},_iconKeyDown:function(g){g=g.rawEvent||g;
var d=g.keyCode||g.which;
var c=(d==Sys.UI.Key.esc)||(g.altKey&&d==Sys.UI.Key.up);
var f=g.altKey&&(d==Sys.UI.Key.down);
if(!f&&!c){return;
}$telerik.cancelRawEvent(g);
if(c){this.hidePalette();
}else{this.showPalette();
}return false;
},_hexCustomKeyDown:function(c){this._hexKeyDown(c,true);
},_hexKeyDown:function(f,c){f=f.rawEvent||f;
var d=f.keyCode||f.which;
if(d!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(f);
this._hexColorChange(f,c);
if(c){this._okClick();
}else{this._applyClick(f);
}return false;
},_rgbInputKeyDown:function(d){d=d.rawEvent||d;
var c=d.keyCode||d.which;
if(c!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(d);
this._rgbInputValueChange(d);
this._applyClick(d);
return false;
},_millionCustomColorsRgbInputKeyDown:function(c){this._millionColorsRgbInputKeyDown(c,true);
},_millionColorsRgbInputKeyDown:function(f,c){f=f.rawEvent||f;
var d=f.keyCode||f.which;
if(d!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(f);
this._millionColorsRgbInputValueChange(f,c);
if(c){this._okClick();
}else{this._applyClick(f);
}return false;
},_millionCustomColorsInputKeyDown:function(c){this._millionColorsInputKeyDown(c,true);
},_millionColorsInputKeyDown:function(f,c){f=f.rawEvent||f;
var d=f.keyCode||f.which;
if(d!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(f);
this._millionColorsInputValueChange(f,c);
if(c){this._okClick();
}else{this._applyClick(f);
}return false;
},_webPaletteKeyDown:function(i){i=i.rawEvent||i;
var h=i.keyCode||i.which;
if(h==Sys.UI.Key.enter){$telerik.cancelRawEvent(i);
this._onBoxClick(i);
}else{var g=this._getColorBoxElement(i.target||i.srcElement);
if(!g){return;
}var d=this._indexByColor[this._getElementColor(g)];
var j=this._columns;
var k=this._webPaletteWrapper.getElementsByTagName("a");
var c=d;
switch(h){case Sys.UI.Key.up:c-=j;
break;
case Sys.UI.Key.down:c+=j;
break;
case Sys.UI.Key.left:c-=1;
break;
case Sys.UI.Key.right:c+=1;
break;
case Sys.UI.Key.home:c=0;
break;
case Sys.UI.Key.end:c=k.length-1;
break;
default:return;
}c=Math.max(0,Math.min(k.length-1,c));
var f=k[c];
f.focus();
this._previewCurrentColor(this._getElementColor(f),true,f.title);
}$telerik.cancelRawEvent(i);
return false;
},_recentColorsKeyDown:function(j){j=j.rawEvent||j;
var i=j.keyCode||j.which;
if(i==Sys.UI.Key.enter){this._onRecentBoxClick(j);
}else{var f=this._recentColors;
if(!f){return;
}var h=this._getColorBoxElement(j.target||j.srcElement);
if(!h){return;
}var d=Array.indexOf(f,this._getElementColor(h));
var k=this._recentColorsWrapper.getElementsByTagName("a");
var c=d;
switch(i){case Sys.UI.Key.up:c-=1;
break;
case Sys.UI.Key.down:c+=1;
break;
case Sys.UI.Key.left:c-=1;
break;
case Sys.UI.Key.right:c+=1;
break;
case Sys.UI.Key.home:c=0;
break;
case Sys.UI.Key.end:c=k.length-1;
break;
default:return;
}c=Math.max(0,Math.min(k.length-1,c));
var g=k[c];
g.focus();
this._previewCurrentColor(this._getElementColor(g),true,g.title);
}$telerik.cancelRawEvent(j);
return false;
},_initializePalleteEventHandlers:function(){var c=this._webPaletteWrapper;
if(c){$addHandlers(c,{mouseover:this._onBoxMouseOver,mouseup:this._onBoxClick,mouseout:this._onBoxMouseOut,click:$telerik.cancelRawEvent,selectstart:$telerik.cancelRawEvent,keydown:this._webPaletteKeyDown},this);
}var d=this._emptyColorElement;
if(d&&this._showEmptyColor){$addHandlers(d,{click:this._onEmptyColorClick},this);
}},_disposeHandlers:function(){var c=this._webPaletteWrapper;
if(c){$clearHandlers(c);
}var d=this._emptyColorElement;
if(d&&this._showEmptyColor){$clearHandlers(d);
}if(this._showIcon){$clearHandlers(this._iconLink);
$clearHandlers(this.get_element());
$telerik.removeExternalHandler(document,"mouseup",this._mouseUpHandler);
this._iconWrapperElement=null;
this._iconLink=null;
}this._mouseUpHandler=null;
},_raiseColorChangedServerEvent:function(){setTimeout(Function.createDelegate(this,function(){__doPostBack(this._uniqueID);
}),0);
},_onMouseUp:function(c){if(!this._enabled){return;
}if(this._eventStartedInControl){this._eventStartedInControl=false;
return;
}var d=c.target||c.srcElement;
if($telerik.isDescendantOrSelf(this._paletteWrapperElement,d)){return;
}this.hidePalette();
},_onBoxMouseOver:function(f){if(!this._enabled){return;
}var d=this._getColorBoxElement(f.target||f.srcElement);
if(d==null){return;
}var c=this._getElementColor(d);
this._previewCurrentColor(c,true,d.title);
},_onBoxMouseOut:function(f){if($telerik.isMouseOverElementEx(this._webPaletteWrapper,f)){return;
}var c=this._recentColorsWrapper;
var d=this.get_selectedColor();
if(c){if($telerik.isMouseOverElementEx(c,f)){return;
}if(this._selectedContainer&&!this._isModeSelected(a.PaletteModes.WebPalette)){d=this._getColorFromRGBControls();
}}this._previewCurrentColor(d);
},_applyClick:function(f){if(this._enabled){var d=this._hexColorInput;
var c=d?d.value:this._getColorFromRGBControls();
this._applyColorAndClose(c,true);
}return $telerik.cancelRawEvent(f);
},_cancelClick:function(c){return this._closeCustomColorPalette(c);
},_okClick:function(f){if(this._enabled){var d=this._hexCustomColorInput;
var c=d?d.value:this._getColorFromRGBControls(true);
this.set_selectedColor(c);
return this._closeCustomColorPalette(f);
}return $telerik.cancelRawEvent(f);
},_customColorClick:function(j){var h=this._customColorModalExtender;
var f=this._customColorPopupBehavior;
if(!f){var d=this._customColorPalette;
if(!d){d=this._createCustomColorPalette();
}h=this._customColorModalExtender=new a.ModalExtender(d);
f=this._customColorPopupBehavior=$create(Telerik.Web.PopupBehavior,{id:this.get_id()+"CustomColorPopupBehavior",overlay:this._overlay,parentElement:document.documentElement,keepInScreenBounds:this._keepInScreenBounds},null,null,d);
}var c=this._getCentralBounds();
f.set_x(c.x);
f.set_y(c.y);
f.show();
h.show();
this._millionColorsSliderAvoidRecursion=true;
this._updateHslPaletteElementsUI(this._getRgbFromHex("#FFFFFF"),null,true);
this._millionColorsSliderAvoidRecursion=false;
var g=this._customColorOkButton;
var i=this._customColorCancelButton;
if($telerik.isIE6&&(g||i)){if(g){g.style.visibility="visible";
}if(i){i.style.visibility="visible";
}setTimeout(Function.createDelegate(this,function(){if(g){g.style.visibility="";
}if(i){i.style.visibility="";
}}),0);
}this._millionCustomColorsInputs.r.focus();
if(this._showIcon){this.hidePalette();
}return $telerik.cancelRawEvent(j);
},_getCentralBounds:function(){var f=this._customColorPalette;
var g={width:parseInt($telerik.getCurrentStyle(f,"width","350px")),height:parseInt($telerik.getCurrentStyle(f,"height","325px"))};
var c=this._getViewportBounds();
var d=parseInt((c.width-g.width)/2);
var e=parseInt((c.height-g.height)/2);
g.x=d+c.scrollLeft;
g.y=e+c.scrollTop;
return g;
},_getViewportBounds:function(){var e=$telerik.getClientBounds();
var c=$telerik.getCorrectScrollLeft(document.documentElement)||$telerik.getCorrectScrollLeft(document.body);
var d=document.documentElement.scrollTop||document.body.scrollTop;
e.scrollLeft=c;
e.scrollTop=d;
if(this.isIE){if(e.width==0){e.width=document.body.clientWidth;
}if(e.height==0){e.height=document.body.clientHeight;
}}return e;
},_getColorFromRGBControls:function(c){var e;
if(!c&&this._isModeSelected(a.PaletteModes.RGBSliders)){e={r:this.get_redSlider().get_value(),g:this.get_greenSlider().get_value(),b:this.get_blueSlider().get_value()};
}else{var d=this[c?"_millionCustomColorsInputs":"_millionColorsInputs"];
e={r:parseInt(d.r.value),g:parseInt(d.g.value),b:parseInt(d.b.value)};
}return this._rgbValuesToHex(e.r,e.g,e.b);
},_onEmptyColorClick:function(c){if(this._enabled){this._applyColorAndClose(null);
}return $telerik.cancelRawEvent(c);
},_applyColorAndClose:function(c,e,f){var d=this._showIcon;
this.set_selectedColor(c,(d||e),f);
if(d){this.hidePalette();
}},_closeCustomColorPalette:function(f){var c=this._customColorModalExtender;
if(c){c.hide();
}var d=this._customColorPopupBehavior;
if(d){d.hide();
}return $telerik.cancelRawEvent(f);
},_onWrapperMouseDown:function(c){if(!this._enabled){return;
}this._eventStartedInControl=true;
},_onIconMouseUp:function(c){if(this._enabled){if(this._paletteDisplayed){this.hidePalette();
}else{this.showPalette();
}}return $telerik.cancelRawEvent(c);
},_getElementColor:function(c){if(c==this._emptyColorElement){return null;
}return c.firstChild.innerHTML;
},_setIconColor:function(c){var e=(c)?c:this._localization[13];
var d=b.trim(this._localization[0]+" "+this._localization[1].toString().replace("{0}",e));
if(d!=""){this._iconWrapperElement.title=d;
}this._iconElement.style.backgroundColor=(c)?c:"#FFFFFF";
},_onBoxClick:function(d,f){if(this._enabled){this._eventStartedInControl=false;
if(d.button){return;
}var c=this._getColorBoxElement(d.target||d.srcElement);
if(!c){return;
}this._applyColorAndClose(this._getElementColor(c),false,f);
}return $telerik.cancelRawEvent(d);
},_onRecentBoxClick:function(c){return this._onBoxClick(c,true);
},_getMarkedElement:function(){var h=this._markedElement;
if(h){return h;
}var e=this._webPaletteWrapper;
if(!e){return null;
}var f=e.getElementsByTagName("A");
for(var c=0,g=f.length;
c<g;
c++){var d=f[c];
if(d.className=="rcpSelectedColor"){return d;
}}return null;
},_setMarkedElement:function(c){this._markedElement=c;
},_getColorBoxElement:function(d){var e=3;
var c=0;
while(c<e){if(d.className=="rcpColorBox"||d.className=="rcpSelectedColor"||d.className.indexOf("rcpEmptyColor")>-1){return d;
}c++;
d=d.parentNode;
}return null;
},_getParentByTagName:function(e,c){var f=3;
var d=0;
while(d<f){if(e.tagName.toLowerCase()==c){return e;
}d++;
e=e.parentNode;
}return null;
},_getBoxElementByColor:function(c){if(!c){return this._emptyColorElement;
}c=c.toUpperCase();
return this._elementsByColor[c];
},_previewCurrentColor:function(i,c,d,e){if(!this.get_isInitialized()){return;
}if(c&&(i!=this._lastPreviewColor)){var h=new a.ColorPickerColorPreviewEventArgs(i);
this.raiseEvent("colorPreview",h);
}this._lastPreviewColor=i;
if(!this._previewColor&&!e){return;
}if(i==null){i="#FFFFFF";
d=this._localization[2];
}i=i.toUpperCase();
if(!d){d=i;
}var f=this[e?"_customColorPreviewElement":"_previewElement"];
if(f){f.style.backgroundColor=i;
}var g=this[e?"_hexCustomColorInput":"_hexColorInput"];
if(g){g.value=i;
}},_updateRecentColors:function(e){var n=this._recentColors;
if(e){var l=Array.indexOf(n,e);
if(l>-1){n.splice(l,1);
}if(n.unshift(e)>this._columns){n.pop();
}}if(this._showRecentColors&&n.length>0){if(!this._recentColorsWrapper){this._createRecentColors(this._multiPage);
}var m=this._recentColorsWrapper;
if(m){var o=this._recentElementsByColor;
for(var k=0,j=n.length;
k<j;
k++){var f=n[k];
var g=this._getBoxElementByColor(f);
var h={value:f,title:(g?g.title:f)};
var d=o[k];
if(!d){var p=this._createColorElement(h,true);
m.appendChild(p);
o[o.length]=d=$telerik.getFirstChildByTagName(p,"a");
}else{d.title=h.title;
d.style.backgroundColor=h.value;
var c=$telerik.getFirstChildByTagName(d,"span");
if(c){c.innerHTML=h.value;
}}d.removeAttribute("tabIndex");
if(k>0){d.setAttribute("tabIndex","-1");
}else{if(this._tabIndex){d.setAttribute("tabIndex",this._tabIndex);
}}}if(o.length>0){m.style.height="";
}}}},saveClientState:function(){var c=["selectedColor"];
var e={};
for(var d=0;
d<c.length;
d++){e[c[d]]=this["get_"+c[d]]();
}return Sys.Serialization.JavaScriptSerializer.serialize(e);
}};
b.registerControlProperties(a.RadColorPicker,{paletteModes:a.PaletteModes.WebPalette,hiddenSlider:null,redSlider:null,greenSlider:null,blueSlider:null,millionColorsSlider:null,millionCustomColorsSlider:null});
b.registerControlEvents(a.RadColorPicker,["load","colorPreview","colorChanging","colorChange","popUpShow"]);
a.RadColorPicker.registerClass("Telerik.Web.UI.RadColorPicker",a.RadWebControl);
})();
