(function(b){var a=Telerik.Web.UI;
var b=$telerik.$;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarChild=function(c){this._parent=null;
this._element=null;
if(c){this._element=c;
}this._text="";
this._imageElement=null;
this._ribbonBar=null;
};
a.RibbonBarChild.prototype={get_element:function(){return this._element;
},set_element:function(c){this._element=c;
},get_text:function(){return this._text;
},set_text:function(c){this._text=c;
},get_imageElement:function(){if(!this._imageElement){if(this._element){var d=b(".rrbButtonImage",this._element);
if(d.length==0){var c=b(".rrbButtonIn",this._element);
var g=b(".rrbButtonText",this._element);
var e=($telerik.isIE&&!$telerik.isIE9)?"about:blank":"";
var f=b('<span class="rrbImagePlaceholder"><img src="'+e+'" class="rrbButtonImage" style="visibility: hidden;"></span>');
if(g.length>0){f.insertBefore(g);
}else{c.append(f);
}this._imageElement=b(".rrbButtonImage",this._element)[0];
}else{this._imageElement=d[0];
}}}return this._imageElement;
},set_image:function(c){var e=this.get_imageElement();
if(e){var d=($telerik.isIE&&!$telerik.isIE9)?"about:blank":"";
if(c==""){c=d;
}e.src=c;
this._resolveImageVisibility();
}},_resolveImageVisibility:function(){var c=this.get_imageElement();
if(c){var d=c.src;
if($telerik.isIE&&(d[d.length-1]=="#")){c.style.visibility="hidden";
}else{c.style.visibility="visible";
}}},get_index:function(){return this._parent.indexOf(this);
},_getRibbonBar:function(){return this._ribbonBar;
},_setRibbonBar:function(c){this._ribbonBar=c;
}};
a.RibbonBarChild.registerClass("Telerik.Web.UI.RibbonBarChild");
})($telerik.$);
(function(){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarChildCollection=function(b){this._owner=b;
this._array=new Array();
};
a.RibbonBarChildCollection.prototype={add:function(b){this._array[this._array.length]=b;
b._parent=this;
if(this._owner&&this._owner._onChildAdded){this._owner._onChildAdded(b);
}},get_count:function(){return this._array.length;
},getItem:function(b){return this._array[b];
},indexOf:function(d){for(var b=0,c=this._array.length;
b<c;
b++){if(this._array[b]===d){return b;
}}return -1;
},forEach:function(d){for(var c=0,b=this.get_count();
c<b;
c++){d(this._array[c]);
}}};
a.RibbonBarChildCollection.registerClass("Telerik.Web.UI.RibbonBarChildCollection");
})();
(function(){var a=Telerik.Web.UI;
var b=$telerik.$;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarTab=function(c){a.RibbonBarTab.initializeBase(this,[c]);
if(c){c._tab=this;
}this._value="";
this._labelElement=null;
this._textElement=null;
this._ribbonBar=null;
this._pageView=null;
this._groups=new a.RibbonBarGroupCollection(this);
};
a.RibbonBarTab.prototype={get_value:function(){return this._value;
},set_value:function(c){this._value=c;
},get_ribbonBar:function(){return this._ribbonBar;
},get_pageView:function(){return this._pageView;
},set_pageView:function(c){this._pageView=c;
},set_ribbonBar:function(c){this._ribbonBar=c;
},get_groups:function(){return this._groups;
},get_textElement:function(){if(!this._textElement){var c=this.get_element();
if(c){this._textElement=b(">.rrbTabLabel>.rrbTabText",c)[0];
}}return this._textElement;
},get_labelElement:function(){if(!this._labelElement){var c=this.get_element();
if(c){this._labelElement=b(">.rrbTabLabel",c)[0];
}}return this._labelElement;
},get_text:function(){if(!this._text){var c=this.get_textElement();
if(c){this._text=b(c).text();
}}return this._text;
},get_hierarchicalIndex:function(){var c=""+this.get_index();
return c;
},set_text:function(d){this._text=d;
var c=this.get_textElement();
if(c){b(c).text(d);
}},findItemByText:function(f){for(var c=0;
c<this._groups.get_count();
c++){var d=this._groups.getGroup(c);
var e=d.findItemByText(f);
if(e){return e;
}}return null;
},findGroupByValue:function(c){var f=this._groups;
var g=f.get_count();
for(var d=0;
d<g;
d++){var e=f.getGroup(d);
if(e.get_value()==c){return e;
}}return null;
},_findByValueInGroupsGeneric:function(c,h){var g=this._groups;
var f=g.get_count();
for(var d=0;
d<f;
d++){var e=g.getGroup(d);
var j=e["find"+h+"ByValue"](c);
if(j){return j;
}}return null;
},findButtonByValue:function(c){return this._findByValueInGroupsGeneric(c,"Button");
},findToggleButtonByValue:function(c){return this._findByValueInGroupsGeneric(c,"ToggleButton");
},findMenuItemByValue:function(c){return this._findByValueInGroupsGeneric(c,"MenuItem");
}};
a.RibbonBarTab.registerClass("Telerik.Web.UI.RibbonBarTab",a.RibbonBarChild);
})();
(function(){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarTabCollection=function(){a.RibbonBarTabCollection.initializeBase(this);
};
a.RibbonBarTabCollection.prototype={getTab:function(b){return this.getItem(b);
}};
a.RibbonBarTabCollection.registerClass("Telerik.Web.UI.RibbonBarTabCollection",a.RibbonBarChildCollection);
})();
(function(b){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarGroup=function(){a.RibbonBarGroup.initializeBase(this);
this._value="";
this._launcherElement=null;
this._collapsedGroup=null;
this._items=new a.RibbonBarChildCollection(this);
};
a.RibbonBarGroup.prototype={get_value:function(){return this._value;
},set_value:function(c){this._value=c;
},get_launcherElement:function(){return this._launcherElement;
},set_launcherElement:function(c){this._launcherElement=c;
},get_tab:function(){return this._parent._owner;
},get_items:function(){return this._items;
},get_hierarchicalIndex:function(){var d=this.get_tab().get_index();
var c=this.get_index();
return d+":"+c;
},get_eventName:function(c){if(c.get_toggleList){var d=c.get_toggleList();
if(d){return a.RadRibbonBar.get_eventName(Object.getTypeName(d));
}}return a.RadRibbonBar.get_eventName(Object.getTypeName(c));
},findItemByText:function(e){for(var c=0;
c<this._items.get_count();
c++){var d=this._items.getItem(c);
if(d.get_text()==e){return d;
}}return null;
},findButtonByValue:function(c){var g=this._items;
for(var d=0;
d<g.get_count();
d++){var f=g.getItem(d);
if(!f.toggle&&f.get_value&&f.get_value()==c){return f;
}else{if(f.findButtonByValue){var e=f.findButtonByValue(c);
if(e){return e;
}}}}return null;
},findToggleButtonByValue:function(c){var f=this._items;
for(var d=0;
d<f.get_count();
d++){var e=f.getItem(d);
if(e.toggle&&e.get_value&&e.get_value()==c){return e;
}}return null;
},findMenuItemByValue:function(c){var g=this._items;
for(var d=0;
d<g.get_count();
d++){var f=g.getItem(d);
if(f.findMenuItemByValue){var e=f.findMenuItemByValue(c);
if(e){return e;
}}}return null;
},_onChildAdded:function(c){c.set_group(this);
}};
b.registerControlProperties(a.RibbonBarGroup,{collapsedImageUrl:""});
a.RibbonBarGroup.registerClass("Telerik.Web.UI.RibbonBarGroup",a.RibbonBarChild);
})($telerik.$);
(function(){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarGroupCollection=function(b){a.RibbonBarGroupCollection.initializeBase(this,[b]);
};
a.RibbonBarGroupCollection.prototype={getGroup:function(b){return this.getItem(b);
}};
a.RibbonBarGroupCollection.registerClass("Telerik.Web.UI.RibbonBarGroupCollection",a.RibbonBarChildCollection);
})();
(function(b){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarItem=function(c){a.RibbonBarItem.initializeBase(this,[c]);
this._owner=null;
this._textElement=null;
this._enabled=null;
this._renderingModeCssClass=(this._element&&b(this._element).hasClass("rrbDualImage"))?"rrbDualImage":"";
};
a.RibbonBarItem.prototype={get_textElement:function(){if(this._textElement){return this._textElement;
}if(this._element){this._textElement=b(".rrbTextContent",this._element);
}return this._textElement;
},get_text:function(){if(this._text){return this._text;
}var c=this.get_textElement();
if(c){this._text=c.text();
}return this._text;
},set_text:function(d){this._text=d;
var c=this.get_textElement();
if(c){c.text(this._text);
}},get_imageUrl:function(){return(this._imageUrl)?this._imageUrl:"";
},set_imageUrl:function(c){this._imageUrl=c;
},get_imageUrlLarge:function(){return(this._imageUrlLarge)?this._imageUrlLarge:"";
},set_imageUrlLarge:function(c){this._imageUrlLarge=c;
},get_disabledImageUrl:function(){return(this._disabledImageUrl)?this._disabledImageUrl:"";
},set_disabledImageUrl:function(c){this._disabledImageUrl=c;
},get_disabledImageUrlLarge:function(){return(this._disabledImageUrlLarge)?this._disabledImageUrlLarge:"";
},set_disabledImageUrlLarge:function(c){this._disabledImageUrlLarge=c;
},get_owner:function(){if(!this._owner){this._owner=this._parent._owner;
}return this._owner;
},get_enabled:function(){if(this._enabled==null){this._enabled=(b(this._element).attr("disabled"))?false:true;
}return this._enabled;
},set_enabled:function(c){if(this.get_enabled()==c){return;
}this._enabled=c;
var f=this.get_element();
if(f){var d="rrbDisabled";
var e=this._getRibbonBar();
if(c){if(b(f).hasClass(d)){b(f).removeClass(d);
b(f).removeAttr("disabled");
}e._updateEnabledItems(this);
}else{if(!b(f).hasClass(d)){b(f).addClass(d);
b(f).attr("disabled","disabled");
}e._updateDisabledItems(this);
}this._updateImageElement();
}},get_hierarchicalIndex:function(){var d=this.get_owner();
var f="";
if(d.get_tab){var c=this.get_owner().get_tab().get_index();
var e=this.get_owner().get_index();
f=c+":"+e;
}else{f=d.get_hierarchicalIndex();
}return f+":"+this.get_index();
},get_isLarge:function(){return b(this._element).hasClass("rrbLargeButton");
},toggle_ImageRenderingMode:function(){var c=this.get_element();
if(c){if(b(c).hasClass("rrbDualImage")){b(c).removeClass("rrbDualImage");
}else{b(c).addClass("rrbDualImage");
}}},_updateParentGroupSize:function(){var d=this._getRibbonBar();
var c=this.get_owner();
d._updateGroupSize(c);
},_updateTextElement:function(){this.set_text(this.get_text());
this._updateParentGroupSize();
},_updateImageElement:function(){var c=b(this._element);
if(this._renderingModeCssClass==""&&c.hasClass("rrbDualImage")){this.toggle_ImageRenderingMode();
}if(c.hasClass("rrbDualImage")){this._updateDualImage();
}else{this._updateClipImage();
}},_updateDualImage:function(){var d;
var c=this.get_isLarge();
if(this.get_enabled()){if(c){d=this.get_imageUrlLarge()?this.get_imageUrlLarge():this._getRibbonBar().get_defaultImageUrlLarge();
}else{d=this.get_imageUrl()?this.get_imageUrl():this._getRibbonBar().get_defaultImageUrl();
}}else{if(c){d=this.get_disabledImageUrlLarge()?this.get_disabledImageUrlLarge():this._getRibbonBar().get_defaultDisabledImageUrlLarge();
}else{d=this.get_disabledImageUrl()?this.get_disabledImageUrl():this._getRibbonBar().get_defaultDisabledImageUrl();
}}this.set_image(d);
},_updateClipImage:function(){var e=this.get_enabled();
var d=(e&&!this.get_imageUrl())||(!e&&!this.get_disabledImageUrl());
if(d){this.toggle_ImageRenderingMode();
this._updateDualImage();
}else{var c;
if(e){c=this.get_imageUrl();
}else{c=this.get_disabledImageUrl();
}this.set_image(c);
}}};
b.registerControlProperties(a.RibbonBarItem,{group:null});
a.RibbonBarItem.registerClass("Telerik.Web.UI.RibbonBarItem",a.RibbonBarChild);
})($telerik.$);
(function(){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarButton=function(b){a.RibbonBarButton.initializeBase(this,[b]);
this._value="";
if(b){b._button=this;
}this._shouldDisplayDefaultImage=true;
};
a.RibbonBarButton.prototype={set_shouldDisplayDefaultImage:function(b){this._shouldDisplayDefaultImage=b;
},get_shouldDisplayDefaultImage:function(){return this._shouldDisplayDefaultImage;
},get_value:function(){return this._value;
},set_value:function(b){this._value=b;
},set_owner:function(b){this._owner=b;
},_updateDualImage:function(){var b;
var d="";
var c=this.get_isLarge();
if(this.get_enabled()){if(c){b=this.get_imageUrlLarge()?this.get_imageUrlLarge():this.get_shouldDisplayDefaultImage()?this._getRibbonBar().get_defaultImageUrlLarge():d;
}else{b=this.get_imageUrl()?this.get_imageUrl():this.get_shouldDisplayDefaultImage()?this._getRibbonBar().get_defaultImageUrl():d;
}}else{if(c){b=this.get_disabledImageUrlLarge()?this.get_disabledImageUrlLarge():this.get_shouldDisplayDefaultImage()?this._getRibbonBar().get_defaultDisabledImageUrlLarge():d;
}else{b=this.get_disabledImageUrl()?this.get_disabledImageUrl():this.get_shouldDisplayDefaultImage()?this._getRibbonBar().get_defaultDisabledImageUrl():d;
}}this.set_image(b);
}};
a.RibbonBarButton.registerClass("Telerik.Web.UI.RibbonBarButton",a.RibbonBarItem);
})();
(function(b){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarToggleButton=function(c){a.RibbonBarToggleButton.initializeBase(this,[c]);
if(c){c._button=this;
}this._toggled=false;
};
a.RibbonBarToggleButton.prototype={set_owner:function(c){this._owner=c;
},get_toggled:function(){if(this._element){return b(this._element).hasClass("rrbToggled");
}return this._toggled;
},set_toggled:function(d){this._toggled=d;
var c=b(this._element).add(this._qatItemElement);
if(d){c.addClass("rrbToggled");
}else{c.removeClass("rrbToggled");
}},toggle:function(){this.set_toggled(!this.get_toggled());
},_setQuickAccessToolbarItemElement:function(c){this._qatItemElement=c;
}};
b.registerControlProperties(a.RibbonBarToggleButton,{toggleList:null});
a.RibbonBarToggleButton.registerClass("Telerik.Web.UI.RibbonBarToggleButton",a.RibbonBarButton);
})($telerik.$);
(function(){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarButtonContainer=function(b){a.RibbonBarButtonContainer.initializeBase(this,[b]);
this._items=new Telerik.Web.UI.RibbonBarChildCollection(this);
};
a.RibbonBarButtonContainer.prototype={get_items:function(){return this._items;
},_onChildAdded:function(c){var b=this.get_owner();
if(b&&b._onChildAdded){b._onChildAdded(c);
}}};
a.RibbonBarButtonContainer.registerClass("Telerik.Web.UI.RibbonBarButtonContainer",a.RibbonBarItem);
})();
(function(){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarMenu=function(b){a.RibbonBarMenu.initializeBase(this,[b]);
if(b){b._menu=this;
}this._items=new Telerik.Web.UI.RibbonBarChildCollection(this);
};
a.RibbonBarMenu.prototype={set_owner:function(b){this._owner=b;
},get_eventName:function(){return a.RadRibbonBar.get_eventName(Object.getTypeName(this));
},get_items:function(){return this._items;
},findMenuItemByValue:function(b){var e=this.get_items();
var d=e.get_count();
for(var c=0;
c<d;
c++){var g=e.getItem(c);
if(g.get_value()==b){return g;
}var f=g.findMenuItemByValue(b);
if(f){return f;
}}return null;
},_onChildAdded:function(b){b.set_group(this.get_group());
if(b.set_owner){b.set_owner(this);
}}};
a.RibbonBarMenu.registerClass("Telerik.Web.UI.RibbonBarMenu",a.RibbonBarItem);
})();
(function(){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarMenuItem=function(d){a.RibbonBarMenuItem.initializeBase(this,[d]);
if(d){d._button=this;
}var c=this.get_imageElement();
if(c){var b=c.src;
if(this.get_enabled()){this.set_imageUrl(b);
}else{this.set_disabledImageUrl(b);
}}this._value="";
this._items=new Telerik.Web.UI.RibbonBarChildCollection(this);
this._parentItem=null;
};
a.RibbonBarMenuItem.prototype={get_value:function(){return this._value;
},set_value:function(b){this._value=b;
},set_owner:function(b){this._owner=b;
},get_parentItem:function(){return this._parentItem;
},set_parentItem:function(b){this._parentItem=b;
},get_items:function(){return this._items;
},findMenuItemByValue:function(b){var e=this.get_items();
var d=e.get_count();
for(var c=0;
c<d;
c++){var g=e.getItem(c);
if(g.get_value()==b){return g;
}var f=g.findMenuItemByValue(b);
if(f){return f;
}}return null;
},get_hierarchicalIndex:function(){var c="";
var b=this.get_parentItem()||this.get_owner();
if(b){c=b.get_hierarchicalIndex();
}return c+":"+this.get_index();
},_updateImageElement:function(){var b=this.get_enabled();
var c="";
if(b){c=this.get_imageUrl();
}else{c=this.get_disabledImageUrl();
}this.set_image(c);
},_onChildAdded:function(c){var b=this.get_owner();
if(b&&b._onChildAdded){b._onChildAdded(c);
}c.set_parentItem(this);
}};
a.RibbonBarMenuItem.registerClass("Telerik.Web.UI.RibbonBarMenuItem",a.RibbonBarItem);
})();
(function(){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarSplitButton=function(b){a.RibbonBarSplitButton.initializeBase(this,[b]);
if(b){b._splitButton=this;
}this._defaultButton=null;
this._enableButtonSelection=false;
this._initialSelectedButtonIndex=null;
this._selectedButtonIndex=null;
this._selectedButtonHierarchicalIndex=null;
};
a.RibbonBarSplitButton.prototype={_getFirstButton:function(f){var e=[];
for(var c=0;
c<f.get_count();
c++){var b=f.getItem(c);
if(!b.get_items){return b;
}else{e[e.length]=b;
}}for(var d=0;
d<e.length;
d++){b=this._getFirstButton(e[d].get_items());
if(b){return b;
}}return null;
},_isSubMenu:function(c){var b=$("span.rrbSubMenu",c.get_element()).length>0;
return b;
},_onChildAdded:function(b){b.set_group(this.get_group());
b.set_shouldDisplayDefaultImage(false);
if(b.set_owner){b.set_owner(this);
}},_updateDualImage:function(){var b;
var c=this.get_isLarge();
var e=this.get_defaultButton();
var d=this.get_enabled()&&e&&e.get_enabled();
if(d){if(c){if(this.get_imageUrlLarge()){b=this.get_imageUrlLarge();
}else{b=(e&&e.get_imageUrlLarge())?e.get_imageUrlLarge():this._getRibbonBar().get_defaultImageUrlLarge();
}}else{if(this.get_imageUrl()){b=this.get_imageUrl();
}else{b=(e&&e.get_imageUrl())?e.get_imageUrl():this._getRibbonBar().get_defaultImageUrl();
}}}else{if(c){if(this.get_disabledImageUrlLarge()){b=this.get_disabledImageUrlLarge();
}else{b=(e&&e.get_disabledImageUrlLarge())?e.get_disabledImageUrlLarge():this._getRibbonBar().get_defaultDisabledImageUrlLarge();
}}else{if(this.get_disabledImageUrl()){b=this.get_disabledImageUrl();
}else{b=(e&&e.get_disabledImageUrl())?e.get_disabledImageUrl():this._getRibbonBar().get_defaultDisabledImageUrl();
}}}this.set_image(b);
},_updateClipImage:function(){var c=this.get_defaultButton();
var e=this.get_enabled()&&c&&c.get_enabled();
var d=((e&&!this.get_imageUrl()&&!(c&&c.get_imageUrl()))||(!e&&!this.get_disabledImageUrl()&&!(c&&c.get_disabledImageUrl())));
if(d){this.toggle_ImageRenderingMode();
this._updateDualImage();
return;
}var b;
if(e){if(this.get_imageUrl()){b=this.get_imageUrl();
}else{b=c.get_imageUrl();
}}else{if(this.get_disabledImageUrl()){b=this.get_disabledImageUrl();
}else{b=c.get_disabledImageUrl();
}}this.set_image(b);
},_updateTextElement:function(b){var c=false;
if(this.get_text(c)){return;
}var d=this.get_textElement();
if(d){d.text(b);
this._updateParentGroupSize();
}},get_text:function(d){if(!d){return this._text;
}var c=this.get_textElement();
var b;
if(c){b=c.text();
}return b;
},set_owner:function(b){this._owner=b;
},get_eventName:function(){return a.RadRibbonBar.get_eventName(Object.getTypeName(this));
},set_defaultButton:function(b){this._defaultButton=b;
},get_defaultButton:function(){var b=(this._defaultButton)?this._defaultButton:this._getFirstButton(this.get_items());
return b;
},findButtonByValue:function(b){var f=this.get_items();
var d=f.get_count();
for(var c=0;
c<d;
c++){var e=f.getItem(c);
if(e.get_value()==b){return e;
}}return null;
},set_selectedButtonIndex:function(b,d){var f=(d)?parseInt(b.split(":")[3]):b;
if(this._initialSelectedButtonIndex==null){this._initialSelectedButtonIndex=f;
}this._selectedButtonIndex=f;
var c=this.get_items().getItem(f);
if((this._initialSelectedButtonIndex!=this._selectedButtonIndex)){if(d){this._selectedButtonHierarchicalIndex=b;
}else{this._selectedButtonHierarchicalIndex=c.get_hierarchicalIndex();
}}this.set_defaultButton(c);
var e=this.get_element();
if(e){e._defaultButton=this._defaultButton;
this._updateTextElement(this.get_defaultButton().get_text());
this._updateImageElement();
}},get_selectedButtonIndex:function(){return this._selectedButtonIndex;
},get_selectedButtonHierarchicalIndex:function(){return this._selectedButtonHierarchicalIndex;
},get_selectedIndexDifferentFromInitial:function(){return(this._selectedButtonIndex!=this._initialSelectedButtonIndex);
},set_enableButtonSelection:function(b){this._enableButtonSelection=b;
},get_enableButtonSelection:function(){return this._enableButtonSelection;
}};
a.RibbonBarSplitButton.registerClass("Telerik.Web.UI.RibbonBarSplitButton",a.RibbonBarButtonContainer);
})();
(function(b){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarToggleList=function(){this._parent=null;
this._owner=null;
this._buttons=[];
};
a.RibbonBarToggleList.prototype={get_owner:function(){if(!this._owner){this._owner=this._parent._owner;
}return this._owner;
},get_buttons:function(){return this._buttons;
},addButton:function(c){this._buttons[this._buttons.length]=c;
c.set_toggleList(this);
}};
b.registerControlProperties(a.RibbonBarToggleList,{group:null,toggledButton:null});
a.RibbonBarToggleList.registerClass("Telerik.Web.UI.RibbonBarToggleList");
})($telerik.$);
$telerik.findRibbonBar=$find;
$telerik.toRibbonBar=function(a){return a;
};
(function(c){var a=Telerik.Web.UI;
var b=Sys.Serialization.JavaScriptSerializer;
Type.registerNamespace("Telerik.Web.UI");
a.RadRibbonBar=function(d){a.RadRibbonBar.initializeBase(this,[d]);
this._toggledIndices=[];
this._toggledIndicesJson="[]";
this._selectedTab=false;
this._selectedTabIndex=-1;
this._splitButtonsWithChangedSelection=[];
this._splitButtonSelectedButtonIndicesJson="[]";
this._enabledItems=[];
this._enabledItemsJson="[]";
this._disabledItems=[];
this._disabledItemsJson="[]";
this._uniqueId="";
this._postBackOnSelectedTabChange=false;
this._postBackOnButtonClick=false;
this._postBackOnSplitButtonClick=false;
this._postBackOnMenuItemClick=false;
this._postBackOnLauncherClick=false;
this._postBackOnButtonToggle=false;
this._postBackOnToggleListToggle=false;
this._postBackOnApplicationMenuItemClick=false;
this._postBackReference="";
this._enableScreenBoundaryDetection=true;
this._expandDelay=300;
this._collapseDelay=300;
this._enabled=true;
this._visible=true;
this._isResizing=false;
this._resizeInterval=0;
this._smallButtonCssClass=".rrbButton";
this._mediumButtonCssClass=".rrbMediumButton";
this._largeButtonCssClass=".rrbLargeButton";
this._splitButtonCssClass=".rrbSplitButton";
this._buttonStripCssClass=".rrbButtonStrip";
this._buttonStripPartCssClass=".rrbButtonStripPart";
this._buttonGroupCssClass=".rrbButtonGroup";
this._buttonGroupHoverCssClass=".rrbButtonGroupHover";
this._buttonGroupInCssClass=".rrbButtonGroupIn";
this._buttonGuideCssClass=".rrbButtonGuide";
this._buttonTextCssClass=".rrbButtonText";
this._buttonOutCssClass=".rrbButtonOut";
this._buttonMidCssClass=".rrbButtonMid";
this._buttonTextHoverCssClass=".rrbButtonTextHover";
this._collapsedGroupCssClass=".rrbCollapsedGroup";
this._menuGroupOutCssClass=".rrbMenuGroupOut";
this._templateItemCssClass=".rrbTemplateItem";
this._templateItemLargeCssClass=".rrbTemplateItemLarge";
this._smallButtonSelector=this._buttonGroupInCssClass+" > "+this._smallButtonCssClass+", "+this._buttonGroupInCssClass+" > "+this._mediumButtonCssClass+", "+this._buttonGroupInCssClass+" > "+this._templateItemCssClass+", "+this._buttonGroupInCssClass+" > "+this._buttonStripCssClass;
this._smallButtonGuideSelector=this._buttonGuideCssClass+" > "+this._smallButtonCssClass+", "+this._buttonGuideCssClass+" > "+this._mediumButtonCssClass+", "+this._buttonGuideCssClass+" > "+this._templateItemCssClass+", "+this._buttonGuideCssClass+" > "+this._buttonStripCssClass;
this._importance=[this._smallButtonCssClass,this._mediumButtonCssClass,this._largeButtonCssClass];
this._skin=null;
this._tabs=new Telerik.Web.UI.RibbonBarTabCollection();
this._pageGroups=null;
this._pageViews=null;
this._tabsLabelElements=null;
this._tabsContainerElement=false;
this._detachedGroup=false;
this._parentElement=false;
this._groupContainer=false;
this._mutationCandidates=false;
this._navigator=null;
this._navigationSettings={};
};
a.RadRibbonBar._typeEventDictionary={"Telerik.Web.UI.RibbonBarButton":"ButtonClick","Telerik.Web.UI.RibbonBarToggleList":"ToggleListToggle","Telerik.Web.UI.RibbonBarMenu":"MenuItemClick","Telerik.Web.UI.RibbonBarSplitButton":"SplitButtonClick","Telerik.Web.UI.RibbonBarToggleButton":"ToggleButtonClick"};
a.RadRibbonBar.get_eventName=function(d){return a.RadRibbonBar._typeEventDictionary[d];
};
a.RadRibbonBar.prototype={initialize:function(){a.RadRibbonBar.callBaseMethod(this,"initialize");
this._updateToggledIndicesJson();
this._hasResizeHandle=c(".rrbResizeHandle",this.get_element()).length>0;
if(this._hasResizeHandle){this._updateWidthInClientState();
}var d=this;
this._jRibbonBar=c(this.get_element());
this._adjustByImportance=c.throttle(40,function(){var h=this._parentElement.width();
var q=0;
if($telerik.isIE6||$telerik.isIE7||$telerik.quirksMode){this._groupContainer.children(":visible").each(function(){q+=c(this).outerWidth(true);
});
}else{q=this._groupContainer.width()+30;
}if(h<=q){var m=this._getImportantResizable();
if(m&&(this._mutationCandidates.length||m.data("hasComposites"))){this._mutateImportance(this._mutationCandidates,-1);
this._setResizableWidth(m,this._calculateGroupWidth(this._mutationCandidates,m));
this._updateGroup(m);
}else{var i=this._getToggleGroup();
if(i){this._toggleGroup(i);
this._updateGroup(i);
}}}else{var p=this._getToggleGroup(true);
if(p){var j=p.data("width")||p.width();
var l=p.data("groupHandle").width();
if(q-l+j<=h){this._toggleGroup(p,true);
this._updateGroup(p);
}}else{var o=this._getImportantResizable(true);
if(o&&(this._mutationCandidates.length||o.data("hasComposites"))){var n=this._calculateGroupWidth(this._mutationCandidates,o,true);
var k=o.width();
if(n>k&&q-k+n<=h){this._mutateImportance(this._mutationCandidates,1);
this._setResizableWidth(o,n);
}this._updateGroup(o);
}}}});
c(this._menuGroupOutCssClass,this._jRibbonBar).each(function(){var i=c(this);
var j=i.prev();
var h=null;
j[0]._dropDown=i[0];
i[0]._button=j;
if(j.children(this._buttonMidCssClass).hasClass("rrbSplitButton")){h=j.children(this._buttonMidCssClass).find(d._buttonTextCssClass);
}i.appendTo(d._jRibbonBar);
if(h==null){h=j;
}if(h.parent().hasClass("rrbMenuGroupIn")){h.mouseenter(function(m){if(i.is(":visible")){return;
}var k=d._getRelativeOffset(h,d._jRibbonBar);
i.stop(true,true).show();
var l=d._getDropDownWidth(i);
i.width(0).children().width(l);
i.css({left:k.left+h.outerWidth(true)-2,top:k.top});
if(!i[0]._button.hasClass("rrbExpanded")){i[0]._button.addClass("rrbExpanded");
}i.animate({width:l},"fast");
});
}else{h.click(function(n){if(j.hasClass("rrbDisabled")){return;
}d._hideMenus();
if(d.get_quickAccessToolbar()){d.get_quickAccessToolbar().hideDropDown();
}var l=d._getRelativeOffset(h,d._jRibbonBar);
i.stop(true,true).show();
var k=i.height();
var m=d._getDropDownWidth(i);
i.width(m).height(0);
i.css({left:l.left-1,top:l.top+h.outerHeight()});
if(!i[0]._button.hasClass("rrbExpanded")){i[0]._button.addClass("rrbExpanded");
}i.animate({height:k},"fast");
n.preventDefault();
n.stopImmediatePropagation();
d._hideApplicationMenu();
});
}});
if(!this._tabsContainerElement){var g=this.get_element();
this._tabsContainerElement=c(".rrbTabs",g)[0];
if(this._tabsContainerElement){var e=this._getTabLabelElements();
e.live("click",function(h){var i=d.findTabByDomElement(h.target);
if(i){d._onTabClick(i,h);
$telerik.cancelRawEvent(h);
d._hideApplicationMenu();
}}).live("mouseenter",function(j){var h=d.findTabByDomElement(j.target);
var i=h.get_element();
if(!c(i).hasClass("rrbHoveredTab")){c(i).addClass("rrbHoveredTab");
}}).live("mouseleave",function(j){var h=d.findTabByDomElement(j.target);
var i=h.get_element();
if(c(i).hasClass("rrbHoveredTab")){c(i).removeClass("rrbHoveredTab");
}});
this._initializeApplicationMenu();
this._initializeTabs();
this._initializeContextualTabGroups();
if(this.get_tabs().get_count()==0){return;
}this._initializeGroups();
if(this._qatItemsHierarchicalIndices){this._initializeQuickAccessToolbar();
}else{this._quickAccessToolbar=null;
}}else{return;
}}else{return;
}var f=this.get_tabs().getTab(this.get_selectedTabIndex());
this._initializePage(f);
this._initializeEvents();
this._initializeKeyboardNavigation();
this._updateGroupsData();
this._adjustByImportance();
this._jRibbonBar.data("isInitialized",true);
c.raiseControlEvent(this,"load",{});
},_initializeKeyboardNavigation:function(){if(this._jRibbonBar.attr("tabIndex")>=0||this._jRibbonBar.attr("accessKey")!=undefined){this._navigator=new a.RadRibbonBar.Navigator(this);
this._navigator.initialize();
}},_initializeEvents:function(){var d=this;
c(this._splitButtonCssClass+" "+this._buttonTextCssClass,this._jRibbonBar).each(function(){var e=c(this);
if(e.parents().hasClass("rrbDisabled")){return;
}e.mouseenter(function(){var f=c(this);
if(!f.hasClass(d._buttonTextHoverCssClass.substr(1))){f.addClass(d._buttonTextHoverCssClass.substr(1));
}}).mouseleave(function(){var f=c(this);
if(f.hasClass(d._buttonTextHoverCssClass.substr(1))){f.removeClass(d._buttonTextHoverCssClass.substr(1));
}});
});
c(this._buttonOutCssClass+":not(.rrbDisabled), "+this._buttonStripPartCssClass+":not(.rrbDisabled)",this._jRibbonBar).live("mousedown",function(g){var f=c(this);
if(!f.hasClass("rrbButtonClicked")&&!f.hasClass(d._buttonStripCssClass.substr(1))){f.addClass("rrbButtonClicked");
}g.preventDefault();
g.stopImmediatePropagation();
}).live("mouseup",function(g){var f=c(this);
if(f.hasClass("rrbButtonClicked")&&!f.hasClass(d._buttonStripCssClass.substr(1))){f.removeClass("rrbButtonClicked");
}g.preventDefault();
g.stopImmediatePropagation();
}).live("mouseenter",function(h){var f=c(this);
if(!f.parent().hasClass("rrbMenuGroupIn")){return;
}var g=f.prevAll(d._buttonOutCssClass).add(f.nextAll(d._buttonOutCssClass));
if(g.length){g.each(function(){var i=c(this._dropDown);
var e=c(this);
if(i.is(":visible")){if(e.hasClass("rrbExpanded")){e.removeClass("rrbExpanded");
}i.stop(true,true).animate({width:0},"fast",function(){i.hide();
});
}});
}}).live("mouseleave",function(){var e=c(this);
if(e.hasClass("rrbButtonClicked")&&!e.hasClass(d._buttonStripCssClass.substr(1))){e.removeClass("rrbButtonClicked");
}}).live("click",function(f){d._hideMenus();
if(d.get_quickAccessToolbar()){d.get_quickAccessToolbar().hideDropDown();
}var g=c(this).parent().hasClass("rrbMenuGroupIn");
if(!g){f.preventDefault();
}f.stopImmediatePropagation();
d._hideApplicationMenu();
if(this._defaultButton){d._onAnyButtonClick(this._defaultButton,f);
}else{if(this._button){d._onAnyButtonClick(this._button,f);
}}});
c(this._buttonGroupCssClass,this._jRibbonBar).live("mouseenter",function(){var e=c(this);
if(!e.hasClass(d._buttonGroupHoverCssClass.substr(1))){e.addClass(d._buttonGroupHoverCssClass.substr(1));
}}).live("mouseleave",function(){var e=c(this);
if(e.hasClass(d._buttonGroupHoverCssClass.substr(1))){e.removeClass(d._buttonGroupHoverCssClass.substr(1));
}});
c(this._templateItemCssClass+", "+this._templateItemLargeCssClass,this._jRibbonBar).bind("mousedown",function(f){f.stopPropagation();
});
c(document).bind("mousedown",function(f){if(d._detachedGroup){d._attachGroup(d._detachedGroup);
}d._detachedGroup=false;
d._hideMenus();
if(c(f.target).parents(".rrbSlide").length==0&&d.get_quickAccessToolbar()){d.get_quickAccessToolbar().hideDropDown();
}});
c(".rrbResizeHandle",this._jRibbonBar).mousedown(function(){d._resizeInterval=setInterval(c.proxy(d._resizeHandler,d),10);
c(document).mousemove(c.proxy(d._resizeRibbon,d));
c(document).mouseup(c.proxy(d._resizeStop,d));
c(document).mouseleave(c.proxy(d._resizeStop,d));
});
if($telerik.isIE){c(".rrbResizeHandle",this._jRibbonBar).bind("selectstart",function(){return false;
}).attr("unselectable","on");
}c(".rrbGroupLauncher:not(.rrbDisabled)",this._jRibbonBar).bind("click",function(f){f.preventDefault();
f.stopImmediatePropagation();
d._onLauncherClick(this);
d._hideApplicationMenu();
});
},_getTabLabelElements:function(){if(!this._tabsLabelElements){this._tabsLabelElements=c(".rrbTab>.rrbTabLabel",this._tabsContainerElement);
}return this._tabsLabelElements;
},findTabByDomElement:function(g){var f=false;
var h=c(g).parents(".rrbTab")[0];
if(h){var d=c(".rrbTab",this._tabsContainerElement);
var e=c.inArray(h,d);
if(e>-1){f=this.get_tabs().getTab(e);
}}return f;
},get_selectedTabIndex:function(){if(this._selectedTabIndex<0){if(this._tabsContainerElement){var e=c(".rrbTab",this._tabsContainerElement);
if(e.length>0){var d=c(".rrbTab.rrbSelectedTab",this._tabsContainerElement)[0];
this._selectedTabIndex=c.inArray(d,e);
this.updateClientState();
}}}return this._selectedTabIndex;
},get_selectedTab:function(){var f=this._selectedTab;
if(!f){var d=this.get_selectedTabIndex();
if(d>-1){var e=this.get_tabs();
f=e.getTab(d);
this._selectedTab=f;
}}return f;
},findItemByText:function(h){for(var e=0,d=this._tabs.get_count();
e<d;
e++){var f=this._tabs.getTab(e);
var g=f.findItemByText(h);
if(g){return g;
}}return null;
},_findByValueInTabsGeneric:function(d,e){var k=this._tabs;
var j=k.get_count();
for(var f=0;
f<j;
f++){var g=k.getTab(f);
var h=g["find"+e+"ByValue"](d);
if(h){return h;
}}return null;
},findTabByValue:function(d){var f=this._tabs;
var g=f.get_count();
for(var e=0;
e<g;
e++){var h=f.getTab(e);
if(h.get_value()==d){return h;
}}return null;
},findGroupByValue:function(d){return this._findByValueInTabsGeneric(d,"Group");
},findButtonByValue:function(d){return this._findByValueInTabsGeneric(d,"Button");
},findToggleButtonByValue:function(d){return this._findByValueInTabsGeneric(d,"ToggleButton");
},findMenuItemByValue:function(d){return this._findByValueInTabsGeneric(d,"MenuItem");
},_hideApplicationMenu:function(){if(this.get_applicationMenuDropDown()){this.get_applicationMenuDropDown().hide();
}},_initializeApplicationMenu:function(){var d=this.get_applicationMenuDropDown();
if(!d){return;
}d._ribbonBar=this;
d.add_hiding(this._onApplicationMenuDropDownHiding);
d.add_itemClicking(this._onApplicationMenuItemClicking);
d.add_itemClicked(this._onApplicationMenuItemClicked);
var e=c(".rrbApplicationTab",this._tabsContainerElement).live("click",function(f){if(!e.hasClass("rrbSelectedApplicationTab")){e.addClass("rrbSelectedApplicationTab");
}$telerik.cancelRawEvent(f);
var g=$telerik.getLocation(this);
d.showAt(g.x,g.y+c(this).outerHeight());
}).live("mouseenter",function(f){if(!e.hasClass("rrbHoveredApplicationTab")){e.addClass("rrbHoveredApplicationTab");
}}).live("mouseleave",function(f){if(e.hasClass("rrbHoveredApplicationTab")){e.removeClass("rrbHoveredApplicationTab");
}});
c(".rmItem a ",d.get_element()).each(function(f,g){var h=c(g).attr("accessKey");
if(h){c(g).append("<span class='rrbKeyBox'>"+h+"</span>");
}});
},_onApplicationMenuDropDownHiding:function(d,e){c(".rrbApplicationTab",d._ribbonBar._tabsContainerElement).removeClass("rrbSelectedApplicationTab");
},_onApplicationMenuItemClicking:function(d,g){var f={applicationMenu:d,item:g.get_item(),domEvent:g.get_domEvent()};
var e=c.raiseCancellableControlEvent(d._ribbonBar,"applicationMenuItemClicking",f);
g.set_cancel(e);
},_onApplicationMenuItemClicked:function(e,g){var f={applicationMenu:e,item:g.get_item(),domEvent:g.get_domEvent()};
var d=e._ribbonBar;
c.raiseControlEvent(d,"applicationMenuItemClicked",f);
if(d._postBackOnApplicationMenuItemClick){d.postback("-"+f.item.get_index());
}},_initializeTabs:function(){var d=c(".rrbTab",this._tabsContainerElement);
var f=this.get_tabData();
for(var e=0,h=d.length;
e<h;
e++){var g=new a.RibbonBarTab(d[e]);
g.set_text(g.get_text());
if(f[e].value){g.set_value(f[e].value);
}this._tabs.add(g);
}},_getNavigator:function(){return this._navigator;
},_getPageViewElements:function(){return this._pageViews;
},_setPageViewElements:function(){this._pageViews=c(".rrbButtonArea",this.get_element()).children(".rrbButtonAreaIn");
},_initializeGroups:function(){var k=this.get_groupData();
this._setPageViewElements();
for(var e=0,n=k.length;
e<n;
e++){var o=k[e].index.split(":");
var m=this._getPageViewElements()[o[0]];
var d=c(".rrbButtonGroup",m)[o[1]];
var g=new a.RibbonBarGroup();
g.set_element(d);
g.set_collapsedImageUrl(k[e].collapsedImageUrl);
var j=c(".rrbGroupTitle",d);
var h=j.text().trim();
g.set_text(h);
if(k[e].value){g.set_value(k[e].value);
}var l=j.children(".rrbGroupLauncher")[0];
if(l){g.set_launcherElement(l);
l._group=g;
}var f=this._tabs.getTab(o[0]);
f.set_pageView(m);
f.get_groups().add(g);
this._initializeItems(g,c(d).children(),k[e].itemData);
if(k[e].toggleListData){this._initializeToggleLists(g,k[e].toggleListData);
}}},_initializeItems:function(e,h,d){var f=h.children("a.rrbButtonOut, div.rrbTemplateItem, div.rrbTemplateItemLarge").add("> .rrbButtonStrip > .rrbButtonStripPart",h);
var g=this;
var i=null;
f.each(function(k){if(g._isItemButtonElement(this)){var n=new a.RibbonBarButton(this);
if(d[k].value){n.set_value(d[k].value);
}if(d[k].text){n.set_text(d[k].text);
}if(d[k].imageUrl){n.set_imageUrl(d[k].imageUrl);
}if(d[k].imageUrlLarge){n.set_imageUrlLarge(d[k].imageUrlLarge);
}if(d[k].disabledImageUrl){n.set_disabledImageUrl(d[k].disabledImageUrl);
}if(d[k].disabledImageUrlLarge){n.set_disabledImageUrlLarge(d[k].disabledImageUrlLarge);
}n._setRibbonBar(g);
e.get_items().add(n);
}else{if(g._isItemToggleButtonElement(this)){var o=new a.RibbonBarToggleButton(this);
if(d[k].value){o.set_value(d[k].value);
}if(d[k].text){o.set_text(d[k].text);
}if(d[k].imageUrl){o.set_imageUrl(d[k].imageUrl);
}if(d[k].imageUrlLarge){o.set_imageUrlLarge(d[k].imageUrlLarge);
}if(d[k].disabledImageUrl){o.set_disabledImageUrl(d[k].disabledImageUrl);
}if(d[k].disabledImageUrlLarge){o.set_disabledImageUrlLarge(d[k].disabledImageUrlLarge);
}var j=c(this).hasClass("rrbToggled");
o.set_toggled(j);
o._setRibbonBar(g);
e.get_items().add(o);
if(j){g._registerToggledIndex(o.get_hierarchicalIndex());
}}else{if(g._isItemMenuElement(this)){var m=new a.RibbonBarMenu(this);
if(d[k].imageUrl){m.set_imageUrl(d[k].imageUrl);
}if(d[k].imageUrlLarge){m.set_imageUrlLarge(d[k].imageUrlLarge);
}if(d[k].disabledImageUrl){m.set_disabledImageUrl(d[k].disabledImageUrl);
}if(d[k].disabledImageUrlLarge){m.set_disabledImageUrlLarge(d[k].disabledImageUrlLarge);
}m._setRibbonBar(g);
e.get_items().add(m);
i=c(this._dropDown);
g._initializeMenuItems(i,m.get_items(),d[k].menuItemData);
}else{if(g._isItemSplitButtonElement(this)){var q=new a.RibbonBarSplitButton(this);
if(d[k].imageUrl){q.set_imageUrl(d[k].imageUrl);
}if(d[k].imageUrlLarge){q.set_imageUrlLarge(d[k].imageUrlLarge);
}if(d[k].disabledImageUrl){q.set_disabledImageUrl(d[k].disabledImageUrl);
}if(d[k].disabledImageUrlLarge){q.set_disabledImageUrlLarge(d[k].disabledImageUrlLarge);
}if(d[k].text){q.set_text(d[k].text);
}if(d[k].enableButtonSelection){q.set_enableButtonSelection(d[k].enableButtonSelection);
}q._setRibbonBar(g);
e.get_items().add(q);
i=c(this._dropDown);
g._initializeSplitButton(i,q.get_items(),d[k].buttonData);
if(!(typeof d[k].selectedButtonIndex==="undefined")){q.set_selectedButtonIndex(d[k].selectedButtonIndex);
}var l=q.get_defaultButton();
if(l){q.get_element()._defaultButton=l;
}}else{if(g._isTemplateItem(this)){var p=c(this);
if(d[k].width){p.width(d[k].width);
}}}}}}});
},_initializeMenuItems:function(g,d,e){var f=this;
var h=g.children(".rrbMenuGroupMid").children(".rrbMenuGroupIn");
h.children("a.rrbButtonOut").each(function(i){var k=new a.RibbonBarMenuItem(this);
d.add(k);
if(e){if(e[i]){if(e[i].value){k.set_value(e[i].value);
}if(e[i].imageUrl){k.set_imageUrl(e[i].imageUrl);
}if(e[i].disabledImageUrl){k.set_disabledImageUrl(e[i].disabledImageUrl);
}}}k._setRibbonBar(f);
if(this._dropDown){var j=[];
if(e&&e[i]&&e[i].menuItemData){j=e[i].menuItemData;
}f._initializeMenuItems(c(this._dropDown),k.get_items(),j);
}});
},_initializeSplitButton:function(g,d,h){var f=this;
var e=g.children(".rrbMenuGroupMid").children(".rrbMenuGroupIn");
e.children("a.rrbButtonOut").each(function(j){var i=new a.RibbonBarButton(this);
i._setRibbonBar(f);
i.set_shouldDisplayDefaultImage(false);
if(h&&h[j]){if(h[j].imageUrl){i.set_imageUrl(h[j].imageUrl);
}if(h[j].imageUrlLarge){i.set_imageUrlLarge(h[j].imageUrlLarge);
}if(h[j].disabledImageUrl){i.set_disabledImageUrl(h[j].disabledImageUrl);
}if(h[j].disabledImageUrlLarge){i.set_disabledImageUrlLarge(h[j].disabledImageUrlLarge);
}if(h[j].value){i.set_value(h[j].value);
}}d.add(i);
});
},_initializeToggleLists:function(f,l){for(var d=0,n=l.length;
d<n;
d++){var k=new a.RibbonBarToggleList();
var h=l[d].buttonIndices;
for(var e=0,m=h.length;
e<m;
e++){var g=f.get_items().getItem(h[e]);
k.addButton(g);
if(g.get_toggled()){k.set_toggledButton(g);
}}}},_isItemButtonElement:function(d){return !this._isItemSplitButtonElement(d)&&!this._isItemMenuElement(d)&&!this._isItemToggleButtonElement(d)&&!this._isTemplateItem(d);
},_isItemToggleButtonElement:function(d){var e=c("span.rrbToggleButton",d).length>0;
return e;
},_isItemSplitButtonElement:function(d){var e=c("span.rrbSplitButton",d).length>0;
return e;
},_isItemMenuElement:function(d){var e=c("span.rrbMenuButton",d).length>0;
return e;
},_isTemplateItem:function(d){var e=c(d).hasClass("rrbTemplateItem")||c(d).hasClass("rrbTemplateItemLarge");
return e;
},_onTabClick:function(d,g){var i=this.get_selectedTab();
var j=this;
if(i){if(i!=d){var h=function(){j.set_selectedTabIndex(d.get_index());
};
var f={tab:d,previouslySelectedTab:i,domEvent:g};
this._raiseEvent("selectedTabChang",i,f,this._postBackOnSelectedTabChange,h);
}}},_onAnyButtonClick:function(d,h){if(!d.get_enabled()){$telerik.cancelRawEvent(h);
return;
}var f=d.get_owner();
var g=f.get_eventName(d);
this["_on"+g](d,h);
},_onButtonClick:function(d,g){var f={button:d,domEvent:g};
this._raiseEvent("buttonClick",d,f,this._postBackOnButtonClick);
},_onToggleButtonClick:function(d,i){var g={button:d,domEvent:i};
var f=this;
var h=function(e){e.toggle();
if(e.get_toggled()){f._registerToggledIndex(e.get_hierarchicalIndex());
}else{f._unregisterToggledIndex(e.get_hierarchicalIndex());
}};
this._raiseEvent("buttonToggl",d,g,this._postBackOnButtonToggle,h);
},_onToggleListToggle:function(d,h){if(d.get_toggled()){return;
}var i=this;
var f=d.get_toggleList();
var g=function(e){var k=f.get_toggledButton();
if(k){k.set_toggled(false);
i._unregisterToggledIndex(k.get_hierarchicalIndex());
}e.set_toggled(true);
i._registerToggledIndex(e.get_hierarchicalIndex());
f.set_toggledButton(e);
};
var j={button:d,buttons:f.get_buttons(),domEvent:h};
this._raiseEvent("toggleListToggl",d,j,this._postBackOnToggleListToggle,g);
},_onMenuItemClick:function(f,g){var d={item:f,domEvent:g};
this._raiseEvent("menuItemClick",f,d,this._postBackOnMenuItemClick);
},_onSplitButtonClick:function(d,g){d=this._updateSplitButtonSelection(d);
var f={button:d,domEvent:g};
this._raiseEvent("splitButtonClick",d,f,this._postBackOnSplitButtonClick);
},_raiseEvent:function(f,d,e,h,g){if(c.raiseCancellableControlEvent(this,f+"ing",e)){return;
}if(g){g(d);
}c.raiseControlEvent(this,f+"ed",e);
if(h){this.postback(d.get_hierarchicalIndex());
}},_onLauncherClick:function(f,g){var d={group:f._group,domEvent:g};
this._raiseEvent("launcherClick",f._group,d,this._postBackOnLauncherClick);
},postback:function(d){eval(this._postBackReference.replace("arguments",d));
},dispose:function(){a.RadRibbonBar.callBaseMethod(this,"dispose");
var d=this.get_applicationMenuDropDown();
if(d){d.remove_hiding(this._onApplicationMenuDropDownHiding);
d.remove_itemClicking(this._onApplicationMenuItemClicking);
d.remove_itemClicked(this._onApplicationMenuItemClicked);
}if(this._quickAccessToolbar){this._quickAccessToolbar.dispose();
}var e=this._getNavigator();
if(e){e.dispose();
}c(window).unbind("resize",this._onResize);
},repaint:function(){var d=this.get_selectedTab();
this._groupContainer.css("visibility","hidden");
c(this._getPageViewElements()).hide();
c(d.get_pageView()).show();
this._initializePage(d);
this._updateGroupsData();
this._updateVisibleGroupsSize();
this._adjustByImportance();
},_onResize:function(d){this._resizeHandler();
},get_tabs:function(){return this._tabs;
},set_selectedTabIndex:function(e){var d=this.get_selectedTab();
var f=this.get_tabs().getTab(e);
this._selectedTabIndex=e;
this.updateClientState();
this._selectedTab=f;
if(d&&f&&(d!=f)){c(d.get_element()).removeClass("rrbSelectedTab");
c(f.get_element()).addClass("rrbSelectedTab");
}this.repaint();
},saveClientState:function(){var e=this._width?(',"width":'+this._width):"";
var d=this._selectedTabIndex?(',"selectedTabIndex":'+this._selectedTabIndex):"";
var f=this._navigationSettings.activated?(',"activated":'+this._navigationSettings.activated):"";
return'{"toggledIndices":'+this._toggledIndicesJson+',"splitButtonSelectedIndices":'+this._splitButtonSelectedButtonIndicesJson+',"clientSideEnabledItems":'+this._enabledItemsJson+',"clientSideDisabledItems":'+this._disabledItemsJson+(this._qatActiveItemIndicesJson?',"qatActiveItemIndices":'+this._qatActiveItemIndicesJson:"")+e+d+f+"}";
},_updateSplitButtonSelection:function(d){var f=d.get_owner();
if(f.get_enableButtonSelection()){var e=true;
f.set_selectedButtonIndex(d.get_hierarchicalIndex(),e);
d=f.get_defaultButton();
if(Array.indexOf(this._splitButtonsWithChangedSelection,f)==-1){Array.add(this._splitButtonsWithChangedSelection,f);
}this._updateSplitButtonSelectedIndicesJson();
}return d;
},_updateSplitButtonSelectedIndicesJson:function(){var f=[];
for(var e=0;
e<this._splitButtonsWithChangedSelection.length;
e++){if(this._splitButtonsWithChangedSelection[e].get_selectedIndexDifferentFromInitial()){Array.add(f,this._splitButtonsWithChangedSelection[e].get_selectedButtonHierarchicalIndex());
}else{Array.remove(this._splitButtonsWithChangedSelection,this._splitButtonsWithChangedSelection[e]);
}}var g=this._splitButtonSelectedButtonIndicesJson;
var d=b.serialize(f);
if(g!=d){this._splitButtonSelectedButtonIndicesJson=d;
this.updateClientState();
}},_updateEnabledItems:function(e){var d=e.get_hierarchicalIndex();
if(Array.indexOf(this._disabledItems,d)!=-1){Array.remove(this._disabledItems,d);
this._updateDisabledItemsJson();
}if(Array.indexOf(this._enabledItems,d)==-1){Array.add(this._enabledItems,d);
this._updateEnabledItemsJson();
}},_updateDisabledItems:function(e){var d=e.get_hierarchicalIndex();
if(Array.indexOf(this._enabledItems,d)!=-1){Array.remove(this._enabledItems,d);
this._updateEnabledItemsJson();
}if(Array.indexOf(this._disabledItems,d)==-1){Array.add(this._disabledItems,d);
this._updateDisabledItemsJson();
}},_updateEnabledItemsJson:function(){var d=this._enabledItemsJson;
var e=b.serialize(this._enabledItems);
if(d!=e){this._enabledItemsJson=e;
this.updateClientState();
}},_updateDisabledItemsJson:function(){var d=this._disabledItemsJson;
var e=b.serialize(this._disabledItems);
if(d!=e){this._disabledItemsJson=e;
this.updateClientState();
}},_registerToggledIndex:function(d){if(Array.indexOf(this._toggledIndices,d)==-1){Array.add(this._toggledIndices,d);
this._updateToggledIndicesJson();
}},_unregisterToggledIndex:function(d){Array.remove(this._toggledIndices,d);
this._updateToggledIndicesJson();
},_updateToggledIndicesJson:function(){this._toggledIndicesJson=b.serialize(this._toggledIndices);
this.updateClientState();
},_updateWidthInClientState:function(){this._width=c(this.get_element()).width();
this.updateClientState();
},_spawnCollapsedGroup:function(i){var j=this;
var k=(($telerik.isIE&&!$telerik.isIE9)||($telerik.isChrome))?"about:blank":"";
var f=c('<a class="rrbButtonOut rrbCollapsedGroup rrbHiddenGroup" href="#"><span class="rrbButtonMid"><span class="rrbButtonIn"><span class="rrbButtonOut rrbDecoration"><span class="rrbButtonMid"><span class="rrbButtonIn"><img src="'+k+'" alt="" class="rrbButtonImage"></span></span></span><span class="rrbButtonText"><span class="rrbTextContent"></span><span class="rrbButtonArrow">&nbsp;</span></span></span></span></a>');
f.find(".rrbTextContent").append(i._text).end().insertBefore(i.get_element());
i._collapsedGroup=f[0];
var d=f.next();
var h=f.find(".rrbButtonImage");
if(i._collapsedImageUrl){h.attr("src",i._collapsedImageUrl);
}else{if(i.get_items().get_count()){var e=i.get_items().getItem(0);
var g=e.get_imageUrl();
if(g!=""){h.attr("src",g);
}}}d.data("groupHandle",f);
f.data("group",d).click(function(l){j._hideMenus();
if(j.get_quickAccessToolbar()){j.get_quickAccessToolbar().hideDropDown();
}if(j._detachedGroup){j._attachGroup(j._detachedGroup);
}j._detachedGroup=j._detachGroup(d);
l.preventDefault();
l.stopImmediatePropagation();
});
},_initializePage:function(g){this._pageGroups=c(".rrbButtonAreaIn:visible "+this._buttonGroupCssClass,this._jRibbonBar);
this._groupContainer=this._pageGroups.parent();
this._parentElement=this._groupContainer.parent();
c(window).bind("resize",c.proxy(this._onResize,this));
var d=this;
var h=g.get_groups()._array;
this._pageGroups.children(this._buttonGroupInCssClass).children(this._smallButtonCssClass+", "+this._mediumButtonCssClass+", "+this._largeButtonCssClass).each(function(){var l=c(this);
for(var j=0,k=d._importance.length;
j<k;
j++){if(l.hasClass(d._importance[j].substr(1))&&!l.attr("rel")){l.attr("rel",j);
}}});
for(var e=0,f=h.length;
e<f;
e++){if(!h[e]._collapsedGroup){this._spawnCollapsedGroup(h[e]);
this._updateGroupSize(h[e]);
}}this._groupContainer.css("visibility","visible");
},_updateGroupSize:function(d){var e=c(d.get_element());
this._updateGroup(e);
this._setImportantResizable(e);
this._setResizableWidth(e,this._calculateGroupWidth(false,e));
},_getMutationClasses:function(d,f){var e="";
for(var g=0,h=this._importance.length;
g<h;
g++){if(c(d).hasClass(this._importance[g].substr(1))){e=f<0?this._importance[0].substr(1):this._importance[Math.max(0,Math.min(g+f,2))].substr(1);
return{from:this._importance[g].substr(1),to:e};
}}return null;
},_mutateImportance:function(d,e){var f=this._getMutationClasses(d[0],e);
if(f){d.removeClass(f.from).addClass(f.to);
d.each(function(){if(this._button){this._button._updateImageElement();
if(this._defaultButton&&c(this._button._element).hasClass("rrbDualImage")){this._defaultButton._updateImageElement();
}}});
}},_getMutationCandidates:function(f){var e=arguments[1];
for(var d=0,g=f.length;
d<g;
d++){if(f[d].length){var h=f[d].filter(function(){return(e?d<+this.getAttribute("rel"):d>0);
});
if(h.length){return h;
}}}return[];
},_getImportantResizable:function(){var e=arguments[0]||false,g=null,f=0,d=this;
this._pageGroups.each(function(){if(this.offsetWidth!=0){var j=c(this);
var i=j.data("hasComposites")&&j.is(":hidden");
var l=j.data("importance");
var h=d._getMutationCandidates(l,e);
var k=e?"originalImportanceIndex":"importanceIndex";
if(j.data(k)>f&&(h.length>0||i)){g=j;
d._mutationCandidates=h;
f=j.data(k);
}}});
return g;
},_setImportantResizable:function(d){var e=arguments[1]||false;
this._mutationCandidates=this._getMutationCandidates(d.data("importance"),e);
},_getToggleGroup:function(){var e=arguments[0]||false,h=null,d=null,f=10000,g=0;
if(e){d=this._pageGroups.filter(":hidden");
}else{d=this._pageGroups.filter(":visible");
}if(!d.length){return null;
}d.each(function(){var i=c(this);
var j=i.data("originalImportanceIndex");
if(e&&j>=g){h=i;
g=j;
}else{if(!e&&j<f){h=i;
f=j;
}}});
return h;
},_toggleGroup:function(e){if(!e){return;
}var d=e.data("groupHandle");
if(!d){return;
}var f=arguments[1];
if(f){d.hide();
e.show();
}else{e.hide();
d.show();
}},_attachGroup:function(e){if(!e){return;
}var d=this;
var f=e.data("groupHandle");
var g=e.parent().closest(".rrbDetachedContainer");
e.stop(true,true).slideUp("fast",function(){d._setImportantResizable(e);
d._mutateImportance(d._mutationCandidates,-1);
d._updateGroup(e);
d._setResizableWidth(e,d._calculateGroupWidth(d._mutationCandidates,e));
d._setImportantResizable(e);
d._mutateImportance(d._mutationCandidates,-1);
d._updateGroup(e);
d._setResizableWidth(e,d._calculateGroupWidth(d._mutationCandidates,e));
e.hide().removeClass("rrbDetachedGroup").insertAfter(f);
e.find(".rrbButtonClicked").removeClass("rrbButtonClicked");
g.remove();
});
},_detachGroup:function(h){if(!h){return;
}var e=h.data("groupHandle");
h.stop(true,true).detach().show();
this._setImportantResizable(h,true);
this._mutateImportance(this._mutationCandidates,1);
this._updateGroup(h);
this._setResizableWidth(h,this._calculateGroupWidth(this._mutationCandidates,h));
this._setImportantResizable(h,true);
this._mutateImportance(this._mutationCandidates,1);
this._updateGroup(h);
this._setResizableWidth(h,this._calculateGroupWidth(this._mutationCandidates,h));
h.addClass("rrbDetachedGroup");
var g=c('<div class="rrbDetachedContainer"><div class="rrbContentWrapOut"><div class="rrbContentWrapMid"><div class="rrbContentWrapIn"></div></div></div></div>').appendTo(this._jRibbonBar);
var j=e.position(),f=g.find(".rrbContentWrapIn"),i=c(this._tabsContainerElement);
g.css({position:"absolute",left:j.left+1,top:i.outerHeight(true)+e.outerHeight(true)-6});
if($telerik.isIE6||$telerik.quirksMode){g.width(h.outerWidth(true)+2);
}f.append(h);
var d=h.height();
h.height(0);
h.animate({height:d},"fast");
return h;
},_resizeHandler:function(d){this._adjustByImportance();
},_resizeRibbon:function(d){this._isResizing=true;
var f=d.clientX-this._jRibbonBar[0].offsetLeft+7;
this._jRibbonBar.width(f);
if(this._hasResizeHandle){this._updateWidthInClientState();
}},_resizeStop:function(d){if(this._isResizing){this._isResizing=false;
var f=this;
clearInterval(f._resizeInterval);
$telerik.$(document).unbind("mousemove",this._resizeRibbon);
$telerik.$(document).unbind("mouseup",this._resizeStop);
}},_setResizableWidth:function(d,j){var g=arguments[2]?arguments[2]:3,e=d.children(this._buttonGroupInCssClass);
var f=e.children(this._smallButtonSelector);
var i=d.data("guideWidths");
var k=this;
f.each(function(l){if(l%g==0){var p=c(this);
var n=i[Math.floor(l/g)];
var o=c('<div class="'+k._buttonGuideCssClass.substr(1)+'" style="width: '+n+'px;"></div>');
var m=p.nextAll(".rrbButtonOut:not(.rrbLargeButton), .rrbTemplateItem");
p.add(m[0]).add(m[1]).wrapAll(o);
}});
if($telerik.isIE6||$telerik.isIE7||$telerik.quirksMode){var h=e.children(".rrbGroupTitle");
if(h.length){h[0].style.cssText=h[0].style.cssText;
h.height("14px");
}}d.width(j);
if($telerik.isIE6||$telerik.quirksMode){d.find(".rrbTextContent").each(function(){this.style.cssText=this.style.cssText;
});
}},_calculateGroupWidth:function(p,q){if(p&&!p.length&&!q.data("hasComposites")){return;
}var n=c(q),f=this;
q.find(".rrbButtonGuide > :first-child").each(function(){var t=c(this);
if(t.parent().hasClass(f._buttonGuideCssClass.substr(1))){t.unwrap();
}});
var e=n.clone(),o=e.children(this._buttonGroupInCssClass);
var r=c('<div style="visibility: hidden; position: absolute; top: -10000px;"></div>').append(e).appendTo(this._jRibbonBar);
if(arguments[2]&&p.length){var l=this._getMutationClasses(p[0],1);
e.find("."+l.from+"[rel="+p[0].getAttribute("rel")+"]").removeClass(l.from).addClass(l.to);
}e.width("auto").show();
var s=$telerik.getMarginBox(e[0]);
var j=s.horizontal;
var d=o.children(this._smallButtonSelector);
var g=arguments[3]?arguments[3]:3;
var h=Math.ceil(d.length/g);
c(this._largeButtonCssClass+", "+this._templateItemLargeCssClass,e).each(function(){j+=c(this).outerWidth(true);
});
var i=new Array(h);
d.each(function(t){var u=Math.floor(t/g);
var v=c(this);
var x=0;
if($telerik.isIE6||$telerik.isIE7||$telerik.quirksMode){var w=c(this).children().children();
if(c(this).hasClass("rrbTemplateItem")){w=c(this).children();
w.each(function(){x+=c(this).outerWidth();
});
}else{if(w.hasClass(this._buttonMidCssClass)){w=w.children(".rrbButtonIn");
}w.each(function(){var y=c(this).children(".rrbImagePlaceholder");
var z=c(this).children(f._buttonTextCssClass);
if(w.length>1){x+=z.outerWidth()+y.outerWidth()+3;
}else{x=z.outerWidth()+y.outerWidth()+6;
}});
}}else{x=v.outerWidth(true)+1;
}if(i[u]===undefined||i[u]<x){i[u]=x;
}});
for(var m=0,k=i.length;
m<k;
m++){j+=i[m];
}r.remove();
n.data("guideWidths",i);
n.data("width",j);
return j;
},_updateGroup:function(d){var e=this._getImportance(d);
d.data("importance",e);
d.data("importanceIndex",this._calculateImportance(e));
},_updateGroupsData:function(){var d=this;
this._pageGroups.each(function(){var e=c(this);
var f=0;
f=d._getCompositeImportance(e);
e.data("hasComposites",!!f.length);
if(!f.length){f=d._getImportance(e);
}e.data("originalImportance",f);
e.data("originalImportanceIndex",d._calculateImportance(f));
e.data("importance",f);
e.data("importanceIndex",d._calculateImportance(f));
});
},_updateVisibleGroupsSize:function(){var f=this.get_selectedTab();
var e=f.get_groups();
for(var d=0;
d<e.get_count();
d++){this._updateGroupSize(e.getGroup(d));
}},_getCompositeImportance:function(d){var g=[];
var f=d.children(this._buttonGroupInCssClass);
f=f.add(f.children(this._buttonGuideCssClass));
var e=f.children(this._buttonStripCssClass);
if(e.length){g.push(e.children(this._buttonStripPartCssClass));
}return g;
},_getImportance:function(d){var h=[];
var g=d.children(this._buttonGroupInCssClass);
g=g.add(g.children(this._buttonGuideCssClass));
for(var f=0,e=this._importance.length;
f<e;
f++){h.push(g.children(this._importance[f]));
}return h;
},_calculateImportance:function(d){var e=0;
for(var f=0,g=d.length;
f<g;
f++){e+=d[f].length*Math.pow(3,f);
}return e;
},_getDropDownWidth:function(e){var d=e.children().children().children(this._buttonOutCssClass);
var g=0;
var f=this;
d.css("float","left");
if($telerik.isIE6||$telerik.quirksMode){d.css({zoom:"normal",width:"1px"});
}d.each(function(){var h=c(this);
var i=h.find(".rrbImagePlaceholder").outerWidth(true)+h.find(f._buttonTextCssClass).outerWidth(true)+($telerik.isIE6||$telerik.isIE7||$telerik.quirksMode?5:0);
if(g<i){g=i;
}});
d.css("float","none");
if($telerik.isIE6||$telerik.quirksMode){d.css({zoom:"1",width:"auto"});
}return g;
},_getRelativeOffset:function(d,e){d=c(d);
if(typeof(e)==="string"){e=d.parents(e);
}var f=e.offset();
var g=d.offset();
return{left:g.left-f.left,top:g.top-f.top};
},_hideMenus:function(){var d=c(this._menuGroupOutCssClass+":visible",this._jRibbonBar);
if(d.length){d.each(function(){var e=c(this);
e.stop(true,true).slideUp("fast",function(){e.hide();
if(e[0]._button.hasClass("rrbExpanded")){e[0]._button.removeClass("rrbExpanded");
}});
});
}}};
Telerik.Web.UI.RadRibbonBar._preInitialize=function(d){var e=c("#"+d).data("isInitialized");
if(e){return;
}c("#"+d+" .rrbButtonAreaIn").css("visibility","hidden");
};
c.registerControlProperties(a.RadRibbonBar,{tabData:[],groupData:[],defaultImageUrl:"",defaultImageUrlLarge:"",defaultDisabledImageUrl:"",defaultDisabledImageUrlLarge:"",applicationMenuDropDown:null,qatItemsHierarchicalIndices:null});
c.registerControlEvents(a.RadRibbonBar,["load","selectedTabChanging","selectedTabChanged","buttonClicking","buttonClicked","splitButtonClicking","splitButtonClicked","menuItemClicking","menuItemClicked","launcherClicking","launcherClicked","buttonToggling","buttonToggled","toggleListToggling","toggleListToggled","applicationMenuItemClicking","applicationMenuItemClicked"]);
a.RadRibbonBar.registerClass("Telerik.Web.UI.RadRibbonBar",a.RadWebControl);
})($telerik.$);
(function(b){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarContextualTabGroup=function(c){this._element=c;
this._textElement=b(".rrbContextualTabLabel",c)[0];
this._text=b(this._textElement).text();
};
a.RibbonBarContextualTabGroup.prototype={get_element:function(){return this._element;
},get_text:function(){return this._text;
},get_isActive:function(){return b(this._element).hasClass("rrbContextualTabActive");
},activate:function(){b(this._element).addClass("rrbContextualTabActive");
},deactivate:function(){b(this._element).removeClass("rrbContextualTabActive");
if(this._onDeactivate){this._onDeactivate(this);
}},get_tabs:function(){if(typeof(this._tabs)=="undefined"){this._tabs=[];
}return this._tabs;
}};
a.RibbonBarContextualTabGroup.registerClass("Telerik.Web.UI.RibbonBarContextualTabGroup");
})($telerik.$);
(function(b){var a=Telerik.Web.UI;
a.RadRibbonBar.prototype.get_contextualTabGroups=function(){if(typeof(this._contextualTabGroups)=="undefined"){this._contextualTabGroups=[];
}return this._contextualTabGroups;
};
a.RadRibbonBar.prototype.findContextualTabGroupByText=function(f){var e=this.get_contextualTabGroups();
for(var c=0;
c<e.length;
c++){var d=e[c];
if(d.get_text()===f){return d;
}}return null;
};
a.RadRibbonBar.prototype._initializeContextualTabGroups=function(){var h=b(".rrbContextualTab",this._tabsContainerElement);
if(h.length){var e=this.get_contextualTabGroups();
for(var d=0;
d<h.length;
d++){var c=h[d];
var f=new a.RibbonBarContextualTabGroup(c);
var g=this;
f._onDeactivate=function(i){g._onContextualTabGroupDeactivate(i);
};
e[e.length]=f;
this._initializeContextualTabs(f);
}}};
a.RadRibbonBar.prototype._onContextualTabGroupDeactivate=function(g){var d=g.get_tabs();
var f=this.get_selectedTab();
var e=null;
for(var c=0;
c<d.length;
c++){if(e=(f==d[c]?d[c]:null)){break;
}}if(e){this.set_selectedTabIndex(0);
}};
a.RadRibbonBar.prototype._initializeContextualTabs=function(f){var c=b(".rrbTab",f.get_element());
var d=f.get_tabs();
for(var g=0;
g<c.length;
g++){var e=c[g]._tab;
e.set_contextualTabGroup(f);
d[d.length]=e;
}};
a.RibbonBarTab.prototype.set_contextualTabGroup=function(c){this._contextualTabGroup=c;
};
a.RibbonBarTab.prototype.get_contextualTabGroup=function(){return this._contextualTabGroup;
};
})($telerik.$);
(function(c){var a=Telerik.Web.UI;
var b=Sys.Serialization.JavaScriptSerializer;
a.RadRibbonBar.prototype._initializeQuickAccessToolbar=function(){var e=[];
var d=this;
c(this._qatItemsHierarchicalIndices).each(function(){var h=this.split(":");
var i=d.get_tabs().getTab(h[0]);
var k=i.get_groups().getGroup(h[1]);
var j=k.get_items().getItem(h[2]);
e[e.length]=j;
});
var f=c(".rrbQuickAccessToolbar",this._jRibbonBar);
var g=true;
this._quickAccessToolbar=new a.RibbonBarQuickAccessToolbar(f);
this._qatActiveItemIndices=[];
this._qatActiveItemIndicesJson="[]";
this._quickAccessToolbar._onItemActivated=function(h){d._onQatItemActivated(h);
if(!g){d._updateShortcuts();
}};
this._quickAccessToolbar._onItemDeactivated=function(h){d._onQatItemDeactivated(h);
if(!g){d._updateShortcuts();
}};
this._quickAccessToolbar.initialize(e);
g=false;
};
a.RadRibbonBar.prototype._updateShortcuts=function(){if(this._quickAccessToolbar&&this._getNavigator()){a.RadRibbonBar.prototype._setKeyboardShortcut(this._quickAccessToolbar._getVisibleElements(),0);
this._getNavigator().rebuild();
}};
a.RadRibbonBar.prototype._setKeyboardShortcut=function(e,d){if(!e[d]){return;
}c(e[d]).find(".rrbKeyBox").html(d).parent("a").attr("accessKey",d);
a.RadRibbonBar.prototype._setKeyboardShortcut(e,++d);
};
a.RadRibbonBar.prototype._registerQatActiveItemIndex=function(d){if(Array.indexOf(this._qatActiveItemIndices,d)==-1){Array.add(this._qatActiveItemIndices,d);
this._updateQatActiveItemIndicesJson();
}};
a.RadRibbonBar.prototype._unregisterQatActiveIndex=function(d){Array.remove(this._qatActiveItemIndices,d);
this._updateQatActiveItemIndicesJson();
};
a.RadRibbonBar.prototype._updateQatActiveItemIndicesJson=function(){this._qatActiveItemIndicesJson=b.serialize(this._qatActiveItemIndices);
this.updateClientState();
};
a.RadRibbonBar.prototype._onQatItemActivated=function(d){this._registerQatActiveItemIndex(d.get_hierarchicalIndex());
};
a.RadRibbonBar.prototype._onQatItemDeactivated=function(d){this._unregisterQatActiveIndex(d.get_hierarchicalIndex());
};
a.RadRibbonBar.prototype.get_quickAccessToolbar=function(){return this._quickAccessToolbar;
};
})($telerik.$);
(function(b){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarQuickAccessToolbar=function(c){this._jElement=c;
this._jDropDownElement=b(".rrbQatDropDown",this._jElement);
this._jDropDownArrowElement=b(".rrbQatButton",this._jDropDownElement);
this._jDropDownListElement=b(".rrbSlide",this._jDropDownElement);
this._items=[];
};
a.RibbonBarQuickAccessToolbar.prototype={initialize:function(c){var f=b(".rrbQatItem:not(.rrbQatDropDown)",this._jElement);
var d=b("li",this._jDropDownListElement);
var e=this;
d.each(function(h,k){var m=c[h];
var g=f[h];
var l=new a.RibbonBarQuickAccessToolbarItem(g,k,m);
l.initialize();
e._items[e._items.length]=l;
var j=b(k).hasClass("rrbMenuItemCheckboxChecked");
if(j&&e._onItemActivated){e._onItemActivated(l._ribbonBarItem);
}});
this._jDropDownArrowElement.click(function(g){e._jDropDownListElement.toggle();
g.preventDefault();
});
b(this._jDropDownListElement).delegate("[type=checkbox]","change",function(g){var h=b(g.target).parents("li").get(0)._item;
if(g.target.checked){h.showQatElement();
b(h._dropDownItemElement).addClass("rrbMenuItemCheckboxChecked");
if(e._onItemActivated){e._onItemActivated(h._ribbonBarItem);
}}else{h.hideQatElement();
b(h._dropDownItemElement).removeClass("rrbMenuItemCheckboxChecked");
if(e._onItemDeactivated){e._onItemDeactivated(h._ribbonBarItem);
}}e._jDropDownListElement.toggle();
});
a.RadRibbonBar.prototype._setKeyboardShortcut(this._getVisibleElements(),0);
},_getVisibleElements:function(){return b(this._jElement).find(".rrbQatItem:not(.rrbQatDropDown)").filter(":visible");
},dispose:function(){b(this._jDropDownListElement).undelegate("[type=checkbox]","change");
},hideDropDown:function(){this._jDropDownListElement.hide();
},get_items:function(){return this._items;
},_putQatItemElementLastInQatItemList:function(c){b(c).insertBefore(this._jDropDownElement);
}};
a.RibbonBarQuickAccessToolbar.registerClass("Telerik.Web.UI.RibbonBarQuickAccessToolbar");
})($telerik.$);
(function(b){var a=Telerik.Web.UI;
Type.registerNamespace("Telerik.Web.UI");
a.RibbonBarQuickAccessToolbarItem=function(d,c,e){this._qatItemElement=d;
this._dropDownItemElement=c;
this._ribbonBarItem=e;
};
a.RibbonBarQuickAccessToolbarItem.prototype={_createQatItemElementContainer:function(){this._qatItemElement=document.createElement("LI");
this._qatItemElement.className="rrbQatItem";
},_cloneRibbonBarItemElement:function(){var c=b(this._ribbonBarItem.get_element()).clone();
return c;
},_setSmallCssClassToRibbonBarItemElement:function(d){var c=d.attr("class");
c=c.replace("rrbLargeButton","rrbButton");
c=c.replace("rrbMediumButton","rrbButton");
c=c.replace("rrbButtonStripPart","rrbButtonOut rrbButton");
d.attr("class",c);
},_createQatItemElement:function(){this._createQatItemElementContainer();
if(this._ribbonBarItem){var c=this._cloneRibbonBarItemElement();
this._setSmallCssClassToRibbonBarItemElement(c);
c.appendTo(this._qatItemElement);
}},_transferButtonExpandosFromSplitButtonElement:function(d){this._qatItemElement.firstChild._defaultButton=d._defaultButton;
var e=b("a",d._dropDown);
var c=b("a",this._qatItemElement.firstChild._dropDown);
e.each(function(f){c.get(f)._button=this._button;
});
},_transferButtonExpandosFromMenuItemElements:function(f,d){var g=b("a",f._dropDown);
var e=b("a",d._dropDown);
var c=this;
g.each(function(j){var h=e.get(j);
h._button=this._button;
if(this._dropDown){c._transferButtonExpandosFromMenuItemElements(this,h);
}});
},initialize:function(){if(this._qatItemElement){var c=this._ribbonBarItem.get_element();
if(c._button){this._qatItemElement.firstChild._button=c._button;
}if(b("span.rrbSplitButton",c).length>0){this._transferButtonExpandosFromSplitButtonElement(c);
}if(b("span.rrbMenuButton",c).length>0){this._transferButtonExpandosFromMenuItemElements(c,this._qatItemElement.firstChild);
}if(b("span.rrbToggleButton",c).length>0){c._button._setQuickAccessToolbarItemElement(this._qatItemElement.firstChild);
}}if(this._dropDownItemElement){this._dropDownItemElement._item=this;
}},get_qatItemElement:function(){if(!this._qatItemElement){this._createQatItemElement();
}return this._qatItemElement;
},get_element:function(){return this.get_qatItemElement();
},hideQatElement:function(){b(this._qatItemElement).hide();
},showQatElement:function(){b(this._qatItemElement).show();
}};
a.RibbonBarQuickAccessToolbarItem.registerClass("Telerik.Web.UI.RibbonBarQuickAccessToolbarItem");
})($telerik.$);
(function(c,d){var f=Sys.UI.Key;
var a="activeItemChanging";
var b={1:function(g){return g.altKey;
},2:function(g){return g.ctrlKey;
},3:function(g){return g.shiftKey;
},4:function(g){return g.altKey&&g.ctrlKey;
},5:function(g){return g.altKey&&g.shiftKey;
},6:function(g){return g.ctrlKey&&g.shiftKey;
}};
var e={ribbon:1,tab:2,applicationMenuItem:3,menu:4,menuItem:5,button:6};
d.Navigator=function(o){var h=null,p=d.Navigator,g=o._navigationSettings;
this._tree=new p.NavigationTree(o);
this._navigator=new p.KeyNavigator(o);
this._arrowsNavigator=new p.ArrowsNavigator();
var j=this._tree._innerTree,l=j,m=c(this._navigator),q=c(this._arrowsNavigator),k=false,n=this,i=null;
c.extend(this,{rebuild:function(){h=l;
n._tree._rebuildQuickAccessSubTree(o);
},initialize:function(){n.initializeHandlers();
n.initializeRootItem();
},initializeRootItem:function(){var r=o.get_selectedTab();
if(g.Activated){c.each(j.children,function(s,t){if(t.type==e.tab){if(t.domElement===c(r.get_element()).children(".rrbTabLabel")[0]){n.handleToggle(c.Event("keydown"));
m.trigger(a,[t]);
return false;
}}});
}},initializeHandlers:function(){m.bind(a,function(t,s){if(h){n.hide(h);
}if(k){n.show(h=s);
}});
var r=o.get_element();
c(r).bind("blur.key",function(s){n._setIsVisible(false);
m.trigger(a,[null]);
m.get(0).reset();
n._updateState(false);
});
c(document).bind("keydown.key",function(s){if(!i){i=s.target;
}n.handle(s);
});
},handle:function(r){if(n.isToggleCommand(r)){n.handleToggle(r);
}else{if(k){n.handleNavigation(r);
}}},handleToggle:function(r){r.preventDefault();
c(o.get_element()).focus();
n._setIsVisible(!k);
m.trigger(a,[l]);
},handleNavigation:function(r){r.preventDefault();
if(r.keyCode==f.up||r.keyCode==f.down){q.get(0).handle(r,h);
}else{n._updateState(true);
m.get(0).handle(r,h,function(){c(o.get_element()).blur();
c(i).focus();
i=null;
k=false;
});
}},isToggleCommand:function(r){var s=b[g.CommandKey](r);
if(s){return r.keyCode==g.FocusKey;
}else{return false;
}},dispose:function(){c(document).unbind("keydown.key");
c(o).unbind("blur.key");
m.unbind(a);
},hide:function(r){n._toggle(r,"hide");
},show:function(r){n._toggle(r,"show");
},_updateState:function(r){o._navigationSettings.activated=r;
o.updateClientState();
},_getActiveitem:function(){return h;
},_getIsVisible:function(){return k;
},_setIsVisible:function(r){k=r;
},_toggle:function(r,s){if(r){c(r.children).each(function(t,u){c(u.domElement).find(".rrbKeyBox")[s]();
});
}}});
};
d.Navigator.KeyNavigator=function(g){var j="",i={children:[],parent:null},h=this;
c.extend(this,{reset:function(){i.children=[];
i.parent=null;
j="";
},backwards:function(l,k){c.each(l.children,function(m,n){if(c(n.domElement).parents().is(g._menuGroupOutCssClass)){g._hideMenus();
return false;
}else{if(c(n.domElement).is(".rmLink")){g._hideApplicationMenu();
return false;
}}});
if(l.parent){l=l.parent;
}else{k();
}h.reset();
c(h).trigger(a,[l]);
},upwards:function(o,l,k){j+=String.fromCharCode(o.keyCode);
i.parent=l;
var n=i.children.length==0?l.children:i.children,m=false;
c.each(n,function(p,q){if(q.accessKey==j){h.triggerEventByType(q.domElement);
l=q;
c(h).trigger(a,[l]);
if(q.children.length==0){k();
}h.reset();
return false;
}else{if(q.accessKey.indexOf(j)==0){i.children.push(q);
m=true;
}}});
if(m){c(h).trigger(a,[i]);
}else{h.reset();
}},handle:function(m,l,k){if(m.keyCode==f.esc){h.backwards(l,k);
}else{h.upwards(m,l,k);
}},triggerEventByType:function(l){$el=c(l);
if($el.children().is(".rrbSubMenu")){$el.mouseover();
}else{if($el.children().is(".rrbSplitButton")){$el.find(".rrbButtonText:first").click();
}else{if($el.is(".rmLink")){var k=c.Event("click",{target:l,eventMapTarget:l});
g.get_applicationMenuDropDown()._onItemClick(k);
}else{$el.click();
}}}},resetMask:function(){j="";
}});
};
d.Navigator.ArrowsNavigator=function(){};
d.Navigator.ArrowsNavigator.prototype={handle:function(){}};
d.Navigator.NavigationTree=function(g){this._innerTree=this.buildTree(g);
};
d.Navigator.NavigationTree.prototype={get_tree:function(){return this._innerTree;
},buildTree:function(g){var h=this,i=this._buildNode(g,function(k){var j=[h._buildTabs(k),h._buildApplicationMenu(k),h._buildQuickAccessToolbar(k)];
return h._flatten(j);
});
this._setParent(i);
return i;
},_flatten:function(l){var k=[];
for(var g=0;
g<l.length;
g++){for(var h=0;
h<l[g].length;
h++){k[k.length]=l[g][h];
}}return k;
},_determineElementType:function(k){var i=c(k),h=".rrbApplicationTab",g=i.is("a")||i.is(".RadRibbonBar"),j=i.parents().is(h);
if(g){if(i.is(".RadRibbonBar")){return e.ribbon;
}else{if(i.parents().is(".rrbMenuGroupIn")){return e.menu;
}else{if(i.parents().is(".rrbButtonOut")){return e.menuItem;
}else{if(i.is(".rrbButtonOut")){return e.button;
}else{if(i.is(".rrbTabLabel")){return e.tab;
}else{return -1;
}}}}}}else{if(j){if(i.is(".rmLink")){return e.applicationMenuItem;
}}}},_determineAccessKeyElementFromSourceElement:function(k){var i=c(k),h=".rrbApplicationTab",g=i.is("a")||i.is(".RadRibbonBar"),j=i.parents().is(h);
if(g){return k;
}else{if(j){if(i.is("li")){return i.find("a").get(0);
}else{return i.parents(h+":first").find("a:first").get(0);
}}else{return i.find("a:first").get(0);
}}},_rebuildQuickAccessSubTree:function(g){var i=[];
var h=this._buildQuickAccessToolbar(g);
c(this.get_tree().children).each(function(j,k){if(!c(k.domElement).parent().is(".rrbQatItem")){i.push(k);
}});
this._innerTree.children=this._flatten([i,h]);
this._setParent(this._innerTree);
},_buildNode:function(h,n){var k=h.get_element(),g=this._determineAccessKeyElementFromSourceElement(k),m="accessKey",j=c(g).attr(m)||"",l=this._determineElementType(g);
var i={accessKey:j,domElement:g,parent:null,children:n(h),type:l};
this._cleanAccessKey(g);
return i;
},_buildTabs:function(g){var i=[],h=this;
g.get_tabs().forEach(function(j){i[i.length]=h._buildNode(j,function(k){return h._buildGroupItems(k);
});
});
return i;
},_buildApplicationMenu:function(g){var i=this,h=g.get_applicationMenuDropDown();
if(h){return[this._buildNode(h,function(j){return i._buildItems(j);
})];
}else{return[];
}},_buildQuickAccessToolbar:function(j){var m=this,l=[],g=j.get_quickAccessToolbar();
if(g){var n=g.get_items();
for(var h=0;
h<n.length;
h++){var o=n[h];
var k=c(o.get_element());
if(k.is(":visible")){l.push(this._buildNode(o,function(p){var q=[];
var i=k.find("a").get(0)._dropDown;
c(i).find("a").each(function(r,t){var s={get_element:function(){return t;
}};
q[q.length]=m._buildNode(s,function(){return[];
});
});
return q;
}));
}}return l;
}else{return[];
}},_buildGroupItems:function(h){var i=[],g=this;
h.get_groups().forEach(function(j){j.get_items().forEach(function(k){i[i.length]=g._buildNode(k,function(l){return g._buildItems(l);
});
});
});
return i;
},_buildItems:function(g){if(!g.get_items||g.get_items().get_count()==0){return[];
}var i=[],h=this;
g.get_items().forEach(function(j){i[i.length]=h._buildNode(j,function(k){return h._buildItems(k);
});
});
return i;
},_setParent:function(h){function g(i){if(i.children.length==0){return;
}c(i.children).each(function(k,j){j.parent=i;
g(j);
});
}c(h.children).each(function(j,i){g(h);
});
},_cleanAccessKey:function(g){c(g).attr("accessKey","");
}};
})($telerik.$,Telerik.Web.UI.RadRibbonBar);
