Type.registerNamespace("Telerik.Web.UI.Spell");
(function(){var b=$telerik.$;
var a=Telerik.Web.UI;
a.Spell.SpellDialog=function(c){a.Spell.SpellDialog.initializeBase(this,[c]);
this._clientParameters=null;
this._spell=null;
this._modeChangedHandler=null;
this._suggestionsDblClickHandler=null;
this._spellProcessor=null;
this._contentDisplay=null;
this._windowClosingDelegate=null;
};
a.Spell.SpellDialog.prototype={initialize:function(){a.Spell.SpellDialog.callBaseMethod(this,"initialize");
this.initChildControls();
},dispose:function(){if(this._contentDisplay){this._contentDisplay.remove_modeChanged(this._modeChangedHandler);
this._modeChangedHandler=null;
this._contentDisplay.remove_suggestionsDblClick(this._suggestionsDblClickHandler);
this._suggestionsDblClickHandler=null;
}this._windowClosingDelegate=null;
a.Spell.SpellDialog.callBaseMethod(this,"dispose");
},clientInit:function(f){this._suggestions.disabled=false;
this._suggestions.options.length=0;
this._suggestions.disabled=true;
this.enableButton(this._cancel);
this._getChildElement("TextContainer").innerHTML="";
this._clientParameters=f;
this._spell=this._clientParameters.spell;
this._textSource=this._clientParameters.textSource;
if(!this._textSource||!this._textSource.get_text){alert("This textsource does not support the get_text() method.");
return;
}var e=a.Dialogs.CommonDialogScript.get_windowReference();
var c=e.BrowserWindow;
this._origFn=c.Function._validateParams;
try{c.Function._validateParams=new c.Function();
}catch(g){}Sys.Application.add_unload(Function.createDelegate(this,this.restoreFrameworkCode));
this._windowClosingDelegate=Function.createDelegate(this,this.prepareClose);
e.add_close(this._windowClosingDelegate);
this._textToCheck=this.escapeNewLines(this._textSource.get_text());
var d=this;
if(this._clientParameters.dictionaryLanguage){this.get_service().set_language(this._clientParameters.dictionaryLanguage);
}this.get_service().spellCheck(this._textToCheck);
},initChildControls:function(){var c=a.Dialogs.CommonDialogScript.get_windowReference();
c.set_title(this.get_localization().Title);
this._suggestions=this._getChildElement("Suggestions");
this._ignore=this.getConfiguredButton("Ignore",this.ignoreHandler);
this._ignoreAll=this.getConfiguredButton("IgnoreAll",this.ignoreAllHandler);
this._addCustom=this.getConfiguredButton("AddCustom",this.addCustomHandler);
this._change=this.getConfiguredButton("Change",this.changeHandler);
this._changeAll=this.getConfiguredButton("ChangeAll",this.changeAllHandler);
this._undo=this.getConfiguredButton("Undo",this.undoHandler);
this._cancel=this.getConfiguredButton("Cancel",this.cancelHandler);
},ignoreHandler:function(c){if(this._contentDisplay.get_editMode()){this._contentDisplay.switchMode();
}else{this._spellProcessor.ignore();
this.raiseOnClientWordIgnoredEvent(false);
this.moveForward();
}return $telerik.cancelRawEvent(c);
},ignoreAllHandler:function(c){if(this._ignoreAll.disabled){return $telerik.cancelRawEvent(c);
}this._spellProcessor.ignoreAll();
this.raiseOnClientWordIgnoredEvent(true);
this.moveForward();
return $telerik.cancelRawEvent(c);
},addCustomHandler:function(f){if(this._addCustom.disabled){return $telerik.cancelRawEvent(f);
}var c=this._spellProcessor.currentBadWord().wordString;
if(!confirm(this.get_localization()["AddWord1"]+c+this.get_localization()["AddWord2"])){return $telerik.cancelRawEvent(f);
}this.disableAllButtons();
var d=this;
this.get_service().addCustomWord(c);
return $telerik.cancelRawEvent(f);
},changeHandler:function(c){if(this._change.disabled){return $telerik.cancelRawEvent(c);
}this.changeCurrentWord(this._contentDisplay.replacementWord());
return $telerik.cancelRawEvent(c);
},changeAllHandler:function(c){if(this._changeAll.disabled){return $telerik.cancelRawEvent(c);
}if(this._spellProcessor.allWordsFixed()){return $telerik.cancelRawEvent(c);
}this._spellProcessor.changeAll(this._contentDisplay.replacementWord());
this.raiseOnClientWordCorrectedEvent(true);
this.moveForward();
return $telerik.cancelRawEvent(c);
},undoHandler:function(d){if(this._undo.disabled){return $telerik.cancelRawEvent(d);
}var c=this._spellProcessor.lastActionBadWordStartCharOffsets();
this._spellProcessor.undo();
this.raiseOnClientActionUndoneEvent(c);
this.processCurrentStep();
return $telerik.cancelRawEvent(d);
},cancelHandler:function(c){if(this._cancel.disabled){return $telerik.cancelRawEvent(c);
}this.closeDialog(this._spellProcessor&&this._spellProcessor.textChanged()&&confirm(this.get_localization()["Confirm"]));
return $telerik.cancelRawEvent(c);
},disableButton:function(c){a.RadFormDecorator.set_enabled(c,false);
},enableButton:function(c){a.RadFormDecorator.set_enabled(c,true);
},setButtonEnabled:function(c,d){if(d){this.enableButton(c);
}else{this.disableButton(c);
}},getConfiguredButton:function(d,e){var c=this._getChildElement(d);
if(c){$addHandlers(c,{click:e},this);
c.disabled=true;
}return c;
},get_service:function(){if(this._service==null){this._service=$create(a.SpellCheckService,null,null,null);
this._service.set_configuration(this.get_serviceConfiguration());
this._service.set_url(this.get_serviceUrl());
this._service.add_complete(Function.createDelegate(this,this.spellCheckResponseReceived));
}return this._service;
},changeCurrentWord:function(c){if(this._spellProcessor.allWordsFixed()){return;
}this._spellProcessor.change(c);
this.raiseOnClientWordCorrectedEvent(false);
this.moveForward();
},moveForward:function(){this._spellProcessor.moveToNextWord();
this.processCurrentStep();
},processCurrentStep:function(){if(!this._spellProcessor.allWordsFixed()){this.updateContent();
}else{this.closeDialog(true);
}},restoreFrameworkCode:function(){if(null!=this._origFn){var c=a.Dialogs.CommonDialogScript.get_windowReference();
if(c){var d=c.BrowserWindow;
d.Function._validateParams=this._origFn;
}this._origFn=null;
}},prepareClose:function(d){if(null!=this._windowClosingDelegate){var c=a.Dialogs.CommonDialogScript.get_windowReference();
c.remove_close(this._windowClosingDelegate);
this._windowClosingDelegate=null;
this.restoreFrameworkCode();
}this.disableAllButtons();
this.raiseDialogClosingEvents();
if(this._spellProcessor){if(this._spellProcessor.allWordsFixed()){this._spell.set_spellChecked(true);
}if(d){this.applyChanges();
}this._spellProcessor=null;
}},closeDialog:function(c){this.prepareClose(c);
this._spell.raiseEvent("clientDialogClosing",Sys.EventArgs.Empty);
a.Dialogs.CommonDialogScript.get_windowReference().close();
},spellCheckResponseReceived:function(f,e){if(e.AddCustomWord){var d=this._spellProcessor.currentBadWord().wordString;
this._spellProcessor.processCustomWordAddition();
this.raiseOnClientCustomWordAddedEvent(d);
this.processCurrentStep();
this.enableButton(this._cancel);
}else{var c={textToCheck:this._textToCheck,badWords:e.badWords,wordOffsets:e.wordOffsets};
this._spellProcessor=$create(a.Spell.SpellProcessor,c,null,null);
if(!this._spellProcessor.allWordsFixed()){this.initContentDisplay();
this.updateContent();
}else{this.closeDialog(true);
}}},escapeNewLines:function(d){var c=d.replace(/\n/gi,"&nbsp;<telerikcr />");
c=c.replace(/\r/gi,"<teleriklf />");
return c;
},unEscapeNewLines:function(d){var c=d.replace(/(&nbsp;)?<telerikcr\s*\/>/gi,"\n");
c=c.replace(/<teleriklf\s*\/>/gi,"\r");
return c;
},updateContent:function(){if(this._contentDisplay.get_editMode()){this._contentDisplay.switchMode();
}this._contentDisplay.showText(this._spellProcessor.currentErrorContent());
this.focusCurrentError();
this._contentDisplay.fillSuggestions(this._spellProcessor.currentSuggestions());
this.updateButtonStates();
},focusCurrentError:function(){var c=document.getElementById(this._spellProcessor.highlightedElementId());
var e=this._contentDisplay;
if(c&&!e.get_editMode()){var d=function(){if(c&&c.parentNode){var f=c.offsetTop-($telerik.isIE?0:2*c.offsetHeight);
e.get_textContainer().scrollTop=f;
c.focus();
}};
if($telerik.isIE){window.setTimeout(d,0);
}else{d();
}}},disableAllButtons:function(){this.disableButton(this._ignore);
this.disableButton(this._ignoreAll);
this.disableButton(this._change);
this.disableButton(this._changeAll);
this.disableButton(this._undo);
this.disableButton(this._cancel);
if(this._addCustom){this.disableButton(this._addCustom);
}},initContentDisplay:function(){this._modeChangedHandler=Function.createDelegate(this,this.contentDisplay_modeChanged);
this._suggestionsDblClickHandler=Function.createDelegate(this,this.contentDisplay_suggestionsDblClick);
var c={localization:this.get_localization(),textContainer:this._getChildElement("TextContainer"),textEditor:this._getChildElement("TextEditor"),suggestions:this._suggestions};
var d={modeChanged:this._modeChangedHandler,suggestionsDblClick:this._suggestionsDblClickHandler};
if(!this._contentDisplay){this._contentDisplay=$create(a.Spell.ContentDisplay,c,d,null);
}this._contentDisplay.focus();
},updateButtonStates:function(){var c=this._spellProcessor.currentSuggestions().length>0;
this.enableButton(this._ignore);
this.setButtonEnabled(this._ignoreAll,!this._contentDisplay.get_editMode());
this.setButtonEnabled(this._undo,this._spellProcessor.currentUndoAction()!=null);
this.setButtonEnabled(this._change,this._contentDisplay.get_editMode()||c);
this.setButtonEnabled(this._changeAll,!this._contentDisplay.get_editMode()&&c);
if(this._addCustom!=null){this.setButtonEnabled(this._addCustom,!this._contentDisplay.get_editMode());
}this._ignore.innerHTML=this._contentDisplay.get_editMode()?this.get_localization()["UndoEdit"]:this.get_localization()["Ignore"];
},contentDisplay_modeChanged:function(e,c){var d="";
if(c.editMode){d=this._spellProcessor.currentBadWord().wordString;
}else{d=this._spellProcessor.currentErrorContent();
}this.updateButtonStates();
this._contentDisplay.showText(d);
this.focusCurrentError();
},contentDisplay_suggestionsDblClick:function(c,d){if(this._spellProcessor.currentSuggestions().length>0){this.changeCurrentWord(d.selectedValue);
}else{alert(this.get_localization()["Nosuggestions"]);
}},applyChanges:function(){this._textSource.set_text(this.unEscapeNewLines(this._spellProcessor.get_textToCheck()));
},raiseDialogClosingEvents:function(){if(this._spellProcessor&&this._spellProcessor.allWordsFixed()){var c={suppressCompleteMessage:false};
this._spell.raiseEvent("clientCheckFinished",c);
if(!c.suppressCompleteMessage){alert(this.get_localization()["SpellCheckComplete"]);
}}else{this._spell.raiseEvent("clientCheckCancelled",Sys.EventArgs.Empty);
}},raiseOnClientWordCorrectedEvent:function(c){var e=this._spellProcessor.currentBadWord();
var d={originalWord:e.originalWordString,newWord:e.wordString,offsets:this._spellProcessor.lastActionBadWordStartCharOffsets(),changeAll:c};
this._spell.raiseEvent("clientWordCorrected",d);
},raiseOnClientWordIgnoredEvent:function(e){var c=this._spellProcessor.currentBadWord();
var d={ignoreWord:c.originalWordString,offsets:this._spellProcessor.lastActionBadWordStartCharOffsets(),ignoreAll:e};
this._spell.raiseEvent("clientWordIgnored",d);
},raiseOnClientActionUndoneEvent:function(c){var d=this._spellProcessor.currentBadWord();
var e={originalWord:d.originalWordString,offsets:c};
this._spell.raiseEvent("clientActionUndone",e);
},raiseOnClientCustomWordAddedEvent:function(d){var c={customWord:d};
this._spell.raiseEvent("clientCustomWordAdded",c);
}};
b.registerControlProperties(a.Spell.SpellDialog,{serviceConfiguration:null,serviceUrl:null,localization:{}});
a.Spell.SpellDialog.registerClass("Telerik.Web.UI.Spell.SpellDialog",a.RadWebControl,Telerik.Web.IParameterConsumer);
b.registerEnum(a.Spell,"SpellProcessorActions",{Change:0,ChangeAll:1,Ignore:2,IgnoreAll:4,AddCustom:8});
a.Spell.SpellProcessor=function(){a.Spell.SpellProcessor.initializeBase(this);
this._undoActions=[];
this._surroundingWordsCount=10;
};
a.Spell.SpellProcessor.prototype={initialize:function(){a.Spell.SpellProcessor.callBaseMethod(this,"initialize");
},dispose:function(){a.Spell.SpellProcessor.callBaseMethod(this,"dispose");
},moveToNextWord:function(){var c=this.nextBadWordIndex();
if(c<0){return;
}this.set_currentBadWordIndex(c);
},moveToPreviousWord:function(){this.set_currentBadWordIndex(this.nextBadWordIndex(0));
},nextBadWordIndex:function(d){if(typeof(d)=="undefined"){d=this.get_currentBadWordIndex();
}for(var c=d;
c<this.get_badWords().length;
c++){if(this.getBadWord(c).originalWordString==null){return c;
}}return -1;
},allWordsFixed:function(){return this.nextBadWordIndex()<0;
},currentErrorContent:function(){var c=this.currentBadWord();
return this.startString(this.get_currentBadWordIndex(),true)+"<a style='border-bottom: 1px dotted red;font-weight: bold;' id="+this.highlightedElementId()+">"+c.wordString+"</a>"+this.endString(this.get_currentBadWordIndex(),true);
},highlightedElementId:function(){return"spell_highlight_"+this.currentBadWord().wordString;
},startString:function(f,g){var d=0;
var c=this.getBadWord(f);
if(g&&(c.textOffset>this._surroundingWordsCount)){var e=c.textOffset-this._surroundingWordsCount;
d=this.get_wordOffsets()[e];
}return this.get_textToCheck().substring(d,this.wordStartCharIndex(f));
},endString:function(f,g){var c=this.get_textToCheck().length;
var d=this.getBadWord(f);
if(g&&(this.get_wordOffsets().length>d.textOffset+this._surroundingWordsCount)){var e=d.textOffset+this._surroundingWordsCount;
c=this.get_wordOffsets()[e];
}return this.get_textToCheck().substring(this.wordEndCharIndex(f),c);
},wordStartCharIndex:function(c){return this.get_wordOffsets()[this.wordOffset(c)];
},wordEndCharIndex:function(c){return this.wordStartCharIndex(c)+this.getBadWord(c).wordString.length;
},getBadWord:function(c){return this.get_badWords()[c];
},currentBadWord:function(){return this.getBadWord(this.get_currentBadWordIndex());
},wordOffset:function(c){return this.getBadWord(c).textOffset;
},currentWordOffset:function(){return this.currentBadWord().textOffset;
},currentSuggestions:function(){return this.currentBadWord().suggestionsString;
},ignore:function(){this.changeWord(this.currentBadWord().wordString,a.Spell.SpellProcessorActions.Ignore);
},ignoreAll:function(){this.changeAllWords(this.currentBadWord().wordString,a.Spell.SpellProcessorActions.IgnoreAll);
},change:function(c){this.changeWord(c,a.Spell.SpellProcessorActions.Change);
},changeAll:function(c){this.changeAllWords(c,a.Spell.SpellProcessorActions.ChangeAll);
},processCustomWordAddition:function(){var c=this.sameWordStringBadWordIndexes();
for(var d=c.length-1;
d>=0;
d--){var e=c[d];
this.get_badWords().splice(e,1);
}this.moveToNextWord();
},changeWord:function(e,c){var d=[this.get_currentBadWordIndex()];
this.processChange(d,e,false,c);
this.registerUndoStep(d);
},changeAllWords:function(e,c){var d=this.sameWordStringBadWordIndexes();
this.processChange(d,e,false,c);
this.registerUndoStep(d);
},changeText:function(d,c){this.set_textToCheck(this.startString(d,false)+c+this.endString(d,false));
},offsetsByBadWordIndexes:function(d){var c=[];
for(var e=0;
e<d.length;
e++){c[c.length]=this.wordOffset(d[e]);
}return c;
},lastActionBadWordOffsets:function(){var c=this.currentUndoAction();
return this.offsetsByBadWordIndexes(c);
},lastActionBadWordStartCharOffsets:function(){var c=[];
var d=this.lastActionBadWordOffsets();
for(var e=0;
e<d.length;
e++){c[c.length]=this.get_wordOffsets()[d[e]];
}return c;
},sameWordStringBadWordIndexes:function(){var c=this.currentBadWord().wordString;
var d=[this.get_currentBadWordIndex()];
for(var e=this.get_currentBadWordIndex()+1;
e<this.get_badWords().length;
e++){if(this.getBadWord(e).wordString==c){d[d.length]=e;
}}return d;
},undo:function(){var d=this.currentUndoAction();
var c=this.getBadWord(d[0]).originalWordString;
this.processChange(d,c,true);
this.unregisterUndoStep();
this.moveToPreviousWord();
},correctWord:function(f,d,c){if(this.getBadWord(f).originalWordString){return;
}var e=this.getBadWord(f);
e.originalWordString=e.wordString;
e.wordString=d;
e.correctionAction=c;
},restoreWord:function(d){var c=this.getBadWord(d);
c.wordString=c.originalWordString;
c.originalWordString=null;
c.correctionAction=null;
},processChange:function(j,g,h,c){for(var d=0;
d<j.length;
d++){var f=j[d];
var e=this.getBadWord(f);
var k=g.length-e.wordString.length;
this.adjustOffsetsAfterChangedWord(e,k);
this.changeText(f,g);
if(h){this.restoreWord(f);
}else{this.correctWord(f,g,c);
}}},adjustOffsetsAfterChangedWord:function(d,e){for(var c=d.textOffset+1;
c<this.get_wordOffsets().length;
c++){this.get_wordOffsets()[c]+=e;
}},currentUndoAction:function(){if(this._undoActions.length==0){return null;
}return this._undoActions[this._undoActions.length-1];
},registerUndoStep:function(c){this._undoActions[this._undoActions.length]=c;
},unregisterUndoStep:function(){this._undoActions=this._undoActions.slice(0,-1);
},textChanged:function(){for(var d=0;
d<this.get_currentBadWordIndex();
d++){var c=this.getBadWord(d).correctionAction;
if(c==a.Spell.SpellProcessorActions.Change||c==a.Spell.SpellProcessorActions.ChangeAll){return true;
}}return false;
}};
b.registerControlProperties(a.Spell.SpellProcessor,{currentBadWordIndex:0,textToCheck:null,badWords:null,wordOffsets:null});
a.Spell.SpellProcessor.registerClass("Telerik.Web.UI.Spell.SpellProcessor",Sys.Component);
a.Spell.ContentDisplay=function(){a.Spell.ContentDisplay.initializeBase(this);
};
a.Spell.ContentDisplay.prototype={initialize:function(){a.Spell.ContentDisplay.callBaseMethod(this,"initialize");
$addHandlers(this.get_textContainer(),{click:this.switchMode},this);
this.get_suggestions().disabled=false;
$addHandlers(this.get_suggestions(),{dblclick:this.suggestionsDblClick},this);
},dispose:function(){$clearHandlers(this.get_suggestions());
$clearHandlers(this.get_textContainer());
this.set_textContainer(null);
this.set_textEditor(null);
this.set_suggestions(null);
this.set_localization(null);
a.Spell.ContentDisplay.callBaseMethod(this,"dispose");
},showText:function(c){if(this.get_editMode()){this.get_textEditor().value=c;
}else{try{this.get_textContainer().innerHTML=c;
}catch(d){c=c.replace(/<\/?form[^>]*>/gi,"");
this.get_textContainer().innerHTML=c;
}}},focus:function(){if(this.get_editMode()){this.get_textEditor().focus();
}else{if(this.get_suggestions().disabled){this.get_suggestions().disabled=false;
}this.get_suggestions().focus();
}},switchMode:function(){this.set_editMode(!this.get_editMode());
if(this.get_editMode()){this.get_textContainer().style.display="none";
this.get_textEditor().style.display="block";
this.get_textEditor().focus();
this.get_suggestions().disabled=true;
}else{this.get_textContainer().style.display="";
this.get_textEditor().style.display="none";
this.get_suggestions().disabled=false;
}this.raiseEvent("modeChanged",{editMode:this.get_editMode()});
this.focus();
},replacementWord:function(){if(this.get_editMode()){return this.get_textEditor().value;
}else{return this.selectedSuggestion();
}},selectedSuggestion:function(){return this.get_suggestions().options[this.get_suggestions().selectedIndex].value;
},fillSuggestions:function(c){this.clearSuggestions();
if(c.length>0){for(var d=0;
d<c.length;
d++){this.addSuggestion(c[d]);
}}else{this.addSuggestion(this.get_localization()["Nosuggestions"]);
}this.get_suggestions().selectedIndex=0;
},clearSuggestions:function(){this.get_suggestions().options.length=0;
},addSuggestion:function(c){this.get_suggestions().options[this.get_suggestions().options.length]=new Option(c,c);
},suggestionsDblClick:function(){this.raiseEvent("suggestionsDblClick",{selectedValue:this.selectedSuggestion()});
},raiseEvent:function(d,e){var c=this.get_events().getHandler(d);
if(c){if(!e){e=Sys.EventArgs.Empty;
}c(this,e);
}}};
b.registerControlProperties(a.Spell.ContentDisplay,{localization:null,suggestions:null,textContainer:null,editMode:false,textEditor:null});
b.registerControlEvents(a.Spell.ContentDisplay,["suggestionsDblClick","modeChanged"]);
a.Spell.ContentDisplay.registerClass("Telerik.Web.UI.Spell.ContentDisplay",Sys.Component);
})();
