(function(){var e=$telerik.$;
var a=Telerik.Web.UI;
var h=a.Scheduler;
var d=a.RadScheduler.prototype;
var c=a.SchedulerAppointment.prototype;
function i(){if(!this._isSchedulerContentRendered()){return;
}this._appLoadContextMenuCallback=Function.createDelegate(this,this._appLoadContextMenus);
Sys.Application.add_load(this._appLoadContextMenuCallback);
this.add_timeSlotContextMenu(f);
this.add_appointmentContextMenu(b);
}function g(){if(!this._isSchedulerContentRendered()){return;
}this.remove_timeSlotContextMenu(f);
this.remove_appointmentContextMenu(b);
this._removeAppointmentContextMenuHandlers();
this._removeTimeSlotContextMenuHandlers();
}function f(j,k){j._showTimeSlotContextMenu(k.get_domEvent(),k.get_targetSlot());
}function b(j,k){j._contextMenuAppointment=k.get_appointment();
k.get_appointment().showContextMenu(k.get_domEvent());
}a.RadScheduler._plugins.push({onInitialize:i,onDispose:g});
h.ContextMenuCommands={Edit:"CommandEdit",Delete:"CommandDelete",AddApt:"CommandAddAppointment",AddAptRecurring:"CommandAddRecurringAppointment",ShowFullTime:"CommandShow24Hours",GoToToday:"CommandGoToToday"};
d._appLoadContextMenus=function(){Sys.Application.remove_load(this._appLoadContextMenuCallback);
this._addAppointmentContextMenuHandlers();
this._addTimeSlotContextMenuHandlers();
};
d._addTimeSlotContextMenuHandlers=function(){this._timeSlotContextMenuHandlersAdded=true;
this._timeSlotContextMenuItemClickingDelegate=Function.createDelegate(this,this._timeSlotContextMenuItemClickingHandler);
this._timeSlotContextMenuItemClickedDelegate=Function.createDelegate(this,this._timeSlotContextMenuItemClickedHandler);
var l=this.get_timeSlotContextMenus();
for(var j=0;
j<l.length;
j++){var k=l[j];
if(k){k.add_itemClicking(this._timeSlotContextMenuItemClickingDelegate);
k.add_itemClicked(this._timeSlotContextMenuItemClickedDelegate);
}}};
d._timeSlotContextMenuItemClickingHandler=function(l,p){var n=p.get_item();
var j=n.get_value();
var o=e.raiseCancellableControlEvent(this,"timeSlotContextMenuItemClicking",{slot:this._contextMenuTimeSlot,item:n});
p.set_cancel(o);
if(o){return;
}if(j===h.ContextMenuCommands.AddApt||j===h.ContextMenuCommands.AddAptRecurring){var m=this._raiseAppointmentInserting();
if(m){return;
}}if(this.get_shouldPostbackOnTimeSlotContextMenuItemClick()&&!this._renderingManager){this._handleServerSideTimeSlotContextMenuItemClick(n);
}else{var k=this._getTimeSlotMenuItemClickHandlers()[j];
if(k){k();
}}};
d._raiseAppointmentInserting=function(){var j=this._contextMenuTimeSlot;
var k=new a.SchedulerAppointmentInsertingEventArgs(j.get_startTime(),j.get_isAllDay(),j);
this._raise_appointmentInserting(k);
return k.get_cancel();
};
d._getTimeSlotMenuItemClickHandlers=function(){var j=this;
if(!this._timeSlotClickHandlers){this._timeSlotClickHandlers={};
this._timeSlotClickHandlers[h.ContextMenuCommands.AddApt]=function(){var l=j.get_selectedSlots();
var m;
var k;
if(l.length>0){m=l[0];
k=l[l.length-1];
}if(m&&k){j.showInlineInsertForm(m,k);
}else{j.showInlineInsertForm(j._contextMenuTimeSlot);
}};
this._timeSlotClickHandlers[h.ContextMenuCommands.AddAptRecurring]=function(){var k=(j.get_selectedSlots().length>0)?j.get_selectedSlots()[0]:j._contextMenuTimeSlot;
var l=j.get_durationOfSelectedArea();
var m;
if(l){m=j._createAppointmentFromTimeSlotAndDuration(k,l);
}else{m=j._createAppointmentFromTimeSlot(k);
}if(j._renderingManager){m.set_recurrenceState(a.RecurrenceState.Master);
m.set_recurrenceRule(j._createDefaultRecurrenceRule(m));
}j._showAdvancedInsertForm(m,true,k);
};
this._timeSlotClickHandlers[h.ContextMenuCommands.ShowFullTime]=function(){if(j._renderingManager){j.set_showFullTime(!j.get_showFullTime());
}else{j.postback({Command:"SwitchFullTime"});
}};
this._timeSlotClickHandlers[h.ContextMenuCommands.GoToToday]=function(){var k={stopPropagation:function(){},preventDefault:function(){}};
j._onTodayClick(k);
};
}return this._timeSlotClickHandlers;
};
d._createDefaultRecurrenceRule=function(m){var k=[a.RecurrenceDay.Sunday,a.RecurrenceDay.Monday,a.RecurrenceDay.Tuesday,a.RecurrenceDay.Wednesday,a.RecurrenceDay.Thursday,a.RecurrenceDay.Friday,a.RecurrenceDay.Saturday];
var j=new a.RecurrencePattern();
j.set_frequency(a.RecurrenceFrequency.Weekly);
j.set_interval(1);
j.set_daysOfWeekMask(k[m.get_start().getDay()]);
var l=new a.RecurrenceRange();
l.set_start(m.get_start());
l.set_eventDuration(m.get_duration());
return a.RecurrenceRule.fromPatternAndRange(j,l).toString();
};
d._handleServerSideTimeSlotContextMenuItemClick=function(j){var k=this;
var p=this._contextMenuTimeSlot.get_index();
var n=null;
var m=k.get_selectedSlots().length;
if(m>0){p=k.get_selectedSlots()[0].get_index();
n=k.get_selectedSlots()[m-1].get_index();
}var q=this._contextMenuTimeSlot.get_domElement().offsetWidth;
var o=this._contextMenuTimeSlot.get_domElement().offsetHeight;
var l={command:"ContextMenuTimeSlotCommand",contextMenuCommandName:j.get_value(),contextMenuID:j.get_menu().get_id(),menuItemIndex:j._getHierarchicalIndex(),appointmentID:-1,targetSlotIndex:p,lastSlotIndex:n,slotWidth:q,slotHeight:o};
this.postback(l);
};
d._timeSlotContextMenuItemClickedHandler=function(l,k){var j=k.get_item();
e.raiseControlEvent(this,"timeSlotContextMenuItemClicked",{slot:this._contextMenuTimeSlot,item:j});
};
d._addAppointmentContextMenuHandlers=function(){this._contextMenuHandlersAdded=true;
this._appointmentContextMenuItemClickingDelegate=Function.createDelegate(this,this._appointmentContextMenuItemClickingHandler);
this._appointmentContextMenuItemClickedDelegate=Function.createDelegate(this,this._appointmentContextMenuItemClickedHandler);
var l=this.get_appointmentContextMenus();
for(var j=0;
j<l.length;
j++){var k=l[j];
if(k){k.add_itemClicking(this._appointmentContextMenuItemClickingDelegate);
k.add_itemClicked(this._appointmentContextMenuItemClickedDelegate);
}}};
d._appointmentContextMenuItemClickingHandler=function(m,l){var k=l.get_item();
var n=k.get_value();
var j=e.raiseCancellableControlEvent(this,"appointmentContextMenuItemClicking",{appointment:this._contextMenuAppointment,item:k});
l.set_cancel(j);
if(j){return;
}if(this.get_shouldPostbackOnAppointmentContextMenuItemClick()&&!this._renderingManager){if(n==h.ContextMenuCommands.Edit){this._handleServerSideContextMenuEdit(this._contextMenuAppointment,k);
}else{if(n==h.ContextMenuCommands.Delete){this._handleServerSideContextMenuDelete(this._contextMenuAppointment,k);
}else{this._handleServerSideContextMenuItemClick(this._contextMenuAppointment,k);
}}return;
}if(n==h.ContextMenuCommands.Edit){this.editAppointmentWithConfirmation(this._contextMenuAppointment);
}else{if(n==h.ContextMenuCommands.Delete){this.deleteAppointmentWithConfirmation(this._contextMenuAppointment);
}}};
d._handleServerSideContextMenuItemClick=function(j,k){var l={command:"ContextMenuAppointmentCommand",contextMenuCommandName:k.get_value(),contextMenuID:k.get_menu().get_id(),menuItemIndex:k._getHierarchicalIndex(),appointmentID:j._internalID};
this.postback(l);
};
d._handleServerSideContextMenuEdit=function(j,l){if(!j){return;
}var k={OnConfirm:this._onContextMenuEditDialogCallback,Scheduler:this,Appointment:j,CallbackIsCalledFromDialog:true,ContextMenuID:l.get_menu().get_id(),MenuItemIndex:l._getHierarchicalIndex()};
this._showEditConfirmationDialog(k);
};
d._onContextMenuEditDialogCallback=function(j,k){if(k.CallbackIsCalledFromDialog){var m=new a.SchedulerRecurrenceActionDialogClosedEventArgs(k.Appointment,a.RecurrenceAction.Edit,j);
k.Scheduler._raise_recurrenceActionDialogClosed(m);
}var l={command:"ContextMenuEdit",contextMenuID:k.ContextMenuID,menuItemIndex:k.MenuItemIndex,appointmentID:k.Appointment._internalID,editSeries:j};
k.Scheduler.postback(l);
};
d._handleServerSideContextMenuDelete=function(j,l){if(!j){return;
}var k={OnConfirm:this._onContextMenuDeleteDialogCallback,Scheduler:this,Appointment:j,CallbackIsCalledFromDialog:true,ContextMenuID:l.get_menu().get_id(),MenuItemIndex:l._getHierarchicalIndex()};
this._showDeleteConfirmationDialog(k);
};
d._onContextMenuDeleteDialogCallback=function(m,k){if(k.CallbackIsCalledFromDialog){var j=new a.SchedulerRecurrenceActionDialogClosedEventArgs(k.Appointment,a.RecurrenceAction.Delete,m);
k.Scheduler._raise_recurrenceActionDialogClosed(j);
}var l={command:"ContextMenuDelete",contextMenuID:k.ContextMenuID,menuItemIndex:k.MenuItemIndex,appointmentID:k.Appointment._internalID,editSeries:m};
k.Scheduler.postback(l);
};
d._appointmentContextMenuItemClickedHandler=function(l,k){var j=k.get_item();
e.raiseControlEvent(this,"appointmentContextMenuItemClicked",{appointment:this._contextMenuAppointment,item:j});
};
d._removeAppointmentContextMenuHandlers=function(){if(!this._contextMenuHandlersAdded){return;
}var l=this.get_appointmentContextMenus();
for(var j=0;
j<l.length;
j++){var k=l[j];
if(k){k.remove_itemClicking(this._appointmentContextMenuItemClickingDelegate);
k.remove_itemClicked(this._appointmentContextMenuItemClickedDelegate);
}}};
d._removeTimeSlotContextMenuHandlers=function(){if(!this._timeSlotContextMenuHandlersAdded){return;
}var l=this.get_timeSlotContextMenus();
for(var j=0;
j<l.length;
j++){var k=l[j];
if(k){k.remove_itemClicking(this._timeSlotContextMenuItemClickingDelegate);
k.remove_itemClicked(this._timeSlotContextMenuItemClickedDelegate);
}}};
d._showTimeSlotContextMenu=function(l,j){this._contextMenuTimeSlot=j;
var k=this._getTimeSlotContextMenu();
if(k){this._filterTimeSlotContextMenu(k);
k.show(l);
}};
d._filterTimeSlotContextMenu=function(k){if(!this._renderingManager){return;
}var l=this.get_selectedView()==a.SchedulerViewType.TimelineView;
var m=this.get_selectedView()==a.SchedulerViewType.MonthView;
var n=k.findItemByValue(h.ContextMenuCommands.ShowFullTime);
if(n){if(l||m){n.hide();
}else{n.show();
var j=this.get_localization();
n.set_text(this.get_showFullTime()?j.ShowBusinessHours:j.Show24Hours);
}}};
d._getTimeSlotContextMenu=function(){var j=this.get_timeSlotContextMenuIDs();
if(j.length==0){return null;
}return $find(this._resolveContextMenuID(j[0]));
};
d._resolveContextMenuID=function(j){return String.format("{0}_{1}",this.get_id(),j);
};
d.get_appointmentContextMenus=function(){if(!this._appointmentContextMenus){this._appointmentContextMenus=[];
var j=this.get_appointmentContextMenuIDs();
for(var k=0;
k<j.length;
k++){Array.add(this._appointmentContextMenus,$find(this._resolveContextMenuID(j[k])));
}}return this._appointmentContextMenus;
};
d.get_timeSlotContextMenus=function(){if(!this._timeSlotContextMenus){this._timeSlotContextMenus=[];
var j=this.get_timeSlotContextMenuIDs();
for(var k=0;
k<j.length;
k++){Array.add(this._timeSlotContextMenus,$find(this._resolveContextMenuID(j[k])));
}}return this._timeSlotContextMenus;
};
c.showContextMenu=function(k){var j=this.get_contextMenu();
if(j){j.show(k);
}};
c.get_contextMenu=function(){if(!this._contextMenu){var j=this.get_owner();
var l=j.get_appointmentContextMenuIDs();
if(l.length==0){return null;
}var k=this.get_contextMenuID()||l[0];
this._contextMenu=$find(j._resolveContextMenuID(k));
}return this._contextMenu;
};
})();
